### ISSUE TITLE
Get Chat Badges by Channel

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#1]
**Brief description**

The API described by https://dev.twitch.tv/docs/v5/reference/chat#get-chat-badges-by-channel doesn't return the current Badge Set that Twitch uses. It includes global_mod which is long dead, doesn't include VIP and all the URL's are wrong for the badge set released yesterday.

Additionally only returns 1 subscriber badge instead of all for the channel

**How to reproduce**

Request any Channel badges and marvel at the inaccuracy. For example https://api.twitch.tv/kraken/chat/26610234/badges

**Expected behavior**

Return the correct global badges and subscriber badges for the channel

**Additional context or questions**

Please fix and/or port to Helix.

**Comment by jbulava** [comment]
Ticketed internally on GQL-911.

**Comment by alazymeme** [comment]
It looks like this was fixed in the new endpoints?
https://dev.twitch.tv/docs/api/reference#get-channel-chat-badges
https://dev.twitch.tv/docs/api/reference#get-global-chat-badges

**Comment by RAnders00** [comment]
I think this can be closed now: https://dev.twitch.tv/docs/api/reference#get-channel-chat-badges
