### ISSUE TITLE
Error loading Drop Settings

### ISSUE THREAD

**Issue by ERomin** [twitchdev/issues#100]
**Brief description**
We couldn't set up a test campaign for our organization
https://dev.twitch.tv/org/d259e072-4321-4cec-aeaf-496357908e1d/console/drops/settings

Request to API return 404:
https://api.twitch.tv/kraken/service/d259e072-4321-4cec-aeaf-496357908e1d

**How to reproduce**
- Go to Drops menu and choose Drop Settings (or use the direct link)
- The problem exists on another account as well https://dev.twitch.tv/org/5f304306-dc6d-4c8d-b7fe-f1ffe1c74f93/console/drops/settings

**Expected behavior**
Drop Settings is open normally and allows you to set up the endpoint of VHS.

**Screenshots**
Drop Settings Menu:
![Screenshot 2020-05-04 17 22 16](https://user-images.githubusercontent.com/34236241/80965929-de72eb80-8e2c-11ea-999e-acc1f3e6dcd5.png)

Infinite loader:
![Screenshot 2020-05-04 17 29 14](https://user-images.githubusercontent.com/34236241/80965945-e7fc5380-8e2c-11ea-9276-03aabaa1f70c.png)

Request from API:
![Screenshot_2020-05-01_10 09 12](https://user-images.githubusercontent.com/34236241/80965991-0bbf9980-8e2d-11ea-9208-8d7f4da3ca24.png)

**Additional context or questions**
In the previous week were was error message - Error loading drop settings:
![Screenshot_2020-04-28_11 06 09](https://user-images.githubusercontent.com/34236241/80966110-488b9080-8e2d-11ea-9e6b-5ac52074da20.png)

Now its only an error message.

P.S. Reward Manager and Campaign Manager (Create New or Edit Drop Campaign) is working

**Comment by lleadbet** [comment]
This was addressed per a conversation in the Discord- closing this issue.
