### ISSUE TITLE
Не пришли скины 

### ISSUE THREAD

**Issue by hello6632** [twitchdev/issues#1001]
На твиче смотрел стримы для получения скинов, после просмотра они появились в инвентаре твича, но в инвентаре игры они так и не появились, помогите пожалуйста получить скины.

**Comment by thedist** [comment]
It's the responsibility of the game developers or publishers that are running the Drops Campaign to award you the items in game, this is not handled by Twitch. Please reach out to the company running the Drops campaign and keep in mind that it may take several days before a claimed Dropped is given in game.

Разработчики или издатели игр, которые проводят кампанию Drops, несут ответственность за предоставление вам предметов в игре, Twitch этим не занимается. Пожалуйста, свяжитесь с компанией, которая проводит кампанию Drops, и имейте в виду, что может пройти несколько дней, прежде чем заявленный Dropped будет выдан в игре.
