### ISSUE TITLE
`Send Chat Message` doesn't return remaining timeout length

### ISSUE THREAD

**Issue by Nerixyz** [twitchdev/issues#1002]
**Brief description**

When a user is timed out in a chat, and they try to send a message with the Helix [`Send Chat Message`](https://dev.twitch.tv/docs/api/reference/#send-chat-message) endpoint, they won't know how long they're timed out for.
The API only returns `You are timed out from talking in the room.` in the message of the `drop_reason` and `user_timed_out` as the code.

**How to reproduce**

- Be timed out in a chat
- Send a message with the Helix API

**Expected behavior**

The error should indicate the length of the timeout (e.g. `You are timed out for <length> from talking in the room.`). Alternatively, there could be another parameter (e.g. `timeout_length` in seconds) to the `drop_reason` so clients can format the message on their own.

This should also be documented if it's added (https://github.com/twitchdev/issues/issues/962).

**Screenshots**

\-

**Additional context or questions**

\-

**Comment by Nerixyz** [comment]
> It's likely for "security" or anti hate raid or similar issues that it's not returned.
> 
> So this is an enhancement request ([uservoice](https://twitch.uservoice.com/forums/310213-developers)) and not a bug really

The `drop_reason` is mostly equivalent to a `NOTICE` message on IRC. On IRC, you get a `NOTICE` with a message ID `msg_timedout` and the message will include the duration of the timeout - `drop_reason` contains a generic message.

I don't see how this could be such an issue. You can manually keep track of timeouts as a bot. For chat clients, however, this is infeasible - especially because Twitch already has the information about the timeout length. If this was a security or harassment issue, it would've been fixed in the last ten years.

**Comment by BarryCarlyon** [comment]
> If this was a security or harassment issue, it would've been fixed in the last ten years.

agreed just wanted to make that suggestion for full information

> On IRC, you get a NOTICE with a message ID msg_timedout and the message will include the duration of the timeout - drop_reason contains a generic message.

There are a few differences here and there between IRC and EventSub.

This is one of them, likely IRC is a "can't fix" and eventsub was a clean slate to build how they wanted it in the first place. IRC being "ancient" at this point.

So, it's either

- a missing feature as they missed it - need uservoice (with use case and reasoning)
- a missing feature as they don't want to support it - need uservoice (with use case and reasoning)

So (in my opinion) this would be better suited on uservoice as a feature request not a bug report.

**Comment by Nerixyz** [comment]
Converted to uservoice → https://twitch.uservoice.com/forums/310213-developers/suggestions/48972260-improve-error-messages-for-send-chat-message.
