### ISSUE TITLE
не могу добавить номер телефона России

### ISSUE THREAD

**Issue by theblackprince77** [twitchdev/issues#1003]
**Brief description**
на моем аккаунте не подключен номер телефона хочу подключить а смс не приходит
**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by thedist** [comment]
This repo is for issues with the 3rd party Twitch API, for account related support you'll have to go to Twitch Support as no one here can assist you https://help.twitch.tv/
