### ISSUE TITLE
https://api.twitch.tv/helix/channels/ads does not return the correct timestamp

### ISSUE THREAD

**Issue by AruIke** [twitchdev/issues#1005]
**Brief description**
As stated in the API documentation, the value "next_ad_at" should return a timestamp in RFC3339 format. Instead, a time in seconds after 1970 is output:
{
  "data": [
    {
      "snooze_refresh_at": 0,
      "duration": 30,
      "next_ad_at": 1729950039,
      "last_ad_at": 1729949449,
      "preroll_free_time": 741,
      "snooze_count": 3
    }
  ]
}

**How to reproduce**
I used the api endpoint https://api.twitch.tv/helix/channels/ads

**Expected behavior**
As noted in the API, a time should be output in the form: "2023-08-01T23:08:18+00:00".

**Screenshots**

**Additional context or questions**
My API call was: https://api.twitch.tv/helix/channels/ads?broadcaster_id=60713488
The documentation doesn't mention whether you can change the time format somehow.

**Comment by Emilgardis** [comment]
See #857
