### ISSUE TITLE
Cant Claim my twitch drop

### ISSUE THREAD

**Issue by Georgi830** [twitchdev/issues#1006]
**Brief description**
Hello it have been 3 months since i had my twitch drop and still cant claim it. i have been claimed my other twitch drop but this one in particular i cant claim and i dont know why
**How to reproduce**

**Expected behavior**

**Screenshots**
![Twitch drop](https://github.com/user-attachments/assets/9eacf826-fa52-4825-a2c1-1e9fbb5d9ab4)
![warframe](https://github.com/user-attachments/assets/8dcc4f67-22c2-4867-bb09-9a3a21cada72)

**Additional context or questions**

**Comment by Wissididom** [comment]
This is the third party developer issue tracker. You'd need to contact Twitch at https://help.twitch.tv/s/contactsupport
