### ISSUE TITLE
Conqueror's Blade (Developers) - Game Ownership

### ISSUE THREAD

**Issue by AntonBooming** [twitchdev/issues#1008]
Good day! 
We are booming.com - the developers and global publishers of the game "Conqueror's Blade". 
We had changes in team members and currently don't have ownership of our own game on Twitch to setup Drops. 

Accounts we have access to: 
1. conquerorsbladedevs   - active, accessible
* Under this account there is organization "Booming Tech" which should have ownership of the game. 
* It says that some other account has ownership over "Conqueror's Blade". **We need to understand which account is that.** 
 
2. cb_twitchdropsww - we can'f find the linked email. Just need the full email, we will find it within the organization. 

Hope for your help.
Kind Regards, 

Anton Mamihonov 
Publishing Producer
booming.com

**Comment by Xemdo** [comment]
Handling this via email. For inquiries regarding game ownership, please reach out to developers@twitch.tv
