### ISSUE TITLE
oAuth Dialog auto scrolls to the bottom of the page

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#101]
**Brief description**

The oAuth/allow/deny application access page auto scrolls down the page.

This "promotes" a user to "just accept" rather than read all the scopes that the app is requesting

**How to reproduce**

Redirect the user to Twitch to authenticate with a window thats not very tall

**Expected behavior**

The page doesn't auto scroll down to accept/deny

**Comment by jbulava** [comment]
Going to be close out as a duplicate. Covered and being tracked via:
https://twitch.uservoice.com/forums/310213/suggestions/39784498

Existing internal ticket is IDPLAT-3012

**Comment by BarryCarlyon** [comment]
Ah ha

I knew I had opened it already _somewhere_
