### ISSUE TITLE
Additional context or questions

### ISSUE THREAD

**Issue by ghost** [twitchdev/issues#1014]
Good afternoon, I turned on two-factor authentication and now I can't log into my account on more than one device. I should receive a confirmation SMS to my number, but it doesn't. Can you fix this bug?

+ add Ukrainian language

**Comment by thedist** [comment]
This repo is for issues relating to 3rd party developer integration. No one here can assist with Account related issues such as 2FA, you'll need to go through Twitch Support [https://help.twitch.tv/](https://help.twitch.tv/)
