### ISSUE TITLE
twitch connections/drops

### ISSUE THREAD

**Issue by luxszryy** [twitchdev/issues#1016]
**Brief description**
i wanted to connect my riot account to my twitch account for the arcane playercard drops but when i try to do so it pops up with an error. it also does this with any accounts i try to connect.
**How to reproduce**

**Expected behavior**
i expect an answer and solution to my issue before the drops are gone
**Screenshots**
![IMG_9458](https://github.com/user-attachments/assets/d09832e8-7385-408f-b607-f74ab3cf5a2a)

**Additional context or questions**
this has been going on for multiple days now and i just want my rewards

**Comment by BarryCarlyon** [comment]
the third party developer bug tracker isn't the correct place to report this issue as it's a first party issue.
