### ISSUE TITLE
Get Channel Stream Schedule: segments will be null if segment count aligns to page size

### ISSUE THREAD

**Issue by MattIPv4** [twitchdev/issues#1020]
**Brief description**

When iterating over pages of segments on a channel, if the total number of segments available on the channel is a multiple of the page size (`first`), then on the penultimate response the API will return the final set of segments, but also returns a cursor still. Requesting with that cursor then results in an API response with `segments` being `null`.

**How to reproduce**

Have a channel with exactly 25 segments in the future.

Request the segments for the channel with first set to 25.

Observe exactly 25 segments returned.

Observe cursor returned.

Request further segments for the channel using the cursor.

Observe null segments returned.

**Expected behavior**

A few different solutions that I'd see as acceptable:

- `segments` is documented as nullable
- Logic is updated to only return a `cursor` if there are more segments
- Logic is updated such that when this situation occurs, `segments` is coalesced to an empty array

**Screenshots**

N/A

**Additional context or questions**

We ran into this in production (cc https://github.com/alveusgg/alveusgg/pull/840) and had multiple folks reproduce the issue as above in the TwitchDev Discord.

**Comment by BarryCarlyon** [comment]
A PR is open for this internally - https://discord.com/channels/504015559252377601/523675960797691915/1310795809159122965

**Comment by MattIPv4** [comment]
This has now been fixed - https://discord.com/channels/504015559252377601/523675960797691915/1311124357531045889
