### ISSUE TITLE
Unauthorized on GET STREAMS with a valid token

### ISSUE THREAD

**Issue by MinnDevelopment** [twitchdev/issues#105]
**Brief description**

I'm using the *get streams* endpoint to fetch a number of streams to send discord webhook notifications. Recently, the endpoint has started responding with a 401 response *consistently*.

**How to reproduce**

1. Setup Application (I tried **ChatBot** and **Application Integration**)
2. Do `client_credentials` oauth token exchange
3. Make a request with the token:

```
GET https://api.twitch.tv/helix/streams?user_login=<name1>&user_loing=<name2>
Authorization: OAuth <access token>
Client-ID: <client id>
```

**Expected behavior**

The response is successful since the token is valid.

**Screenshots**

N/A

**Additional context or questions**

This was working fine just yesterday, with the same logic.

Here is the response:
```json
{
  "error": "Unauthorized",
  "status": 401,
  "message": "OAuth token is missing"
}
```

I used cURL to check if the oauth token is valid:

```
$ curl -H "Authorization: OAuth <access token>" https://id.twitch.tv/oauth2/validate
{"client_id":"<client id>","scopes":[],"expires_in":5206826}
```

**Comment by MinnDevelopment** [comment]
It seems to be working again, gonna wait and see if it remains that way.

**Comment by RAnders00** [comment]
You need a `Bearer` not `OAuth` prefix in the Authorization header when calling the Helix API.

**Comment by BarryCarlyon** [comment]
> GET https://api.twitch.tv/helix/streams?user_login=<name1>&user_loing=<name2>
> Authorization: OAuth <access token>
> Client-ID: <client id>

Should be

> GET https://api.twitch.tv/helix/streams?user_login=<name1>&user_loing=<name2>
> Authorization: Bearer <access token>
> Client-ID: <client id>

As documented:

https://dev.twitch.tv/docs/api/reference#get-streams

**Comment by MinnDevelopment** [comment]
Thank you for the information, I thought the header was valid because the requests didn't reject it and the verification endpoint also accepted it. I have updated the header to use bearer.

**Comment by BarryCarlyon** [comment]
Yeah that was due to #53 you specify a bad auth token/format it wrong, it didn't stop your call working to none privileged endpoints, just drops to the lower rate limit
