### ISSUE TITLE
Cant access Your Console

### ISSUE THREAD

**Issue by fghjfjhk** [twitchdev/issues#109]
**keep saying I need to enable my cookies which are already enabled**
<img width="1440" alt="Screenshot 2020-05-10 at 14 59 12" src="https://user-images.githubusercontent.com/63376759/81501191-d3a5d400-92ce-11ea-8c54-56d9c8ad31d4.png">

**Comment by BarryCarlyon** [comment]
Whats the URL you are trying to reach?

**Comment by lleadbet** [comment]
@fghjfjhk - Can you provide more details here? Happy to help with this. 

Until then, going to close as we can't replicate the issue.
