### ISSUE TITLE
Helix Streams is skipping Streams

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#11]
**Brief description**

Some small streams are missing from helix streams again.

This happened recently with small streamers and may be reoccuring

**How to reproduce**

> when testing with https://api.twitch.tv/helix/streams?game_id=6715&first=100 1 to get all live streams for the game Doom the twitch api doesnt return everything, from 16 streams it drops FlexistentialCrisis , hells_quarantine and latalainis . i dont see what causes this or how to actually get all streams. all 3 appear in the twitch website doom section, are live streaming since hours and have a few viewers.
> is this known ?

https://discuss.dev.twitch.tv/t/api-doesnt-return-all-llive-streams/23378

**Expected behavior**

The API to match the directory

**Additional context or questions**

This may also be related to #2 or #3

**Comment by mauerbac** [comment]
HLX-1335

**Comment by Xemdo** [comment]
Unable to reproduce this. Is this issue still occuring?
