### ISSUE TITLE
Cant delete my extension

### ISSUE THREAD

**Issue by sylvesterlan100** [twitchdev/issues#112]
**Brief description**
I created an extension called CatzBot as a test project. I created a secret. I tried to delete the extension and it says I can't. An error message said I was not authorized to delete it.

**How to reproduce**

**Expected behavior**
I should be able to delete it.

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
If you have no versions, you can't delete your extension.

This is a common issue that is floating about for a while, means you dumped out of the extension create wizard

This is a duplicate of #46

**Comment by jbulava** [comment]
Closing this issue as it is a duplicate of #46 as Barry mentioned.
