### ISSUE TITLE
Send extension chat is 401-ing for no reason

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#113]
**Brief description**

https://dev.twitch.tv/docs/extensions/reference#send-extension-chat-message

Is 401-ing even though I've changed nothing with the extension, how it auths, or version(s) installed, or extensions active on the channel

> '{"error":"Unauthorized","status":401,"message":"unauthorized"}'

I've logged the error as consistent (every 15 minutes or at the top of the hour) since

> date: 'Wed, 13 May 2020 18:30:18 GMT',

**How to reproduce**

Try to send an extension chat as documented today, where it was working fine yesterday.

**Expected behavior**

Chat sends

**Comment by jbulava** [comment]
Issue has been resolves.
