### ISSUE TITLE
Error on spanish translation when uploading a discovery icon of an extension

### ISSUE THREAD

**Issue by DysonSmith** [twitchdev/issues#119]
**Brief description**
Error on spanish translation when uploading a discovery icon of an extension. It shows "300x300" when it should show "300x200"

**How to reproduce**
Go to Version Details on the Spanish translation, and it appears on the Discovery Icon

**Expected behavior**
It should show "300x200" not "300x300"

**Screenshots**
![image](https://user-images.githubusercontent.com/54469750/82559846-98c65a80-9b70-11ea-87e8-33259f748a41.png)

**Additional context or questions**

**Comment by lleadbet** [comment]
This appears to affect a few languages beyond Spanish, but we're looking into it.

**Comment by DysonSmith** [comment]
Ok, thanks for looking into it.

**Comment by lleadbet** [comment]
Hey there- this should be fixed now. Thanks for flagging!
