### ISSUE TITLE
Language Codes Sometimes Return Uppercase

### ISSUE THREAD

**Issue by RokuHodo** [twitchdev/issues#120]
**Brief description**

When getting videos through the ``/videos`` endpoint, the language code is sometimes uppercase instead of lowercase.

**How to reproduce**

- Make this initial request: https://api.twitch.tv/helix/videos?game_id=509658&type=highlight&first=100
- Follow the cursor until a non-lowercase language code is returned.

**Expected behavior**

The language codes should be lowercase instead of uppercase, i.e., ``pt`` instead of ``PT``.

**Screenshots**

![devenv_2020-05-21_23-38-11](https://user-images.githubusercontent.com/17150170/82629242-11eb9f00-9bbd-11ea-8cc1-a66bc571cb2c.png)

![2020-05-21_23-40-53](https://user-images.githubusercontent.com/17150170/82629247-1617bc80-9bbd-11ea-9090-65507095711b.png)

![2020-05-21_23-41-23](https://user-images.githubusercontent.com/17150170/82629251-187a1680-9bbd-11ea-8609-cbf5c5bdd82f.png)

**Additional context or questions**

This is sporadic and is not restricted to certain languages. This also happened to ``en`` on several occasions. The same language codes can be returned in both upper case and lowercase format. It is not exclusive to one or the other.

**Comment by lleadbet** [comment]
@RokuHodo - I'm digging into this, but having problems replicating this- are you still seeing this?

**Comment by RokuHodo** [comment]
I re-ran my tests that gave the result the first time around, and I couldn't reproduce it myself either. This was with the ``/videos`` and the ``/streams`` endpoints. Both of them returned the language in all lowercase as expected. Well, except for when the offset when following the cursor for the ``/videos`` endpoint got above 600; but that's a separate issue.

**Comment by lleadbet** [comment]
Got it- feel free to file another ticket for the cursor issue. Going to close this one out.
