### ISSUE TITLE
Android links in chat

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#121]
**Brief description**

To same character count/blocking chat with walls of texts, bot commands that include links often omit `https://` at the start.

The Twitch website parser automatically puts `https://` at the start.

But for android users it doesn't/does something else, and users clicking the link in the Android app get an error page instead

**How to reproduce**

- Send a link to chat using, say "words and stuff cohh.tv/coffee other words`
- Via the Android app finger punch that link
- marvel at the webview throwing a lovely error page instead of the target page

**Expected behavior**

- it works

**Comment by iProdigy** [comment]
Able to reproduce.

`https://example.com` works

While `http://example.com` and `example.com` fail with the following error: `net::ERR_CLEARTEXT_NOT_PERMITTED`

**Comment by lleadbet** [comment]
Ticketed as: AND-10937

**Comment by iProdigy** [comment]
Still broken on version 9.4.0

**Comment by lleadbet** [comment]
Wanted to confirm that the fix has rolled out and this should be resolved now. Thanks for the report!
