### ISSUE TITLE
Unable to delete Extension

### ISSUE THREAD

**Issue by TheHellcat** [twitchdev/issues#127]
**Brief description:**
This is for the Twitch account "SpaceflowerDE" and the company "Spaceflower", regarding the extension "Live Games Collection":

We created a new extension and then had our company created in the Twich dev backend.
Since there is no option to move the already created extension to the company, to be able to assign permissions to the actual dev and we haven't done much on it so far, anyways, we wanted to simply delete and re-create it on the company account.
However, hitting the "delete" button yield and "not authorized" message.

**How to reproduce:**
Go to "manage extension", click on "delete extension", in the next dialog again click "delete" to confirm the action.

**Expected behavior:**
The extension beeing deleted.

**Screenshots:**
n/a

**Additional context or questions**
We want to move the extension to the company account, so if it's possible to simple move it from the Twitch account based dev dashboard into the company based one, that'll be super fine.

This is for the Twitch account "SpaceflowerDE" and the company "Spaceflower", regarding the extension "Live Games Collection"

Thank you.

**Comment by BarryCarlyon** [comment]
Duplicate of #46 

Related issue #112 

You can't delete an extension if it has no versions

**Comment by TheHellcat** [comment]
I feel really silly now....
Thank you! That did the trick :-)

**Comment by BarryCarlyon** [comment]
Yeah this issue, _normally_ means you dumped out/aborted during the extension create wizard. Hence no version
