### ISSUE TITLE
Chat embed breaks Back button

### ISSUE THREAD

**Issue by kaldune** [twitchdev/issues#129]
**Brief description**

After the chat embed loads, it inappropriately adds the current page to the browser history. This usually breaks the Back button but not always. Sometimes the browser detects the duplicate history and navigates back correctly. When the Back button breaks, the experience is terrible.

**How to reproduce**

1) Open Chrome, Edge or Firefox
2) Navigate to one of the following and wait for chat to fully load: 
   https://www.twitch.tv/embed/rifftrax/chat
   https://codesandbox.io/s/dazzling-gates-y7wnt

3) Hit the refresh button and wait for the chat to load again. Repeat this a few times. The chat embed keeps pushing the current page into the browser history.

**Expected behavior**

Chat embed should not alter browser history.

**Screenshots**
![image](https://user-images.githubusercontent.com/64940906/83526967-03926280-a49c-11ea-9281-a6f0b45fc5f7.png)

**Additional context or questions**
N/A

**Comment by kaldune** [comment]
There's a history.push in the embed that might cause the issue.

https://static.twitchcdn.net/assets/pages.embed-chat-b5a0efdcd9e88ffd5fe5.js

```
        function g(e, n, t, i) {
            var r = i || v(n)
              , o = "";
            r && (o = "?" + m + "=" + function(e) {
                switch (e) {
                case d.a.VIEWS:
                    return a.Popular;
                case d.a.TIME:
                    return a.Newest;
                default:
                    return e
                }
            }(r));
            var s = t ? t.toLowerCase() : function(e) {
                var n = b(e);
                return n ? n.toLowerCase() : "all"
            }(n);
            c.p.history.push(e + "/" + s + o)
        }
```

**Comment by mzmiric5** [comment]
I noticed a similar issue (although, was only able to reproduce it when embedding chat in addition to a player embed on the same page). I posted on the forums about it yesterday ( https://discuss.dev.twitch.tv/t/twitch-stream-and-chat-embed-hijacking-parent-navigation/26059 ), though I might add a +1 here

**Comment by kaldune** [comment]
This might be fixed. I haven't been able to reproduce the issue for almost 3 weeks.

**Comment by lleadbet** [comment]
@kaldune - We believe we addressed this, but if you continue to see this happening, please feel free to reopen.
