### ISSUE TITLE
onContext returns light when it should be dark

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#13]
**Brief description**

If you have a cookieless session
Then login to Twitch
And your Twitch is dark mode
Then open a ext configuration panel, that configuration panel is onContext passed "light" instead of dark.

**How to reproduce**

1. Delete all the cookies/chrome incognito etc
1. Login to Twitch
1. If you Twitch is auto dark mode (from browser detect or otherwise)
1. Open a configuration panel for an extension
1. Marvel in how bright the configuration panel is in error

**Expected behavior**

It be dark

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/70449601-2a964b80-1a9a-11ea-9a0c-37cdbcd32f51.png)

**Comment by billygerhard** [comment]
I am getting this error on a panel as well, it isn't limited to the configuration page.

**Comment by BarryCarlyon** [comment]
Issue confirmed also on front end with a "full" video extension.

Same repeat steps

Login, open an extension

<img width="637" alt="Screenshot 2019-12-27 at 20 37 36" src="https://user-images.githubusercontent.com/20999/71531938-eb188d80-28e8-11ea-92bb-c99b9eec8f75.png">

**Comment by jbulava** [comment]
Ticketed internally on EXT-1151.

**Comment by marcandrews** [comment]
I'm experiencing this on the config view, but not on the video overlay view.

**Comment by ricardjorg** [comment]
![image](https://user-images.githubusercontent.com/3237751/82080365-44ffd100-9699-11ea-9bd7-0f4fe3c420e0.png)
I also get that on the live config view. The twitch theme is dark, but the theme I get from the context is the light one

**Comment by TristanWiley** [comment]
This should now be resolved! :+1:

**Comment by Djiit** [comment]
Working like a charm !
![image](https://user-images.githubusercontent.com/1169844/85376775-79886780-b538-11ea-8958-23bc2f5ab0bb.png)

**Comment by BarryCarlyon** [comment]
I ran the repeat steps. Seems ok!

**Comment by BarryCarlyon** [comment]
UPDATED: onContext is now NOT FIRING when you change from dark/light mode.

It's only firing at page load!

REOPEN THE ISSUE @TristanWiley

**Comment by jbulava** [comment]
Tristian's on it.  He created a new ticket for this on ANC-2398.

**Comment by roikoren755** [comment]
Testing my extension, I see onContext fired a lot when the channel is live and streaming, which is great.
However, I still do not see it fired when changing the theme, or as soon as the channel goes offline and the video stops.

**Comment by lleadbet** [comment]
As an update, this should be resolved now.
