### ISSUE TITLE
User not showing as Live via API but is actually Live on their Twitch Page

### ISSUE THREAD

**Issue by bsquidwrd** [twitchdev/issues#130]
**Brief description**
I have come across a user that doesn't show in the `helix/streams` endpoint but I am able to watch their stream on the Twitch website

**How to reproduce**
GET request `https://api.twitch.tv/helix/streams?user_login=plavorseol`
GET request `https://api.twitch.tv/helix/streams?user_id=438030919`

**Expected behavior**
Results indicating that the user is Live as well as the related Stream data

**Screenshots**
https://imgur.com/a/L0nM8T6

**Additional context or questions**
Are they not allowed to show up in the Streams endpoint, even when they are live? 
Is there a way to check if a user is marked as "excluded" from the Stream endpoint?

**Comment by bsquidwrd** [comment]
I'm getting the same issue with another user, `mrcurlim`

**Comment by lleadbet** [comment]
Ticketed internally as HLX-1448.
