### ISSUE TITLE
player.setVolume(0) Throws TypeError

### ISSUE THREAD

**Issue by ShayHacohen** [twitchdev/issues#131]
**Brief description**
The setVolume function of the embedded player (as returned from Twitch.Player calls when including the script https://player.twitch.tv/js/embed/v1.js) recently started throwing TypeErrors when passed 0 as a parameter.

**How to reproduce**
Embedding the Twitch player by including https://player.twitch.tv/js/embed/v1.js and grabbing a player object; the way I did it was similar to the following:
```
var options = {
	height: '400px',
	width: '100%',
	channel: "$userLogin"
};   
var player = new Twitch.Player("twitch-player-div", options);
```
And then calling:
`player.setVolume(0);`  

The above call consistently results in a TypeError being raised.

**Expected behavior**
The player's volume should be set to 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/44909655/83948840-d68dd900-a828-11ea-9046-dc03fe89eb56.png)

**Additional context or questions**
The setMuted method works great, and passing any value other than 0 to setVolume also seems to work as usual, but setVolume(0) specifically errors out. It used to work fine until rather recently (not sure exactly when it stopped working, but I think it's been a couple of weeks). It's nothing serious since, as I mentioned, setMuted works just fine (as does setVolume(0.000000001), if I was that kind of person), but I figured it's worth a mention.

Thanks :)

**Comment by kaldune** [comment]
Posting directly to the iframe works fine* so it's probably in the player embed wrapper js like you mentioned.

```typescript
export const setVolume = (host: Window, volume: number) => {
    host.postMessage(
        {
            eventName: 11, // 'SetVolume',
            namespace: 'twitch-embed-player-proxy',
            params: volume,
        },
        '*'
    );
};
```

*This is an unofficial way of interfacing with the player and only recommended for testing.

**Comment by lleadbet** [comment]
This should be resolved now. Thank you for the report!
