### ISSUE TITLE
https://id.twitch.tv. is dead 

### ISSUE THREAD

**Issue by nostone123** [twitchdev/issues#132]
Trying to get onto https://id.twitch.tv. to get a new Oauth token and i keep getting  404 page not found

is there a new way to get Oauth tokens?

**Comment by BarryCarlyon** [comment]
404 sounds like you did a GET instead of a POST request. Which step are you failing at?

**Comment by brandinarsenault** [comment]
This is definitely just an invalid call - can confirm the Auth endpoints are working fine with Post Requests, I've tested this every day since the reporter.

**Comment by lleadbet** [comment]
We've not noticed any issues, but it sounds like you might be using a GET vs. POST as outlined in our documentation here: https://dev.twitch.tv/docs/authentication

Please let us know if you see any issues- closing for now.
