### ISSUE TITLE
Creating clips for online channels return 302 Service Unavailable, works as expected for offline channels

### ISSUE THREAD

**Issue by corgrath** [twitchdev/issues#135]
**Brief description**
Creating clips for online channels return 302 Service Unavailable, works as expected for offline channels.

**How to reproduce**
Send a POST request to `https://api.twitch.tv/helix/clips?has_delay=false&broadcaster_id=##BROADCASTER_ID##`, with following headers:
- ` Authorization: Bearer ##ACCESS_TOKEN##`
- `Client-ID: ##APP_CLIENT_ID##` 

**Expected behavior**
- End point should return a non-300x HTTP response.

**Screenshots**

Channel offline (expected)
![twitchdev_offline2](https://user-images.githubusercontent.com/472514/84299443-03a3f980-ab51-11ea-8a72-7e8b4f290260.png)

Channel online (broken)
![twitchdev_online](https://user-images.githubusercontent.com/472514/84299389-eff89300-ab50-11ea-8b12-329154c9c656.png)

**Additional context or questions**
Tried repeatedly over an hour, always getting 302 Service Unavailable.

![twidev_status](https://user-images.githubusercontent.com/472514/84299558-364df200-ab51-11ea-8917-6bbd3c1ec153.png)

**Comment by lleadbet** [comment]
@corgrath - Are you seeing 302s or 503s? Screenshot shows 503s- regardless, you are correct in your assumption there. We'll work to improve that status code and document the change.
