### ISSUE TITLE
Bug: [InvalidCharInParent] parent query string value contains invalid character

### ISSUE THREAD

**Issue by justanotherco** [twitchdev/issues#136]
Embeds no longer work since the forced introduction of the parent query.

No matter what I put in the parent query, I always get the error:

`[InvalidCharInParent] parent query string value contains invalid character`

I tried everything:

//player.twitch.tv/?channel=channelname&parent=http://mydomain.test&muted=true&autoplay=1

//player.twitch.tv/?channel=channelname&parent=mydomain.test&muted=true&autoplay=1

//player.twitch.tv/?channel=channelname&parent=http://mydomain.test/&muted=true&autoplay=1

I tried url encoding the parent parameter, etc.

Nothing works.

Which character is invalid in the parent query string from my examples above?

**Comment by leotrieu** [comment]
This works for me (you need to include "www" in the domain name):

<iframe src="https://player.twitch.tv/?channel=ChannelName&parent=www.domain.com" width="620" height="380" frameborder="0" scrolling="no" allowfullscreen="allowfullscreen"></iframe>

**Comment by justanotherco** [comment]
Thanks for the response, and actually I realized it is due to http://. But I use WordPress and so to dynamically use get_site_url() to get the site's url which will include the http/s part.

I imagine a lot of people will do something like this, surely twitch can just filter out the https parts on their side?

**Comment by crisona** [comment]
hello I have the same issue starting from around 15 hours ago. i tried any string, but it doesnt work to me. any suggestion? Until yesterday it was working with no parent string

**Comment by BarryCarlyon** [comment]
@crisona https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956/

@justanotherco no you have to explicitly declare your domain

You can also do multiple parents, so include one with and one without `www.`

**Comment by jbulava** [comment]
As this is not a product bug, I'm going to close the ticket.  @justanotherco, if you would like to submit the feedback to accept parent values with and without the protocol, please feel free to create a UserVoice suggestion [here](https://twitch.uservoice.com/forums/310213-developers?category_id=356962).  From my understanding, I assume the team wanted to simplify the value you need to send since HTTPS is required (other than for `localhost` and the `127.0.0.1/8` IP range).
