### ISSUE TITLE
DevRig: No "Extension Name is taken" warning

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#137]
**Brief description**

No feedback on extension create when the name is already taken

**How to reproduce**

Use the rig wizard to create a new extension using a name that is taken

**Expected behavior**

A suitable warning is returned

**Additional context or questions**

Reported here: https://discordapp.com/channels/504015559252377601/530543302622183453/720673871920889967

**Comment by Tenchumaru** [comment]
Developer Rig version 1.2.6 addresses this issue.
