### ISSUE TITLE
DevRig: live stream - parent

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#138]
**Brief description**

![image](https://user-images.githubusercontent.com/20999/84423841-02d59b00-ac17-11ea-965b-7c4e322854b7.png)

**How to reproduce**

Rig has not been updated for the embed changed

**Comment by BarryCarlyon** [comment]
This also isn't fixable for "view in browser" since thats not on 90 or 443

**Comment by jbulava** [comment]
GSDK-286 is the internal ticket.

**Comment by Tenchumaru** [comment]
Developer Rig version 1.2.6 addresses this issue.

**Comment by BarryCarlyon** [comment]
![image](https://user-images.githubusercontent.com/20999/86145999-8df7d180-baef-11ea-9d00-8a74d8a05a3e.png)

This does not seem to be fixed.

I get a error message and no player
