### ISSUE TITLE
Embed on Reddit doesn't work anymore

### ISSUE THREAD

**Issue by billy242428** [twitchdev/issues#139]
![image](https://user-images.githubusercontent.com/66819094/84474499-3baf5780-ac8b-11ea-9f4f-655493f586cb.png)

Users can't obviously change Reddit's code, so what are you going to do to fix it? Right now it's not possible to embed any stream on Reddit

**Comment by BarryCarlyon** [comment]
Reddit needs to fix this. It's not a Twitch issue.

Reddits needs to update it's implementation of the embed

**Comment by jbulava** [comment]
We're in close communication with embed.ly and can pass this along.  Is this being seen across Reddit or on a specific subreddit?

**Comment by iProdigy** [comment]
Embed.ly is used across reddit. Currently, the `parent` parameter is being set to `meta.tag` in the url for the iframe

**Comment by billy242428** [comment]
Hey! To answer jbulava, this is being seen across all Reddit. I tested it on multiple Subreddits and I get the same error message. By what you guys wrote, seems clear to me that this is on Embed.ly side. Can you guys tell them to update their code and fix this? Seems like they are not aware at all of the issue, because it's been going for a few days. Shouldn't take long once they know how to do that. Thank you.

**Comment by iProdigy** [comment]
The parent parameter has been updated and the clip embeds on reddit are fixed.
