### ISSUE TITLE
Webhooks (Un)Subscribe Parameters

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#14]
**Brief description**

https://dev.twitch.tv/docs/api/webhooks-reference

the `hub.topic` section is out of date, in the JSON Body Parameters

**Expected documentation**

Just changed it to something like "refer to later in this docs for the available topics"

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39847678-webhooks-un-subscribe-parameters
