### ISSUE TITLE
"Full name" field in verified bot request form is vague

### ISSUE THREAD

**Issue by RAnders00** [twitchdev/issues#140]
**Brief description**
In the form for verified bot requests, it just says "Full Name", which is too vague. Should I enter my real name in there, the full name of the bot, or my own Twitch name?

**How to reproduce**
Visit https://dev.twitch.tv/limit-increase

**Expected behavior**
It would be nice to have it worded more explicitly, e.g. "your own first and last name"

**Screenshots**
![image](https://user-images.githubusercontent.com/1629196/84590965-034e7b80-ae3b-11ea-912e-81e74adc1a6f.png)

**Additional context or questions**

**Comment by lleadbet** [comment]
@RAnders00 - We've updated the form to be more explicit on what information is being required. Thank you for the report!
