### ISSUE TITLE
Missing flag for streams that can only be watched on the Twitch website

### ISSUE THREAD

**Issue by kaldune** [twitchdev/issues#145]
**Brief description**

In the streams endpoint, there's no property in the response data that indicates whether a stream can be viewed on other sites. 

**How to reproduce**

Get stream data for sjokz when she's live. She does not allow her stream on other sites.
https://api.twitch.tv/helix/streams?user_login=sjokz

**Expected behavior**

A property that indicates if the stream can be watched on other sites or Twitch only.

**Screenshots**

![image](https://user-images.githubusercontent.com/64940906/84949110-94269080-b0a1-11ea-8ada-257eb5e81931.png)

**Additional context or questions**

We need to know if streams can be viewed on other sites before we render the embed. This means the streams api needs to return this information.

**Comment by BarryCarlyon** [comment]
This technically isn't a bug. But a feature request.

And it should be raised on the Twitch UserVoice instead

https://twitch.uservoice.com/forums/310213-developers

**Comment by kaldune** [comment]
Closed as not a bug. Here's the [feature request](https://twitch.uservoice.com/forums/310213-developers/suggestions/40737367-add-flag-for-streams-that-can-t-be-embedded-and-wa).
