### ISSUE TITLE
embed.twitch.tv refused to connect.

### ISSUE THREAD

**Issue by mitiavr** [twitchdev/issues#146]
i have problems with embedding my twitch to my website, works normal on localhost but when i upload it to my website it goes wrong.

code i used:

<div class="video__twitch">
    <div id="twitch-embed" ></div>

    <script src="https://embed.twitch.tv/embed/v1.js"></script>

    <script type="text/javascript">
      new Twitch.Embed("twitch-embed", {
        width: 1440,
        height: 560,
        channel: "icalmyth"
        parrent: ["http://mythicaldesigns.be"]
      });
    </script>
</div>

.....................................................................
console displays:
A cookie associated with a cross-site resource at http://twitch.tv/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by TimothyCole** [comment]
It appears that the options you are using for the embed are slightly off, you're using `parrent` instead of `parent` as well as it requires just the domain, not the protocol so should look something like `parent: ["mythicaldesigns.be"]`

**Comment by BarryCarlyon** [comment]
For further help please visit

https://discuss.dev.twitch.tv/t/the-great-big-im-using-wix-somewebsitemaking-tool-and-i-dont-know-how-to-fix-my-embed-thread/26297/

**Comment by lleadbet** [comment]
Closing as both Tim and Barry have correctly identified the issue. 

Please reopen if you're still seeing issues.
