### ISSUE TITLE
Non Intertactive Clip embed on a website issue for mobile devices

### ISSUE THREAD

**Issue by gegis** [twitchdev/issues#147]
**Brief description**
Non Intertactive Clip embed on a website recently stopped working for mobile devices, but it still works for desktop. When testing from mobile device - it shows 'm.twitch.tv refused to connect', by the way - parent is specified.

**How to reproduce**
Navigate to https://classybeef.com/big-wins/100k-hit-on-fruit-party-maxwin on mobile.

**Expected behavior**
Displays embed video/clip

**Screenshots**
![twitch-embed-mobile-error-1](https://user-images.githubusercontent.com/13258341/85210752-e9cd9800-b342-11ea-83c2-a7233b1b3308.png)
![twitch-embed-mobile-error-2](https://user-images.githubusercontent.com/13258341/85210755-f0f4a600-b342-11ea-9b83-80b28ae0e2b8.png)

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
Further context/discsussion

https://discordapp.com/channels/504015559252377601/523675960797691915/723991761227350066

**Comment by kaldune** [comment]
They turned on Content Security Policy so you need to use the `parent` query string param for all sites that host the embed.

https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956/120

**Comment by gegis** [comment]
Hi,

Parent query param was fixed before and it worked, this is something
different, that appeared on mobile only.

Best regards,

Egidijus Gegeckas

+350 5600 0364
+34 6666 18075
egidijus.gegeckas@gmail.com

**Comment by lleadbet** [comment]
@gegis - I can't seem to replicate this any longer on the site. 

If you're still seeing issues, please feel free to reply and reopen the issue. Thanks!
