### ISSUE TITLE
Configure link on the old Extension information page is broken

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#15]
**Brief description**

I have 

https://www.twitch.tv/ext/xptunrxv6b9qmk5uyeg08iw1cm2i6o-0.0.5

as got to via

![image](https://user-images.githubusercontent.com/20999/70742511-9d5f2b00-1d15-11ea-9cac-c10db75b3bd7.png)

Installed.

The configure link doesn't go to the configuration for that extension anymore

**Expected behavior**

Go to the right place on the new dashboard

Broken: https://www.twitch.tv/barrycarlyon/dashboard/extensions/manage?configure=true&extensionID=xptunrxv6b9qmk5uyeg08iw1cm2i6o-0.0.5
Correct: https://dashboard.twitch.tv/u/barrycarlyon/extensions/manage?configure=true&extensionID=xptunrxv6b9qmk5uyeg08iw1cm2i6o-0.0.5

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/70742493-8f110f00-1d15-11ea-93af-a873ab80e7f2.png)

**Additional context or questions**

![image](https://user-images.githubusercontent.com/20999/70742521-a64ffc80-1d15-11ea-83d1-d7d200169ceb.png)

Links to the old extension location over the new dashboard location

Old: https://www.twitch.tv/ext/xptunrxv6b9qmk5uyeg08iw1cm2i6o-0.0.5
New: https://dashboard.twitch.tv/extensions/xptunrxv6b9qmk5uyeg08iw1cm2i6o-0.0.5

For example

**Comment by mauerbac** [comment]
Verified and fixed
