### ISSUE TITLE
Unable to remove my organization

### ISSUE THREAD

**Issue by gpoussel** [twitchdev/issues#152]
In my organization, we unfortunately sent two organization creation on Twitch. Only one of them got access on our game (that's fine), but now we are stuck:

- I can't delete my organization (the console doesn't give me the option to do that).
- I have tried to add another administrator, but I can't transfer the organization ownership.
- I got invited to the other organization (the appropriate one for managing our game), but can't join because I have reached the max number of organizations.

How can I remove my organization?

**Comment by lleadbet** [comment]
@gpoussel - Apologies for the delay- can you reply with: 

1. Your Twitch username
2. The org you need deleted

I can look to get this addressed for you. Alternatively, if you don't feel comfortable with that information public, feel free to join our Discord and send a DM to ConcreteEntree (that's me in there). 

Happy to assist here.

**Comment by gpoussel** [comment]
Thanks for the answer, I've just sent you a PM!

**Comment by gpoussel** [comment]
Problem solved, thanks!
