### ISSUE TITLE
DevRig: Player is all white/doesn't load

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#154]
**Brief description**

Player is white and fails to load

DevRig is 1.2.6

**How to reproduce**

Create a video view

**Expected behavior**

player is visible/loads

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/86146348-02cb0b80-baf0-11ea-9885-921904b80f34.png)

**Additional context or questions**

This is a reopen of #138

**Comment by Tenchumaru** [comment]
This is addressed in Developer Rig version 1.2.7.

**Comment by BarryCarlyon** [comment]
Confirmed as fixed!
