### ISSUE TITLE
Download Developer Rig Link

### ISSUE THREAD

**Issue by kingga** [twitchdev/issues#156]
The link for "Download Developer Rig" needs to be updated on the URL dev.twitch.tv/console/extensions/{client_id}/{version}/status. It is currently going to https://link.twitch.tv/DevRig-Win which takes you to a bitly warning screen.

**How to reproduce**
1. Go to dev.twitch.tv/console/extensions/{client_id}/{version}/status
2. Click the "Download Developer Rig" button under the "Get started with the Developer Rig or Sample Code" heading

**Expected behavior**
It should download a file or take me to a downloads page.

**Screenshots**
![image](https://user-images.githubusercontent.com/20036047/86440892-660ea500-bd5f-11ea-8b92-28a1b5cf3a2d.png)
![image](https://user-images.githubusercontent.com/20036047/86440914-6eff7680-bd5f-11ea-8f45-16d2f5fb7585.png)

**Comment by BarryCarlyon** [comment]
Side note: it's a false positive on bitLy's part. I clicked continue and downloaded the rig, but would be wise for Twitch to skip bitLy

**Comment by Tenchumaru** [comment]
All such links now refer to https://developer-rig.twitchcdn.net/Twitch+Developer+Rig+Setup.exe.

**Comment by Katzen48** [comment]
The issue still exists.
Could the link in the screenshot be changed to the one in the docs, where the download is working fine?

**Comment by jbulava** [comment]
Closing since the Developer Rig has reached its end of support date.
