### ISSUE TITLE
General Category <select> color mismatch

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#161]
**Brief description**

The colors on the Category drop down and mismtached on the Dark theme.

**How to reproduce**

- Console
- Extensions
- Manage an extension
- Manage a version
- Version Details
- Click on the Category drop down

You then have a dropdown with bad colors and cannot read the text.
If you then close the dialog but clicked on the dropper and click again the colors are correct.
Seems something awry between not focus and focused on the parent

**Expected behavior**

Can read the UI

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/86928012-ebad9e80-c12b-11ea-8c87-1f0b05f38fe4.png)

Compared to second click/opening

![image](https://user-images.githubusercontent.com/20999/86928241-38917500-c12c-11ea-922e-390dcfd364a9.png)

Video to demonstrate

https://youtu.be/TqDfCQfCSUw

**Comment by jbulava** [comment]
Do you still seen this today in the developer console?

**Comment by BarryCarlyon** [comment]
I believe this got fixed at some point yes
