### ISSUE TITLE
DevRig panel views: height wrong

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#162]
**Brief description**

Extension views in the developer rig are ignoring the panel height set in the console as of the 1.2.8 release

**How to reproduce**

Have a panel view where the console is set to not 300 and see a view at 300 when it shouldn't be

**Expected behavior**

The selected height

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/86953930-13612e80-c14d-11ea-9f53-787f5e9ddcb7.png)

![image](https://user-images.githubusercontent.com/20999/86953934-15c38880-c14d-11ea-9697-b0f120e7182f.png)

**Additional context or questions**

Discord Report: https://discordapp.com/channels/504015559252377601/530543302622183453/730481748474855607

**Comment by Tenchumaru** [comment]
This is addressed in Developer Rig version 1.2.9.

**Comment by BarryCarlyon** [comment]
Looks for to me
