### ISSUE TITLE
room-id is empty string on CLEARMSG messages

### ISSUE THREAD

**Issue by RAnders00** [twitchdev/issues#163]
**Brief description**
If you listen for `CLEARMSG` messages via IRC, you receive messages whose `room-id` tag is an empty string.
Example:

```none
@login=randers;room-id=;target-msg-id=91a0b09f-bd8a-4150-923f-4c032d953d71;tmi-sent-ts=1594562127680 :tmi.twitch.tv CLEARMSG #pajlada :TESTING abc def 123
```

**How to reproduce**
Connect to IRC and listen for incoming messages on a channel (tags and commands capabilities must be enabled). Then trigger a `CLEARMSG` message via `/delete <message ID>` in chat.

**Expected behavior**
The room ID is present like on other message types

**Screenshots**
![image](https://user-images.githubusercontent.com/1629196/87248164-3004ab80-c458-11ea-9b5f-ad02dd84752a.png)

**Additional context or questions**
Although to be fair the `room-id` is not [documented](https://dev.twitch.tv/docs/irc/tags#clearmsg-twitch-tags) sending an empty string in its place feels silly. I think it would be a good addition/fix to have a proper `room-id` present on those messages.

**Comment by BarryCarlyon** [comment]
As a feature request this may gain more traction if posted to the Developer UserVoice as feature requests go on the UserVoice https://twitch.uservoice.com/forums/310213-developers

**Comment by Xemdo** [comment]
Closing this old ticket as /delete has been removed:
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486

**Comment by iProdigy** [comment]
Delete message functionality still exists via helix and GQL & this bug continues to occur:

`@login=ogprodigy;room-id=;target-msg-id=10e178ca-88a3-4d20-aed0-9fdb471d3226;tmi-sent-ts=1691542954048 :tmi.twitch.tv CLEARMSG #izeeh :test`

**Comment by Xemdo** [comment]
Checking with internal teams to see what the behavior should be.
Since the original post the tag has been documented, but I'm not sure if its used at all. It's just marked as "optional".

**Comment by iProdigy** [comment]
Yeah the optional marker doesn't make sense since any message deletion would have a corresponding channel

**Comment by Xemdo** [comment]
`room-id` was indeed previously not being set, but was appearing as an unset tag regardless. The chat team at Twitch changed it to now include the User ID of the channel.

For example, iProdigy's example would now appear similar to this:
`@login=ogprodigy;room-id=210261439;target-msg-id=10e178ca-88a3-4d20-aed0-9fdb471d3226;tmi-sent-ts=1691542954048 :tmi.twitch.tv CLEARMSG #izeeh :test`
