### ISSUE TITLE
StreamChanged topic does not include mature flag setting

### ISSUE THREAD

**Issue by csharpfritz** [twitchdev/issues#167]
**Brief description**
The StreamChanged topic "https://api.twitch.tv/helix/streams" does not report the mature flag when sending notifications

**How to reproduce**
Trigger the stream changed event, the field is not included

**Expected behavior**
Mature property in the payload, similar to the v5 GetStreamByUser payload:  https://dev.twitch.tv/docs/v5/reference/streams#get-stream-by-user

**Comment by kaldune** [comment]
This would be nice to have and allows us to provide filter capability based on user preference.

**Comment by BarryCarlyon** [comment]
Not a bug, but a feature request

There is already a feature request for this on the Uservoice

https://twitch.uservoice.com/forums/310213-developers/suggestions/38375011-mature-flag-on-get-streams-endpoint

**Comment by lleadbet** [comment]
As Barry noted, this is a field that doesn't exist on the current version of the Twitch API, so it wouldn't be in the webhook. 

Please feel free to vote/comment on the link Barry noted- feature requests are reviewed and monitored there.
