### ISSUE TITLE
Embedded player does not work with blocked 3rd party cookies

### ISSUE THREAD

**Issue by oliverfindl** [twitchdev/issues#168]
**Brief description:**
If browser is set to block 3rd party cookies, embedded player does not work.

Errors from Chrome console:
```
Failed to get log level override from local storage.
7:41:28 PM [ERROR] Uncaught error. DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
Errors from Firefox console:
```
Failed to get log level override from local storage.
7:42:02 PM [ERROR] Uncaught error. DOMException: The operation is insecure.
```

**How to reproduce:**
Set your browser to block 3rd party cookies and try to watch some embedded stream or VOD.

**Expected behavior:**
Working embedded player as before.

**Screenshots:**
N/A

**Additional context or questions:**
- tested using [Non-Interactive Inline Frames for Live Streams and VODs](https://dev.twitch.tv/docs/embed/video-and-clips/#non-interactive-inline-frames-for-live-streams-and-vods) method
- probabaly same issue as [issue #149](https://github.com/twitchdev/issues/issues/149)
- probably related to latest changes with required parent parameter

**Comment by jbulava** [comment]
An update for this issue will potentially go into effect next week.
Internal tracking: ANC-2414.

**Comment by jbulava** [comment]
The fix was deployed on the same day as the comment above. Closing the issue.
