### ISSUE TITLE
twitch - srsly - get your crap fixed

### ISSUE THREAD

**Issue by n0xena** [twitchdev/issues#169]
as twitch support doesnt seem to care:
last weekend I reported these 3 users for streaming F1:

- tarkovic96
- szakuzye
- johnscott406783

they even still have clips of it online
what happened within that week since report? NOTHIN!

really twitch - what's wrong with you?

oauth - crap (violating RFC - hence can'T be used with libs complient to RFC)
api - crap (default is still v3 - you want to use v5? you have to abuse "Accept" header)
support - crap (doesn even somebody care about all what's wrong)
report function - crap (why there's is no option to report copyright infringement like streaming F1?)
bot prevention - crap (uhm - isn't it quite strange that there'Re users which spam about any other user with the same crap link ad? shouldn't it raise suspicious if one account whispers to quite a lot of random other users the same message?)
quality - crap (at least I got a reply to that - which said: "yea, most of our viewers use mobile devices with limited data plans - so we cap at 1080p60 with 6.000kbit/s bandwidth ... oh, and we only offer transcoding for affiliates if there'Re not that many partners online)

does ANYBODY care about the quality of that service? in my eyes not really - it's just another way amazon makes additional money
youtube has so much more to offer - transcoding for anyone - basically limitless bandwidth, quality and resolution (4k60 - no problem width about 50.000kbit/s) - even 360°
the only downside is this crap api quota rate limit of 10.000 per day - even if you only query chat messages along with userdata every 10 sec you munch through your quota in about 3 hours ... and if you want to get more you have to pay g-suite business account
ok - the big players like elgato, streamlabs and whoever is in there all got their raised quotas to support millions of queries ... but if the only downside is that I have to rate-limit my bot to only query once every minute to get long enough time for my several-hour streams - that'S a small price to pay

**Comment by jbulava** [comment]
Off-topic and does not contain bug reports; closing the issue. To provide direct product feedback and constructive suggestions, please use twitch.uservoice.com.
