### ISSUE TITLE
query webhook subscriptions fail with 401

### ISSUE THREAD

**Issue by n0xena** [twitchdev/issues#171]
```
curl -H 'Client-ID: xxx' -H 'Authorization: Bearer xxx' -X GET 'https://api.twitch.tv/helix/webhooks/subscriptions'
{"error":"Unauthorized","status":401,"message":"Must provide valid app token."}
```

**Comment by BarryCarlyon** [comment]
Someone asked this exact issue on the forums

https://discuss.dev.twitch.tv/t/helix-webhooks-subscriptions-fails-with-401/27220/

You need to call the end point with an "App Access Token" as the documentation states

https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-client-credentials-flow

**Comment by n0xena** [comment]
Well, aside from the really weird structure itself the documentation is at least hard to understand, if not vague in some parts. Yes, after you mentioned to me that I require an APP token I realized: "AHHH - it says 'APP token' up there ...", but if you do use it for the very first time it's easy to miss, even if you have read about the different types of tokens (which, btw, also not actually follow suit the RFC same as the wrongly formated scope parameter in a token response message which I also already reported - and, in fact, if this would had been done right from the very start this problem wouldn't exist and now you wouldn't be in a struggle to break pretty much anything IF you MAYBE actually consider to fix it at some point in time in the future - which I may assume correctly will never happen).
Next: I can't see the mention of a "bug" anywhere here - github calls it "issues" for a reason - and this is an issue, even when some may argue it's just bad naming. The doc mentions "user access tokens" and "app access tokens" - and quite honestly - I asked several other devs independently how they understand it - and only ONE did the way the doc tries to suggest - all other did misinterpreted as "well, the user stuff is for anything you do from your side - and that app thingy has be all that overlays and such". So, it's obviously not just ME who seem to struggle quite hard with the way the api is structured and the way the doc is written and misses to explain rather important requirements - along with all that not following the RFC.

As github issues also meant to be some sort of "resolving it" here's some points that missing critical information and what they need to be added:

1) neither the table with the three token types nor the webhook guide explain in anyway that one needs an app token instead of an user token - the most simplest an easy "fix" for that "bug" would be to add this in the webhook guide:
"In order to call webhook subscriptions you require an app token"
this critical information is completely absent from all over the doc
2) better differentiation about "required authentication": just mention some scopes or that rather easy to miss "app token" just doesn'T cut it - the webhook reference completely misses some examples like the rest of the reference - also: yes, althought both are auth tokens - it could be made more visible and by it understandable to call it something else - I'm sure the RFC does in fact offer some rules for such construct - oh, right, I forgot - you don't follow it anyways ... screw it
3) although just related: the way twitch tries to tell v3 and v5 apart - abusing the Accept header isn't the right way - as the Accept header is meant to tell the server what format the client understands - not the type of resource to server should execute
4) another fail as in "nowhere mentioned": the scope moderation:read is only ever mentioned in the five "moderation" typed endpoints - have a look in the scope overview in the guide sections it's missing there - and some other one causes the auth-page to throw the error about illegal scope or some crap ...
5) to keep the pressure up: why the hell isn't there any way to ban and unban users from chat? this is an API - it's meant to be operated OUTSIDE/APART from the actual services - but chat bans - nope - you have to connect to the chat as an user with enough rights to manage bans - although one can retrieve the list of banned users via api ... that's inconsistent

shall I continue? I guess I made my point very clear that there's a ton (yes, of course a metric ton - there's no such thing as a non-metric ton) just completely wrong with the api, it's structure, the oauth flow, the available and not available functions - someone not just had a really bad friday evening - but also a bad weekend and a bad monday morning when who ever the F came up with that pile of crap ... and more severe: instead of any of the big ones standing up and just raising the hand and shouting out load: "wait a second - there's something fishy here ..." just anyone blindly fallen into the trap - making fixing it to comply with the standards it should rely on pretty much impossible without taking a mjor sh!tstorm about breaking about pretty much anything ... THANX !

I leave it up to who ever is in charge to decide what to do about all that mess - but the way I see it: this person is now that much high up in bezos butt he wouldn't be able to hear any complaints ... just rather free following the president: make it murica ...
