### ISSUE TITLE
Sandbox not updated for parent

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#177]
**Brief description**

Sandbox for extensions has not been updated for the parent tag

https://dev.twitch.tv/extensions/sandbox

**How to reproduce**

https://dev.twitch.tv/extensions/sandbox

and test an video extension

**Expected behavior**

Video shows

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/88484602-a41a7580-cf67-11ea-9c30-d69878b0d045.png)

**Additional context or questions**

Reported https://discuss.dev.twitch.tv/t/the-great-big-im-using-wix-somewebsitemaking-tool-and-i-dont-know-how-to-fix-my-embed-thread/26297/262?u=barrycarlyon

**Comment by lleadbet** [comment]
Ticketed internally as E2-512.
