### ISSUE TITLE
PubSub: context: resubgift -> wrong user_name

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#181]
**Brief description**

A new message "context" is occuring on the Subscriptions topic and some of the data is mismatched for the payload is mismatched

The `user_name` should be the `user_name` of the gifter no the giftee
The `display_name` and `recipient` keys are set correctly.

**How to reproduce**

Listen to the subscribers topic on pubsub and wait for a message of context `resubgift`

Example messages

> {"type":"MESSAGE","data":{"topic":"channel-subscribe-events-v1.26610234","message":"{\"benefit_end_month\":0,\"user_name\":\"archangelm\",\"display_name\":\"sirlanceolot\",\"channel_name\":\"cohhcarnage\",\"user_id\":\"43331077\",\"channel_id\":\"26610234\",\"recipient_user_name\":\"archangelm\",\"recipient_display_name\":\"Archangelm\",\"time\":\"2020-07-27T14:02:33.816264969Z\",\"sub_message\":{\"message\":\"Thanks to @sirlanceolot for my sub gift! cohhWaii cohh3\",\"emotes\":[{\"start\":41,\"end\":48,\"id\":\"302744004\"},{\"start\":50,\"end\":54,\"id\":\"301758574\"}]},\"sub_plan\":\"1000\",\"sub_plan_name\":\"CohhCarnage Subscription ($4.99)\",\"months\":0,\"cumulative_months\":40,\"context\":\"resubgift\",\"is_gift\":true,\"multi_month_duration\":0}"}}

> {"type":"MESSAGE","data":{"topic":"channel-subscribe-events-v1.26610234","message":"{\"benefit_end_month\":0,\"user_name\":\"laurix246\",\"display_name\":\"TBoneAble\",\"channel_name\":\"cohhcarnage\",\"user_id\":\"36441361\",\"channel_id\":\"26610234\",\"recipient_user_name\":\"laurix246\",\"recipient_display_name\":\"Laurix246\",\"time\":\"2020-07-23T14:19:42.401636896Z\",\"sub_message\":{\"message\":\"Thanks to @TBoneAble for my sub gift!\",\"emotes\":null},\"sub_plan\":\"1000\",\"sub_plan_name\":\"CohhCarnage Subscription ($4.99)\",\"months\":0,\"cumulative_months\":33,\"context\":\"resubgift\",\"is_gift\":true,\"multi_month_duration\":0}"}}

**Expected behavior**

Message should read

> {"type":"MESSAGE","data":{"topic":"channel-subscribe-events-v1.26610234","message":"{\"benefit_end_month\":0,\"user_name\":\"sirlanceolot\",\"display_name\":\"sirlanceolot\",\"channel_name\":\"cohhcarnage\",\"user_id\":\"43331077\",\"channel_id\":\"26610234\",\"recipient_user_name\":\"archangelm\",\"recipient_display_name\":\"Archangelm\",\"time\":\"2020-07-27T14:02:33.816264969Z\",\"sub_message\":{\"message\":\"Thanks to @sirlanceolot for my sub gift! cohhWaii cohh3\",\"emotes\":[{\"start\":41,\"end\":48,\"id\":\"302744004\"},{\"start\":50,\"end\":54,\"id\":\"301758574\"}]},\"sub_plan\":\"1000\",\"sub_plan_name\":\"CohhCarnage Subscription ($4.99)\",\"months\":0,\"cumulative_months\":40,\"context\":\"resubgift\",\"is_gift\":true,\"multi_month_duration\":0}"}}

> {"type":"MESSAGE","data":{"topic":"channel-subscribe-events-v1.26610234","message":"{\"benefit_end_month\":0,\"user_name\":\"tboneable\",\"display_name\":\"TBoneAble\",\"channel_name\":\"cohhcarnage\",\"user_id\":\"36441361\",\"channel_id\":\"26610234\",\"recipient_user_name\":\"laurix246\",\"recipient_display_name\":\"Laurix246\",\"time\":\"2020-07-23T14:19:42.401636896Z\",\"sub_message\":{\"message\":\"Thanks to @TBoneAble for my sub gift!\",\"emotes\":null},\"sub_plan\":\"1000\",\"sub_plan_name\":\"CohhCarnage Subscription ($4.99)\",\"months\":0,\"cumulative_months\":33,\"context\":\"resubgift\",\"is_gift\":true,\"multi_month_duration\":0}"}}

**Additional context or questions**

See also

https://twitch.uservoice.com/forums/310213-developers/suggestions/41016568-context-resubgift-in-resub-events

**Comment by jbulava** [comment]
Ticketed internally on SUBS-6659.

**Comment by Xemdo** [comment]
Issue has since been resolved. Closing this out.
