### ISSUE TITLE
Extensions bug

### ISSUE THREAD

**Issue by Matadorsam2** [twitchdev/issues#183]
when i execute the extensions my twitch screen turns grey
![Screenshot_1](https://user-images.githubusercontent.com/69089486/89109020-e6363200-d413-11ea-835b-cd7bbf68638b.png)

**Comment by BarryCarlyon** [comment]
This is an issue you need to raise with the developer of that extension.

They they can investigate and determine if they need to raise a bug with Twitch.

 It doesn't look like a Twitch bug, but a problem with the extension, that extensions developer will need to investigate
