### ISSUE TITLE
Can't create twitch extension

### ISSUE THREAD

**Issue by bradens** [twitchdev/issues#186]
**Brief description**

Try to create a twitch extension with a certain name "Props"

**How to reproduce**

Try to create an extension with the name "Props" 

**Expected behavior**

It should succeed

**Screenshots**

![image](https://user-images.githubusercontent.com/727605/89309502-574e3300-d628-11ea-8f30-bb44f28afc82.png)

**Additional context or questions**

Other names work.

**Comment by BarryCarlyon** [comment]
It's likely that someone else has taken the name "Props" and extension names need to be unique.

**Comment by bradens** [comment]
Ah that makes sense. It would be nice to be told that the name must be unique as well.  

FWIW I did have the name "Props" under another twitch account, deleted it, and am still getting that error.

**Comment by bradens** [comment]
Is there maybe something cached somewhere preventing me from creating that new app with the same name?

**Comment by BarryCarlyon** [comment]
Exactly!

When you delete an extension, the old name stays locked for a undefined/unknown time.

It would of been easier to rename the old extension and rename the newer extension to the old ones name than to delete the older extension.

So you are stuck for a while.

**Comment by bradens** [comment]
Ok we can close this then. Would be nice to have a slightly better error handling here though. 😀
