### ISSUE TITLE
Broken url embed for embed urls

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#188]
**Brief description**
Twitch is sending metadata that makes apps like Discord think that they should show a embed like they would for a channel except you can't cause there isn't a channel to embed but there technically is cause someone created the channel embed before Twitch started using /embed
**How to reproduce**
Just send a chat embed url on Discord like https://www.twitch.tv/embed/bluelava/chat?parent=localhost&no-mobile-redirect=true
**Expected behavior**
Don't show a channel embed
**Screenshots**
![20200805055649](https://user-images.githubusercontent.com/17624700/89370245-8fb14800-d6e0-11ea-873a-205a5e4762a2.png)
**Additional context or questions**
Created as a issue here on request of the Frustrations manager @jbulava himself

**Comment by jbulava** [comment]
A fix has been deployed with yesterday's release.
