### ISSUE TITLE
Docs missing first/pagination on API's that support them

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#19]
**Brief description**

Many API's don't document that they support `first` and `after`

**Expected documentation**

Document first/after in the optional query parameters

**Additional context or questions**

Missing First in `Optional Query Parameters`
- Get Banned Users
- Get Moderators
- Get Moderator Events
- Get Broadcaster Subscriptions
- Get Videos

Missing Pagination in the `Return Values`
- Get Broadcaster Subscriptions
- Get Videos

**Comment by JaielSoft** [comment]
Adding as well:
Some API's need to be quality checked for the descriptions of the parameters like the moderation API ones. 

For example: 

https://dev.twitch.tv/docs/api/reference/#get-banned-users 
and 
https://dev.twitch.tv/docs/api/reference/#get-moderators

have the same description text for the parameter that one gets as response

**Comment by Breci** [comment]
@JaielSoft You should open a different ticket for your issue, it's not the same problem as the one mentioned on this issue

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213/suggestions/39847735
