### ISSUE TITLE
Embed chat has different conversation than native chat

### ISSUE THREAD

**Issue by yuriburk** [twitchdev/issues#190]
Hey all, weird issue I’m encountering during a stream tonight! The conversations happening in the Twitch chat embed I have and the one on the native Twitch site are totally different! For some reason, users in one can’t see the conversation happening in the other and vice versa.

Everything is configured correctly with my iframe embed (with the correct parent link and all that good stuff) so I’m truly stumped here. Tried the “id” param with the channel name and the channel id, none of it is working.

**Comment by lleadbet** [comment]
Can you provide more information and replication steps for the issue?

**Comment by lleadbet** [comment]
@yuriburk - if you're still seeing this and having issues, please feel free to reopen this issue. I'm going to close out as we cannot replicate this issue unfortunately.
