### ISSUE TITLE
HTML Issue

### ISSUE THREAD

**Issue by gaminggearztv** [twitchdev/issues#191]
Hello im using this code to embedded to my website using gator hosting service. 

<html>
  <body>
    
    <div id="twitch-embed"></div>

    
    <script src="https://embed.twitch.tv/embed/v1.js"></script>

    
    <script type="text/javascript">
      new Twitch.Embed("twitch-embed", {
        width: 954,
        height: 580,
        channel: "omegagamingesports",
        // only needed if your site is also embedded on embed.example.com and othersite.example.com 
        parent: ["embed.example.com", "othersite.example.com"]
      });
    </script>
  </body>
</html>

I get this issue:
https://i.gyazo.com/ec2b04e360513c158006af66e210d5f0.png

**Comment by BarryCarlyon** [comment]
- This issue tracker is for bug reports. this isn't a bug

You need to update

    parent: ["embed.example.com", "othersite.example.com"]

To match your website.

https://discuss.dev.twitch.tv/t/the-great-big-im-using-wix-somewebsitemaking-tool-and-i-dont-know-how-to-fix-my-embed-thread/26297/ for further help

**Comment by gaminggearztv** [comment]
Oh sorry, I thought it was a bug since it wasn't working anymore. 

If it's not too much to as what does it need to be changed to to work on the site. 

Twitch channel is omegagamingesports

Website: https://www.omegagamingesports.com/

**Comment by BarryCarlyon** [comment]
https://discuss.dev.twitch.tv/t/the-great-big-im-using-wix-somewebsitemaking-tool-and-i-dont-know-how-to-fix-my-embed-thread/26297/ for further help (not this github)

However change your code to

```
<script type="text/javascript">
  new Twitch.Embed("twitch-embed", {
    width: 954,
    height: 580,
    channel: "omegagamingesports",
    parent: ["www.omegagamingesports.com","components.mywebsitebuilder.com"]
  });
</script>
```

Should do the trick
