### ISSUE TITLE
helix/games requires authentication against the spec

### ISSUE THREAD

**Issue by VPenkov** [twitchdev/issues#192]
**Brief description**
[This page](https://dev.twitch.tv/docs/api/reference#get-games) says `Authentication: none`. This seems incorrect.

**How to reproduce**
Ping https://api.twitch.tv/helix/games?name=Fortnite with correct `Client-ID` and `Accept` header.
Actual result:

```json
{
    "error": "Unauthorized",
    "status": 401,
    "message": "OAuth token is missing"
}
```

**Expected behavior**
A successful response

**Comment by lleadbet** [comment]
[As previously stated](https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916/2), all endpoints now require tokens to get a response. 

The documentation there is noting that there are no scopes required to access that data, and can be accessed with an App Access Token. 

We'll be tracking the doc updates in #155 and you can submit feedback via the widget on various pages.

**Comment by VPenkov** [comment]
But then developers need to spin up lambdas so they can proxy their calls, then figure out how to update the tokens.
This basically kills all client-side API usages, is that the intention?

**Comment by Breci** [comment]
You can still oauth client side only with the [OAuth implicit code flow ](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-implicit-code-flow)

**Comment by VPenkov** [comment]
No, this requires the user to login to a platform they may not have an account on, then through a scary screen that prompts them for access, all to see some widget. A widget that directs traffic to Twitch and does not display data that requires authentication on Twitch. Please tell me someone is working on solving this :)

**Comment by Breci** [comment]
That's how Twitch decided to handle traffic to their API. If you want to avoid people to log in, build a server that handles the requests to Twitch, so you can also manage some data caching, etc.
This is not a bug, so there is no "solving this". If you want to ask for a feature request use https://twitch.uservoice.com/forums/310213-developers

**Comment by VPenkov** [comment]
When I said "solving this", I was suggesting that there was an unexpected behavior. Maybe I should have explained why I was not expecting that:
- The documentation says "Authentication: none". I'm not sure what lleadbet meant when they said "there are no scopes required to access that data" but I'm assuming that it's about additional permissions which would be authorization and not authentication. If my assumption is wrong then my point is wrong here. 
- What I'm trying to access is not data that's normally behind authentication so I don't understand why the API is behind authentication. I understand access control and rate limiting but there are other ways of doing that as evident from the previous versions of the API.
- Speaking of that, I'm assuming that this will break a myriad of pre-existing integrations in an unfixable way (sans extra infrastructure or a scary page that requires an account). It caught me by surprise that a company of the size of Twitch would take a turn like this.

I had a glimpse of the forum mentioned above and it seems that your community echoes the above.

In any case, this looks like a done deal already. For me this means sacrificing a nice-to-have widget and for Twitch this means less traffic sent from my domain. 

Thanks for bearing with me on this!
