### ISSUE TITLE
Twitch clips preview not working

### ISSUE THREAD

**Issue by riyadoshi** [twitchdev/issues#193]
Hello,

I am trying to integrate twitch feature in my vue js project and I want to embed twitch video, clips and live stream preview in that.

I have integrated video and live stream preview with twitch player as below

```
let options = {
                    width: 520,
                    height: 520,
                    video: "366873829",
                    parent: []
                };
                this.player = new Twitch.Player("twitch_embed", options);
```
Now if I want to embed clips in preview,I tried using clip in options,being passed to player object. But it does not seem to work.

So I tried iframe preview which is given in twitch doc https://dev.twitch.tv/docs/embed/video-and-clips#non-interactive-iframes-for-clips

```
<iframe
    src="https://clips.twitch.tv/embed?clip=<slug>&parent=streamernews.example.com"
    height="<height>"
    width="<width>"
    frameborder="<frameborder>"
    scrolling="<scrolling>"
    allowfullscreen="<allow full screen>">
</iframe>

```
But its showing an error like

![Screenshot from 2020-08-12 13-20-49](https://user-images.githubusercontent.com/17445024/89989567-bd792c80-dc9e-11ea-9774-a1230cbfb21f.png)

Please help me how can I achieve this. Is there any other way to preview clips in my vue js project?

Thanks!

**Comment by BarryCarlyon** [comment]
This is not a bug.

It should be on the forums

```
let options = {
                    width: 520,
                    height: 520,
                    video: "366873829",
                    parent: []
                };
```

You declared no parents, and since you passed a parent, it didn't auto detect a parent

```
So I tried iframe preview which is given in twitch doc https://dev.twitch.tv/docs/embed/video-and-clips#non-interactive-iframes-for-clips

<iframe
    src="https://clips.twitch.tv/embed?clip=<slug>&parent=streamernews.example.com"
```

You didn't update the `parent` and left it as the example

Based on your screenshot, your parent is localhost.

Either change your code to, for auto detect

```
let options = {
                    width: 520,
                    height: 520,
                    video: "366873829"
                };
                this.player = new Twitch.Player("twitch_embed", options);
```

or to specify your parents

```
let options = {
                    width: 520,
                    height: 520,
                    video: "366873829",
                    parent: ['localhost']
                };
                this.player = new Twitch.Player("twitch_embed", options);
```

See also the support megathread

https://discuss.dev.twitch.tv/t/the-great-big-im-using-wix-somewebsitemaking-tool-and-i-dont-know-how-to-fix-my-embed-thread/26297/
