### ISSUE TITLE
The game not showing up in search 

### ISSUE THREAD

**Issue by ZiggyTheChaser** [twitchdev/issues#194]
Hi there! 
Just recently I have registered my organization Pepe Soft and uploaded my game Ziggy The Chaser to Twitch. Before that the game was approved by GiantBomb, so the complete procedure was executed according to the given instructions. My problem is that the game is not showing up in search and it does not exist in the game list, I checked it a few times. 
Is there a certain amount of time that needs to pass for the game to show up in search and on the general game list?
Looking forward to hearing back from you! 

Dejan Cicic
Pepe Soft Team

**Comment by lleadbet** [comment]
Hey there- the game is on Twitch, but won't show up in search if nobody has it set as their category when live. Once they're live, it should show up. 

Category: https://www.twitch.tv/directory/game/Ziggy%20The%20Chaser
