### ISSUE TITLE
Chat embed just redirecting to the Twitch front page on iOS

### ISSUE THREAD

**Issue by moocat** [twitchdev/issues#195]
The chat embed is just straight away redirecting to the Twitch front page on iOS (Safari) No need to interact with it to reproduce the bug. Only bugs out if you're logged in to Twitch.

Should be pretty easy to reproduce:
1. Make sure you're logged in to Twitch on Safari iOS
2. View a chat embed
3. See that is says "Failed to load module" for a brief moment, and then redirect to the front page of Twitch.

**Comment by BarryCarlyon** [comment]
I couldn't replicate with https://twitch.extensions.barrycarlyon.co.uk/temp/test_chat.html

![IMG_6B20138E4EE1-1](https://user-images.githubusercontent.com/20999/90149658-a7419e00-dd7c-11ea-92bc-1b242b56f5c8.jpeg)

**Comment by moocat** [comment]
From same page, latest iOS with fresh cleared Safari history and website data.
![image](https://user-images.githubusercontent.com/662289/90151632-35bb1d00-dd87-11ea-9ac1-62d15edfc61a.png)

**Comment by moocat** [comment]
Getting those ghosts with "Failed to load module" before it redirects to the front page.

**Comment by moocat** [comment]
Seems to only happen when you're already logged in to Twitch on Safari (which happens if you use any sort of Twitch oauth.)
I've updated the op.

**Comment by lleadbet** [comment]
Ticketed internally as BROWSER-6731.

**Comment by Xemdo** [comment]
Failed to reproduce on our end. Product has greatly changed since 2020, so I'd be interested in hearing if this is still happening.
