### ISSUE TITLE
Known bot gets kicked from IRC after sending 50 messages (and not 100 like one would expect)

### ISSUE THREAD

**Issue by RAnders00** [twitchdev/issues#198]
**Brief description**
I'm mostly relaying this information from here: https://github.com/pajbot/tmi-rate-limits/issues/3
@cineafx has a known bot (https://dev.twitch.tv/docs/irc/guide#known-and-verified-bots), and as reported above his bot gets kicked from chat after sending exactly 50 messages as a moderator.

One would expect that to happen at 100, which is the documented limit for "Users sending commands or messages to channels in which they have Moderator or Operator status". Arguably it does say 50 for Known bots, but it seems nonsensical that a known bot would have lower rate limits than an ordinary user without any particular special verification status.

**How to reproduce**
- Log into IRC with known bot
- Send `PRIVMSG` messages to a channel with moderator messages, with text 1, 2, 3, 4, ... and so on
- Watch at what number the arriving messages stop, in this case 50 instead of the expected 100

this bash script will take care of it:

```bash
#!/usr/bin/env bash

channel="cineafx"
oauth_token="abcdef"
bot_name="icdbot"

function commands {
  echo "CAP REQ :twitch.tv/commands twitch.tv/tags"
  echo "PASS oauth:$oauth_token"
  echo "NICK $bot_name"

   for i in {1..105}; do
     echo "PRIVMSG #$channel :$i"
   done
}

commands | tee /dev/stderr | nc irc.chat.twitch.tv 6667
```

**Expected behavior**
- messages get cut off at 100, not 50, due to the rate limit.

**Screenshots**
![image](https://user-images.githubusercontent.com/1629196/90339999-4cff4200-dff5-11ea-92f7-2267c220d504.png)

**Additional context or questions**
if there is no intention of fixing the limit for known bots then this could also be seen as a suggestion to improve the documentation in that regard.

**Comment by BarryCarlyon** [comment]
Has this been tested in a channel where the account(s) are a moderator instead of the broadcaster.

Looks like the rate limit might not be applied where the account is the broadcaster, so it's using 50 per 30s as a known bot instead of 100 per 30s as a moderator?

And for this argument, broadcasters are not treated as moderator/operator. so the bug is "not applying moderator limit when account is the broadcaster"?

**Comment by RAnders00** [comment]
Would have to ask @cineafx about that.

**Comment by cineafx** [comment]
Even as a moderator the known bot is getting kicked after exactly 50 message in 30s
![image](https://user-images.githubusercontent.com/7873738/90365067-8ec7d100-e065-11ea-8920-f69b36e57ef0.png)

**Comment by lleadbet** [comment]
Hey everyone - we just deployed a fix for this, so the rate limits should be properly applied. If you don't see that, please ping me and I'll be happy to check in.
