### ISSUE TITLE
Application to increase API Request Rate is gone

### ISSUE THREAD

**Issue by TETYYS** [twitchdev/issues#20]
**Brief description**
There was an application form to apply for API Request Rate increase, however now I can only find a form that is designed only for IRC limit increase. Is it still available?

**Expected documentation**
An application form for API Request Rate increase

**Screenshots**
![chrome_akgn1caQmX](https://user-images.githubusercontent.com/3091645/70929535-fd1e4480-203b-11ea-87bb-14e39ac4fc88.png)

**Comment by Syzuna** [comment]
Currently rate limit increases are only granted to stategic partners and therefore that form does not exist anymore at the moment.

**Comment by jbulava** [comment]
Syzuna is correct. An API limit increase request is no longer available. Our goal is to provide functionality in Helix to support developer use cases in a way that fits into rate limits without needing a manual API rate limit increase process.
