### ISSUE TITLE
PubSub server keeps user-related topic subscriptions alive even after application is disconnected in Twitch account settings

### ISSUE THREAD

**Issue by RAnders00** [twitchdev/issues#201]
**Brief description**
There is no mechanism to disconnect a PubSub listener connection in case the underlying OAuth token gets revoked.

**How to reproduce**
- Use a test account to generate an OAuth token containing some PubSub-related scope, like `whispers:read`: https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=q6batx0epp608isickayubi39itsckt&redirect_uri=https://twitchapps.com/tmi/&scope=whispers:read
- Connect to Twitch PubSub
- Listen to something user-specific that requires authentication, like whispers:
    ```json
    {
        "type": "LISTEN",
        "nonce": "xd123",
        "data": {
            "topics": [
                "whispers.553170741"
            ],
            "auth_token": "xxxxxxxxxxxxxxx"
        }
    }
    ```

- PubSub server acknowledges subscription:
    ```json
    {
        "type": "RESPONSE",
        "error": "",
        "nonce": "xd123"
    }
    ```

- Send your test account some whispers, they will be received under the subscribed topic.

- Now, go to https://www.twitch.tv/settings/connections and disconnect the third-party application that you generated the token with in the first place.

- Now continue to send whisper messages to your test account. They will continue to be received as long as you keep the PubSub connection alive (I suspect if neither end of the connection fails this could be kept alive for days or weeks)

**Expected behavior**

- The PubSub client stops being able to receive the events
- There is some (preferrably documented) type of notification message to the PubSub client that informs them that the subscription has been aborted

**Screenshots**

**Additional context or questions**

**Comment by iProdigy** [comment]
This was added today https://dev.twitch.tv/docs/pubsub/#authorization-revoked
