### ISSUE TITLE
Extension analytics API doesn't work on Organizations

### ISSUE THREAD

**Issue by alacroix** [twitchdev/issues#202]
**Brief description**

When I try to fetch [extension analytics](https://dev.twitch.tv/docs/api/reference#get-extension-analytics) with the `extension_id` parameter to only select the extensions part of my organization (i'm the owner), I end up with a 403 Forbidden Access. 

**How to reproduce**

Create a User Access Token OAuth Token for your extension (in your organization) with the following scope: `analytics:read:extensions` (I used a Authorization Code flow in my case)

If I validate my token, I've got the following (with CLIENT_ID = My extension ID)

```
{
  client_id: 'CLIENT_ID',
  login: 'some-login',
  scopes: [ 'analytics:read:extensions', 'user:read:email' ],
  user_id: 'randomnumber',
  expires_in: 12774
}
```

Simply use a cURL with extension_id parameter corresponding to an extension in your organization:

```
curl -H 'Client-ID: CLIENT_ID' \
-H 'Authorization: Bearer <OAuth Access Token>' \
-X GET 'https://api.twitch.tv/helix/analytics/extensions?extension_id=CLIENT-ID'

{"error":"Forbidden","status":403,"message":"Access Forbidden"}
```

**Expected behavior**

As owner/administrator, I should have access to the extensions analytics of my organization.

**Screenshots**

**Additional context or questions**

When I use a simple cURL without specifying my extension ID:

```
curl -H 'Client-ID: CLIENT_ID' \
-H 'Authorization: Bearer <OAuth Access Token>' \
-X GET 'https://api.twitch.tv/helix/analytics/extensions'

{"error":"Not Found","status":404,"message":"Report Not Found"}
```

Which is normal(?) because I don't have extension on my account, just on the organization.

Do I need something else (or can't I) for requesting analytics on my organization?

Thanks :)

**Comment by lleadbet** [comment]
This has been ticketed internally as E2-490.

**Comment by lleadbet** [comment]
This has been resolved. Thanks for the flag!
