### ISSUE TITLE
HTML responses instead of JSON

### ISSUE THREAD

**Issue by AlexWayfer** [twitchdev/issues#203]
**Brief description**

API should not response with HTML, even for 5xx errors. Templates for 5xx errors, for example `nginx`s, should be formatted as JSON for API servers.

Discussion: https://discuss.dev.twitch.tv/t/html-response-with-502-error-from-api-end-point/27445

**How to reproduce**

Make requests and sometimes you'll get HTML response instead of JSON with 5xx error.

**Expected behavior**

5xx errors are OK, bad things happen, but I want to get it as JSON instead of parsing error via HTML.

**Comment by Breci** [comment]
What do you expect as a response?
a JSON with "error: 500" and "message: something went wrong" ? I mean you can't expect the server to send back valuable information in case of a 500, so just handle errors 500 by checking the status and you will be fine.

**Comment by AlexWayfer** [comment]
> What do you expect as a response?
> a JSON with "error: 500" and "message: something went wrong" ?

Yes, something like that.



> I mean you can't expect the server to send back valuable information in case of a 500

I know, but if a server can render some information (error code and description) as HTML — I'm sure it can do the same as JSON.



> so just handle errors 500 by checking the status and you will be fine.

I think I'll do it, thank you, but there is still a server-side issue.

**Comment by jbulava** [comment]
Thanks for pointing this out, @AlexWayfer. You're right that we should be as consistent as possible with API response formats.  However, as v5 is deprecated, we are not making changes unless there is a major service disruption.

We will certainly keep this in mind moving forward with the latest version of the API.
