### ISSUE TITLE
Twitch developer rig

### ISSUE THREAD

**Issue by JohnyGGG** [twitchdev/issues#205]
**Brief description**
I'm trying to create a project on twitch developer rig. On the 'Select folder' form, when I select a folder nothing happens and I get the following error on developer tools: 

Uncaught (in promise) Error: Cannot read property '0' of undefined
    at EventEmitter.<anonymous> (api.ts:42)
    at Object.onceWrapper (events.js:273)
    at EventEmitter.emit (events.js:182)
**How to reproduce**
Create a project on developer rig
**Expected behavior**
Cannot select a folder
**Screenshots**

**Additional context or questions**

**Comment by Tenchumaru** [comment]
What is the version of your Developer Rig? On what OS are you running the Developer Rig?

**Comment by WanderingBME** [comment]
Same issue here on 1.2.11 running on Catalina 10.15.4.

**Comment by Tenchumaru** [comment]
This is addressed in 1.2.12.
