### ISSUE TITLE
How to loop twitch videos and clips 

### ISSUE THREAD

**Issue by riyadoshi** [twitchdev/issues#206]
Hello,

Can please anyone tell me how can we keep playing videos and clips in twitch embed in loop?

I am using non-interactive embeds for twitch channel,videos and clip preview in my project and I want to replay that when it finishes.

Thanks in advance.

**Comment by BarryCarlyon** [comment]
This is the bug tracker for reporting bugs

For support please join us on either

- The Forums https://discuss.dev.twitch.tv/
- The Discord https://link.twitch.tv/devchat

**Comment by riyadoshi** [comment]
ok.Thanks for the response
