### ISSUE TITLE
Monster Couch is duplicated as an organization

### ISSUE THREAD

**Issue by iamsed** [twitchdev/issues#207]
**Brief description**
I see Monster Couch is duplicated as an organization in the https://dev.twitch.tv/organizations
Even though one of the organizations shows Games: 1 when I switch to those organizations neither of them actually shows any games on the games tab.

**How to reproduce**
:)

**Expected behavior**
The organization should not be duplicated and I should be able to access games.

**Screenshots**
![image](https://user-images.githubusercontent.com/3625532/91319874-2e4f3700-e7bd-11ea-9767-9805d5582264.png)

**Additional context or questions**

**Comment by jbulava** [comment]
Hi @iamsed, can you send this information to developers@twitch.tv?  You'll most likely get an auto-reply, but I'll make sure this gets to someone who can assist with the organization issue.  Since it's not a product bug, I'll close out this ticket.  Thanks!
