### ISSUE TITLE
Blocked users limitations

### ISSUE THREAD

**Issue by 634396b** [twitchdev/issues#208]
**Brief description**
Blocking additional users when at 1000 blocked users replaces previously blocked users.
**How to reproduce**
Block 1000 users and block another user. 
**Expected behavior**
There is no warning/error message or any feedback in response to blocking a user with 1000 users already blocked in the API or Twitch website. 
**Screenshots**
N/A
**Additional context or questions**
1. Could the limit to how many blocked users be increased?
2. In the twitch v5 API for getting blocked users, limit & offset query parameters appear to do nothing. Yes the v5 API is deprecated, but the helix api does not offer any end points for blocking or viewing blocked users.

**Comment by lleadbet** [comment]
@vibosxD - Quick question, when you block a user at the limit you've identified, does the total change at all, or does it remain at 1000? Additionally, does the new block show up at the top of the response?

**Comment by vibosxD** [comment]
@lleadbet  The total remains at 1000 and the user who was blocked is in the response to blocking a user.

**Comment by Xemdo** [comment]
Closing out this issue as v5 has since been fully deprecated and removed.
