### ISSUE TITLE
Summary API Endpoint 404

### ISSUE THREAD

**Issue by xokocodo** [twitchdev/issues#21]
**Brief description**
The streams/summary endpoint does not work with game_name param set properly (e.g. `game=Overwatch`). However, the endpoint DOES seem to work if the game name is downcased (e.g. `game=overwatch`). This behavior is new (started 12/12/2019) and is undocumented. 

**How to reproduce**
```curl -H 'Accept: application/vnd.twitchtv.v5+json' -H 'Client-ID:<clientID>' -X GET 'https://api.twitch.tv/kraken/streams/summary?game=Overwatch'```
returns:
{"error":"Not Found","status":404,"message":"no summary available"}

**Expected behavior**
Returns empty summary or current stats for the game

**Screenshots**
N/A

**Additional context or questions**
It would be nice to get some clarification from Twitch whether or not this is intentional or if it’s being addressed as a bug.

Also, the canonical example for this endpoint in the documentation is failing, so if this is intentional the documentation should be updated.

https://dev.twitch.tv/docs/v5/reference/streams#get-streams-summary

**Comment by jbulava** [comment]
This is ticketed internally as GQL-913. The request is to confirm if this is a bug that needs to be fixed, or if game names now need to be lowercased, and in that case, an update to the docs are needed.
