### ISSUE TITLE
Slowmode chat shows scroll on text input.

### ISSUE THREAD

**Issue by adrianloopz** [twitchdev/issues#210]
**Brief description**
When chat is in slow mode on spanish version of Twitch, the placeholder text is 2 line height and it makes a scroll to exist and it blocks half of the icons button. 
 
**How to reproduce**
Twitch.tv in spanish languaje and slowmode chat. (Google Chrome Browser)
**Expected behavior**
Not to show that scroll.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/13318413/91507325-62902980-e889-11ea-91f8-5d6d2102e3b5.PNG)

**Additional context or questions**
Thank you very much! bug is like this since many many time ago. Hope it gets fixed.

**Comment by jbulava** [comment]
Thanks for the submission, @adrianloopz. We can only address third-party developer products via GitHub Issues though.  The chat category is for bugs related to using Twitch IRC.  Can you add this to the [Chat/Messaging UserVoice forum](https://twitch.uservoice.com/forums/310201-chat-messaging) instead?
