### ISSUE TITLE
Critical Issue with Transactions / Unauthorized response

### ISSUE THREAD

**Issue by streamstickers** [twitchdev/issues#213]
We are facing an issue for users who spend bits. We are not receiving the proper response from the transactions endpoint.

When subscribing to Hub Topic URL https://api.twitch.tv/helix/extensions/transactions
(Valid App Access Token is passed and Client ID also) we receive a response with the following:
query:
{ 'hub.mode': 'denied',
  'hub.reason': 'unauthorized',
  'hub.topic': 'https://api.twitch.tv/helix/extensions/transactions?extension_id=5tbyqce941455yffg7fzg36tp6or8p&first=1' }
headers:
{ host: 'extension.streamstickers.com:8081',
  'user-agent': 'Go-http-client/1.1',
  connection: 'close',
  'accept-encoding': 'gzip' }
method: GET
payload: undefined (no payload)

Additionally:
The same app access token and client id are used for 'https://api.twitch.tv/helix/users' and this works fine. 

This started around 6-8 PM EST. No code changes have been made on our side.

**Comment by BarryCarlyon** [comment]
The issue is also presents on the 

https://dev.twitch.tv/docs/api/reference#get-extension-transactions

End point

The error returned is similar to

        AccessDeniedException: User: arn:aws:sts::SomeNumber:assumed-role/ecsrole-ecstaskroleLetters/MD5Typething is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-west-2:Numners:function:DaggerfallLambda-LambdaFunction-SomeCode\n'

Replace some elements in case they are me/my extension specific

**Comment by lleadbet** [comment]
@BarryCarlyon - This has been resolved. Thanks for flagging!
