### ISSUE TITLE
“Get Videos” endpoint - Problem with some video thumbnails

### ISSUE THREAD

**Issue by esalvi** [twitchdev/issues#214]
Hi.

I’m noticing some video thumbnails doesn’t work correctly. Twitch only returns an image with purple background.

URL Examples (“Get Videos” endpoint):
- https://static-cdn.jtvnw.net/cf_vods/d3c27h4odz752x/3da97cf8cba09d5b1edb_goes_x_490147586_1494702109//thumb/thumb0-1920x1080.jpg
- https://static-cdn.jtvnw.net/cf_vods/d3c27h4odz752x/320212667bc6b8807596_coolifegame_490438370_1494720286//thumb/thumb0-1920x1080.jpg
- https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/03483b660a921cc41a1f_momonkunn_490249218_1494708463//thumb/thumb0-1920x1080.jpg
- https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/fb1753952181cf514c19_bystaxx_492552722_1494852439//thumb/thumb0-1920x1080.jpg

This problem also happens in Twitch web site:

![image](https://user-images.githubusercontent.com/5692158/91886152-327dc780-ec89-11ea-9273-b878dc4f8f3a.png)

![image](https://user-images.githubusercontent.com/5692158/91886228-4fb29600-ec89-11ea-961c-746f86d79c1b.png)

Best regards.

**Comment by lleadbet** [comment]
Hey everyone- thanks for the reports. 

This has been resolved on our end, however you may continue to see these purple thumbnails until the broadcaster restarts their stream. They should be gone shortly!
