### ISSUE TITLE
Helix Get Moderators endpoint returns null data instead of empty array if there are no channel Moderators

### ISSUE THREAD

**Issue by billygerhard** [twitchdev/issues#215]
**Brief description**
https://dev.twitch.tv/docs/api/reference#get-moderators

If a channel has no moderators, the API returns 
```json
{
    "data": null,
    "pagination": {}
}
```
instead of 
```json
{
    "data": [],
    "pagination": {}
}
```
**How to reproduce**
Call https://api.twitch.tv/helix/moderation/moderators with a broadcaster_id on a channel with no moderators.

**Expected behavior**
returns 
```
{
    "data": null,
    "pagination": {}
}
```
**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
This is the same bug as was fixed in #30 

Maybe Twitch needs a sweep across all the endpoints to check it's a blank array rather than a null where relevant!

**Comment by lleadbet** [comment]
Ticketed internally as HLX-1492.

**Comment by deefdragon** [comment]
Not sure if the documentation is generated automatically or not, but in case it is, if you can update the user_id description when working on this, that would be appreciated. [this user voice](https://twitch.uservoice.com/forums/310213-developers/suggestions/40281571-document-correction-for-helix-moderators-endpoint) has been "in progress" for 7 months.

**Comment by jbulava** [comment]
Corrected to return empty array. The UserVoice @deefdragon had been addressed at some point, so I closed that suggestion on UserVoice as well.
