### ISSUE TITLE
Submit extension error

### ISSUE THREAD

**Issue by aplinxy9plin** [twitchdev/issues#217]
I have a problem with submit for review. I got this:
![image](https://user-images.githubusercontent.com/6073897/92328817-9d663e80-f08d-11ea-9932-94f07c643dfb.png)

but I filled in all the fields in the version details. Including Terms of Service URL and Privacy Policy URL.
I tried uploading all images again, including screenshots. But nothing.

**Comment by lleadbet** [comment]
Hello!

Do you mind checking out https://discuss.dev.twitch.tv/t/cant-submit-new-version-for-review-missing-required-information/23130/18 and seeing if any of the replies fix it for you?

**Comment by lleadbet** [comment]
Hi there! 

If you you tried the above and are still seeing this, please feel free to reopen, otherwise I'm going to close for now.
