### ISSUE TITLE
Fetching a token returns `bearer` but Helix doesn't accept `bearer`

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#219]
**Brief description**

https://dev.twitch.tv/docs/authentication/getting-tokens-oauth

When you get a token, it returns `token_type` as `bearer`

If you take this value as is and call helix endpoints it doesn't work as helix only accepts `Bearer`

**How to reproduce**

- Generate a token
- Construct a header using the returned data by concatenating elements from the returned JSON

``` `Authorization: ' . token_type . ' ' . access_token```

- Call a helix endpoint
- Get a 401

**Expected behavior**

Twitch accepts `Bearer` and `bearer` as valid

or

returns `Bearer` as the token type when fetching a token.

**Additional context or questions**

I'm not sure what the correct solutions is after a brief perusal of the RFC's

**Comment by lleadbet** [comment]
Hi @BarryCarlyon! 

Do you mind filing this as a Uservoice? At the moment the teams don't consider this a bug, but definitely something we'd like to explore as a possible feature improvement. 

Thanks!

**Comment by BarryCarlyon** [comment]
PFFFFT

https://twitch.uservoice.com/forums/310213-developers/suggestions/41446723-fetching-a-token-returns-bearer-but-helix-doesn
