### ISSUE TITLE
Game analytics API doesn't work on Organizations

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#223]
**Brief description**

Same issue as #202 but for Game Analytics

**How to reproduce**

1) Get a API key with `analytics:read:games`
2) Response is an empty array `{ data: [] }`

**Expected behavior**

Analytics is returned

**Additional context or questions**

**Comment by lleadbet** [comment]
We have resolved #202 - are you still seeing this?

**Comment by BarryCarlyon** [comment]
Yeah

If I authenticate as me (no games at all) HTTP 403
If authenticated as someone in a Organisation ` { data: [] }` at time for writing

The documentation doesn't cover the 403 - 'User Has No Access To Any Games'

https://dev.twitch.tv/docs/api/reference#get-game-analytics

So dunno if that missing from the docs or something else

So if I get a non 4xx code I should _assume_ they have games even if the response is an empty data array?

**Comment by lleadbet** [comment]
Thanks, Barry! Flagged to the team.

**Comment by lleadbet** [comment]
@BarryCarlyon - got it. Do you have the user ID handy? 

This sounds like it might be expected although the error codes aren't documented.

**Comment by lleadbet** [comment]
@BarryCarlyon - wanted to check in on this. :)

**Comment by lleadbet** [comment]
To the point you raised in the above note, yes, a non 4XX error indicates they should have a report. Otherwise, treat it as if they either don't have a report, or don't have access to a report.
