### ISSUE TITLE
Modify Channel Information is not propagated correctly on twitch

### ISSUE THREAD

**Issue by sogehige** [twitchdev/issues#224]
**Brief description**
If game is changed with PATCH https://api.twitch.tv/helix/channels. Change is not properly propagated on Twitch site.

We already pointed that out on https://discuss.dev.twitch.tv/t/announcing-the-latest-helix-endpoints-and-hype-train-api/26530/25?u=sogehige without any response.

This introduces several problems (out of my head)
a) Game is not changed in channel listing
b) Game is not changed for clip creation

What is correctly changed
a) Game is changed in dashboard
b) Game is changed on channel page
c) API have game changed

**How to reproduce**
Patch game in https://api.twitch.tv/helix/channels endpoint

**Expected behavior**
Game change is propagated across twitch

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
Here's what I've got, having just done a change via the API

![image](https://user-images.githubusercontent.com/20999/93619714-d62cde80-f9d0-11ea-9dec-e9331e11c455.png)

Channel is "missing" from the Directory category, but is showing on the API category lookup.
So I don't get a proper change on the channel page it just disappears for a while instead/or until reload the actual channel page

Somethings is a bit screwy propagation wise somewhere

**Comment by zikaeroh** [comment]
For me, the old API (kraken) doesn't update when the helix API changes things; I'm guessing that is more propagation stuff. (Wasn't mentioned in the original post, but was mentioned on that discussion thread with no answer.)

A real shame, because this is almost the last endpoint I need to drop kraken. 🙁

**Comment by zikaeroh** [comment]
I've just retested this, and I believe that the propagation problem is gone. I'd be interested to see if anyone here has seen the same (before I rip out the last of my kraken code for this :slightly_smiling_face:).
