### ISSUE TITLE
Helix Stream shows game_id that does not exist (duplicate game issue)

### ISSUE THREAD

**Issue by kaldune** [twitchdev/issues#225]
**Brief description**

Game does not exist.

**How to reproduce**

https://api.twitch.tv/helix/streams?user_login=mommarb

returns game_id "2031465855"

```json
{
    "data": [
        {
            "id": "646933154",
            "user_id": "90735664",
            "user_name": "MommaRB",
            "game_id": "2031465855",
            "type": "live",
            "title": "Chaos/Crystal DRINKS !discord #teamb42",
            "viewer_count": 4,
            "started_at": "2020-09-19T01:29:04Z",
            "language": "en",
            "thumbnail_url": "https://static-cdn.jtvnw.net/previews-ttv/live_user_mommarb-{width}x{height}.jpg",
            "tag_ids": [
                "6ea6bca4-4712-4ab9-a906-e3336a9d8039",
                "dcf598ca-b5de-47d4-af33-ecabe9eaeee1",
                "353ab6ac-a0ee-404e-9bfa-217446b97718"
            ]
        }
    ],
    "pagination": {}
}
````

https://api.twitch.tv/helix/games?id=2031465855

returns no data

```json
{
    "data": []
}
```

**Expected behavior**

always return a game object for every helix stream

**Screenshots**

**Additional context or questions**

**Comment by iProdigy** [comment]
Note: the streamer did not have a valid game set at the time - https://i.imgur.com/rOnJ21p.png

Things seem to be fine after they set the game properly - https://i.imgur.com/kAbv9IP.png

**Comment by kaldune** [comment]
That's not what happened.

2031465855 was the game_id for FINAL FANTASY XIV Online but has since been deactivated. That's why the streamer didn't have a game set at the time.

Now the game_id is replaced by 24241.

```json
{
    "data": [
        {
            "id": "24241",
            "name": "FINAL FANTASY XIV Online",
            "box_art_url": "https://static-cdn.jtvnw.net/ttv-boxart/FINAL%20FANTASY%20XIV%20Online-{width}x{height}.jpg"
        }
    ]
}
```

When a game gets deactivated, the helix streams endpoint have stale data. This is what caused the issue.

**Comment by BarryCarlyon** [comment]
Yeah this isn't a bug.

The channel was set to a game that was removed/moved and Twitch won't go back and update everyone set to the wrong game to another game. Since this (probably) wasn't a move but a duplication removal.

Might be warranted to raise a uservoice feature request, so Twitch does _something_ to channels if a game that channel is set to is removed

**Comment by kaldune** [comment]
@BarryCarlyon Now there are two Music games. This is the first time I've seen the issue ever and it's breaking things on our end because there should never be a duplicate of a game. I can try the user voice.

```json
{
    "data": [
        {
            "id": "749080534",
            "name": "Music",
            "box_art_url": "https://static-cdn.jtvnw.net/ttv-boxart/Music-{width}x{height}.jpg"
        },
        {
            "id": "26936",
            "name": "Music",
            "box_art_url": "https://static-cdn.jtvnw.net/ttv-boxart/Music-{width}x{height}.jpg"
        }
    ]
}
```

**Comment by lleadbet** [comment]
Hi everyone! 

Thanks for flagging these. We've resolved the two noted above, but I'll leave this open for now in case you see any further. 

I'll close this in a few days. :)

**Comment by kaldune** [comment]
@lleadbet I created my unique keys incorrectly. I have a unique key on the box_art_url and game_id but not the name.

One duplicate was found.

![image](https://user-images.githubusercontent.com/64940906/93814569-8c7b0880-fc09-11ea-9324-2801ce051249.png)

![image](https://user-images.githubusercontent.com/64940906/93814880-03180600-fc0a-11ea-88de-5b2a7ce31ffa.png)

If duplicate games can return from the Helix API, then I will figure out how to handle it on my end.

**Comment by kaldune** [comment]
It turns out there is lots of duplicates from the past but only the Music category has live streams with duplicate games. I'll let you know if I find any more.

![image](https://user-images.githubusercontent.com/64940906/93822549-3dd36b80-fc15-11ea-9e18-aa94fd0e0e3d.png)

**Comment by lleadbet** [comment]
@kaldune - Flagged both, thanks!

**Comment by kaldune** [comment]
@lleadbet Twitch Sings has two streams pointing to different game_id's

![image](https://user-images.githubusercontent.com/64940906/93832603-11c2e500-fc2b-11ea-8621-d19976bce9c9.png)

![image](https://user-images.githubusercontent.com/64940906/93832681-4afb5500-fc2b-11ea-8cd2-c31095c592ab.png)

Here's the full list.

```
Age of Empires II: The Age of Kings	13389
Age of Empires II: The Age of Kings	505373
Call of Duty: Warzone	1614555304
Call of Duty: Warzone	516666
Kingdom Hearts HD 1.5 + 2.5 ReMIX	494099
Kingdom Hearts HD 1.5 + 2.5 Remix	496456
Music	26936
Music	749080534
Resident Evil 2	490868
Resident Evil 2	8645
System Shock	12801
System Shock	516082
Twitch Sings	280582309
Twitch Sings	509481
```

**Comment by kaldune** [comment]
The list of streams that point to different game_id's grew overnight.

```
Chess	1722425209
Chess	743
God of War	1821221053
God of War	6369
Pathologic 2	1865303615
Pathologic 2	6652
Resident Evil 2	490868
Resident Evil 2	8645
Sabotaj	405890966
Sabotaj	517476
Spelunky	1360153950
Spelunky	22619
Tetris	1434410339
Tetris	1736
Trials of Mana	1186
Trials of Mana	512997
```

```
God of War	1821221053	wscieklakoala	2020-09-22 16:23:52.0000000 +00:00
God of War	6369	missladyjay	2020-09-22 16:35:47.0000000 +00:00
God of War	6369	professorxavier_rex	2020-09-22 16:20:58.0000000 +00:00
```

Seems to be an ongoing thing now. This never happened prior to Friday 9/18.

**Comment by kaldune** [comment]
When someone searches 'god of war' on Twitch, there is only 1 result.

![image](https://user-images.githubusercontent.com/64940906/93919148-24d4c400-fcc2-11ea-9302-61ceb1fbf4b1.png)

How is this possible when 6369 and 1821221053 are both God of War? Does each game have an array of game_id now?

If each game_id is supposed to be a different game, then it would look like this:

![image](https://user-images.githubusercontent.com/64940906/93919338-65ccd880-fcc2-11ea-87f7-aac0f55f6dfc.png)

**Comment by kaldune** [comment]
I still see duplicates but it seems there's nothing to be done about it. Closing issue.
