### ISSUE TITLE
Game Disappearing from Dev Dashboard

### ISSUE THREAD

**Issue by MonicaSzabo** [twitchdev/issues#226]
**Brief description**

Hello!

A game that belongs to my company has disappeared from our dev dashboard. This interrupts our twitch integration services.
A previous outage occurred on Friday, 9/18 from 18:30 UTC to 20:00 UTC.
It is most recently disabled today, 9/21, starting at 16:45 UTC.

(Please note: These are exact time stamps, not rounded.)

This has previously resolved on its own, but we don't know why this is happening, and we would like to prevent it from happening again. Can you have someone contact us for more details?

**How to reproduce**

This seems to be happening randomly.

**Expected behavior**

Games do not disappear from the dev dashboard.

**Additional context or questions**

The disappearance of this title affects our twitch integration services; we stop receiving calls from the Twitch API.

**Comment by lleadbet** [comment]
Hello! 

What games are you seeing disappear?

**Comment by MonicaSzabo** [comment]
Eternal from Dire Wolf Digital's official account.

**Comment by lleadbet** [comment]
Sorry about the delay on this- looks like you have access to the game again. Sorry about that!
