### ISSUE TITLE
Spelling Error on Scopes + Invalid Scope 

### ISSUE THREAD

**Issue by TroyDota** [twitchdev/issues#229]
**Brief description**
1. Spelling Error (see attachment)
2. `channel:manage:extension` is invalid is a user requests for it.

**How to reproduce**
1. Read the spelling error.
2. Try request `channel:manage:extension` scope.

**Expected behavior**
1. Spelt Correctly
2. The scope is not invalid.

**Screenshots**
![spelling](https://user-images.githubusercontent.com/49777269/94234063-36f47380-ff09-11ea-85c9-db1af39524f4.PNG)
**Additional context or questions**

**Comment by TroyDota** [comment]
Documentation.

**Comment by BarryCarlyon** [comment]
Documentation issues go to the uservoice

https://twitch.uservoice.com/forums/310213-developers?category_id=358000

**Comment by lleadbet** [comment]
As Barry correctly noted, doc issues should go to the above link. Additionally, the extension scope is also a misspelling: 

`channel:mangage:extensions` (plural) works. 

Apologies for that!
