### ISSUE TITLE
onContext limited data when in popout  mode and config view(s)

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#232]
**Brief description**

An extension in popout mode with onContext lacks the player information that is presented to onContext when in "regular/on the page" mode

Most notably missing is `hlsLatencyBroadcaster` which some extensions use to time/sync extension events with the stream

**How to reproduce**

Repro code in this gist

https://gist.github.com/BarryCarlyon/71c15dc7f82f28ef5c59064be74e065a

**Expected behavior**

Consistency in data provided to `onContext` regardless of mode

**Screenshots**

As a popped out panel:

![image](https://user-images.githubusercontent.com/20999/94929050-75b39c00-04bc-11eb-80b0-f59d9a59852b.png)

As config or live config view

![image](https://user-images.githubusercontent.com/20999/94940214-1e68f800-04cb-11eb-9273-38b8cbcbaa72.png)

**Additional context or questions**

**Comment by lleadbet** [comment]
Hi there!

This is unfortunately expected for popout extensions views, but we're going to make sure this is well-documented going forward. 

I've gone ahead and filed the Uservoice here: https://twitch.uservoice.com/forums/310213-developers/suggestions/41761504-pop-out-extensions-should-include-same-context-as 

Appreciate the flag on this, though!
