### ISSUE TITLE
Helix category search returns null instead of empty array

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#238]
**Brief description**

As per #215 and #30 but for 

https://dev.twitch.tv/docs/api/reference#search-categories

**How to reproduce**

https://api.twitch.tv/helix/search/categories?query=sdflkjasdfklasdjjklasdf

Returns

```
{
"data": null,
"pagination": {}
}
```

**Expected behavior**

Return

```
{
"data": [],
"pagination": {}
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/95000747-58192c00-05bb-11eb-9078-a47915e61ed8.png)

**Comment by lleadbet** [comment]
Ticketed internally as HLX-1492 (same as previous ticket).

**Comment by jbulava** [comment]
Empty array is now returned as documented.
