### ISSUE TITLE
OpenID: Discovery endpoint scopes incorrect for upcoming changes

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#24]
**Brief description**

The changelog declares

> Updated the Getting Tokens OIDC doc to note that the email and email_verified claims will soon be gated by user:read:email scope.

But as per the "Discovery Endpoint" Documented at https://dev.twitch.tv/docs/authentication/#types-of-tokens found at https://id.twitch.tv/oauth2/.well-known/openid-configuration

It has not had it's `scopes_supported` updated to declare `user:read:email` as a valid scope.

**How to reproduce**

Load https://id.twitch.tv/oauth2/.well-known/openid-configuration

**Expected behavior**

scopes to read:

    "scopes_supported": [
        "openid",
        "user:read:email"
    ],

**Additional context or questions**

If #23 is accepted, this issue will need relabeling.

**Comment by mauerbac** [comment]
IDPLAT-3001

**Comment by lleadbet** [comment]
This is going to be updated shortly- the changelog had this change noted, but the change wasn't actually implemented yet. 

We'll update the discovery endpoint with these changes as well. Thanks for the flag, Barry.
