### ISSUE TITLE
Incorrect _id returned by streams endpoint

### ISSUE THREAD

**Issue by vanym** [twitchdev/issues#243]
**Brief description**
"_id" parameter returned by streams endpoint don't equals (less then) "broadcast_id" of last (currently increasing) "archive" video.
It equals "broadcast_id" of forth video in "archive".

**How to reproduce**
I do not know, maybe screenshot, logs and context will help you.
All responses was incorrect while that stream was running.
I guess you can find same cases in currently running streams by comparing id from streams endpoint and greatest broadcast_id from videos endpoint.

**Expected behavior**
Expect to current stream id be same as "broadcast_id" of current video in archive.

**Logs**
Streams request: https://pastebin.com/raw/yAFDw41S
Videos request 1: https://pastebin.com/raw/6wUXSH0Y
Videos request 2 (some time after): https://pastebin.com/raw/ENS9tmj5
("Date" header can help you understand timeline)

**Screenshots**
Past broadcasts tab: https://i.imgur.com/68GnMEy.png
(screenshot was made right after videos req 2)

**Additional context**
As you can see streams request returned object with "_id": 39735470556, "created_at": "2020-10-21T18:02:07Z".
Same id and created_at has forth object of videos request.

First object of videos request has greater id and created date.
By the difference in "length" parameter of first object in videos req 1 and req 2 you can see that it is archive video of running stream. ("broadcast_id": 39735567548)

Looks like stream breaks first minutes and only forth try become stable, but api returns id of first try.

**Comment by BarryCarlyon** [comment]
This isn't a bug.

It's just not a way to align a stream with a VOD

**Comment by vanym** [comment]
Okay, thanks, its little bit strange, but don't cause any significant problems.
I guess we should close this issue.
