### ISSUE TITLE
Twitch Lolarabia channel IAC Split two competition extension is not working with me

### ISSUE THREAD

**Issue by Amirox1** [twitchdev/issues#244]
**Brief description**
Twitch Channel : https://www.twitch.tv/lolarabia
Extension :  IAC Split two competition extension  
Extension URL: https://dashboard.twitch.tv/extensions/6kt2xusp7rcoq3x7q5kz4n427qm1wz-0.0.2?fbclid=IwAR3NSMaNiiE0GxIDxA_E0XuCDt5aQvGxluAuOCclq5l4-tnMynGITbN-7hs
The Extension is not working doesn't show the welcoming screen 
![image](https://user-images.githubusercontent.com/73341391/96996179-b5a3f700-152f-11eb-988f-41e0a61b2157.png)
so all the other features are not working 
only showing this : 
![image](https://user-images.githubusercontent.com/73341391/96996280-e126e180-152f-11eb-8cb1-b41ceffd12e8.png)

**How to reproduce**
i have no idea what is the problem 
**Expected behavior**
the expected behavior is to show welcome screen for the first time and then calculate the watching time and then give rewards 
**Screenshots**
1. i opened a new explorer (chrome) window
![image](https://user-images.githubusercontent.com/73341391/96996421-221ef600-1530-11eb-8878-aea97290f007.png)
2. i logged in my account 
![image](https://user-images.githubusercontent.com/73341391/96996464-32cf6c00-1530-11eb-9686-50e48695370f.png)
3. my twitch name is : amirox1 and the show is live 
![image](https://user-images.githubusercontent.com/73341391/96996507-44187880-1530-11eb-92e0-c672bf416029.png)
4. no welcome screen showed and the extension looks only like this 
![image](https://user-images.githubusercontent.com/73341391/96996543-54c8ee80-1530-11eb-8ef7-f33c5dfedbc1.png)
5. my twitch account is connected to riot account 
![image](https://user-images.githubusercontent.com/73341391/96996570-64483780-1530-11eb-8943-bc0fe5bc7ba4.png)
6. i got back the extension and i tried different buttons there 
![image](https://user-images.githubusercontent.com/73341391/96996631-76c27100-1530-11eb-8dc0-938fa938f68a.png)
7. A) i tried build extension button :
![image](https://user-images.githubusercontent.com/73341391/96996653-83df6000-1530-11eb-8391-0f7d313db256.png)
B) i tried grant permission : 
![image](https://user-images.githubusercontent.com/73341391/96997462-1cc2ab00-1532-11eb-9b48-c5f3fb9d6f6a.png)
8. i tried contacting riot games iac split 2 support after long discussion over days they told me they didnt program the extension and they have no idea why it is not working and i should reach you (twitch)

**Additional context or questions**
whom should i ask to resolve my problem in the extension ?

**Comment by BarryCarlyon** [comment]
You need to contact the developer of this extension

Which can be found on the information page for this extension

**Comment by jbulava** [comment]
Closing the issue as it is feedback for the Extension developer rather that Twitch itself.
