### ISSUE TITLE
Webhook unsubscribe doesnt perform correctly

### ISSUE THREAD

**Issue by marcobuettner** [twitchdev/issues#245]
**Brief description**
Webhook unsubscribe doesnt perform correctly

**How to reproduce**
I make a fiddler request to the webhook and got 202, which means for me the request was successful. But when I look into my webhook subscription the topic is still subscribed

**Expected behavior**
When I got 202 request for unsubscribe the webhook should no more longer include to subscription webhooks

**Screenshots**
![before_removing](https://imgur.com/eVK0m3a.png)
![remove_webook](https://imgur.com/0LS4UE8.png)
![after_removing](https://imgur.com/Ubc7STE.png)

**Comment by BarryCarlyon** [comment]
Not a bug.

When you create or delete a webhook

It makes a HTTP Get request to your callback
Your callback needs to echo the `hub.challenge`

If it doesn't then your webhook will not be created or deleted
