### ISSUE TITLE
Embeds cannot follow a raid

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#246]
**Brief description**

When a raid occurs, the embed tries to follow the raid and dies

**How to reproduce**

Make a embed go on a raid

**Expected behavior**

Not sure what the correct behaviour is

**Screenshots**

Strippin (bottom) raided JesseCox (top)

Resulting in a dead embed

![image](https://user-images.githubusercontent.com/20999/97245281-9be60680-17f2-11eb-9eef-79429fde2b49.png)

`www.twitch.tv failed to connect`

`Refused to display 'https://www.twitch.tv/jessecox?channel=strippin&height=480&migration=true&parent=myvalidparemt&referrer=raid&theme=dark&width=100%25' in a frame because it set 'X-Frame-Options' to 'sameorigin'`

**Comment by lleadbet** [comment]
This was ticketed internally as BROWSER-6858 and has since been resolved - let us know if this hasn't been fixed and feel free to reopen.

**Comment by BarryCarlyon** [comment]
Looks like it has not been resolved it has reoccured

**Comment by Ayrthon** [comment]
Using the embed code from the Twitch docs. The chat still breaks after a raid.

Or did I miss the fix?

**Comment by Phononenom** [comment]
This does not appear to be fixed still
