### ISSUE TITLE
Cannot create ClientID if category is other and the reason is too long

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#249]
**Brief description**

The Client ID Creator will silently fail with a server 500 and no useful error to the user

**How to reproduce**

1. Attempt to Create a ClientID
2. Select the category as other
3. Put a long description in the "other" field that pops up

If you don't blank this field and change to another category you still error 500 transparently

**Expected behavior**

Throws a human friendly error

**Additional context or questions**

https://discordapp.com/channels/504015559252377601/523675960797691915/772851975371882526

**Comment by Xemdo** [comment]
Closing as "Other" no longer prompts for a custom field.
