### ISSUE TITLE
PubSub Docs don't mention Token Type

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#25]
**Brief description**

https://dev.twitch.tv/docs/pubsub#topics

PubSub documentation mentions the requirement to use an oAuth token, but doesn't directly specify which type of token, nor the requirement for the UserID of the token to match the UserID of the topic.

```
Authentication
All topics require an OAuth token, but only some topics have a specific required scope (noted in the table below).

Available Topics
All topics require an OAuth token, but only some topics have a specific required scope (noted in the table).
```

**Expected documentation**

```
Authentication
All topics require a User Access OAuth token, where the UserID of the token matches the userID of the topic, but only some topics have a specific required scope (noted in the table below).

Available Topics
All topics require a User Access OAuth token, where the UserID of the token matches the userID of the topic, but only some topics have a specific required scope (noted in the table).
```

**Additional context or questions**

Raised on the forums at 

https://discuss.dev.twitch.tv/t/only-getting-err-badauth-from-listen-pubsub-request/23598/3

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39847792-pubsub-docs-don-t-mention-token-type
