### ISSUE TITLE
Link to embedded twitch stream on website not working

### ISSUE THREAD

**Issue by emanheimer** [twitchdev/issues#251]
The link to the page on a website that has the embedded twitch stream is not working correctly. It only works if you go to the homepage first and then click on the tab to the page, rather than clicking on the direct link to the page. 

This is what it looks like when you click on www.project88berwyn.org/live: 
![Screen Shot 2020-11-02 at 3 51 17 PM](https://user-images.githubusercontent.com/56458099/97923590-d9332280-1d23-11eb-811b-92b9adfba1d2.png)

This is what it looks like when you go to www.project88berwyn.org and navigate to "Livestream" under the "Concerts" tab:
![Screen Shot 2020-11-02 at 3 51 39 PM](https://user-images.githubusercontent.com/56458099/97923738-1c8d9100-1d24-11eb-95e6-c4d6c49e8e3c.png)

I need pretty urgent help with making the link work. Thank you!

**Comment by iProdigy** [comment]
Hi Emily,

One of the [requirements](https://dev.twitch.tv/docs/embed) for twitch embeds is that the page is served via SSL. Since that first link does not go to a HTTPS page, the player will not work. I would recommend having the homepage automatically redirect to https to avoid this issue

**Comment by lleadbet** [comment]
Hi @emanheimer!

@iProdigy is correct- please take a look at the guidelines and if you have any further questions or issues, feel free to repoen the issue.
