### ISSUE TITLE
503 Error when creating clips on specific channels

### ISSUE THREAD

**Issue by ghost** [twitchdev/issues#253]
**Brief description**
Specific channels always return 503 errors when trying to create clips via the API.

**How to reproduce**
Request clips for botezlive, or adeptthebest, for example

**Expected behavior**
Clip edit URL and ID returned

**Screenshots**
https://gyazo.com/50d2c3d21ad77996a4a98b46b3c2d53f

**Additional context or questions**
N/A

**Comment by Xemdo** [comment]
Cannot reproduce this issue at this time
