### ISSUE TITLE
Erroneous cheermote object

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#257]
**Brief description**
The Get Cheermotes endpoint contains a "Charity" cheermote that has erroneous (although not breaking) values.
```javascript
{
      "prefix": "Charity",
      "tiers": [...], // Omitted as tier data is fine
      "type": "display_only",
      "order": 2147483647,
      "last_updated": "0001-01-01T00:00:00Z",
      "is_charitable": false
    }
```
Issues:

- `order` value far out of standard range (all other cheermotes are incrementally ordered from 1 to 39)
- `last_updated` while a valid date, appears to be a placeholder date so should be updated to where the object was actually last update.d
- `is_charitable` may not be a bug, but it is somewhat odd for the **Charity** Cheermote to not be charitable, so some feedback on the use of this cheermote would be appreciated.

**How to reproduce**
Use the Get Cheermotes endpoint https://api.twitch.tv/helix/bits/cheermotes and look at the entry with prefix "Charity"

**Expected behavior**
My assumption is that the large `order` value is to force it to be the last entry, but this can be achieved by simply setting it to 40, which would be the next, and last, in the incremental order.

`last_updated` should be a realistic date.

Clarification on the Cheermote itself and why a **Charity** cheermote isn't charitable.

**Comment by lleadbet** [comment]
@thedist - This was fixed, although a note that the order is still very high as it's intended to force it as the last option as you correctly noted. 

Otherwise- the last_updated and charitable fields have been fixed.
