### ISSUE TITLE
"justinfan" read-only user without character length limit

### ISSUE THREAD

**Issue by D1360-64RC14** [twitchdev/issues#258]
**Brief description**
The user `justinfan` (used by twitch read-only chat) has no character limit (numbers, in this case)

**How to reproduce**
Connect to Twitch IRC chat with a large nick and you will be successfully connected

JavaScript example:
```js
let ws = new WebSocket("ws://irc-ws.chat.twitch.tv:80")

ws.onmessage = (event) => {
	console.log(event.data)
}
ws.onopen = (event) => {
    ws.send("PASS 0")
	ws.send("NICK justinfan" + Array(100 * 1024).fill("0").join(""))
}
```

**Expected behavior**
I expected to have a nick character limit (128 characters, for exemple)

**Screenshots**
![image](https://user-images.githubusercontent.com/33406930/100707607-ad8a7300-3389-11eb-8025-c63a6ecebedc.png)

**Additional context or questions**
I have not tested in `wss` and `irc` protocols

**Comment by D1360-64RC14** [comment]
Oh, sorry, I mistook "webhook" with "websocket". Someone change the label.

**Comment by lleadbet** [comment]
Ticketed internally as MES-6304

**Comment by lleadbet** [comment]
This should be resolved now.
