### ISSUE TITLE
first - inconsistent data type used

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#260]
**Brief description**

Most endpoints document the `first` parameter as a `integer`

However

https://dev.twitch.tv/docs/api/reference#get-custom-reward-redemption

Documents `first` as a `string`

**Expected documentation**

Consistent across all endpoints for the documentation of `first`

**Comment by lleadbet** [comment]
This was fixed prior to the new year. Thanks for the flag!
