### ISSUE TITLE
Channel Points rewards - background color - add a note

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#262]
**Brief description**

background color doesn't state that the color should be define in ALL CAPS.

Create/Update errors if you do `#ffffff` instead of `#FFFFFF` for the background color

https://dev.twitch.tv/docs/api/reference#create-custom-rewards
https://dev.twitch.tv/docs/api/reference#update-custom-reward

**Expected documentation**

```

background_color | No | string | Custom background color for the reward. Format: Hex with # prefix. Example: #00E5CB. Hex colors should be declared in all capitals.
-- | -- | -- | --

```

**Additional context or questions**

https://discuss.dev.twitch.tv/t/channel-points-api-background-color/29414/

**Comment by lleadbet** [comment]
Ticketed internally as https://jira.twitch.com/browse/POINTS-1738.

**Comment by lleadbet** [comment]
This has been resolved- color codes can now be uppercase or lowercase.
