### ISSUE TITLE
Get Custom Rewards - endpoint params

### ISSUE THREAD

**Issue by jwaugh3** [twitchdev/issues#263]
Brief description

Documentation for getting users manageable rewards provides the URL in the example:
'https://api.twitch.tv/helix/channel_points/custom_rewards?broadcaster_id=274637212?&only_manageable_rewards=true'

Expected Documentation
'https://api.twitch.tv/helix/channel_points/custom_rewards?broadcaster_id=274637212&only_manageable_rewards=true'
('?' between params need removed)

reference: 
[https://dev.twitch.tv/docs/api/reference#get-custom-reward](url)

additional references:
[https://discuss.dev.twitch.tv/t/channel-points-api-get-custom-rewards-endpoint/29428](url)

**Comment by lleadbet** [comment]
This was fixed prior to break, and just confirmed on my end. Appreciate the flag!
