### ISSUE TITLE
Extension Client Configuration show broken UTF characters

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#264]
**Brief description**

The dev console doesn't return the Extension Client Secret correctly.

**How to reproduce**

Try to get the extension client secret

**Expected behavior**

Display the correct extension client secret

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/101724818-541bf580-3aa7-11eb-8811-e7bc8f79d2a0.png)

**Comment by BarryCarlyon** [comment]
![image](https://user-images.githubusercontent.com/20999/101931006-c805ed00-3bd0-11eb-99ab-6c5bb3b32583.png)

Currently seems to be throwing back a string of letters/numbers

It does not base64 encode to match the one I have on file

**Comment by lleadbet** [comment]
@BarryCarlyon - This was fixed this morning. Appreciate the flag as always, Barry.

**Comment by BarryCarlyon** [comment]
Confirmed!
