### ISSUE TITLE
Webhooks sending displayName instead of userName

### ISSUE THREAD

**Issue by Satont** [twitchdev/issues#265]
**Brief description**
In webhooks **stream changed** data array, twitch sending displayname instead of username
**How to reproduce**
Subscribe to stream changes to some user, wait for data.
**Expected behavior**
Should send usernames, instead of displaynames
**Screenshots**

**Additional context or questions**

**Comment by jbulava** [comment]
Webhooks are passing along the payloads from the Twitch API. As such, this issue is reported and will be tracked on Issue #3.
