### ISSUE TITLE
Confusing table order for twitch.ext.configuration.set docs

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#267]
**Brief description**
The reference for the [twitch.ext.configuration.set ](https://dev.twitch.tv/docs/extensions/reference#helper-configuration) function has differing order of params listed for the function, and in the table below the function describing their usage. 

**Expected documentation**
The reference refers to the function as `twitch.ext.configuration.set: void function (segment: String, version: String, content: String)`, and so the table below should be ordered `segment`, `version`, `content`.

**Additional context or questions**
While the table doesn't guarantee order, it's perhaps poor design and has caused some developers to pass params to the function in the wrong order.

**Comment by BarryCarlyon** [comment]
The same "problem" exists for send/listen/unlisten

All tables list the parameters in alphabetic order.

**Comment by thedist** [comment]
Not all tables are alphabetical, such as onTransactionComplete which is not.

**Comment by BarryCarlyon** [comment]
Yes that is the one exception to the rule as noted in discord

https://discord.com/channels/504015559252377601/523676096277905419/788224922429423617

**Comment by jbulava** [comment]
I also find this rather confusing and easy to put things in the wrong order. I've updated the page to be in the order they need to be provided in the function. This update will be included in today' deploy.
