### ISSUE TITLE
Channel Update Notification Example Contradicts Channel Update Event Documentation

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#268]
**Brief description**
[Channel Update Event Documentation](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-update-event) indicates these fields should be present: `broadcaster_user_id` and `broadcaster_user_name`.

[Channel Update Notification Example](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channel-subscriptions) uses `user_id` and `user_name`

**How to reproduce**
Go to the links above

**Expected behavior**
Channel Update Notification Example should be:
```json
{
    "subscription": {
        "id": "f1c2a387-161a-49f9-a165-0f21d7a4e1c4",
        "type": "channel.update",
        "version": "1",
        "condition": {
           "broadcaster_user_id": "1337"
        },
         "transport": {
            "method": "webhook",
            "callback": "https://example.com/webhooks/callback"
        },
        "created_at": "2019-11-16T10:11:12.123Z"
    },
    "event": {
        "broadcaster_user_id": "1337",
        "broadcaster_user_name": "cool_user",
        "title": "Best Stream Ever",
        "language": "en",
        "category_id": "21779",
        "category_name": "Fortnite",
        "is_mature": false
    }
}
```

**Comment by jbulava** [comment]
Corrected in today's documentation deployment.
