### ISSUE TITLE
Extensions fun: How to find where to submit Apple TeamID's

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#27]
**Brief description**

The `NOTE:` text for running an extension on iOS links to a non useful place

**How to reproduce**

- Visit -> https://dev.twitch.tv/console/
- Click Extensions
- Manage an Extension
- Manage a Version
- Click Asset Hosting
- Read the "Note:" text, under Mobile Path
- Click "please contact Twitch Support"
- Be taken to a place that doesn't help

The documentation at: https://dev.twitch.tv/docs/extensions/building/ gives the correct link to the form to submit your iOS Team ID.

**Expected behavior**

Reword or relink the UI to be more useful.

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/71589889-7890f300-2b1e-11ea-98b8-ea58d9d9d2fe.png)

**Additional context or questions**

It's also "annoying" that I have to submit for _each_ extension, rather than just tying an Apple ID to my Account.

Long run would be more useful to have the dev console provide a way to submit/manage your TeamID

**Comment by BarryCarlyon** [comment]
> Click Asset Hosting
> Read the "Note:" text, under Mobile Path

Was fixed, the asset hosting page now direct links to the google form in question.

**Comment by mauerbac** [comment]
Looks fixed
