### ISSUE TITLE
Drops Bugged informations

### ISSUE THREAD

**Issue by Xeideo** [twitchdev/issues#270]
Hello,

im got same strange Bug on your Homage. 

I watching Wargaming.net streams to get drops (if they are activated) and ingame it show and give me sometimes that i get a drop item but on Twitch.tv there is no information and nothing is in my Drop Inventory (https://www.twitch.tv/drops/inventory).
I got Wargaming.net linked since 2 Years now on Twitch.

I was test if this Bug has something to with my settings (PC/HP) and created a 2 Account o Twitch and Ingame to link them and at this Account (same settings like my Main) everything is normal. It shows me the Messages on Twitch and Ingame and i can find everything in the Twitch Drops inventory.

For me it looks like there was some update on Twitch.tv Homepage in last 2 Years that broke something on my main account.

Btw i can still see Drops on other linked thinks like the Twitch Presents i got last week.

Is there anything i can do to help you?

**Comment by lleadbet** [comment]
Hello, you'll need to contact Wargaming to identify this issue. This forum is intended for developer-facing issues only.
