### ISSUE TITLE
Get EventSub Subscriptions "first"

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#271]
**Brief description**

First doesn't work and probably should?
If it shouldn't it throws an error if you `out of bounds` a value

**How to reproduce**

A call to `https://api.twitch.tv/helix/eventsub/subscriptions?first=1`

results in 

```json
{
  "error": "Bad Request",
  "status": 400,
  "message": "The parameter \"first\" was malformed: the value must be greater than or equal to 10"
}
```

And `https://api.twitch.tv/helix/eventsub/subscriptions?first=101`

```json
{
  "error": "Bad Request",
  "status": 400,
  "message": "The parameter \"first\" was malformed: the value must be less than or equal to 100"
}
```

But `https://api.twitch.tv/helix/eventsub/subscriptions?first=50` (or any other "valid" `first` value)

Results in 100 records always

**Expected behavior**

First to work and be added to the documentation in line with other helix endpoints

**Additional Context**

Documentation would need to be updated to say first is supported

https://dev.twitch.tv/docs/eventsub/helix-endpoints#get-eventsub-subscriptions

**Comment by lleadbet** [comment]
Ticketed internally as ASYNC-1570.

**Comment by Xemdo** [comment]
Closing as `first` is no longer supported by the Create EventSub Subscriptions endpoint.
