### ISSUE TITLE
Get EventSub Subs doesn't document `after`

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#272]
**Brief description**

https://dev.twitch.tv/docs/eventsub/helix-endpoints#get-eventsub-subscriptions

Omits the optional query parameter for `after` for cursor usage as per other helix endpoints

**Comment by jbulava** [comment]
Related to #271 and tracking on the same internal ticket, ASYNC-1570.  Helix is accepting `first` and `after` but this functionality is currently not used by EventSub. Whether these should be supported for pagination is being investigated.
