### ISSUE TITLE
Drops inventory has disappeared / Won't load.

### ISSUE THREAD

**Issue by Andreakos** [twitchdev/issues#273]
**Brief description**
When i open inventory page for drops all i get is a black page, i cannot see past drops or claim newest one.
I am able to somehow see them from the Twitch smartphone app, but from desktop, it won't work.
If i create a completely new Twitch account, everything works perfectly, page loads, i can see claimable drops and oldest ones, but that's not a solution for me.

**How to reproduce**
Heading to this page https://www.twitch.tv/drops/inventory with multiple browsers while logged into the Andreakos Twitch account.

**Expected behavior**
Being able to claim newest drops and see the previous ones.

**Screenshots**
![DropsPage](https://user-images.githubusercontent.com/52977790/102616612-1c145280-4138-11eb-909c-bf8777086bfa.jpg)

**Additional context or questions**
Not sure if this is the correct place to report the issue, i also sent in a support ticket directly to Twitch, but it never got fixed.
The Twitch account which is having issues is Andreakos.

**Comment by Tecfan** [comment]
I have the exact same issue. I have over 50 drops on my account, but I can not see them anymore, or get any new drops.

**Comment by BarryCarlyon** [comment]
This bug tracker is for issues with the API/Third party developer stuff

For issues with the main website like this, you need help from `@TwitchSupport` on Twitter or the general uservoice for general bug reports https://twitch.uservoice.com/

You are in the wrong place!

**Comment by lleadbet** [comment]
As Barry noted, I recommend contacting Twitch Support or filing a Uservoice with details. Closing here.
