### ISSUE TITLE
helix/subscriptions give 500 error when "after" or "first" param are not null

### ISSUE THREAD

**Issue by bananneAle** [twitchdev/issues#274]
**Brief description**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
I cannot replicate this

![image](https://user-images.githubusercontent.com/20999/102895531-c05e0800-445c-11eb-8cef-29b583c38763.png)

I tried,

- only `first`
- only `after` 
- both `after` and `first`

What is your repeat steps?

**Comment by lleadbet** [comment]
@bananneAle - Friendly ping for more info as Barry noted. We're unable to replicate here as well.

**Comment by lleadbet** [comment]
Given we've not heard back, going to close. If you have reproduction steps, that'd be much appreciated. Feel free to reopen if you're still seeing this.
