### ISSUE TITLE
Google Analytics in extensions: example not up to date with GA changes

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#277]
**Brief description**

https://dev.twitch.tv/docs/extensions/using-google-analytics-in-extensions

"Next Steps" Is out of date (and badly formatted)

**Expected documentation**

Something more similar to 

```
(​function​(i,s,o,g,r,a,m){i[​'GoogleAnalyticsObject'​]=r;i[r]=i[r]||​function​(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=​1​*​new​ ​Date​();a=s.createElement(o), m=s.getElementsByTagName(o)[​0​];a.async=​1​;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,​'script'​,​'https://www.google-analytics.com/analytics.js'​,​'ga'​);
ga(​'create'​, ​'UA-123456-1'​, {
    cookieFlags: 'max-age=7200;secure;samesite=none'
}​);
ga(​'set'​, ​'anonymizeIp'​, ​true​);
ga('send', 'pageview', 'home');
```

To account for the need for cookieflags.
And this example will also use a "pageview" for the "home" of an extension

**Other notes**

https://www.simoahava.com/analytics/cookieflags-field-google-analytics/

**Comment by jbulava** [comment]
Updated in today's documentation deployment.
