### ISSUE TITLE
emoticon_images missing new data

### ISSUE THREAD

**Issue by bashtech** [twitchdev/issues#278]
**Brief description**

`GET https://api.twitch.tv/kraken/chat/emoticon_images` in Kraken v5 is missing at least some approved emotes added at least over the last week. 

At least two channels have reported this issue: twitch.tv/ryleerawrs and twitch.tv/holak1337. For the ryleerawrs, emotes were approved on 12/19 but still do not appear in the API. 

**How to reproduce**

Compare emotes visible in the emote menu on an affected channel to the API response. 

For example, ryleerawrs as a prefix of "ryleer" but no emotes with that prefix are present in the API response. 

```
curl -H "Client-ID: xxxxx" -H "Accept: application/vnd.twitchtv.v5+json" https://api.twitch.tv/kraken/chat/emoticon_images | jq '.emoticons[] | select(.code | contains("ryleer"))'
```

holak1337 (prefix holak1) returns 6 results in the API but has 15 active emotes.
```
 curl -H "Client-ID: xxxxx" -H "Accept: application/vnd.twitchtv.v5+json" https://api.twitch.tv/kraken/chat/emoticon_images | jq '.emoticons[] | select(.code | contains("holak1"))'
```

**Expected behavior**

All emotes are present in the API response. 

**Screenshots**

ryleerawrs 

https://f.xg.gs/sx-2245-PPX4RTfobqFRBt.png

https://f.xg.gs/sx-2252-Isa5xDrXTIQl1U.png

holak1337 

https://f.xg.gs/sx-2248-6WxvlmYyznbakm.png

https://f.xg.gs/sx-2250-GCV62dkFlTtytC.png

**Additional context or questions**

**Comment by CommanderRoot** [comment]
I can confirm this issues as it's also happening to me. The `last-modified` header on the response makes it seem that the last update was on `Fri, 18 Dec 2020 07:45:10 GMT`
The [Get Chat Emoticons by Set](https://dev.twitch.tv/docs/v5/reference/chat#get-chat-emoticons-by-set) endpoint has the same issue if used withou an `emotesets` parameter.

**Comment by lleadbet** [comment]
Ticketed internally as DIGI-822.

**Comment by lleadbet** [comment]
This has been resolved. Feel free to reopen if you’re still seeing issues.
