### ISSUE TITLE
Twitch Dev Rig error

### ISSUE THREAD

**Issue by GeekFailure** [twitchdev/issues#279]
**Brief description I tried making a new project and I get this error "Check your console log".**

**How to reproduce To reproduce, create a new project and do the first option (Recommended for new users) and then continue.**

**Expected behavior It'll load for a second and say Check your console log.**

**Screenshots https://gyazo.com/e1ada5eaa001e288c7fa6c533b2390cb**

**Additional context or questions Yeah it's my first time using this program.**

**Comment by deanpcmad** [comment]
The Dev Rig is an Electron app so you should be able to access the developer tools by clicking `View -> Toggle Developer Tools` or by <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>I</kbd>

**Comment by BarryCarlyon** [comment]
Or right click on any of the "white" space and you and toggle from there also

**Comment by GeekFailure** [comment]
Okay I know what the issue is which is enabling Javascript?

**Comment by BarryCarlyon** [comment]
The whole Developer Rig is building using Javascript as it's an Electron app.

A few people have reported a similar issue in the Discord, and it seems to be related to Git pathing

So you can try creating a blank project instead

**Comment by GeekFailure** [comment]
Blank project works.
