### ISSUE TITLE
"kraken/channels/follows" response is missing the "_cursor" value

### ISSUE THREAD

**Issue by xxdocobxx** [twitchdev/issues#280]
**Brief description**
`GET https://api.twitch.tv/kraken/channels/<channel ID>/follows??direction=asc&cursor=<cursor>` is sometimes missing the `_cursor` value in response json if the returned list includes the last follower.

**Comment by lleadbet** [comment]
@xxdocobxx - Question for you- are you saying it happens only sometimes, or all the time?

**Comment by Xemdo** [comment]
Closing due to the deprecation of the Kraken API as of January 2023.
