### ISSUE TITLE
RFC2812 compliance for IRC

### ISSUE THREAD

**Issue by casKd-dev** [twitchdev/issues#282]
**Brief description**

The Twitch IRC server/gateway located at irc.chat.twitch.tv:6697 doesn't follow RFC2812[1]. Some messages may cross the 512 character limit which doesn't comply with the standard.

**How to reproduce**

1. Join irc.chat.twitch.tv:6697 with nickname and oauth token
2. Connect to a chatroom
3. From another account, send a long message
3. Receive the message, now with a prefix and passing the 512 character limit

**Expected behavior**

- The server cuts/discards the message
- The clients are not allowed to send messages longer than the limit

**Additional context or questions**

Strict RFC-compliant IRC daemons/clients might not be able to handle the message. I have noticed this behavior when testing things with one daemon i wrote which happened to give this error.
```
[D:L344] Read 512 bytes from socket buffer. Now appending at 512 with ":streamlabs!streamlabs@streamlabs.tmi.twitch.tv PRIVMSG #xxxxxx :REDACTED ....".
[W:L388] Read buffer is full and no message could be parsed.
```
In the above example the message didn't fit in the buffer and the daemon then either had to:
- resize the buffer (ignoring the standard) and continuing to read
- restart the connection
- clear the buffer and attempt to sync again

RFC2812[1] states:
*"IRC messages are always lines of characters terminated with a CR-LF (Carriage Return - Line Feed) pair, and these messages SHALL NOT exceed 512 characters in length, counting all characters including the trailing CR-LF. Thus, there are 510 characters maximum allowed for the command and its parameters.  There is no provision for continuation of message lines.  See section 6 for more details about current implementations."*

However in some cases the combinations of nicknames and usernames plus the long host might end up in the message being too long.

Considering all of the above:
**Is Twitch IRC supposed to follow this standard?**

If yes, i have listed a few ideas on how this could be solved.

**Solution ideas**

1. Shorten the prefix to just the nick (remove optional user and host since they are fixed and Twitch doesn't inter-connect servers)
```prefix     =  servername / ( nickname [ [ "!" user ] "@" host ] )```
2. Negotiate support for longer messages from browser-based chat via IRCv3 cap negotiation (to not break compatibility)

**Resources**
[1] https://tools.ietf.org/html/rfc2812

**Comment by BarryCarlyon** [comment]
Twitch Chat AKA TMI AKA Twitch Messaging interface is not intended to be IRC Compliant

It just implements part of it.

So TMI will never be RFC2812 compliant

Let alone it "speaks" IRC compatible over websockets.

**Comment by 3ventic** [comment]
The chat service is [_generally_ compatible](https://dev.twitch.tv/docs/irc/guide) with [RFC1459](https://tools.ietf.org/html/rfc1459.html), but it is not a fully compliant IRC server. It is a first-party product first and foremost and the requirements of the website and official apps are the priority. IRC clients that strictly follow the spec are indeed not compatible, some truncate the messages while others crash entirely.

The message length limit in chat is currently 500 characters with UTF-8 encoding, which can take up to 4 bytes per character, not including the terminating CRLF.

This isn't to say better compliance will never come, but it would be a breaking change to the current behavior and current integrations.

**Comment by lleadbet** [comment]
Both Barry and 3v are correct- Twitch is not following specification and doesn't intend to be. As such, going to close this since it's expected.
