### ISSUE TITLE
Inconsistency in the PubSub Topics

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#283]
**Brief description**

PubSub inconsistencies

**Expected documentation**

Remove `Example: Commerce Event Message`
Fix bits v2
If v1 is dead/deprecated, remove it from the docs

Also revise

```
Where:

<channel ID> is the _id field returned by the Twitch API v5 Get Channel endpoint.
<user ID> is the _id field returned by the Twitch API v5 Get User endpoint.
```

to the helix equivalents

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/103568284-3599f600-4ebd-11eb-8349-5a6f0084057c.png)

**Additional context or questions**

https://dev.twitch.tv/docs/pubsub#topics
https://discuss.dev.twitch.tv/t/channel-bits-events-v1-doesnt-receive-anything/29771/5

**Comment by lleadbet** [comment]
Ticketed as DXDOC-347.

**Comment by lleadbet** [comment]
This has been completed, so closing the ticket.
