### ISSUE TITLE
Error in "Refreshing access tokens" section

### ISSUE THREAD

**Issue by AndColla** [twitchdev/issues#285]
**Brief description**
The actual docs states that "When you make a request with expired or incorrect authorization credentials, the API returns a `WWW-Authenticate` header (with an invalid_token error) and a 401 Unauthorized status", but the `WWW-Authenticate` header is not present in the response.
Moreover the example shows a kraken endpoint.

**Expected documentation**
The documentation should use an helix endpoint as an example.
The `WWW-Authenticate` header reference should be removed if it's not used anymore by the APIs.

**Comment by lleadbet** [comment]
Ticketed as DXDOC-347.

**Comment by lleadbet** [comment]
This has been completed, so closing the ticket.
