### ISSUE TITLE
People like to use client_secret as EventSub secret in bad practice

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#286]
**Brief description**

A number of times, both on the forums and discord, people have had issues connecting to event sub.
We'll ask them to post their code and often will find they are using their application/client secret as the eventsub secret.

The documentation at 

https://dev.twitch.tv/docs/eventsub
https://dev.twitch.tv/docs/eventsub/eventsub-reference/#transport

Should be revised to clarify what the `transport secret` is and used for, and add a specific note, that the `client secret` should not be used as the `transport secret` 

And yeah, in theory it's _valid_ to use the client secret here, it's just bad practice

**Comment by lleadbet** [comment]
Closing this, as #287 is going to accomplish this as well with a note about not using Client Secrets.
