### ISSUE TITLE
EventSub "secret" restrictions

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#287]
**Brief description**

The EventSub documentation doesn't note anything about the "restrictions" for the "shared secret" which is

> secret must be between 10 and 100 characters

**Expected documentation**

Include a note about the length and any character restirctions of the "shared secret"

**Comment by lleadbet** [comment]
Ticketed as DXDOC-347.

**Comment by lleadbet** [comment]
This has been completed, so closing the ticket.
