### ISSUE TITLE
Helix "Update Redemption Status"

### ISSUE THREAD

**Issue by imerr** [twitchdev/issues#288]
**Brief description**
I've been messing around with the channel point rewards and noticed an error in the api documentation (or an api bug?)
The introduction states:

> Updates the status of Custom Reward Redemption objects on a channel that are in the UNFULFILLED status.
> Only redemptions for a reward **created manually by a broadcaster in the Creator Dashboard**, or created programmatically by the same `client_id` as attached to the access token can be updated.

This would lead you to believe you CAN infact update redeptions for custom rewards manually created by the owner of the oauth token, but this doesn't seem the case (api rejects it with a 403).

Further down it states:
> Authorization
> Requires OAuth Scope: `channel:manage:redemptions`
> The Custom Reward Redemption specified by `id` must be for a Custom Reward created by the `client_id` attached to the access token.

So something is wrong here, unless im completely misunderstanding the wording. Either the api isn't handling this correctly, or the docs are wrong

**Expected documentation**

Removed wording about `created manually by a broadcaster in the Creator Dashboard` from the intro.

**Screenshots**
n/a

**Additional context or questions**
It'd be great if the api could just be updated to allow updating redemption statuses for manually created rewards, but I can definitely see why you wouldn't want to allow that.

**Comment by jbulava** [comment]
Thanks, @imerr.  The team has confirmed that "created manually by a broadcaster in the Creator Dashboard" is inaccurate.  I added this on Friday assuming this was possible and will be correcting it now.  Apologies for the confusion.
