### ISSUE TITLE
Wrong date time format in EventSub docs

### ISSUE THREAD

**Issue by TETYYS** [twitchdev/issues#291]
**Brief description**
In EventSub Subscriptions section, `Twitch-Eventsub-Message-Timestamp` header is mentioned and specified with following format: `2019-11-16T10:11:12.123Z`, while in reality it's different.

**Expected documentation**
Experimentation shows that Twitch sends this request in following format: `2021-01-23T23:03:27Z`.

**Comment by TETYYS** [comment]
I'm now seeing values like in this format: `2021-02-14T17:06:09.899233788Z`. I'm not sure if ngrok has truncated it when I tested it, but I'm sure that now nginx doesn't pull numbers out of thin air. This kind of precision is too much and still doesn't correspond to the example in docs

**Comment by scott-a-white** [comment]
Hello. Thanks for identifying this doc issue. We'll update the doc examples to show the timestamps using nanoseconds. 
The Helix APIs use millisecond resolution (up to 3 decimal places) and EventSub uses nanosecond resolution.
