### ISSUE TITLE
Twitch Player Playback Stats Object Docs Incorrect

### ISSUE THREAD

**Issue by talk2MeGooseman** [twitchdev/issues#292]
**Brief description**
Wanted to bring attention to the docs being incorrect for the “PlaybakStats Object attributes” section of the docs.
The following attributes are all marked as boolean instead of number or string.

- hlsLatencyBroadcaster
- playbackRate
- skippedFrames
- videoResolution

**How to reproduce**
https://dev.twitch.tv/docs/embed/video-and-clips#interactive-frames-for-live-streams-and-vods

**Expected behavior**
Should probably have number type or string type.

**Screenshots**
![image](https://user-images.githubusercontent.com/1203718/105942521-39302100-6014-11eb-80ec-31f11dab13da.png)

**Additional context or questions**
How's your day going?

**Comment by lleadbet** [comment]
Fixed in this week's docs update. :)
