### ISSUE TITLE
Step 2: Sample Code -> search API

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#295]
**Brief description**

https://dev.twitch.tv/docs/api

Step 2 uses uses the "search api". The text does say `This request searches to see if A Seagull is live:`

But there have been a number of people coming into Discord, citing the search API, becuase they only see the sample code and don't go to the reference docs.

**Expected documentation**

~~Link to the "Search Channels" documentation, or mention the "Streams API" instead (or both)~~

The "Streams API" is more appropriate for this example, since search is fuzzy.

**Comment by BarryCarlyon** [comment]
Step 3: Response, is a "poor example" as my own "test" of `https://api.twitch.tv/helix/search/channels?query=a_seagull` returns 3 hits.

So users will not be expecting a more than one result

**Comment by BarryCarlyon** [comment]
I note there is a link to the docs _at the bottom_ 

But it should be more prominent if the example is to stay using search

**Comment by jbulava** [comment]
The example will no longer use search.  I am revamping the API landing page and example and proposing the Twitch CLI as the method to get an OAuth token.  Targeting early next week to get this updated, it's mostly finished. The steps will be:

1. Create a Twitch application, get the client ID
2. Install the CLI, get a bearer token
3. Use the two things above to make a GET channel information call
4. Bonus: explore making API calls directly with the CLI

@lleadbet for visibility, thoughts as well.

**Comment by scott-a-white** [comment]
Closing because the revamped topic is complete.
