### ISSUE TITLE
Rules dialog doesn't new line sentences in an embed

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#297]
**Brief description**

![image](https://user-images.githubusercontent.com/20999/106302145-7da80080-6250-11eb-9ab9-5bbc1802c1f3.png)

**How to reproduce**

In embed via a channel that has rules that you have not accepted yet

**Expected behavior**

Corred word wrapping

**Comment by lleadbet** [comment]
Ticketed internally as MES-6338- this is known to affect the site as well.

**Comment by BarryCarlyon** [comment]
I was trying to replicate using `/rules` which I swear used to work to prompt the rules but doesn't now. Dunno if it's supposed to work.

**Comment by kanawi-twitch** [comment]
To my knowledge `/rules` hasn't been a thing on web, but you can clear a `localStorage` key to reset which rules you have 'seen' in a given browser state.
