### ISSUE TITLE
Bits leaderboard should error if no started_at but period

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#298]
**Brief description**

The [Bits Leaderboard](https://dev.twitch.tv/docs/api/reference#get-bits-leaderboard) says that if you use a `period` of not `all` you need to specify a `started_at` if you don't specify a `started_at` then it doesn't error it just returns no data.

**How to reproduce**

Call `https://api.twitch.tv/helix/bits/leaderboard?count=2&period=week` and get no data

Call `https://api.twitch.tv/helix/bits/leaderboard?started_at=2021-01-29T00:00:00Z&period=week&count=2` and get data.

The former should error indicating the missing `started_at`

**Expected behavior**

If you specify a `period` and no `started_at` return an error

**Additional context or questions**

https://discuss.dev.twitch.tv/t/issue-with-curl-query-for-bits-leaderboard/30201

**Comment by scott-a-white** [comment]
Thanks Barry for the feedback. Going to close this since it looks like the code has been fixed and the doc update will go out in this week's build.
