### ISSUE TITLE
EventSub Missing/blank logins on redemption.update

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#299]
**Brief description**

Event sub presents blank logins for both the user/broadcaster on the `channel.channel_points_custom_reward_redemption.update` topic

**How to reproduce**

Subscribe to the redeem update topic and process a redeem update

**Expected behavior**

Broadcaster/login being not empty

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/106399947-898ff000-6413-11eb-8da5-988dc03d5433.png)

**Additional context or questions**

To confirm this doesn't effect the response to the PATCH that causes the eventsub message

**Comment by lleadbet** [comment]
This has been resolved. :)
