### ISSUE TITLE
Inconsistency in the API on ban check

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#30]
**Brief description**

Get banned users with a single users look, returns `data: null` instead of `data: []` which is inconsitent with other helix API's. Such as Get Streamers or get User

```
{
"data": null,
"pagination": {}
}
```

**How to reproduce**

Call

https://dev.twitch.tv/docs/api/reference#get-banned-users

With a broadcaster_id and a user_id

**Expected behavior**

```
{
"data": [],
"pagination": {}
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/71917652-73642180-3178-11ea-9025-ec58f2d71668.png)

**Additional context or questions**

Not sure if this is a bug or intended? It's just a odd inconsistency

**Comment by lleadbet** [comment]
@BarryCarlyon - to confirm, this was fixed a bit ago. If you're still seeing this, let me know.

**Comment by BarryCarlyon** [comment]
Confirmed looks good now
