### ISSUE TITLE
Helix get Streams: needs a multi user_login/user_id example

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#301]
**Brief description**

Add Example 3, to demonstrate how "Returns streams broadcast by one or more specified user login names. You can specify up to 100 names." works

> This gets information about if Twitch and/or TwitchGaming are live.

```
curl -X GET
'https://api.twitch.tv/helix/streams?user_login=twitch&user_login=twitchgaming' \
-H 'Authorization: Bearer 2gbdx6oar67tqtcmt49t3wpcgycthx' \
-H 'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2'
```

**Comment by lleadbet** [comment]
Fixed in this week's docs update. :)

**Comment by BarryCarlyon** [comment]
I appreicate the use of Space Jam here!
