### ISSUE TITLE
Get users doesn't note the email address for the user needs to be verified

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#303]
**Brief description**

The users endpoint notes that you can get the email address if you apply a token with the relevant scope attached.

https://dev.twitch.tv/docs/api/reference#get-users

However it doesn't mention that the email will only be returned if the scope is applied _and_ the email attached to the account is verified.

**Expected documentation**

Revise

email | string | User’s email address. Returned if the request includes the user:read:email scope.
-- | -- | --

to

email | string | User’s verified email address. Returned if the request includes the user:read:email scope.
-- | -- | --

And

    OAuth token with user:read:email scope required to include the user’s email address in response.

to

    OAuth token with user:read:email scope required to include the user’s verified email address in response.

**Comment by lleadbet** [comment]
Will be fixed in this week's docs update.
