### ISSUE TITLE
IRC doesn't mention that a roomname you join should be lowercase

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#304]
**Brief description**

Specifically `join`

https://dev.twitch.tv/docs/irc/guide#generic-irc-commands

But no where in https://dev.twitch.tv/docs/irc is it covered that a channel/room is only identified as the lowercase/login form

**Additional context or questions**

Leads to odd confusions such as https://discuss.dev.twitch.tv/t/have-to-reload-twitch-channel-to-see-messages-sent-via-irc-socket/30331

**Comment by aidenwallis** [comment]
It is documented. https://dev.twitch.tv/docs/irc/guide#syntax-notes - first line on that section.

**Comment by lleadbet** [comment]
Given the above, going to close out for now.

**Comment by BarryCarlyon** [comment]
It should be added to the JOIN for improved clarity

**Comment by aidenwallis** [comment]
While it could be useful, it does repeat the same piece of information within a few scrolls, considering it's a guide I personally think it's reasonable to keep it in one place on that page, given it's already relatively close to the `JOIN` section on that page.

**Comment by lleadbet** [comment]
Per the above conversation, we'll add a note in the noted section.
