### ISSUE TITLE
invalid redirect URI provided

### ISSUE THREAD

**Issue by FezVrasta** [twitchdev/issues#305]
**Brief description**

I'm trying to setup the OAuth2 Twitch integration with my website, but when I go in the console and I set my URL as "OAuth Redirect URL" it returns the error "invalid redirect URI provided".

**How to reproduce**

Set as URL `https://mydodo.link`, I also tried `https://mydodo.link/twitch-login.html` with the same error.

**Expected behavior**

The URL should be accepted.

**Screenshots**

![image](https://user-images.githubusercontent.com/5382443/107115337-45b24600-686c-11eb-964f-ca6127473a0e.png)

![image](https://user-images.githubusercontent.com/5382443/107115343-506cdb00-686c-11eb-89c5-4c3dad84db01.png)

**Additional context or questions**

**Comment by FezVrasta** [comment]
If I leave localhost it seems to work 🤷‍♂️

**Comment by billygerhard** [comment]
You added a 2nd row but did t populate it so the redirect url is blank. Remove that second row to save
