### ISSUE TITLE
Cannot add redirect url in extension configuration 

### ISSUE THREAD

**Issue by VinChiar** [twitchdev/issues#306]
**Brief description**
When configuring the OAuth2.0 flow for a new extension, I am not able to register a redirect url from the console panel. 

**How to reproduce**
Log in to the Twitch developer console, go to your extension settings and in the Twitch API Client Configuration panel try to add a new redirect url with the Add button, and then save the changes. Independently from the url (https, http, local or remote), the request fails and the url is not added. 
 
**Expected behavior**
The added url(s) shall be registered as valid redirect url(s) for the chosen extension.

**Screenshots**
<img width="628" alt="Screenshot 2021-02-12 at 01 02 18" src="https://user-images.githubusercontent.com/23531722/107714666-fb96ed80-6ccd-11eb-8a1a-74e4bf9d8567.png">

**Additional context or questions**

**Comment by lleadbet** [comment]
Hello - the Add/Remove buttons are for adding additional redirects. If you only have the one, make sure to only fill in that one field and hit "Save".
