### ISSUE TITLE
GetUserExtensions API Requires Edit Privileges to View Deactivated Extensions 

### ISSUE THREAD

**Issue by tpower3** [twitchdev/issues#308]
**Brief description**
Documentation at https://dev.twitch.tv/docs/api/reference#get-user-extensions indicates that you can retrieve both `Activated` and `Deactivated` extensions.  However, when scope permissions are set to `user:read:broadcast`, Deactivated extensions are not retrieved. Setting scope permissions for `user:edit:broadcast` resolves this. It is unexpected that the caller would need edit permissions to view Deactivated extensions. Filing this report to request the documentation be updated to call this out, or if it is incorrect behavior, for it to be resolved.

**Expected documentation**
It's not clear to me if the behavior is a bug or intended behavior. The documentation snippet below only applies if the behavior is intended.
```
Authentication
OAuth token required
Required scope: user:read:broadcast
Optional scope: user:edit:broadcast - Required to retrieve deactivated extensions.
```

**Additional context or questions**
My original post in the extension-help Discord channel contains full context for my original issue and how I resolved it. I've linked it here and pasted the contents below.
https://discord.com/channels/504015559252377601/523676096277905419/810602283342889040

What I'm Trying To Do
My Twitch Extension has a companion client run by the streamer. As part of the onboarding experience, the client checks to see if the extension is installed on your channel and follows the documentation at https://dev.twitch.tv/docs/api/reference#get-user-extensions
Ideally, I'd like to show which of the three states a channel's extension is in:
- Not installed on your channel
- Installed on your channel, but deactivated
- Installed on your channel, and activated

The documentation seems to indicate that I should be able to determine if the extension is installed on the users channel (activated or deactivated)
Gets a list of all extensions **(both active and inactive)** for a specified user, identified by a Bearer token.

I can then use https://dev.twitch.tv/docs/api/reference#get-user-active-extensions to get just the active set of extensions. With these two sets (<All installed extensions> and <All active extensions>), I should be able to determine which of the 3 states the extension is in for your channel.

What I'm Seeing
However I'm finding that get_user_extensions returns empty data when the extension is installed but deactivated. This prevents me from determining if the extension is not installed or just not activated. (note I do not have any other extensions installed on my channel).
{"data":[]}

For reference, if I first go to my channel and activate my extension, I then get the following response when calling get_user_extensions. The fields here all match what I expect.
{"data":[{"id":<CLIENT_ID>,"version":<VERSION>,"name":<NAME>,"can_activate":true,"type":["mobile","overlay"]}]}

My Question
Are my results expected? If not, any suggestions on how to debug this? If so, are there other solutions for determining that an extension is installed but deactivated?

My question above is Resolved!
I was requesting scope permissions for user:read:broadcast, and this was returning the empty result.
I'm expanded the permission request to include user:edit:broadcast and am now getting the expected data returned.

It seems unexpected that I would need edit permissions in order to view the deactivated extensions. Is this a bug? Should the documentation be updated to make this clearer? Or maybe I'm misunderstanding why edit permissions should gate this information and return an empty result instead of an error

**Comment by scott-a-white** [comment]
Hello. Thanks for bringing the issue to our attention. I've updated the doc to include the user:edit:broadcast scope and behavior (the update will go out later this week).
