### ISSUE TITLE
Locales/language valid options

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#31]
**Brief description**

The documentation doesn't advise anything regarding what languages/localses exist/are valid to be called.

For example

https://dev.twitch.tv/docs/api/reference#get-streams

has a `language` query string argument, but doesn't advise what is valid for a langauge.

**Expected documentation**

Document the list of locales of if it matches a ISO, update documentation on endpoints using language/locale with a note about what is valid

**Additional context or questions**

Raised/queried on discord

https://discordapp.com/channels/504015559252377601/523675960797691915/664243349309620225

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848104-locales-language-valid-options
