### ISSUE TITLE
User oAuth Token/Any oAuth token

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#310]
**Brief description**

Some users whom don't understand the API or authentication mechanisms don't understand the difference between User Tokens and Server Tokens

**Expected documentation**

Revise all references to

`OAuth Token required`

on

https://dev.twitch.tv/docs/api/reference

to

`User OAuth Token required`

or

`Client Credentials OAuth Token required`

or 

`Any OAuth Token required`

as appopriate

**Comment by jbulava** [comment]
I think it's important to explicitly state or list "User OAuth Token" and/or "Client Credentials OAuth Token" with each one linking back into an appropriate place in the authentication guide.  I think that and consistent terminology throughout will help.  I could see "any token" being a confusing deadend, unless that also linked to a place in the authentication guide.

**Comment by scott-a-white** [comment]
Thanks for the feedback, Barry. The last doc release identified the type of required access token. The week's build includes links to the Authentication doc.
