### ISSUE TITLE
Update PubSub to use helix scope

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#311]
**Brief description**

Channel Subscriptions topic still references the v5/kraken scope

**Expected documentation**

![image](https://user-images.githubusercontent.com/20999/107965889-fd4d0380-6fa2-11eb-96bb-df155a6c4430.png)

Update to `channel:read:subscriptions` from `channel_subscriptions`

**Comment by lleadbet** [comment]
In this week's doc update.

**Comment by lleadbet** [comment]
Deployed the change on Friday.
