### ISSUE TITLE
/validate endpoint is not reporting full list of scopes when v5 scopes are included

### ISSUE THREAD

**Issue by billygerhard** [twitchdev/issues#312]
**Brief description**
When I generated a new token, I received 

`#access_token=12345&scope=moderation:read+channel:read:subscriptions+channel_subscriptions+channel_check_subscription+channel_read+channel:read:hype_train+channel:read:redemptions&token_type=bearer`

When I check the `/validate` endpoint, I receive 
```
{
    "client_id": "gp762nuuoqcoxypju8c569th9wz7q5",
    "login": "wlg3r",
    "scopes": [
        "channel:read:subscriptions",
        "moderation:read"
    ],
    "user_id": "145796834",
    "expires_in": 0
}
```
The same token on `https://api.twitch.tv/kraken/` returns 
```
{
    "token": {
        "valid": true,
        "authorization": {
            "scopes": [
                "channel:read:hype_train",
                "channel:read:redemptions",
                "channel:read:subscriptions",
                "channel_check_subscription",
                "channel_read",
                "channel_subscriptions",
                "moderation:read"
            ],
            "created_at": "2021-02-15T15:02:37Z",
            "updated_at": "2021-02-15T15:02:37Z"
        },
        "user_name": "wlg3r",
        "user_id": "145796834",
        "client_id": "f32p3no3oxomqviy35liavolqb4gyo",
        "expires_in": 5671147
    }
}
```
**How to reproduce**
Request a token (I used implicit auth) for scopes 
`moderation:read+channel:read:subscriptions+channel_subscriptions+channel_check_subscription+channel_read+channel:read:hype_train+channel:read:redemption`

**Expected behavior**
`/validate` endpoint should always return all scopes

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
Also note that in /validate it returns expires 0
But /kraken is returned a non 0 expires.

**Comment by billygerhard** [comment]
Weird caching issues seems to have cached a different header for a different super old key from tokengenerator that I haven't used in like a year. Redeployed backend to cloud as well, and that worked. I don't know how it happened, it worked Friday, and I didn't touch any code, and it just stopped working this morning.
