### ISSUE TITLE
Bug or Feature: Broadcaster is not a mod of their own channel

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#313]
**Brief description**

Moderation tools such as bot control panels, could allow moderators to edit commands on a channel.

So the panel (at moderator login) will use "Get Moderators" with a userID/broadcasterID pair to see if a given user is a moderator on the channel.

The endpoint doesn't return the broadcaster as being a mod on the channel

**How to reproduce**

Call "Get Moderators" with a suitable oAuth token, where query string parameters of `broadcaster_id` and `user_id` are the same.

**Expected behavior**

Not sure hence this GitHub.

- If it is a bug, please fix Get Moderators
- If it is not a bug, add a note to the documentation for developer clarity:

> Returns all moderators in a channel. The Broadcaster is not considered a moderator of their own channel for this API Endpoint.

**Additional context or questions**

https://dev.twitch.tv/docs/api/reference#get-moderators

**Comment by lleadbet** [comment]
This appears to be expected, so going to update the docs to reflect this.

**Comment by lleadbet** [comment]
Deployed the change on Friday.
