### ISSUE TITLE
popup on FOLLOW/UNFOLLOW dont dissapear

### ISSUE THREAD

**Issue by 1danil10** [twitchdev/issues#315]
**Brief description**
popup(tooltip) doesnt dissapear when mouse out from button.
**How to reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16972926/108390416-b4ef4900-7221-11eb-807b-829913b36c22.jpg)

**Additional context or https://guides.github.com/features/mastering-markdown/questions**

**Comment by BarryCarlyon** [comment]
This is a first party bug and not relevant to this issue tracker.

It should be reported on https://twitch.uservoice.com/ in the corret category

**Comment by lleadbet** [comment]
Barry is correct; please file the bug via the Uservoice link above.
