### ISSUE TITLE
Readable colors

### ISSUE THREAD

**Issue by aegosz** [twitchdev/issues#317]
Readable colors deteriorate after each update. I can even understand in advance that it will be updated if it is broken.

**Comment by BarryCarlyon** [comment]
It is unclear what you refer to.

Which page of the dev site has this issue?

**Comment by aegosz** [comment]
in chat twitch has a readable colors feature. usernames colors make easier to read.

**Comment by BarryCarlyon** [comment]
This is a "first party" problem and needs to be reported on https://twitch.uservoice.com/ in the corret category not here which is the third party API/DevSite tracker

**Comment by lleadbet** [comment]
As Barry noted, general Twitch site issues should be raised on the above UserVoice or via a Support ticket.
