### ISSUE TITLE
Broken links in table

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#318]
**Brief description**
Links broken
**Expected documentation**
Working links
**Screenshots**
![image](https://user-images.githubusercontent.com/17624700/108613725-c2a8f800-73f4-11eb-8297-077071da388b.png)

**Comment by Dkamps18** [comment]
This is happening to all links in tables in the IRC documentation

**Comment by jbulava** [comment]
These links have been corrected and will be deployed on Friday, February 26.
