### ISSUE TITLE
NBL Twitch Extention bugged

### ISSUE THREAD

**Issue by Hayden3000** [twitchdev/issues#322]
Twitch NBL extention is ran by Twitch staff is what is said by NBL staff. As a NBL chat moderator, I do get lots of complaints that it was working for 98% of the last season and then works for the first 2 mins of the start of the game then switches to a future game.

**How to reproduce**

**Expected behavior** Extention is to use NBL stats to gather points to participate against either other viewers.

**Screenshots** N/A

**Comment by BarryCarlyon** [comment]
The only NBL extension I can find is this one

https://dashboard.twitch.tv/extensions/0wuzg8mtzhlj7eji6ckuwhi07bdy1b-1.1.0

You need to contact Muxy on this address

![image](https://user-images.githubusercontent.com/20999/108846008-0444c900-75d6-11eb-8317-55fcb4e382aa.png)

This BugTracker is not for issues with "an extension", you should visit the extensions details page for the support details for that extension
