### ISSUE TITLE
Redeem Code: URL missing Method

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#323]
**Brief description**
In the Redeem Code reference, the URL is missing the POST method that is normally put in front of the URL
**Expected documentation**
`POST` in front of `https://api.twitch.tv/helix/entitlements/code`
**Screenshots**
![RedeemCode](https://user-images.githubusercontent.com/3053654/109263723-644f9100-77c9-11eb-8747-40162fbe8837.png)
**Additional context or questions**
Assuming POST based on example request
[https://dev.twitch.tv/docs/api/reference#redeem-code](https://dev.twitch.tv/docs/api/reference#redeem-code)

**Comment by jbulava** [comment]
Thanks for catching it. The URL also needs an "s" at the end. This has been added to our deployment for Friday.
