### ISSUE TITLE
Replace Stream Tags: Conflicting Maximum Tag Count

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#324]
**Brief description**
In the Replace Stream Tags reference, the tag_ids parameter is listed as having a maximum number of 100 supported values in the parameter, but the documentation the line above says that only 5 can be applied.
**Expected documentation**
Consistent value of tags that will be accepted, or documentation of how extra tags are handled
**Screenshots**
![ReplaceStreamTags](https://user-images.githubusercontent.com/3053654/109264687-fd32dc00-77ca-11eb-87a5-7905bb0e42d6.png)
**Additional context or questions**
[https://dev.twitch.tv/docs/api/reference#replace-stream-tags](https://dev.twitch.tv/docs/api/reference#replace-stream-tags)

**Comment by jbulava** [comment]
Good catch, it's definitely 5 tags.  100 max must have been a copy/paste from user id return values.  Updated for Friday.
