### ISSUE TITLE
Update User: description parameter listed as optional

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#325]
**Brief description**
For the Update User reference, the parameter `description` is the only parameter, and the only action that the endpoint supports, however, the parameter is listed as optional.
**Expected documentation**
Moving of description to required, or explanation of what happens if description is not included.
**Screenshots**
![UpdateUser](https://user-images.githubusercontent.com/3053654/109265437-2acc5500-77cc-11eb-8af3-de29cd489802.png)

**Additional context or questions**
[https://dev.twitch.tv/docs/api/reference#update-user](https://dev.twitch.tv/docs/api/reference#update-user)

**Comment by jbulava** [comment]
We can clarify this better in the docs.  It is intended to be optional. Should we ever add fields that you could also update, we wouldn't want description to be a requirement if you only wanted to update other fields.

**Comment by jbulava** [comment]
Added for today's updates.
