### ISSUE TITLE
Delete Video: No Response Fields, but response shown in example

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#326]
**Brief description**
The Delete Videos reference has an example response containing 
```JSON
{
  "data": [
    "1234",
    "9876"
  ]
}
``` 
but no response fields, or description of the response format. While it can be assumed that the data is the array of videos deleted, it should still be listed in the documentation explicitly.
**Expected documentation**

Inclusion of a Response Fields table, explaining explicitly the data in the response
**Screenshots**

![DeleteVideo](https://user-images.githubusercontent.com/3053654/109266299-7c291400-77cd-11eb-9b4e-d1a170fe6e2f.png)

**Additional context or questions**
[https://dev.twitch.tv/docs/api/reference#delete-videos](https://dev.twitch.tv/docs/api/reference#delete-videos)

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#delete-videos.
