### ISSUE TITLE
Create Custom Rewards: Content-Type Header missing from example

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#327]
**Brief description**
On the docs/api/reference page All other requests that have a json body have a content type header set in the example. Create Custom Rewards does not.
**Expected documentation**
```
curl -X POST 'https://api.twitch.tv/helix/channel_points/custom_rewards?broadcaster_id=274637212' \
-H 'client-id: gx2pv4208cff0ig9ou7nk3riccffxt' \
-H 'Authorization: Bearer vjxv3i0l4zxru966wsnwji51tmpkj2' \
-H 'Content-Type: application/json' \
-d '{
    "title":"game analysis 1v1",
    "cost":50000
}'
```
**Screenshots**
![CreateCustomRewards](https://user-images.githubusercontent.com/3053654/109267897-e6db4f00-77cf-11eb-85e3-b7f2dfe01013.png)

**Additional context or questions**
[https://dev.twitch.tv/docs/api/reference#create-custom-rewards](https://dev.twitch.tv/docs/api/reference#create-custom-rewards)

**Comment by jbulava** [comment]
Added for Friday.
