### ISSUE TITLE
Get All Stream Tags: Response Fields extra field; Example Response poor formatting and errors

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#337]
**Brief description**
`Example Response` JSON has several errors, and is also difficult to read. Last `localization_descriptions` is missing closing brace. The inclusion of 5 localization and the `...` is unnecessary and makes it slightly more difficult to read. Really only the first data is necessary, and the rest can be represented via `...`.

Also: The response fields have an `id` field and a `tag_id` field, with the same description.

**Expected documentation**
```JSON
{
  "data": [
    {
      "tag_id": "621fb5bf-5498-4d8f-b4ac-db4d40d401bf",
      "is_auto": false,
      "localization_names": {
        "bg-bg": "Завършване без продължаване",
        "cs-cz": "Na jeden z&aacute;tah",
        ...
      },
      "localization_descriptions": {
        "bg-bg": "За потоци с акцент върху завършване на аркадна игра с монети, в която не се използва продължаване",
        "cs-cz": "Pro vys&iacute;l&aacute;n&iacute; s důrazem na plněn&iacute; mincov&yacute;ch ark&aacute;dov&yacute;ch her bez použit&iacute; pokračov&aacute;n&iacute;.",
        ...
      }
    },
    ...
  ],
  "pagination": {
    "cursor": "eyJiIjpudWxsLCJhIjp7IkN1cnNvciI6ImV5SnBaQ0k2ZXlKQ0lqcHVkV3hzTENKQ1QwOU1JanB1ZFd4c0xDS kNVeUk2Ym5Wc2JDd2lUQ0k2Ym5Wc2JDd2lUU0k2Ym5Wc2JDd2lUaUk2Ym5Wc2JDd2lUbE1pT201MWJHd3NJazV WVEV3aU9tNTFiR3dzSWxNaU9pSXhZell5T0dJM05TMWlNV016TFRSaE1tWXRPV1F4WkMwd05UWmpNV1kxTlRWb U1HVWlMQ0pUVXlJNmJuVnNiSDE5In19"
  }
}
```
**Screenshots**
![GetAllStreamTags](https://user-images.githubusercontent.com/3053654/109454419-d28a9280-7a19-11eb-9928-659f43fe0147.png)

![GetAllStreanTags2](https://user-images.githubusercontent.com/3053654/109454685-5f355080-7a1a-11eb-9e85-11c7b56158db.png)

**Additional context or questions**
https://dev.twitch.tv/docs/api/reference#get-all-stream-tags

**Comment by jbulava** [comment]
The example payload and return values table have been updated for Friday's deployment.
