### ISSUE TITLE
Get Drops Entitlements: Pagination datatype

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#340]
**Brief description**
The `pagination` datatype is shown in the `Example Response` as a raw string type instead of as the `"pagination":{"cursor":"X"}` object. It is also defined as a string in the Return Values table.
**Expected documentation**
```JSON
{
  "pagination": {
      "cursor":""
  },
  "data": [
  {
      "id": "fb78259e-fb81-4d1b-8333-34a06ffc24c0",
      "benefit_id": "74c52265-e214-48a6-91b9-23b6014e8041",
      "timestamp": "2019-01-28T04:17:53.325Z",
      "user_id": "25009227",
      "game_id": "33214"
  },
  {
      "id": "862750a5-265e-4ab6-9f0a-c64df3d54dd0",
      "benefit_id": "74c52265-e214-48a6-91b9-23b6014e8041",
      "timestamp": "2019-01-28T04:16:53.325Z",
      "user_id": "25009227",
      "game_id": "33214"
  },
  {
      "id": "d8879baa-3966-4d10-8856-15fdd62cce02",
      "benefit_id": "cdfdc5c3-65a2-43bc-8767-fde06eb4ab2c",
      "timestamp": "2019-01-28T04:15:53.325Z",
      "user_id": "25009227",
      "game_id": "33214"
  }]
}
```
**Screenshots**
![GetDropsEntitlements](https://user-images.githubusercontent.com/3053654/109578460-d0c5db00-7abc-11eb-9545-938c89d9d21c.png)

**Additional context or questions**
https://dev.twitch.tv/docs/api/reference#get-drops-entitlements

**Comment by jbulava** [comment]
Great catch, pagination was documented incorrectly. It behaves like the pagination object throughout other helix endpoints and has now been updated.
