### ISSUE TITLE
Create Stream Marker: Example Response JSON data key missing quotes

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#341]
**Brief description**
In the `Example Response` JSON for the Create Stream Markre request, the `data` key is not surrounded by quotes
**Expected documentation**
```JSON
{
  "data": [
     {
        "id": 123,
        "created_at": "2018-08-20T20:10:03Z",
        "description": "hello, this is a marker!",
        "position_seconds": 244
     }
  ]
}
```
**Screenshots**
![CreateStreamMarker](https://user-images.githubusercontent.com/3053654/109602006-78ef9a00-7ae5-11eb-9061-690577fb6a25.png)
**Additional context or questions**
https://dev.twitch.tv/docs/api/reference#create-stream-marker

**Comment by jbulava** [comment]
Fixed for Friday.
