### ISSUE TITLE
Check User Subscription doesn't work with the advertised scope

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#344]
**Brief description**

The new endpoint for checing a subscription via user permission doesn't work with the advertised scope

The response is

> {"error":"Unauthorized","status":401,"message":"Missing scope: user:read:subscriptions or user_subscriptions"}

**How to reproduce**

- Generate a token with _only_ `user:read:subscriptions` applied
- Call the endpoint

**Expected behavior**

- Return the subscription data if any

**Additional context or questions**

https://dev.twitch.tv/docs/api/reference#check-user-subscription

It does work if the token has `channel:read:subscriptions` applied to it..

Discord Discussion https://discord.com/channels/504015559252377601/523675960797691915/820274507175690245

It also doesn't work if you use the legacy/kraken scope.

**Comment by freaktechnik** [comment]
The `user:read:subscriptions` scope works as advertised when querying using an app access token, this issue only affects user tokens.

**Comment by jbulava** [comment]
Fix is in production.

**Comment by mattjuk** [comment]
App access tokens still do not work with user:read:subscriptions in prod.

**Comment by freaktechnik** [comment]
> App access tokens still do not work with user:read:subscriptions in prod.

Still? At the time this issue was filed the app access token behavior was as expected.

**Comment by BarryCarlyon** [comment]
Did you authenticate the user via a user access flow at least once
And then use an app access token.

Or did you start with an app access token?

**Comment by mattjuk** [comment]
Started with an app access token as per the "Getting a Token" documentation on the developer website.

**Comment by BarryCarlyon** [comment]
Thats your issue. You need to have authenticated the user _at least once_ using the user flow.

As otherwise you have no permission to read on behalf of the specified user.

The work flow here is similar to EventSub. You need permission to read for that user for that scope, before you can use an app access token to call the API

**Comment by mattjuk** [comment]
Ok, that's a documentation issue then as the "OAuth client credentials flow" section of "Getting Tokens" completely fails to explain that.

**Comment by BarryCarlyon** [comment]
It is noted on the documentation

https://dev.twitch.tv/docs/api/reference#check-user-subscription

> App Access Token (if the user has authorized your application)

The user authorises an application via a "normal" user oAuth flow.

IE before you can call the endpoint with a "userless token" you need to have asked the user if you are allowed to do that.

**Comment by mattjuk** [comment]
Fair enough - the documentation is still pretty seriously impenetrable on this for someone new to the API though (having used *many* other APIs before, this one is bad).
