### ISSUE TITLE
Check User Subscription always says `is_gift` is false

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#345]
**Brief description**

Testing the endpoint to check a documentation omission

```
{"data":[{"broadcaster_id":"26610234","broadcaster_name":"CohhCarnage","broadcaster_login":"cohhcarnage","is_gift":false,"tier":"1000"}]}
```

The corresponding sub from the `/helix/subscriptions/events` endpoint

```
{
"id": "1philFqHfIEcvXSGwEoeSlLJauI",
"event_type": "subscriptions.subscribe",
"event_timestamp": "2021-03-13T13:24:31Z",
"version": "1.0",
"event_data": {
"broadcaster_id": "26610234",
"broadcaster_name": "CohhCarnage",
"gifter_id": "15185913",
"gifter_name": "BarryCarlyon",
"is_gift": true,
"plan_name": "CohhCarnage Subscription ($4.99)",
"tier": "1000",
"user_id": "24261394",
"user_name": "freaktechnik"
}
},
```

**How to reproduce**

Try to load a subscription from `subscriptions/user` that is known to be a gift

**Expected behavior**

Returns gift data

**Additional context or questions**

Discord Discussion: https://discord.com/channels/504015559252377601/523675960797691915/820286197405843497

**Comment by jbulava** [comment]
Fix is in production
