### ISSUE TITLE
Teams API shows incorrect timestamp

### ISSUE THREAD

**Issue by stachu540** [twitchdev/issues#347]
**Brief description**
Currently timestamp shows different format rather then in documentation exist. It applies to booth endpoints:
- https://dev.twitch.tv/docs/api/reference#get-channel-teams
- https://dev.twitch.tv/docs/api/reference#get-teams

**How to reproduce**
Change timestamp format to [RFC 3339](https://tools.ietf.org/html/rfc3339)

**Expected behavior**
Currently present format is like `YYYY-MM-DD HH:mm:ss.SSS Z` and should be `YYYY-MM-DD'T'HH:mm:ss'Z'` but we are not complain to the time zone, which is correct.

**Screenshots**
![Actual Callback](https://user-images.githubusercontent.com/359222/111071848-593e7580-84d8-11eb-8e4c-c6bba10549a0.png)

**Additional context or questions**
This issue was spotted by @iProdigy (pinging him to see existing report the API issue)

**Comment by Marenthyu** [comment]
This is also inconsistent with other Endpoints like `/users`, which returns it as the documentation mentions it - additionally, other Endpoints with timestamps returned specifically mention RFC3339, whereas the Teams Endpoints currently do not.

**Comment by Xemdo** [comment]
This has been fixed since this bug report was made:
![image](https://github.com/twitchdev/issues/assets/11840265/672b10ad-26a2-4f59-aa9e-c068cc7f8299)
