### ISSUE TITLE
gifter_id not documented for Check User Subscription

### ISSUE THREAD

**Issue by freaktechnik** [twitchdev/issues#348]
**Brief description**
When `is_gift` is true, there is a `gifter_id` field with the user ID of the gifter.

**Expected documentation**

Field | Type | Description
-- | -- | --
`gifter_id` | string | User ID of the gifter (if `is_gift` is `true`).

**Screenshots**
Not a screenshot, but the actual API response to the subscription relation described in the previous issue:
```json
{"data":[{"broadcaster_id":"26610234","broadcaster_name":"CohhCarnage","broadcaster_login":"cohhcarnage","gifter_id":"15185913","gifter_name":"BarryCarlyon","gifter_login":"barrycarlyon","is_gift":true,"tier":"1000"}]}
```

**Additional context or questions**

This is a follow-up to #345

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#check-user-subscription.
