### ISSUE TITLE
Pubsub examples one big mess

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#355]
**Brief description**
Some have broken formatting, some have the entire message, some have just the message data, some have a table explaining the message fields and some don't. Its one big mess.
**Expected documentation**
Fixed examples preferably of the entire message with a table explaining the fields.

**Comment by Xemdo** [comment]
Closing as PubSub will be deprecated April 14, 2025
https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043
