### ISSUE TITLE
Add Character lenght limits to Channel Point rewards create/update

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#357]
**Brief description**

Create/Update a reward doesn't note the character limitations on title/name and description/prompt

**Expected documentation**

Notes on the character limits

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/112184799-79b4b100-8bf7-11eb-9d2c-460523d0bb49.png)

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: 
https://dev.twitch.tv/docs/api/reference#update-custom-reward
https://dev.twitch.tv/docs/api/reference#create-custom-rewards
