### ISSUE TITLE
EventSub doesn't support "redirects" for verification/data sendings

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#358]
**Brief description**

EventSub docs doesn't note that when calling the callback for the Webhook transport it will **not** follows redirects.

**Expected documentation**

A note in https://dev.twitch.tv/docs/eventsub about this.

(Also I wonder if _important_ stuff like this needs a "danger box" in the docs for clarity)

**Additional context or questions**

https://discuss.dev.twitch.tv/t/google-apps-script-eventsub/30983/27

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/eventsub/eventsub-reference#transport.
