### ISSUE TITLE
onPositionChanged still in docs

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#36]
**Brief description**

https://dev.twitch.tv/docs/extensions/reference#helper-extensions

The JS helper/callback function `onPositionChanged` is still documented but is no longer relevant post video component redesign

**Expected documentation**

Section Should be removed

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848116-onpositionchanged-still-in-docs
