### ISSUE TITLE
Response 500 after several calls to get_clips 

### ISSUE THREAD

**Issue by dxxdv** [twitchdev/issues#360]
I am making paused calls to get_clips with pagination, everything ok, but always at the 7th petition fails.

Parameters informed: game_id, started_at and ended_at (a complete day)

**Comment by BarryCarlyon** [comment]
Which Get Clips?

You calling Kraken?
You calling Helix?

What call are you making that is failing?
Whats the call history?

**Comment by dxxdv** [comment]
Helix, new petition.
I just call get_clips with the parameters I said, and then several calls more with pagitacion parameter recovered from the previous petition.
Everything works until 7th call, response 500.

**Comment by BarryCarlyon** [comment]
But what are the parameters you are using?

**Comment by dxxdv** [comment]
{'game_id': '509658', 'started_at': '2021-04-01T00:00:00.00Z', 'ended_at': '2021-04-01T23:59:00.00Z', 'first': 100}
{'game_id': '509658', 'started_at': '2021-04-01T00:00:00.00Z', 'ended_at': '2021-04-01T23:59:00.00Z', 'after': u'eyJiIjpudWxsLCJhIjp7IkN1cnNvciI6Ik16QXcifX0', 'first': 100}
...
...
{'game_id': '509658', 'started_at': '2021-04-01T00:00:00.00Z', 'ended_at': '2021-04-01T23:59:00.00Z', 'after': u'eyJiIjpudWxsLCJhIjp7IkN1cnNvciI6Ik5EQXcifX0', 'first': 100}

{'game_id': '509658', 'started_at': '2021-04-01T00:00:00.00Z', 'ended_at': '2021-04-01T23:59:00.00Z', 'after': u'eyJiIjpudWxsLCJhIjp7IkN1cnNvciI6Ik5UQXcifX0', 'first': 100} -> this one response 500

**Comment by Xemdo** [comment]
Can't reproduce this. Likely resolved since the initial opening of this issue
