### ISSUE TITLE
thumbnail_url links don't work

### ISSUE THREAD

**Issue by Mihail-Shch** [twitchdev/issues#363]
**Brief description**
Using api request to get videos fron a random twitch channel(by random I mean, that i type login of a streamer in the input), then i get a response, where i can see an array of objects, each object contains a thumbnail_url, i guess that you have to replace words "height" and "width" with values, but it doesn't work, it shows an error.

**How to reproduce**
Make an api request using this link - https://api.twitch.tv/helix/videos?user_id=${id}, where id is the id of a streamer, then try to follow the link of a thumbnail_url.

**Expected behavior**
After following the link we should see the thumbnail of a video.

**Comment by BarryCarlyon** [comment]
This is not a bug

You need to replace `%{width}` and `%{height}` in the URL with the widht and height you want

So

> "https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/a310b2fa6b23bbdbb725_cohhcarnage_72491331536_7503939878//thumb/thumb978233485-%{width}x%{height}.jpg

becomes

> "https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/a310b2fa6b23bbdbb725_cohhcarnage_72491331536_7503939878//thumb/thumb978233485-1920x1080}.jpg

It would appear that the template variable for thumbnails has changed to include a % at the start for this endpoint

**Comment by Mihail-Shch** [comment]
@BarryCarlyon ty man, didn't know that you also have to replace %, my bad xd
