### ISSUE TITLE
Twitch Emotes don't work in whispers

### ISSUE THREAD

**Issue by zneix** [twitchdev/issues#367]
**Brief description**
Emotes in whispers return improper ID (all IDs are 0) thus it's impossible to e.g. render emotes.

Example IRC message of a received whisper:
`@badges=bits-charity/1;color=#9ACD32;display-name=Leppunen;emotes=0:0-4;message-id=8;thread-id=42239452_99631238;turbo=0;user-id=42239452;user-type= :leppunen!leppunen@leppunen.tmi.twitch.tv WHISPER zneix :pajaW`

**How to reproduce**
1. Connect to IRC.
2. Request capabilities.
3. Receive a whisper.
4. `emotes` tag returns emotes, but their ID is always `0`.

**Expected behavior**
Emote ID should be `80481`, not `0`.

**Screenshots**
![xd](https://cdn.zneix.eu/AkFGLF8.png)

**Additional context or questions**
Breaks our 3rd-party chat client, as seen above.

**Comment by jbulava** [comment]
The team is aware of this issue and is working on a resolution.

**Comment by jbulava** [comment]
This should now be fixed.  There is one other thing the team is looking into just in case there is a related issue, so I will leave this open for the rest of the day.

**Comment by jbulava** [comment]
Extra zeroes have been fixed, closing out the issue.
