### ISSUE TITLE
Remove the git installed dependancy from the Dev Rig.

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#368]
**Brief description**

Too many developers run into the issue of not having git installed/available in $path when using the Developer rig.

**How to reproduce**

Use the rig, without git installed, and try to checkout one of the examples/boilerplates

**Expected behavior**

It to not need Git installed just to fetch the example.

**Additional context or questions**

Update the examples on github to create a "release" that includes a Zip file.
Use _not git_ to fetch/download and unzip those zip file releases instead.

**Comment by Xemdo** [comment]
Developer Rig has reached end-of-life as of January 31st, 2023. For more information see the announcement here:
https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995
