### ISSUE TITLE
msg-id docs are horribly outdated

### ISSUE THREAD

**Issue by Mm2PL** [twitchdev/issues#376]
**Brief description**
That page looks like it hasn't been checked with actual state of TMI for a long time. It even mentions [global moderators](https://blog.twitch.tv/en/2018/12/13/thank-you-global-moderators-4d44cfccf22/).

**Expected documentation**
Notices about entries that were removed.

**Screenshots**
![DonoWall](https://user-images.githubusercontent.com/25011746/115569283-97377200-a2ac-11eb-8db3-8ce6affba731.png)

**Additional context or questions**

[https://dev.twitch.tv/docs/irc/msg-id](https://dev.twitch.tv/docs/irc/msg-id)

**Comment by jbulava** [comment]
An audit of the msg-ids – those that are manually documented as well as those that are found directly in the chat product – has been completed and includes any and all differences between the lists. The public documentation will be updated following a full review with the chat team regarding what actions need to be taken for each msg-id.

**Comment by Xemdo** [comment]
Still relevant due to deprecation of chat commands
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486/83

**Comment by Mm2PL** [comment]
`msg-id`s aren't only replies to commands. They are basically everything that happens on IRC and has a NOTICE. Ids for command replies are still on the page. Still outdated.

**Comment by Xemdo** [comment]
`msg-id` possible values were updated: https://dev.twitch.tv/docs/chat/irc/#notice-reference
