### ISSUE TITLE
How does a streamer have access to personal information?

### ISSUE THREAD

**Issue by clean415** [twitchdev/issues#381]
**Brief description**
I don't know your language.
However, you can communicate through a translator.
The reason for doing this is. Chat history and information on my Discord and cell phone
Through your application.
And according to Twitch's contract of use. It is because I have doubts that it is possible.
I don't want my information to be exposed to anyone I don't want.
**How to reproduce**
I think there is a history of use of the authority
**Expected behavior**
View and read my articles and transmitted files
**Screenshots**
No clear proof
**Additional context or questions**
Knowing that there is such a fact, and accessing through self-authentication,
It’s only the difference between a camcorder and a microphone,
Why can I view the viewer's information?

And I want you to permanently block this person from me. I have never given this person permission to view my information.
ID : fkaus70_

**Comment by BarryCarlyon** [comment]
This is a bug tracker for TwitchDev and Twitch Products.

I have no idea what this is

**Comment by clean415** [comment]
what I'm saying is .
Information written on Discord.
Mobile phone with Twitch installed.
My information is delivered to the streamer.
"I have no way to prove this"

**Comment by BarryCarlyon** [comment]
And this is the third party bug tracker for TwitchAPI's.

So I'm still not sure what your question pertians to.

Since Discord is nothing to do with the TwitchAPI or other third party TiwtchDev Products

**Comment by clean415** [comment]
Thank you for your help.
You're working on Twitch API.
I understood that this has nothing to do with the discode.
I'm using TWITCH, and my cell phone and discode are being hacked, so I was asking for it. Thank you.
