### ISSUE TITLE
Prediction EventSub Doc Issues

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#385]
**Brief description**

Channel Prediction End Event
 (<https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-prediction-end-event>)

* `Includes top_predictors.` should be in the description of `outcomes`, not `status`
* `eneded_at` should be `ended_at`

&nbsp;

Top Predictors (<https://dev.twitch.tv/docs/eventsub/eventsub-reference#top-predictors>)

* `channel_points_won` should be labeled as an `integer`, not `string`

&nbsp;

**Screenshots**
<https://i.imgur.com/t4yYWYg.png>
<https://i.imgur.com/PBDmMlQ.png>

**Comment by jbulava** [comment]
Corrected for this week's update.

**Comment by iProdigy** [comment]
> Corrected for this week's update.

The other items have been resolved but the `eneded_at` typo is still present: https://i.imgur.com/jOFjTBs.png

**Comment by jbulava** [comment]
Remaining item corrected on #391.
