### ISSUE TITLE
Polls EventSub Docs Issues

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#386]
**Brief description**

Channel Poll End Notification Example (<https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelpollend-beta>)
* `status` is missing from the event example

Bits Voting (<https://dev.twitch.tv/docs/eventsub/eventsub-reference/#bits-voting>)
* `amount_per_vote` should be labeled as an `integer`, not `boolean`

Channel Points Voting (<https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-points-voting>)
* `amount_per_vote` should be labeled as an `integer`, not `boolean`

**Additional context or questions**
Docs for "Channel Poll End Event" indicate that `status` ought to be present: https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-poll-end-event

**Comment by jbulava** [comment]
Corrected for this week's update.
