### ISSUE TITLE
"End Poll" example uses "POST" instead of documented "PATCH"

### ISSUE THREAD

**Issue by AlcaDesign** [twitchdev/issues#387]
**Brief description**

The "End Poll" example uses "POST" instead of documented "PATCH".

**Expected documentation**

```
curl -X PATCH 'https://api.twitch.tv/helix/polls' \
-H 'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y' \
-H 'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2' \
-H 'Content-Type: application/json' \
-d '{
  "broadcaster_id":"141981764",
  "id":"ed961efd-8a3f-4cf5-a9d0-e616c590cd2a",
  "status":"TERMINATED"
}'
```

**Screenshots**

![image](https://user-images.githubusercontent.com/7132646/117386535-b63d2300-aeac-11eb-9e70-0f32f3c8f9c8.png)

**Additional context or questions**

**Comment by jbulava** [comment]
Corrected to PATCH, thanks!
