### ISSUE TITLE
Create clips throws a 503 if a username is sent as broadcaster_id

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#389]
**Brief description**
Create clips throws a 503 if a username is sent as broadcaster_id
**How to reproduce**
Send a username as value of the broadcaster_id parameter rather than a userid
**Expected behavior**
To throw a 400 rather than a 503.
**Screenshots**
![image](https://user-images.githubusercontent.com/17624700/117860627-cbd99080-b290-11eb-8001-010164051a37.png)

**Comment by jbulava** [comment]
Ticketed internally as HLX-1780.

**Comment by Dkamps18** [comment]
This got fixed to the extend that the endpoint no longer returns a 503 but now returns an empty data array instead of returning a 400

**Comment by Xemdo** [comment]
Endpoint is now returning HTTP 400 instead of an empty array. Seems to be resolved
