### ISSUE TITLE
ReRuns have disappeared from Kraken v5

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#39]
**Brief description**

Similar to #38 but recently, ReRuns have completely disappeared from Helix

Affects the streams and followed/streams endpoints

**How to reproduce**

Call https://api.twitch.tv/kraken/streams/?stream_type=playlist

**Expected behavior**

Get ReRuns/playlists

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/72662765-f3914f00-39e2-11ea-8816-a7629e277028.png)

**Comment by BarryCarlyon** [comment]
Source Forum post: https://discuss.dev.twitch.tv/t/kraken-streams-followed-endpoint-no-longer-returning-re-run-streams/23786/

**Comment by BarryCarlyon** [comment]
```
{
    "stream": {
        "_id": 36689307040,
        "game": "The Forest",
        "broadcast_platform": "other",
        "community_id": "",
        "community_ids": null,
        "viewers": 0,
        "video_height": 720,
        "average_fps": 60,
        "delay": 0,
        "created_at": "2020-01-17T20:07:24Z",
        "is_playlist": false,
        "stream_type": "live",
        "preview": {
            "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_welovegames-80x45.jpg",
            "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_welovegames-320x180.jpg",
            "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_welovegames-640x360.jpg",
            "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_welovegames-{width}x{height}.jpg"
        },
        "channel": {
            "mature": false,
            "status": "Хороших вам выходных!",
            "broadcaster_language": "ru",
            "broadcaster_software": "watch_party_rerun",
            "display_name": "WELOVEGAMES",
            "game": "The Forest",
            "language": "ru",
            "_id": 30814134,
            "name": "welovegames",
            "created_at": "2012-05-26T11:18:26.294212Z",
            "updated_at": "2020-01-18T12:33:41.379427Z",
            "partner": true,
            "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/welovegames-profile_image-15afef2e74a108da-300x300.png",
            "video_banner": null,
            "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/welovegames-profile_banner-5700d3683ec069c3-480.png",
            "profile_banner_background_color": "",
            "url": "https://www.twitch.tv/welovegames",
            "views": 73783254,
            "followers": 386026,
            "broadcaster_type": "partner",
            "description": "vk.com/welovegames",
            "private_video": false,
            "privacy_options_enabled": false
        }
    }
}
```

Call a stream directly, it shows as "live" instead of a "watch party" have to use the "channel" with "broadcaster_software" to differentiate at time of writing

**Comment by BarryCarlyon** [comment]
Additionally: adding `?stream_type=all` breaks the viewer count

Calling `https://api.twitch.tv/kraken/streams/26610234?stream_type=all` 

```
{
"stream": {
"_id": 36705562864,
"game": "Star Wars: Knights of the Old Republic",
"broadcast_platform": "other",
"community_id": "",
"community_ids": null,
"viewers": 0,
```
~Snip~

**Comment by tduva** [comment]
As you said, this has the broken viewercount:
> https://api.twitch.tv/kraken/streams/22680841?stream_type=all

But this one appears to work:
> https://api.twitch.tv/kraken/streams/?channel=22680841&stream_type=all

Might be a possible workaround or a clue for fixing it.

**Comment by BarryCarlyon** [comment]
Interesting, `channel` as a query string argument is undocumented… Didn't know that was a thing

**Comment by tduva** [comment]
It's the [second variant](https://dev.twitch.tv/docs/v5/reference/streams#get-live-streams) of `/kraken/streams` (I'm just using it for a single channel in this case):

![streams](https://user-images.githubusercontent.com/5621113/73266134-95305180-41d6-11ea-96f4-697b47df9dc0.png)

**Comment by jbulava** [comment]
Ticketed internally on GQL-914. There are a couple of questions here; whether reruns was removed intentionally or if they should be included, as well as why the view count is broken and if that should be fixed.

**Comment by garyking** [comment]
If re-runs were intentionally removed, I'd be interested to know what the reason was. Since of course, it'd be better to include re-runs, and let us filter them out if we don't want them, rather than forcefully removing them, and not letting us retrieve them, at all.

**Comment by BarryCarlyon** [comment]
As per #216 this issue has reoccured

And this ticket never got marked as "fixed"

**Comment by BarryCarlyon** [comment]
Issue still occurring
