### ISSUE TITLE
channel.prediction.end `eneded_at`

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#391]
**Brief description**
https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-prediction-end-event fields has misspelled `ended_at` field 
**Expected documentation**
<html><body>

ended_at | string | The time the Channel Points Prediction ended.
-- | -- | --

</body>
</html>

**Comment by Emilgardis** [comment]
https://github.com/twitchdev/issues/issues/385#issuecomment-834549933

**Comment by jbulava** [comment]
Corrected and published, thanks!
