### ISSUE TITLE
Search Channels example uses mispelled field tags_ids -> tag_ids

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#394]
**Brief description**
https://dev.twitch.tv/docs/api/reference#search-channels example uses `tags_ids` when it should be `tag_ids`
**Expected documentation**
```json
{
      "broadcaster_language": "en",
      "broadcaster_login": "loserfruit",
      "display_name": "Loserfruit",
      "game_id": "498000",
      "game_name": "House Flipper",
      "id": "41245072",
      "is_live": false,
      "tag_ids": [],
      "thumbnail_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/fd17325a-7dc2-46c6-8617-e90ec259501c-profile_image-300x300.png",
      "title": "loserfruit",
      "started_at": ""
    }
```
**Screenshots**
![image](https://user-images.githubusercontent.com/1502855/118319150-ad76cd80-b4fa-11eb-876f-5787d1ad3c31.png)

https://github.com/Emilgardis/twitch_api2/pull/130

**Comment by iProdigy** [comment]
Able to replicate, but this is actually for the [Search Channels](https://dev.twitch.tv/docs/api/reference#search-channels) endpoint

**Comment by jbulava** [comment]
Spelling has been corrected. 👍
