### ISSUE TITLE
Create clips throws a 503 if clip creation is disabled by the broadcaster

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#395]
**Brief description**

if you try to use the API to create a Api of a braodcaster whom has disabled clipping the API 503's instead of returns a useful message

**How to reproduce**

In this example the user `my_zone_` is live and has clipping disabled/restricted (screenshot 1)

Calling the API results in screenshot 2

**Expected behavior**

A 4xx error with a useful message

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/118328952-5541ca80-b4fe-11eb-8588-e8788c4af051.png)

![image](https://user-images.githubusercontent.com/20999/118328976-5e329c00-b4fe-11eb-9f47-e567f60def44.png)

**Additional context or questions**

Original report 

https://discuss.dev.twitch.tv/t/create-clip-api-503-service-unavailable/31671

**Comment by BarryCarlyon** [comment]
Similar in "error scope" as #389

**Comment by brandinarsenault** [comment]
Encountered this error today and had to do some digging to find out what the issue was. Would be great to see the messaging in the API improved for this. Thanks!

**Comment by jbulava** [comment]
Ticketed internally as HLX-1780.

**Comment by Brandin** [comment]
It appears as if this was resolved - the API now returns `403` for at least a week now. No specific reason (followers, subscribers or disabled), just that permission is lacking.

**Comment by lleadbet** [comment]
This has been resolved.
