### ISSUE TITLE
Helix moderators/events returns empty list

### ISSUE THREAD

**Issue by ChrisGuilbault** [twitchdev/issues#397]
**Brief description**
"https://api.twitch.tv/helix/moderation/moderators/events?first=100&broadcaster_id=" returns 0 events and "https://api.twitch.tv/helix/moderation/moderators?broadcaster_id=" returns a list of mods.

Also using user_id returns an empty struct on the moderation/moderators/events.

**How to reproduce**
Request the following url on a channel with mods.
"https://api.twitch.tv/helix/moderation/moderators?broadcaster_id="

**Expected behavior**
Return a list of all mod/unmod events with pagination if required.

**Screenshots**
None required.

**Additional context or questions**
Also recent request from a broadcaster to know when their mods where first modded. As this is a new broadcaster I am working with I do not have that data cached and this endpoint is the only way to find out.

**Comment by BarryCarlyon** [comment]
The various events endpoints only go back so many days

See also #330 

Not a bug but "intended"

**Comment by jbulava** [comment]
I'll follow up about how to best explicitly document this and resolve on #330.
