### ISSUE TITLE
Cannot subscribe to points redemption

### ISSUE THREAD

**Issue by bmurray** [twitchdev/issues#398]
**Brief description**
I am unable to subscribe to channel.channel_points_custom_reward.update unless the broadcaster itself has authenticated with OAuth against my app. Moderators who can use the standard Mod view web may access these subscriptions, but I cannot access them programatically. 

**How to reproduce**
"Broadcaster" gives "Bot Account" moderator rights. 
"Bot Account" authenticates to the application via OAuth with the "channel:read:redemptions" scope. 
The application is Unable to view the channel point redemptions, nor subscribe to "channel.channel_points_custom_reward.update"
If "Broadcaster" authenticates to the app via OAuth, with the "channel:read:redemptions" scope, then I can subscribe to the event. 

**Expected behavior**
"Broadcaster" gives "Bot Account" moderator rights. 
"Bot Account" authenticates to the application via OAuth with the "channel:read:redemptions" scope. 
The application should then have access to read or subscribe to the redemptions on Broadcasters channel. 

**Screenshots**

**Additional context or questions**
It may sound picky, but I do not want to force the broadcaster to authenticate; they should be able to use the application/bot account to manage this if they're given mod access. This is for a chatbot that interacts with overlays and the requests queue automatically.

**Comment by ChrisGuilbault** [comment]
Would this be better suited for a uservoice as it is a feature request instead of a bug in the current auth flow. The issue you describe is how the system was designed to work.

**Comment by BarryCarlyon** [comment]
Yeah this isn't a bug
it's a feature request.

So uservoice

The bot doesn't have any rewards, and the scope is to manage that authenticating user
Not to manage someone else.

The broadcaster needs to authenticate with that scope.
Not someone else

**Comment by lleadbet** [comment]
Closing as this is a UserVoice request.
