### ISSUE TITLE
Language filter returns no results as of Dec 5

### ISSUE THREAD

**Issue by jbulava** [twitchdev/issues#4]
**Brief description**
Originally reported in the forums [here](https://discuss.dev.twitch.tv/t/helix-streams-endpoint-language-filter-not-working/23346).

**How to reproduce**
Send GET with language filter set to “en”
GET 'https://api.twitch.tv/helix/streams?language=en'
result: {"data":[],"pagination":{}}

**Comment by jbulava** [comment]
API team has acknowledged this issue and should be deploying a fix soon.

**Comment by mauerbac** [comment]
pinging @jbulava to check if deployed and fixed

**Comment by jbulava** [comment]
The `language` filter was also affected alongside `offset` and `_total` by the [internal service changes in February](https://discuss.dev.twitch.tv/t/upcoming-changes-to-the-streams-v5-endpoints/23926). To fix the filtering issue on language, the team deployed an update on March 30 that maps the language parameter of the API request to filtering on the broadcaster language as this information is still available in the backend service.
