### ISSUE TITLE
Config Service links to wrong reference

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#40]
**Brief description**

https://dev.twitch.tv/docs/extensions/building/#using-the-configuration-service

Mentions "twitch api reference" but the config service endpoints are on in the Extension Reference

> For extension examples that leverage the configuration service see the new Twitch API Reference. Also, see these repositories:

**Expected documentation**

Links to `https://dev.twitch.tv/docs/api/reference` but the configuration API is documented `https://dev.twitch.tv/docs/extensions/reference#set-extension-required-configuration`

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848128-config-service-links-to-wrong-reference
