### ISSUE TITLE
Specific team is causing 500 errors

### ISSUE THREAD

**Issue by opti21** [twitchdev/issues#400]
**Brief description**
When trying to get team data for the `onlydevs` team using the `Get Teams` endpoint I get a 500 error. This was replicated by one of the Twitch Dev Ambassadors on the discord server. It's specifically this team other teams work so not sure why it's specifically this team.

**How to reproduce**
Making a `GET` request to `https://api.twitch.tv/helix/teams?name=onlydevs`

**Expected behavior**
Return Team Data

**Screenshots**
![image](https://i.imgur.com/ZbhcFP9.png)

**Additional context or questions**

**Comment by twitch-chandog** [comment]
here are a bunch of broadcaster_ids that also 500

76508554 127506955 30281925 121111915 30917811 27992608 69588825 41136772 87056709 70791800 139634148 38927816 89390235 123275679 95055754 153176290 171986284 143646010 107440924 48357329 551447844 32658521 159935710 127939464 118202507 150066856 75012097 557148694 53621919 139125840 27369897 147649918 497503001 84847071 104686093 132471249 577107718 557720142 1251709 140881916 134629462 95917582 150627893 140937907 145151151 82826005 122881889 80615421 44741426 79355177 38135752 8650361 55159684 558820706 59966426 26830215 36594525 32034190 449470373 110996832 129625799 54165962 147016458 119917354 195323276 40619591 82896213 30255906 518016053 45047724 459331509 39276140 83232866 181077473 464695543 165357469 36587781 62502182 118786264 169638772

**Comment by lleadbet** [comment]
This should be resolved now. Please tag me if you're still seeing issues.
