### ISSUE TITLE
Two different ids return the same user on the channels endpoint

### ISSUE THREAD

**Issue by MattBroach** [twitchdev/issues#401]
**Brief description**

On the kraken `channels` endpoint, The user ids `27895236` and `21015760` appear to return the same user (the user matching the latter id, `21015760`).  Weirdly, the helix users?id= endpoint gives different responses, so it's appears to only be a kraken issue.

**How to reproduce**

Use the endpoints `api.twitch.tv/kraken/channels/21015760` and `api.twitch.tv/kraken/channels/27895236`.  These will return the same channel (SuperMCGamer).

**Expected behavior**

The endpoint for `27895236`should return a different user (Zeldathon).

**Additional context or questions**

We check thousands of channels a day, and to our knowledge we haven't found another channel with this issue.

**Comment by Xemdo** [comment]
Kraken has shut down as of January 2023, and the bug appears to have not resurfaced in Helix.
If it does, please let us know by reopening this issue.
