### ISSUE TITLE
PubSub Examples for automod-queue & user-moderation-notifications are inaccurate

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#405]
**Brief description**
The message examples for `automod-queue` and `user-moderation-notifications` are inaccurate as they:

1. Leave out `data.message.type`, which should be `automod_caught_message` (as this is what is actually being sent over the socket)
2. Use the wrong field name for `id` in `user-moderation-notifications`: this should be `message_id`

These discrepancies can yield issues for folks attempting to implement this topic.

**Expected documentation**

```json
{
  "type": "MESSAGE",
  "data": {
    "topic": "automod-queue.46024993.44322889",
    "message": {
      "type": "automod_caught_message",
      "data": {
        "message": {
          "id": "some-automod-caught-message-id",
          "content": {
            "text": "a bad word",
            "fragments": [
              {
                "text": "a bad word",
                "automod": {
                  "topics": {
                    "swearing": 6
                  }
                }
              }
            ]
          },
          "sender": {
            "user_id": "559969259",
            "login": "msongvo222",
            "display_name": "msongvo222",
            "chat_color": "#8A2BE2"
          },
          "sent_at": "2021-05-24T18:46:20.964Z"
        },
        "content_classification": {
          "category": "swearing",
          "level": 2
        },
        "status": "PENDING",
        "reason_code": "",
        "resolver_id": "",
        "resolver_login": ""
      }
    }
  }
}
```

&

```json
{
  "type": "MESSAGE",
  "data": {
    "topic": "user-moderation-notifications.46024993.44322889",
    "message": {
      "type": "automod_caught_message",
      "data": {
        "message_id": "some-automod-caught-message-id",
        "status": "DENIED"
      }
    }
  }
}
```

**Screenshots**
https://i.imgur.com/XggRYmj.png & https://i.imgur.com/KPMd0tB.png

**Additional context or questions**
Technically `data.message` would be a string, but this is keeping in accordance with `Typically, message is a JSON object that has been escaped` for readability

**Comment by jbulava** [comment]
Thanks for mentioning this and providing the expected examples! These have been updated for accuracy.

**Comment by iProdigy** [comment]
Thank you! @jbulava Also, the field table for user moderation notifications needs to be updated to reflect the `id` => `message_id` change: https://i.imgur.com/UDvv5gY.jpg
