### ISSUE TITLE
Missing full json in refreshing access tokens example response

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#407]
**Brief description**
When comparing the example response on https://dev.twitch.tv/docs/authentication#refreshing-access-tokens to the response I got from an actual execution, There were several important fields that were missing from the documentaiton.
**Expected documentation**
The inclusion of the full example json, not just the access and refresh tokens. Also, scope was a single value instaed of an array of values as I got from the endpoint.
IE: 
```JSON
{
    "access_token": "asdasdasd",
    "expires_in": 13030,
    "refresh_token": "asdasdasdasdasdasdasdasdasdasdasd",
    "scope": [
        "openid",
        "etc..."
    ],
    "token_type": "bearer"
}
```

**Comment by jbulava** [comment]
Great catch, thanks!  The authentication guide is now updated to reflect the expected payload.
