### ISSUE TITLE
My Twitch link no longer embeds after Twitch Channel Name change <--

### ISSUE THREAD

**Issue by ByakkoTV** [twitchdev/issues#408]
**Brief description**
My Twitch URL (https://www.twitch.tv/byakkotv) does not get embedded in Discord. I reached out to Discord Help Support desk and they reproduced the same results. Other people twitch links work but not mine. They asked me if I had changed my Twitch name recently. I did, I used to be named byakko_chan (https://www.twitch.tv/byakko_chan) and now I am named ByakkoTV (https://www.twitch.tv/byakkotv) and that one no longer embeds. Before the name change I had no problems. Discord Support Team said they cannot help me as all other Twitch links are working fine and recommended me to contact Twitch Support. 

I contacted Twitch support (ticket/case number: 05015754) and they referred me to this Developer page. The application is Discord <-- and it's not working in Discord. Which is causing damages to my brand because Twitch Streamers advertise their url links in many servers. People tend to click on things that are ''visually pleasing'' so not having an embed is really bad. Again, it worked fine before the name change. Discord themselves tested it and they too have the same issue, only with my link/name.

I followed and read the embedding guide and nothing there could help me because that is related to website embedding. My issue is with my link no longer embedding in Discord (application) after the Twitch Channel Name Change. I never received an email that Twitch revoked my embedding rights so something went wrong after the username change. Can I kindly ask you to look into this issue?

**How to reproduce**
Open Discord, make sure the channel (and your role privileges) allow embedded links, type in https://www.twitch.tv/byakkotv and you will see it does not embed.

**Expected behavior**
Before the name change it would embed.

**Screenshots**
See attached screenshots

**Additional context or questions**
![01](https://user-images.githubusercontent.com/85044635/120089562-04d08c80-c0fc-11eb-80fb-8dcbb72e3bd0.JPG)
![02](https://user-images.githubusercontent.com/85044635/120089563-0732e680-c0fc-11eb-939b-d27adb29b7f5.JPG)

**Comment by ByakkoTV** [comment]
Additionally, I provide this screenshot where my "old" user name (Byakko_chan) still embeds (albeit with no picture because that account is now named ByakkoTV so technically shouldn't exist).

This proves that the user name change of the channel negatively effected embedding on my account and broke it.

![03](https://user-images.githubusercontent.com/85044635/120089726-457cd580-c0fd-11eb-8a7a-5b298b011e39.JPG)

Would you be so kind to look into this please. 

And again, I already had extensive contact with Discord Support Team, they said it is 100% on Twitch side, because all other links do work. The name change caused these issues.

Warm and kind regards,
ByakkoTV

**Comment by ByakkoTV** [comment]
Update~~~~~

After some testing it appears my twitch link doesn't work in Discord Community Servers (embed). In Discord DM"s they work. In Discord small servers (non community servers) it works. But in Discord Community Servers, the embed does not work.

I reached out to helpdesk of Discord again to see if they can check that on their side if somehow my link is on some exclusion/block list for Community Servers and if so, why on earth that is~

If it is related to the Twitch side do let me know~ This whole situation is starting to seriously frustrate me.

**Comment by BarryCarlyon** [comment]
Discord "embeds" don't have a category on this tracker.
This is a problem discord side.

I tested this in my own discord

It's likely a problem with Discord's embed caching.

![image](https://user-images.githubusercontent.com/20999/120505905-578c9b80-c3bd-11eb-9b25-360ad659bba3.png)

Not a bug for this tracker
