### ISSUE TITLE
Dead kraken Endpoints in the docs

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#41]
**Brief description**

Long dead endpoints are still in the docs

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/73178532-5da7a380-4109-11ea-8488-5439e15b1046.png)

**Comment by mauerbac** [comment]
ah, finally - something we can do easily and quickly :) DXDOC-245

**Comment by jbulava** [comment]
Resolved on April 1, the docs for these have been removed.
