### ISSUE TITLE
Subscribers API error when calling not as affilaite+

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#410]
**Brief description**

If you call subscribers API for a channel that isn't at least affiliate it returns

    {"error":"Bad Request","status":400,"message":"channel_id must be a partner or affiliate"}

**How to reproduce**

Call `helix/subscribers` with a `broadcaster_id` for a user whom is a "regular" user with a key that has the scope

**Expected behavior**

It should say `broadcaster_id` since the query param for this endpoint is `broadcaster_id`

**Comment by Xemdo** [comment]
The helix/subscribers endpoint does not exist anymore, and helix/subscriptions does not validate if they are an affiliate or partner (instead returns empty array).
