### ISSUE TITLE
emote_set_id in Get Channel Emotes is not properly set

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#413]
**Brief description**
The `emote_set_id` for emotes returned in [Get Channel Emotes](https://dev.twitch.tv/docs/api/reference#get-channel-emotes) is not accurate; currently it is simply being set to the `id` itself.

**How to reproduce**
1. Query "Get Channel Emotes" with a broadcaster id (e.g. `207813352`)

For example, here is an abridged emote example from the data response:
```
{id=300709075, name=hasKomrade, images={ ... }, tier=1000, emote_type=subscriptions, emote_set_id=300709075}
```

Notice that `id` == `emote_set_id`. This is repeated across the emotes in the response.

&nbsp;

2. To solidify the point, we can pass this `emote_set_id` to "Get Emote Sets"

```
{data=[{id=301266433, name=martioMaestria1, images={url_1x=https://static-cdn.jtvnw.net/emoticons/v1/301266433/1.0, url_2x=https://static-cdn.jtvnw.net/emoticons/v1/301266433/2.0, url_4x=https://static-cdn.jtvnw.net/emoticons/v1/301266433/3.0}, emote_type=subscriptions, emote_set_id=300709075, owner_id=411550143}]}
```

Notice that this response deals with a completely different broadcaster.

**Expected behavior**
`emote_set_id` should actually be set to the emote set id, not emote id.

**Comment by iProdigy** [comment]
Looks like this issue was reproduced before me: https://github.com/Chatterino/chatterino2/issues/2875#issuecomment-857204521

**Comment by jbulava** [comment]
This fix is now in production.
