### ISSUE TITLE
channel.subscription.message eventsub: example uses different field name than documented

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#415]
**Brief description**
[Channel Subscription Message Event](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-subscription-message-event) is documented to contain `cumulative_total`. However, the [notification example](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelsubscriptionmessage-beta) calls this field `cumulative_months`. 

**Expected documentation**
The docs should stick to the single correct field name.

**Screenshots**
https://i.imgur.com/TENTvrH.png & https://i.imgur.com/X5iKfq1.png

**Additional context or questions**
I haven't tested this type yet to know the "correct" field name

**Comment by Emilgardis** [comment]
do we know the "correct" name for this? I don't have the capacity right now to test it

**Comment by edwinsage** [comment]
Looking at the code I only see a reference to cumulative_total, so I assume that one is correct.  Please fix the docs :(

**Comment by Emilgardis** [comment]
The correct value is `cumulative_months`
