### ISSUE TITLE
Get Global Emotes endpoint is missing a lot of emotes

### ISSUE THREAD

**Issue by badoge** [twitchdev/issues#417]
**Brief description**
The endpoint returns 138 emotes only, but there are 236 global emotes as far as I know.

**How to reproduce**
GET https://api.twitch.tv/helix/chat/emotes/global -> response will include 138 emotes only

**Expected behavior**
A response with all global emotes :)

**Screenshots**
Emotes returned by the endpoint:
![image](https://user-images.githubusercontent.com/18620902/122073928-dcd66e00-ce09-11eb-80e0-08824655499b.png)
Emotes available in chat:
![image](https://user-images.githubusercontent.com/18620902/122071566-e1018c00-ce07-11eb-82fa-9e9b9039d846.png)

**Additional context or questions**
The endpoint also returns a mixture of default and purple/monkey emoticons, it would be better if it returned all 3 types, or just the default robot emoticons since the other 2 are not really global.

**Comment by pabloalber84** [comment]
The rest of emotes are obtained from: https://api.twitch.tv/helix/chat/emotes?broadcaster_id=0
Just merge array's.

**Comment by zneix** [comment]
> The rest of emotes are obtained from: [api.twitch.tv/helix/chat/emotes?broadcaster_id=0](https://api.twitch.tv/helix/chat/emotes?broadcaster_id=0)
> Just merge array's.

Twitch made an endpoint which is meant to give you **ALL** global emotes. It currently does not do that, thus it is a bug.
Your comment makes zero sense - you should be able to get what you want in just **ONE** API call, not bother with alternative hacky fixes and hardcoding global emoteset ID in an ugly way.
If your suggested solution is something we should do, then the endpoint could as well be removed as it's literally pointless. Think again.

**Comment by pabloalber84** [comment]
> > The rest of emotes are obtained from: [api.twitch.tv/helix/chat/emotes?broadcaster_id=0](https://api.twitch.tv/helix/chat/emotes?broadcaster_id=0)
> > Just merge array's.
> 
> Twitch made an endpoint which is meant to give you **ALL** global emotes. It currently does not do that so this is a bug so I have no idea what's the point of 👎 reaction on the issue - it's a fair report of an existing bug that shouldn't be a thing.
> Your comment makes zero sense - you should be able to get what you want in just **ONE** API call, not bother with alternative hacky fixes and hardcoding global emoteset ID in an ugly way.
> If your suggested solution is something we should do, then the endpoint could as well be removed as it's literally pointless. Think again.

Temporal fix, not FULL SOLUTION, you genius.

**Comment by Supinic** [comment]
>Temporal fix, not FULL SOLUTION, you genius.

The issue is about fixing something, not working around it, you genius

**Comment by pabloalber84** [comment]
> > Temporal fix, not FULL SOLUTION, you genius.
> 
> The issue is about fixing something, not working around it, you genius

Ultimately wait another week, this has already passed 1 week and it still has not been fixed, people like who created the issue don't view temporal alternatives, and wait to fix like "full problem of Twitch, I just do nothing", good luck.

**Comment by jbulava** [comment]
This issue has been corrected within the last half hour.  All global emotes should now be returned.
