### ISSUE TITLE
"Create Channel Stream Schedule Segment" - one off stream

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#418]
**Brief description**

It seems that not all streamers/users have access to create a non recurring schedule event.
But the documentation doesn't note this odditity

And there is no way to check/know the criteria for whom has access to non recurring streams.

**Expected documentation**

is_recurring | boolean | Indicates if the scheduled broadcast is recurring weekly.
-- | -- | --

Becomes

is_recurring | boolean | Indicates if the scheduled broadcast is recurring weekly, only if the option is availble on the target channel
-- | -- | --

**Screenshots**

Left is barrycarlyon (a partner) right is barrycarlyonbot (a regular user)
![image](https://user-images.githubusercontent.com/20999/122249921-27ff8800-cec1-11eb-9c1a-3757996910a2.png)

**Comment by lluisemper** [comment]
@BarryCarlyon  Also I would like to add that the `start_time` Required Body Parameters does not work properly for non partner accounts. Even if you set it for 2 months time in your Schedule would appear for the most recent day.

For example:`"start_time": "2021-07-01T18:00:00Z",`

Will set it for ` "2021-06-17T18:00:00Z"`

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#create-channel-stream-schedule-segment.
