### ISSUE TITLE
Chat Documentation Missing!

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#42]
**Brief description**

A bunch of the IRC/Chat documentation is missing.

https://dev.twitch.tv/docs/irc/commands#overview
https://dev.twitch.tv/docs/irc/msg-id#msg-id-tags-for-notice

MISSING! But also still shows in search.
The direct URL's 404

**Expected documentation**

The documentation

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/73263465-86db3900-41c8-11ea-8e3c-5ba6113de1f6.png)

**Comment by jbulava** [comment]
We are aware of the issue and will be addressing shortly. Apologies for the disruption.

**Comment by jbulava** [comment]
Fixed and restored at time of issue.
