### ISSUE TITLE
Get Emote Sets doesn't allow querying emotesets with non-numeric emoteset IDs

### ISSUE THREAD

**Issue by zneix** [twitchdev/issues#420]
**Description**

I checked recently added Hype Train emotes that are under `qa_TW_Partner` (id `139075904`) account and came across some emotes with weird `emote_set_id`.
Example of the emotes that are in that set:
```json
{
  "id": "emotesv2_f35caa0f5f3243b88cfbd85a3c9e69ff",
  "name": "HypeAttack",
  "images": {
    "url_1x": "https://static-cdn.jtvnw.net/emoticons/v1/emotesv2_f35caa0f5f3243b88cfbd85a3c9e69ff/1.0",
    "url_2x": "https://static-cdn.jtvnw.net/emoticons/v1/emotesv2_f35caa0f5f3243b88cfbd85a3c9e69ff/2.0",
    "url_4x": "https://static-cdn.jtvnw.net/emoticons/v1/emotesv2_f35caa0f5f3243b88cfbd85a3c9e69ff/3.0"
  },
  "tier": "",
  "emote_type": "hypetrain",
  "emote_set_id": "c9f00977-83ce-4391-bef1-525ae806b16f"
}
```

First thing that I noticed is the `emote_set_id` in the form of UUID, which is different than all other emoteset IDs but I assume that this is what twitch now wants to use for emoteset IDs (?)

**How to reproduce**

Anyway, when I made the request to `https://api.twitch.tv/helix/chat/emotes/set?emote_set_id=c9f00977-83ce-4391-bef1-525ae806b16f` I got the following error message:

```json
{
  "error": "Bad Request",
  "status": 400,
  "message": "emote_set_id \"c9f00977-83ce-4391-bef1-525ae806b16f\" must be numeric"
}
```

**Expected behavior**

The API call posted above should return 200 with the emotes and details from emoteset with ID `c9f00977-83ce-4391-bef1-525ae806b16f`

**Screenshots**

N/A

**Additional context or questions**
I noticed that this emoteset is obviously not present in USERSTATE nor Kraken's [Get User Emotes](https://dev.twitch.tv/docs/v5/reference/users#get-user-emotes) response, so there's no way for third parties to know if the user has this emote available or not. Please add a way to detect that.

**Comment by zneix** [comment]
With newly introduced follower emotes I see more of those non-numeric emoteset IDs in USERSTATE messages now and can't fetch emotes from those sets in any way... @jbulava could you guys actually look into this and stop ignoring issues with bug reports of your buggy API?
It's just like the team that works on first-party never ever speaks to third-party team or the other way around.

**Comment by BlueCakeWithCows** [comment]
This issue should be corrected now.
