### ISSUE TITLE
Service Error: "VideoFieldEditor UpdateContentTags"

### ISSUE THREAD

**Issue by thaMANSTA** [twitchdev/issues#421]
**Brief description**
I am unable to remove Content Tags from a VOD currently. 

**How to reproduce**
When trying to remove tags on a VOD, when hitting Save, this error occurs.

**Expected behavior**
Content Tags should be removed from the VOD when I hit Save.

**Screenshots**
![image](https://user-images.githubusercontent.com/874469/122522978-61241f00-cfcb-11eb-9471-dcf7cec1c450.png)

**Additional context or questions**
Using latest Chrome on MacOS

**Comment by BarryCarlyon** [comment]
This is a first party bug/issue not a "product: extensions"/third party bug and probably needs to be reported on the uservoice.

Sounds like https://twitch.uservoice.com/forums/923368-video-features is the best place for this

**Comment by thaMANSTA** [comment]
> This is a first party bug/issue not a "product: extensions"/third party bug and probably needs to be reported on the uservoice.
> 
> Sounds like https://twitch.uservoice.com/forums/923368-video-features is the best place for this

Thanks!  Done: https://twitch.uservoice.com/forums/923368-video-features/suggestions/43669779-service-error-videofieldeditor-updatecontenttags

**Comment by alazymeme** [comment]
> This is a first party bug/issue not a "product: extensions"/third party bug and probably needs to be reported on the uservoice.
> 
> Sounds like https://twitch.uservoice.com/forums/923368-video-features is the best place for this

The readme of this repo states:

> his repository provides a means for third party developers to report bugs – unexpected errors or flaws – related to Twitch developer products such as the **API**, Extensions, and PubSub.

By the looks of it, this is a GQL issue and falls under the developer product **API**. Why would it be reported on uservoice? UserVoice is for feedback and suggestions, not bug reporting.

**Comment by Xemdo** [comment]
Closing as this was a first-party issue.
It is far since relevant, but GQL issues are first-party issues as the 1st party GQL is not a supported interface for 3rd party developers. It may relate in debugging, but issues that exist only in GQL and not in supported 3rd party services are not to be reported in this Github repo.
