### ISSUE TITLE
Get Channel iCalendar: 500 Error on Empty Calendar

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#422]
**Brief description**

If a broadcaster has no schedule.
The iCalendar endpoint will HTTP 500

**How to reproduce**

- Find a streamer without a schdule - https://twitch.tv/barrycarlyonbot/schedule
- Call iCal URL - https://api.twitch.tv/helix/schedule/icalendar?broadcaster_id=56410307

Marvel at

```json
{
"error": "Internal Server Error",
"status": 500,
"message": ""
}
```

**Expected behavior**

A "blank"/empty schedule iCalendar file

**Comment by Magnificus36** [comment]
It looks like this HTTP 500 error got fixed however, the returned iCalendar does not comply with the RFC.
This can be validated easily with: https://icalendar.org/validator.html?url=https://api.twitch.tv/helix/schedule/icalendar?broadcaster_id=56410307

According to RFC 5545 point 3.6 an iCalendar `MUST include at least one calendar component. Special forms of iCalendar objects are possible to publish just busy time (i.e., only a "VFREEBUSY" calendar component) or time zone (i.e., only a "VTIMEZONE" calendar component) information.`
Always including some `VTIMEZONE` components could easily fix this. See also #428

**Comment by Xemdo** [comment]
500 error has since been resolved, so closing this out.
Other issue mentioned is relevant in #805
