### ISSUE TITLE
Schedule endpoints, `is_recurring` should be on segment.*, not the top level data.

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#424]
**Brief description**
All Schedule Helix endpoints mentions `is_recurring` as a field on data, when it is in fact a field on segments
**Expected documentation**
![image](https://user-images.githubusercontent.com/1502855/122646971-3bf5f480-d122-11eb-82ef-02ff14bd3145.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1502855/122646987-4d3f0100-d122-11eb-83b8-46ef929953f5.png)

**Additional context or questions**

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-channel-stream-schedule.
