### ISSUE TITLE
Websub 404ing and saying deprecated to a client Id that's been accessing it for months.

### ISSUE THREAD

**Issue by jdudetv** [twitchdev/issues#425]
So my client ID no longer has access to websub even though I've been using websub for the last year+. I'm getting a 404 error on my calls now with the deprecated response. As it's not September yet this seems like a bug.

My client ID is: 01vdkwx5pl2iq62xjhsbabpwd9t53g

**Comment by lleadbet** [comment]
You should be set- sorry about that.
