### ISSUE TITLE
Get Emote Sets endpoint only allows up to 10 sets per request

### ISSUE THREAD

**Issue by badoge** [twitchdev/issues#426]
**Brief description**
Documentation says that the maximum number of sets per call is 25, but when I make a request with 11 sets I get an error saying that the number of sets should be 10 or less.
https://dev.twitch.tv/docs/api/reference#get-emote-sets

**Expected documentation**
State that the maximum number of sets is 10 in the docs, or allow requests with up to 25 sets.

**Screenshots**
![image](https://user-images.githubusercontent.com/18620902/122664632-9db26f00-d1b3-11eb-8759-a8a06be9859a.png)
![image](https://user-images.githubusercontent.com/18620902/122664641-a7d46d80-d1b3-11eb-90e8-00cad8ca4faf.png)

**Additional context or questions**
:)

**Comment by Xemdo** [comment]
Seems to be resolved. I can only enter a max of 25
