### ISSUE TITLE
Get Broadcaster Subscriptions with a blank user_id - misleading error

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#427]
**Brief description**

If you call get broadcaster subscriptions with a valid broadcaster_id and a blank user_id, you get a misleading error response

**How to reproduce**

call 

- https://api.twitch.tv/helix/subscriptions?broadcaster_id=USERID&user_id=

Get

```json
{
"error": "Bad Request",
"status": 400,
"message": "owner_id is required"
}
```

- https://api.twitch.tv/helix/subscriptions?broadcaster_id=USERID&user_id=barrycarlyon

get 

```json
{
"data": []
}
```

**Expected behavior**

On blank error to say "needs an ID"
On invalid userID say "is invalid"

**Comment by Xemdo** [comment]
`owner_id` message has since been resolved. Empty array for bad user_id is valid as per our documentation.
