### ISSUE TITLE
Get Channel Chat Badges documented as requiring broadcaster auth

### ISSUE THREAD

**Issue by tduva** [twitchdev/issues#429]
**Brief description**
The [Get Channel Chat Badges](https://dev.twitch.tv/docs/api/reference#get-channel-chat-badges) endpoint states for the `broadcaster_id` Parameter:

> The broadcaster whose chat badges are being requested. Provided broadcaster_id must match the user_id in the user OAuth token.

That doesn't seem to be accurate, since I can request the channel badges for any channel with my User OAuth Token (which makes sense, since it's public information).

**Expected documentation**

The `broadcaster_id` Parameter description should simply state:

> The broadcaster whose chat badges are being requested.

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-channel-chat-badges.
