### ISSUE TITLE
Malformed PRIVMSG message received

### ISSUE THREAD

**Issue by RAnders00** [twitchdev/issues#431]
**Brief description**
A user of my library is reporting to have received a malformed `PRIVMSG` message related to an incoming host, the following is the error message:

```
2021-02-27 17:01:34,327 ERROR [twitch_irc::connection::event_loop] Failed to parse incoming message as ServerMessage (emitting as generic instead): Could not parse IRC message :jtv!jtv@jtv.tmi.twitch.tv PRIVMSG stuck_overflow :laempie is now hosting you for up to 6 viewers. as ServerMessage: Malformed channel parameter (# must be present + something after it)
```

Repeating the raw IRC message received:

```
:jtv!jtv@jtv.tmi.twitch.tv PRIVMSG stuck_overflow :laempie is now hosting you for up to 6 viewers.
```

**How to reproduce**
I do not know of any way to reproduce this. I myself have never seen this message being emitted by a Twitch IRC server.

**Expected behavior**
The `PRIVMSG` message conforms to the documented format: https://dev.twitch.tv/docs/irc/tags#privmsg-twitch-tags

**Screenshots**

**Additional context or questions**
Related issue: https://github.com/robotty/twitch-irc-rs/issues/114

**Comment by iProdigy** [comment]
It's worth noting that twitch has been sending such "malformed" notices for a long time (but it's only sent to the broadcaster): `:jtv!jtv@jtv.tmi.twitch.tv PRIVMSG posadabot :OGprodigy is now hosting you.`

The inclusion of the viewer count is new though

**Comment by nerosnm** [comment]
I'm now running into the same error:

```
Jul 31 10:01:10.053 ERROR twitch_irc::connection::event_loop: Failed to parse incoming message as ServerMessage (emitting as generic instead): Could not parse IRC message :oxoboxowot!oxoboxowot@oxoboxowot.tmi.twitch.tv JOIN stuck_overflow as ServerMessage: Malformed channel parameter (# must be present + something after it)
```

**Comment by nerosnm** [comment]
Okay, in my case it seems to be a result of me mistakenly passing a comma-separated list of channel names to @RAnders00's library, which presumably passed them on to the Twitch API. I was asking my bot to join the channel `nerosnm,stuck_overflow` due to a misunderstanding about my CLI parsing. The interesting thing is that I think this was silently accepted by Twitch before, because my documentation says to use a comma-separated list, and that's what I've been doing this whole time.

**Comment by RAnders00** [comment]
> Okay, in my case it seems to be a result of me mistakenly passing a comma-separated list of channel names to @RAnders00's library, which presumably passed them on to the Twitch API. I was asking my bot to join the channel `nerosnm,stuck_overflow` due to a misunderstanding about my CLI parsing. The interesting thing is that I think this was silently accepted by Twitch before, because my documentation says to use a comma-separated list, and that's what I've been doing this whole time.

Which library is that? (Because I made two)

**Comment by nerosnm** [comment]
I was referring to the Rust crate, specifically the issue that led me here was the one you mentioned originally: robotty/twitch-irc-rs#114

**Comment by Xemdo** [comment]
Cannot reproduce, and hosting has been deprecated so it shouldn't reoccur.
If something similar occurs please reopen.
