### ISSUE TITLE
No broadcasterID in the example for check automod enforcment

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#434]
**Brief description**

As Raised on discord

https://discord.com/channels/504015559252377601/523675960797691915/857881702097747968

https://dev.twitch.tv/docs/api/reference#check-automod-status

has no `broadcaster_id` in the example

**Expected documentation**

Revise example to include a `broadcaster_id` in the example call URL

**Comment by Xemdo** [comment]
Docs have since been updated to include `broadcaster_id` in the example.
