### ISSUE TITLE
Error renaming extension.

### ISSUE THREAD

**Issue by cyraid** [twitchdev/issues#440]
**Brief description**
Error

Your request could not be completed at this time. Please double check the format of your request and try again. If you need additional support, please visit this page to submit a ticket.

**How to reproduce**
Try to rename your extension?

**Expected behavior**
My extension renamed.

**Screenshots**
![image](https://user-images.githubusercontent.com/7562753/125174707-ff4f7300-e18c-11eb-9443-a41ab0331a52.png)

**Comment by BarryCarlyon** [comment]
That might indicate the new name you are trying to use is in use, or belongs to a "deleted" extension.
Since a "deleted" extension leaves the name "locked"

So did you delete an extension then try to rename an extension to the "deleted" extension name?

**Comment by cyraid** [comment]
Hi Barry. I'm just trying to rename it to something else (haven't renamed it yet), tried quite a few other names. Just trying to rename my extension. Renaming the extensions are through the OAuth Client Name, right?

**Comment by cyraid** [comment]
Actually, the name included one of the keywords it shouldn't have. Maybe a bit generic of an error message, but in the end my fault!

**Comment by BarryCarlyon** [comment]
Is this also a duplicate of #438 ?
