### ISSUE TITLE
No PubSub event when host used from quick actions

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#441]
**Brief description**

if the dashboard quick action button is used to start a host.

It doesn't trigger a pubsub message (or mod actions in the moderator dashboard)

Quick actions sub only

**How to reproduce**

Use quick actions to start a host
Discover no pubsub message was sent to the moderators topic
And nothing was logged to the "mod actions" in the moderator log or dashboard log

**Expected behavior**

A message to be emitted

**Additional context or questions**

This is likely a bug in the back end reporting system preventing it percolating to all systems and may be a similar bug to what was fixed in #86

**Comment by Xemdo** [comment]
Hosting has since been removed, so this issue shouldn't be relevant anymore.
