### ISSUE TITLE
No one else can see my messages

### ISSUE THREAD

**Issue by Hello22222333456** [twitchdev/issues#442]
**Brief description**
Every time I type on twitch chat it looks normal but no one else sees my messages I send
**How to reproduce**
I made a new account when I joined back to the stream it happened
**Expected behavior**
Call support team and calm down
**Screenshots**
![Screenshot (83)](https://user-images.githubusercontent.com/87386649/125496729-992677f0-61d5-418c-8e73-84e559c71d04.png)
**Additional context or questions**
no questions

**Comment by lleadbet** [comment]
Hello- this github is intended for third party developer issues only. For this issue, please contact Twitch Support. http://link.twitch.tv/help
