### ISSUE TITLE
Can not read bits/cheermotes using helixToken

### ISSUE THREAD

**Issue by freaktechnik** [twitchdev/issues#444]
**Brief description**
All enthusiastic about the new `helixToken` I immediately set to validate that it works, sadly all requests to `bits/cheermotes` seem to return a 401 error with the error `app access or user token is required`.

**How to reproduce**
Make a request to `https://api.twitch.tv/helix/bits/cheermotes?broadcaster_id=<some user id with cheermotes>` using a `helixToken`.

**Expected behavior**
The request works just like with an app token.

**Screenshots**

**Additional context or questions**
I share the request logic with other API requests and it works fine for `users?id=` and `chat/emotes/?broadcaster_id=`.

**Comment by ecressey** [comment]
@freaktechnik the fix for this rolled out yesterday. This should be resolved now.

**Comment by freaktechnik** [comment]
Can confirm, request now succeeds, thanks!
