### ISSUE TITLE
Cannot run "editor" level commands via chat.

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#446]
**Brief description**

I cannot run host/unhost/raid/unraid/commercial commands as a chat bot 

This occurs if the authenticating user is the broadcaster _or_ an editor of the channel.

It does work _if_ you use the "old" `channel_editor` scope as I'm using this currently with some of my bots.

**How to reproduce**

- Generate a user Token that has _every_ helix API/"new" Chat scope on it
- Connect a chat bot to chat
- Try to run unhost in a channel;
- recv `"@msg-id=no_permission :tmi.twitch.tv NOTICE #flightsimtrack :You don't have permission to perform that action.\r"`

test was done with _every new scope_ to just _test_

**Expected behavior**

It unhost/host/raid/unraids

**Additional context or questions**

Sure /commercial has an API endpoint to call but host/raid does not.

**Comment by PalmettoBling** [comment]
Further confirmation that the old scope does resolve the issue, and current/modern scopes do not cover this situation.

**Comment by jbulava** [comment]
Updates have been deployed for the newer, equivalent scopes. I'll leave this ticket open until we add the scope definitions to the [Scopes for IRC Commands](https://dev.twitch.tv/docs/irc/guide#scopes-for-irc-commands) section of the docs.

**Comment by BarryCarlyon** [comment]
The "new chat docs" at https://dev.twitch.tv/docs/irc/chat-commands have the _old_ scope. so not sure which scope is the true scope :-P

**Comment by BarryCarlyon** [comment]
Issue no longer relevant since commands are no longer in chat.
