### ISSUE TITLE
Get Broadcaster Subscriptions with an App Access Token

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#45]
**Brief description**

Get Broadcaster Subscriptions doesn't describe how you can use an "App Access Token" for an extension that has sub status enabled, to use the end point

**Expected documentation**

Describe that an "Extension App Access token" can be used when a broadcaster has granted the "channel:read:subscriptions" scope via the Twitch Extension Manager

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848143-get-broadcaster-subscriptions-with-an-app-access-t

**Comment by BarryCarlyon** [comment]
(Reopened since we moved _back_ from uservoice to github

**Comment by jbulava** [comment]
Added for today's deployment. 👍
