### ISSUE TITLE
invalid json response during websub webhooks

### ISSUE THREAD

**Issue by pkdev08** [twitchdev/issues#451]
**Brief description**
Basically upon trying to subscribe, I've been getting this error the past few days. When this occurs, my bot is no longer able to continue subscribing to the remaining subscriptions that are left. I was told this a library side issue.
FetchError: invalid json response body at https://api.twitch.tv/helix/streams?user_id=601103444 reason: Unexpected token < in JSON at position 0
    at /src/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
**How to reproduce**
Try to subscribe with WebSub webhooks
**Expected behavior**
**Screenshots**
FetchError: invalid json response body at https://api.twitch.tv/helix/streams?user_id=601103444 reason: Unexpected token < in JSON at position 0
    at /src/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
**Additional context or questions**

**Comment by Emilgardis** [comment]
Note that webhooks are [deprecated](https://discuss.dev.twitch.tv/t/deprecation-of-websub-based-webhooks/32152).

This issue doesnt seem like a problem on twitchs side, have you checked with the library maintainers?

**Comment by BarryCarlyon** [comment]
This also looks like you direct called the users and streams API

And you haven't actually tried to create a subscription.
