### ISSUE TITLE
window.Twitch.ext.configuration.set does nothing

### ISSUE THREAD

**Issue by nixxquality** [twitchdev/issues#452]
**Brief description**
Calling `window.Twitch.ext.configuration.set` does nothing, even when in a Broadcaster config view with the correct user selected.

**How to reproduce**
No idea. Only seems to happen for some users.

**Expected behavior**
It should work like when it's hosted for real.

**Additional context or questions**
Binding a callback to onError doesn't lead to any error messages printed.
Refreshing the manifest didn't fix it.
Running localStorage.clear() in the rig didn't fix it.
Closing and creating the project again didn't fix it.

If you threw a bunch of error handlers into whatever logic is behind here, perhaps we could debug this issue.
Right now it's a real mystery of a bug.

edit: this is with v1.2.14 on macOS Mojave

**Comment by Xemdo** [comment]
Closing this out as the developer rig has since been deprecated
