### ISSUE TITLE
Get Channel Stream Schedule: broadcaster_id

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#454]
**Brief description**

https://dev.twitch.tv/docs/api/reference#get-channel-stream-schedule

says

> User ID of the broadcaster who owns the channel streaming schedule. Provided broadcaster_id must match the user_id in the user OAuth token.

**Expected documentation**

> User ID of the broadcaster whose schedule you wish to fetch

**Comment by jbulava** [comment]
Fixed and deployed.
