### ISSUE TITLE
Get Extension Configuration Segment doesn't document required broadcaster_id query parameter

### ISSUE THREAD

**Issue by nixxquality** [twitchdev/issues#456]
**Brief description**
The reference on https://dev.twitch.tv/docs/api/reference#get-extension-configuration-segment doesn't specify any query parameters besides extension_id and segment.
I guessed correctly that you need to specify broadcaster_id to access the broadcaster and developer segments.

Additionally if you try to access the broadcaster or developer segment without supplying the broadcaster_id parameter you get a ***500 Internal Server Error*** instead of something more useful.

edit:
You also get an error 500 if you supply broadcaster_id while asking for the global segment.

**Comment by scott-a-white** [comment]
Thanks for pointing out the issue, much appreciated! We've updated the doc accordingly.

**Comment by Xemdo** [comment]
This has been fixed. Closing this out.
