### ISSUE TITLE
Extension Endpoints various

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#461]
**Expected documentation**

# 1

Set Extension Required Configuration

```
URL
PUT helix/extensions/required_configuration
```

Should be 

```
URL
PUT https://api.twitch.tv/helix/extensions/required_configuration
```

# 2

The following say 

`200` instead of `204` in the Response Code table

- Set Extension Configuration Segment
- Set Extension Required Configuration
- Send Extension PubSub Message

# 3

Get Extension Configuration Segment

Omits a `Optional Query Parameters` of `broadcaster_id` for when loading _not_ the global segment

**Comment by jbulava** [comment]
1 and 2 are corrected for today's deployment. Doesn't the description for `broadcaster_id` indicate the conditional requirement, i.e., do not specify if you set segment to global?

**Comment by BarryCarlyon** [comment]
3 does seem no longer relevant.

However the wording on it is wrong

> The ID of the broadcaster that owns the extension. This parameter is required if you set the segment parameter to broadcaster or developer. Do not specify this parameter if you set segment to global.

Should probably read

> The ID of the broadcaster that you wish to get the configuration of. This parameter is required if you set the segment parameter to broadcaster or developer. Do not specify this parameter if you set segment to global.

The broadcaster doesn't "own the extension"

**Comment by jbulava** [comment]
Ah, yes. That makes sense.

**Comment by jbulava** [comment]
Fixed and deployed.
