### ISSUE TITLE
Get Extension Configuration Segment - Internal server Error

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#462]
**Brief description**

If you try to load a `broadcaster` or `developer` segment from the config service and omit the `broadcaster_id` whose config you want to fetch, the API replies with 

HTTP: 500
And body

```
{ error: 'Internal Server Error', status: 500, message: '' }
```

https://dev.twitch.tv/docs/api/reference#get-extension-configuration-segment

**How to reproduce**

```
got({
    url: 'https://api.twitch.tv/helix/extensions/configurations',
    method: 'GET',
    headers: {
        'Client-ID': config.client_id,
        'Authorization': 'Bearer ' + sig
    },
    searchParams: {
        extension_id: config.client_id,
        segment: 'broadcaster'
    },
    responseType: 'json'
})
.then(resp => {
    console.log(resp.body);
})
.catch(err => {
    if (err.response) {
        console.error('API ERROR', err.response.statusCode, err.response.body);
        return;
    }
    console.error('BAD ERROR', err);
});
```

**Expected behavior**

HTTP 4xx with a "missing broadcaster_id" message

**Comment by scott-a-white** [comment]
Thanks for pointing out the issue, much appreciated! We've updated the doc accordingly.

**Comment by Xemdo** [comment]
This looks to be fixed. Closing this out.
