### ISSUE TITLE
Get Extension Configuration Segment - Broadcaster segment

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#464]
**Brief description**

The response omits the `broadcaster_id`

I assume the same issue occurs with the developer segment.

**How to reproduce**

Set a config into a broadcaster segment.
Load it via the API

```
{
  data: [
    {
      segment: 'broadcaster',
      broadcaster_id: '',
      content: '{"style":"cat"}',
      version: ''
    }
  ]
}
```

**Expected behavior**

```
{
  data: [
    {
      segment: 'broadcaster',
      broadcaster_id: 'the_broadcaster_id',
      content: '{"style":"cat"}',
      version: ''
    }
  ]
}
```

**Comment by iProdigy** [comment]
This appears to be fixed now

**Comment by Xemdo** [comment]
This has been fixed. Closing this out.
