### ISSUE TITLE
Replace Stream Tags returns 401 Missing User OAUTH Token even with valid token

### ISSUE THREAD

**Issue by Gambloide** [twitchdev/issues#466]
**Brief description**
I was trying to use Nightbot to update my tags, but only got an error.
I then asked in their community about the issue and was informed the issue was supposedly raised in the past, but not yet resolved. Since I am able to also locally reproduce the issue with my own twitch application and couldn't find a report here, I opened this issue.

The steps to reproduce below are what I did a few minutes ago.

**How to reproduce**
1. Follow https://dev.twitch.tv/docs/api/ to:
    * create a Developer application (https://dev.twitch.tv/console/apps)
    * setup the twitch cli
    * create an auth token with the cli (including the required scope `channel:manage:broadcast`)
    * test everything via the given curl example
2. Call https://dev.twitch.tv/docs/api/reference#get-all-stream-tags to get a list of valid tag_id s
3. Call https://dev.twitch.tv/docs/api/reference#get-users to get my broadcaster_id
3. Call https://dev.twitch.tv/docs/api/reference#replace-stream-tags as documented with a valid not automatically set tag_id

Request and response for the problematic call (redacted bearer token and client id):

``` bash
$ curl -X PUT 'https://api.twitch.tv/helix/streams/tags?broadcaster_id=23853738' \
> -H 'Authorization: Bearer <redacted>' \
> -H 'Client-Id: <redacted>' \
> -H 'Content-Type: application/json' \
> -d '{"tag_ids":["77017b7b-6b98-4f0d-bd39-3ba96b66ec7a"]}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   126  100    74  100    52    323    227 --:--:-- --:--:-- --:--:--   555{"error":"Unauthorized","status":401,"message":"Missing User OAUTH Token"}
```

**Expected behavior**
1. 204 response with no content
2. tags being replaced with the given tags

**Additional context or questions**
The same happens when using the example provided in the docs and just replacing the client_id and bearer token.
I also tried sending an empty body as per the docs, but the response is the same.

Given the error message this is not about missing scopes, but the endpoint ignores the provided token.
I tried it with a token generated via the cli and another created via manual POST request as per https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-client-credentials-flow

**Comment by BarryCarlyon** [comment]
> Given the error message this is not about missing scopes, but the endpoint ignores the provided token.
I tried it with a token generated via the cli and another created via manual POST request as per https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-client-credentials-flow

Wrong token type.

You need a user token that has access to talk to the users account.

You generated a server token and the server doesn't doesn't have access.

You need token type 1 or 2 from https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-authorization-code-flow

not token 3 (Client Credentials)

**Comment by BarryCarlyon** [comment]
However there is also this issue #467 which covers the issue (using the correct token type)

**Comment by Gambloide** [comment]
I'll close this issue then, since #467 is cleaner and about the same topic. Thank you for the clarification.

Since the docs just say "OAuth token required" and I am not familiar with the API at all, I assumed any OAuth token with the scope would do.
