### ISSUE TITLE
Webhooks don't hook when a gift sub ends

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#47]
**Brief description**

No payloads are broadcast for a "unsubscribe" aka expiration of a gift sub

**How to reproduce**

Listen to webhooks

**Expected behavior**

Get a payload when a gift sub dies

**Comment by jbulava** [comment]
Tracking internally on SUBS-5378.

**Comment by jbulava** [comment]
Context also includes the conversation mentioned in Discord:

> Not sure if issue, bug or something else. I'm monitoring, in this case, cohh's subscription events via webhooks and have been pure webhooks for a while. Cohh reported a disparity between dashboard and my count of 600 subs. Which would suggest 600 unsub events were not sent to me.
> I've now done a dump and refil from helix and it's running on pure webhooks again (yes an argument for doing this periodicially anyway) but odd to have a large disparity. Which may have been building up over time

**Comment by jbulava** [comment]
Fix submitted to production on April 9.

**Comment by BarryCarlyon** [comment]
At time of writing, I am yet to receive any gift downs/ends
