### ISSUE TITLE
"Learn More" link for Bounty documentation is broken

### ISSUE THREAD

**Issue by corgrath** [twitchdev/issues#470]
**Brief description**

The "Read More" link when reading about Bounties is broken.

It does to the URL https://twitchadvertising.tv/bountyboard/

**Expected documentation**

I think the link should go to https://twitchadvertising.tv/bounty-board/

**Screenshots**

![broken](https://user-images.githubusercontent.com/472514/128596576-b059b7ec-4e8f-43c8-a35d-101077063596.png)

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
This isn't a bug with the Twitch Third party documentation.

You've reported this issue in the wrong place.

That sounds like a uservoice https://twitch.uservoice.com/

**Comment by corgrath** [comment]
On the organization's Twitch developer dashboard

https://dev.twitch.tv/org/bla-bla-bla-bla/console

**Comment by corgrath** [comment]
Also, the tag was automatically added AFAIK.

**Comment by BarryCarlyon** [comment]
Tag depends on which template you used from https://github.com/twitchdev/issues/issues/new/choose so if you hit "dev site" and got "documentation" might be a bug in the template
