### ISSUE TITLE
No `helixToken` in the rig

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#471]
**Brief description**

Same issue as #455 but for the developer rig

**How to reproduce**

Try to load the helix token

**Expected behavior**

A token exists

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/128628959-1fafd387-f520-490d-80f4-1df53ae17c1d.png)

Left Twitch Website, right is  the rig

**Comment by Hmaal** [comment]
I am also seeing this issue. The 'helixToken' property doesn't even come back in the response, via testing in the Rig. 

Is there a good way to confirm a proper TwitchAPI request in a Front End without this property?

**Comment by BarryCarlyon** [comment]
> Is there a good way to confirm a proper TwitchAPI request in a Front End without this property?

Test on the Twitch Website instead of the Rig.

The rig is analogous, and doesn't quite match the Twitch website.

For best testing, test on the website rather than the Rig.

There is no ETA on when (or even if) the Rig will be patched for this.

**Comment by Hmaal** [comment]
@BarryCarlyon Ahh, you mean by adding the extension in on a channel and confirming in that way?

**Comment by BarryCarlyon** [comment]
Yes

**Comment by Zozman** [comment]
Will +1 this issue.

**Comment by Xemdo** [comment]
Developer Rig has reached end-of-life as of January 31st, 2023. For more information see the announcement here:
https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995
