### ISSUE TITLE
"Learn More" link for Bounty documentation is broken

### ISSUE THREAD

**Issue by corgrath** [twitchdev/issues#472]
**Brief description**

The "Read More" link when reading about Bounties is broken.

It goes to the URL https://twitchadvertising.tv/bountyboard/

**How to reproduce**

Visit the organization's Twitch developer dashboard

https://dev.twitch.tv/org/bla-bla-bla-bla/console

**Expected behavior**

I think the link should go to https://twitchadvertising.tv/bounty-board/

**Screenshots**

![broken](https://user-images.githubusercontent.com/472514/128629347-bc32f7fd-04e1-4d85-94be-8127ebf97ba8.png)

**Additional context or questions**

**Comment by Xemdo** [comment]
This has since been fixed
