### ISSUE TITLE
Referencing V5 Link on IRC privmsg docs

### ISSUE THREAD

**Issue by deefdragon** [twitchdev/issues#474]
**Brief description**
The documentation for the bits parameter of [PRIVMSG](https://dev.twitch.tv/docs/irc/tags#privmsg-twitch-tags) references using the data returned from "the get cheermotes" endpoint, which currently points to a V5 endpoint.
**Expected documentation**
The documentation to point to the equivalent helix endpoint.
**Screenshots**

**Additional context or questions**

**Comment by jbulava** [comment]
Fixed and deployed.
