### ISSUE TITLE
Send Extension PubSub Message random 500

### ISSUE THREAD

**Issue by nixxquality** [twitchdev/issues#479]
**Brief description**
I received an unexpected 500 response while using the Send Extension PubSub Message endpoint correctly

**How to reproduce**
Impossible? Internally you could maybe build some tests where your backend is disabled for the request.

**Expected behavior**
According to the documentation, problems with your backend should return a 503:
https://dev.twitch.tv/docs/api/guide#service-unavailable-error

**Comment by BarryCarlyon** [comment]
Any 5xx code is a problem with the service. Which applies to _any_ Service really.

Twitch just specifically documents the 503. (5xx codes are common everywhere)

Are you always getting 500's? or just spotty ones?

**Comment by nixxquality** [comment]
We talked about this on the Discord, Barry.

This issue is just here as a todo for a Twitch dev to implement error recovery for this function as is implemented on many others.
