### ISSUE TITLE
Predictions and polls partial validation?

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#489]
**Brief description**

If you try to create a poll or a prediction.
With a bad payload, such as _just_ the `broadcaster_id`
If you make the same request twice you get a different error response

**Expected behavior**

Report _all_ the invalid fields in one response, rather than just one random invalid field.

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/130322967-737fb79b-3754-4357-88ee-0e7e253307ad.png)

![image](https://user-images.githubusercontent.com/20999/130322962-b0f74540-7799-468a-8c6b-2cb002702e9f.png)

**Comment by Xemdo** [comment]
The current behavior of all Twitch's APIs is to report an individual error, not a collective list of them. This behavior does not have plans to change at this time.
