### ISSUE TITLE
Prediction create reports non specific error

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#491]
**Brief description**

Automod errors for predictions (and poll creates)
Should report if it was in the title or which of the outcomes it was and what the conflicting word/phrase was.

**How to reproduce**

Create a prediction with

```
{
	"broadcaster_id": "15185913",
	"title": "test",
	"outcomes": [
		{
			"title": "fuck"
		},
		{
			"title": "One"
		}
	],
	"prediction_window": 120
}
```

Results in
```
{
  "error": "Bad Request",
  "status": 400,
  "message": "title or outcome titles are not compliant with content guidelines"
}
```

**Additional context or questions**

If #490 is fixed to be "inline" with predictions then this issue applies to predictions

**Comment by Xemdo** [comment]
Investigated this internally. This functionality has no plans to change.
