### ISSUE TITLE
Twitch CSS

### ISSUE THREAD

**Issue by k-gorod** [twitchdev/issues#492]
```
.persistent-player {
    user-select: none;
}

```
add this lines on any css file, and by this action u will make our lives much better.

![Screenshot from 2021-08-21 21-40-58](https://user-images.githubusercontent.com/58625453/130343169-205f8fb3-9457-4ecd-bc25-adef98b007f1.png)

**Comment by k-gorod** [comment]
mb wrong category. sorry for that. Have a nice day

**Comment by BarryCarlyon** [comment]
This looks like a first party suggestion which should be made to the uservoice https://twitch.uservoice.com/
