### ISSUE TITLE
part of the text on the follow button is not visible

### ISSUE THREAD

**Issue by Grimmlok1** [twitchdev/issues#493]
**Brief description**
In Russian, the text on the foul button is displayed incorrectly.
 **Actual result:** "Отслежи" - "вать" is not visible
**Expected Result:** "Отслеживать"
**How to reproduce**
1) Open twitch and change language on Russian (check screenshots 1 and 2);
2) Select any unfollow Chanel;
3) Look at the Follow button under the player;
4) Check it.
**Expected behavior**
The text on the button "Отслеживать" should be completely visible
**Screenshots**
![12](https://user-images.githubusercontent.com/89391767/131161507-57abf2d8-571c-451b-b5b9-83407483c301.png)
![Screenshot_52](https://user-images.githubusercontent.com/89391767/131161599-466f7d96-a730-4bbd-9775-6ab22c82c0b1.png)
![Screenshot_2](https://user-images.githubusercontent.com/89391767/131162149-85361b26-1699-43c1-a355-4d0afd16a8fe.png)

**Additional context or questions**
 Defect is not critical, but it doesn't looks good.

**Comment by BarryCarlyon** [comment]
First party problems need to be reported ot the uservoice - https://twitch.uservoice.com/

We do not have a category for the frontend on this GitHub, as this GitHub is for third party issues.
So your issue is also mis-categorized as we don't have a category for the frontend

**Comment by Grimmlok1** [comment]
Got it thanks.
