### ISSUE TITLE
Make rate limit headers available to CORS / client-side requests

### ISSUE THREAD

**Issue by CommanderRoot** [twitchdev/issues#499]
Currently the rate limit headers `ratelimit-reset`, `ratelimit-remaining` and `ratelimit-limit` are not accessible on browser / cors requests due to browser restrictions.
I request that Twitch adds the [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) header on the helix endpoints so that tools running in a browser can follow the rate limits without guessing if they are still within the limits or having to watch for 429 HTTP codes.

**Comment by BarryCarlyon** [comment]
This would be a feature reuqest and feature requests should go to the uservoice https://twitch.uservoice.com/forums/310213-developers

**Comment by CommanderRoot** [comment]
Ok, [created ](https://twitch.uservoice.com/forums/310213-developers/suggestions/44104659-make-rate-limit-headers-available-to-cors-client) as requested
