### ISSUE TITLE
Certain emotesets return error 500 when retreiving emote images

### ISSUE THREAD

**Issue by jjlucsy** [twitchdev/issues#50]
The chat message USERSTATE will contain all the emotesets that a user has. I've found two sets that will produce an error 500 when trying to retrieve the emote images for them.

**How to reproduce**
curl -H "Accept: application/vnd.twitchtv.v5+json" -H "Client-ID: 046ape8hh5j3y3vx13ta1hdpliu4s2" -X GET "https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=1115262924"
curl -H "Accept: application/vnd.twitchtv.v5+json" -H "Client-ID: 046ape8hh5j3y3vx13ta1hdpliu4s2" -X GET "https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=1500636590"

**Comment by jbulava** [comment]
Ticketed internally as GQL-915. Investigating if this is a bug that needs further attention.

**Comment by mccxiv** [comment]
Another one for your investigation: `950319492`

```
curl -X GET \
  'https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=950319492' \
  -H 'Accept: application/vnd.twitchtv.v5+json' \
  -H 'Cache-Control: no-cache' \
  -H 'Client-ID: 1pr5dzvymq1unqa2xiavdkvslsn4ebe'
```

```
{
    "error": "Internal Server Error",
    "status": 500,
    "message": ""
}
```

**Comment by tduva** [comment]
My users (and myself) are having this issue as well. In addition to some emotesets always causing error 500 (others posted examples above), it lately seems to be returning error 500 on and off for any request.

**Comment by remixer-dec** [comment]
I have 100% error rate in the last 4 days with emotesets=0

**Comment by DaGaffer** [comment]
@remixer-dec Same here.

**Comment by RAnders00** [comment]
I think this issue is a bit more severe than "Investigating if this is a bug that needs further attention." if it affects emote set 0 (global emotes). I reckon a number of integrations are relying on global emotes in some way.

**Comment by Xemdo** [comment]
Closing due to the deprecation of the Kraken API as of February 2023.
