### ISSUE TITLE
Empty user_name field in Get Followed Streams endpoint when channel first comes online

### ISSUE THREAD

**Issue by Wallboy** [twitchdev/issues#500]
**Brief description**
When a channel first comes online, if you make a request to the [Get Followed Streams](https://dev.twitch.tv/docs/api/reference#get-followed-streams) endpoint, the `user_name` field will be an empty string for that channel.

**How to reproduce**
It's easy to reproduce: 

Use a test account and follow yourself on another account. Go online on the test account and make a request to [Get Followed Streams](https://dev.twitch.tv/docs/api/reference#get-followed-streams) endpoint until the channel shows up. The `user_name` field will be an empty string. This problem persists when making the same request for roughly ~15-30 seconds until the problem fixes itself and the `user_name` will finally have the proper value.

**Expected behavior**
`user_name` field is not an empty string

**Screenshots**
Here is the JSON returned when the problem happens:

https://pastebin.com/KM5cF5Za

**Additional context or questions**
I noticed [someone having a similar issue with the webhook](https://discuss.dev.twitch.tv/t/webhook-sometimes-sending-blank-user-name/19712) that was posted nearly 3 years ago. I'm not sure if the problem is related.

**Comment by bastimeyer** [comment]
Still not fixed. Both the `user_name` and `tag_ids` fields are empty/null.

Example response from a followed stream which has just come online:

```json
{
	"id": "45250445197",
	"user_id": "26490481",
	"user_login": "summit1g",
	"user_name": "",
	"game_id": "138585",
	"game_name": "Hearthstone",
	"type": "live",
	"title": "chillin on hearth. !gfuel !merch - @summit1g",
	"viewer_count": 0,
	"started_at": "2022-01-22T23:15:17Z",
	"language": "en",
	"thumbnail_url": "https://static-cdn.jtvnw.net/previews-ttv/live_user_summit1g-{width}x{height}.jpg",
	"tag_ids": null,
	"is_mature": false
}
```

As a workaround, the users endpoint can be queried with the user_id, which is available (fortunately).

**Comment by Klemms** [comment]
Still an issue

**Comment by Xemdo** [comment]
Unable to reproduce this when testing. Not sure if this is still an occurring issue.
