### ISSUE TITLE
"Get Live Channels" - rename to "Get Extension Live Channels"

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#503]
**Brief description**

The name of the documentation section is kinda misleading.

**Expected documentation**

Get Live Channels
https://dev.twitch.tv/docs/api/reference#get-live-channels

Get Extension Live Channels
https://dev.twitch.tv/docs/api/reference#get-extension-live-channels

**Comment by jbulava** [comment]
The title and anchor link have been updated to use "Get Extension Live Channels" to give context in the API reference that this applies to Extensions. The update will be included in today's documentation deployment.
