### ISSUE TITLE
Whisper messages are sporadically not displayed

### ISSUE THREAD

**Issue by Lord-Vendreth** [twitchdev/issues#504]
**Brief description**
I have created a game called "HackGame" in a bot with the tmi.js (version 1.8.3) that outputs whisper messages and also checks them itself to see if they were really written in chat. The console output shows that both the text was sent and the output of the text occurred. However, looking at the history of the whisper messages, some messages are swallowed. The message at 14:52:20 (see screenshots) is not displayed in the chat.

**How to reproduce**
Create a script that sends 3 whisper messages within 400 - 1200 milliseconds on a given command. 
Execute the command several times in a row. Sometimes all messages are displayed, sometimes one or more messages are not displayed. Check if the messages were sent and check if the script receives the messages again. Then compare what the bot receives and chat output.

To test this with my bot "Der_Kanalarbeiter" it is enough to whisper >> !skillshop << at my bot. The bot must return 3 messages.
1. "Skill: Trace | Beschreibung: Erhalte die IP-Adresse eines Benutzers der an einem laufenden Hack teilnimmt. Anwendung per Whisper: !trace <Benutzername> | Level: 1 | Abklingzeit: 300s | Energie-Kosten: 15 | Kaufbefehl: !skillbuy trace"
2. "Skill: Kill Support Connection | Beschreibung: Wirf einen unterstützenden Benutzer aus einem laufenden Hack. Anwendung per Whisper: !killsupport <IP-Adresse> | Level: 1 | Abklingzeit: 900s | Energie-Kosten: 50 | Kaufbefehl: !skillbuy killsupport"
3. "Skill: Kill Hacker Connection | Beschreibung: Unterbreche einen laufenden Hack indem der leitende Hacker raus geworfen wird. Anwendung per Whisper: !killhack <IP-Adresse> | Level: 1 | Abklingzeit: 3600s | Energie-Kosten: 150 | Kaufbefehl: !skillbuy killhack"

**Expected behavior**
The whisper messages displayed should correspond to what the bot receives.

**Screenshots**
![mRemoteNG_2021-09-25_14-53-12](https://user-images.githubusercontent.com/29972163/134772540-fc9685e8-f57d-47ea-8c35-b5fed5908ba3.png)

![Chatty_2021-09-25_14-53-23](https://user-images.githubusercontent.com/29972163/134772545-0bf2c90b-495c-49af-9197-86f47a198e58.png)

**Additional context or questions**

**Comment by Xemdo** [comment]
This was using the /whisper IRC command, which is now deprecated:
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486/

Shouldn't be happening using Helix API's whisper endpoint, although whispers can still be subject to being dropped for reasons not revealed externally by Twitch's systems.
