### ISSUE TITLE
Creator Goals EventSub event has conflicting docs for 'type' field

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#505]
**Brief description**
Under [Goals Event](https://dev.twitch.tv/docs/eventsub/eventsub-reference#goals-event), the `type` field is documented to take on either `followers` or `subscriptions` (notice that these are plural).

However, the [notification examples](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#begin-goals-event) use the *singular* form: `"type": "subscription"`.

**Expected documentation**
Consistent usage of the correct possible values in the docs

**Comment by jackmcguire1** [comment]
Bunp

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/eventsub/eventsub-reference#goals-event.
