### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CTACHEAHAHAC** [twitchdev/issues#506]
**Brief description**

**How to reproduce**

**Expected behavior**

![image](https://user-images.githubusercontent.com/91540255/135081887-7fe7933d-11de-41aa-8048-ac9cb4fdfa05.png)
![image](https://user-images.githubusercontent.com/91540255/135082010-6b00e8c7-2715-46f2-86fd-60e0f829e68d.png)

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
This is a first party bug/translation issue and should be reported to the uservoice https://twitch.uservoice.com/

it should not be reported ot the third party products issue tracker

You are in the wrong place!
