### ISSUE TITLE
Extension viewer Session Token

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#51]
**Brief description**

https://dev.twitch.tv/docs/extensions/reference#helper-viewer

documentation wrong:

```
sessionToken
Twitch.ext.viewer.isLinked: string

The encoded JWT. This is the same as the token property of the authData parameter that currently gets passed to the onAuthorized callback.
```

**Expected documentation**

```
sessionToken
Twitch.ext.viewer.sessionToken: string

The encoded JWT. This is the same as the token property of the authData parameter that currently gets passed to the onAuthorized callback.
```

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848161-extension-viewer-session-token

**Comment by jbulava** [comment]
Corrected for today's deployment. 👍
