### ISSUE TITLE
Can't upload Game Boxart image

### ISSUE THREAD

**Issue by NakanaMika** [twitchdev/issues#512]
**There's an unexpected error when I upload a Boxart for my organization's game**

**Go to an organization's console and to Games https://dev.twitch.tv/org/xxxxx/console/games. Then click on a Game. Then in the Box Art section click on the placeholder image. Then browse an appropriate file and click Submit. The mention "UNEXPECTED ERROR, PLEASE TRY AGAIN." shows up. Around two weeks ago it was working well. **

**It should properly upload and feature the image**
![Screenshot_1](https://user-images.githubusercontent.com/64533373/137459717-197a903e-17e1-4506-b80f-ede293973ffc.jpg)

Apologies if this was not the right category to report this bug.

**Comment by BarryCarlyon** [comment]
Currently box art uploads are disabled.

https://discuss.dev.twitch.tv/t/error-uploading-box-cover-art-for-my-game/33899/2

**Comment by beheh** [comment]
With the [recent announcement](https://discuss.dev.twitch.tv/t/twitch-game-cover-art-to-be-powered-by-igdb/34346) of the switch to IGDB as box art source, it seems like uploading box art to Twitch will probably not be possible again:

> To answer another frequently asked question, the self-service functionality in the developer console that has been the process until this point in time will remain unavailable leading up to the transition to IGDB on November 17.

From the same announcement, until November 17th you can update your box art as follows:

> If you are a game developer or publisher who wishes to change the cover art for a game you own, please review these requirements 4, then contact developers@twitch.tv or your designated Solutions Architecture representative with a qualifying image asset. We will be taking cover art update requests via email until November 17. 

After November 17th, according to the announcement, you will have to submit the box art to IGDB from where Twitch will pick it up.

**Comment by jbulava** [comment]
@beheh Thanks for including those notes here.

Please feel free to send an email to update cover art until November 17.
