### ISSUE TITLE
Teams API 500 when ID is non numeric

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#514]
**Brief description**

When reqeusting the teams API if you specify a non numerica as the TeamID, you get a 500 error

```json
{
  "data": [],
  "error": "Internal Server Error",
  "status": 500
}
```

**How to reproduce**

Using CLI

>  twitch api get 'teams?id=aword'

**Expected behavior**

HTTP 4xx with a "this is not a number" messagte

**Comment by Xemdo** [comment]
This behavior seems to be resolved:
```
> twitch api get teams -q id=aword
{
  "data": [],
  "error": "Bad Request",
  "message": "The ID in the id query parameter is not valid.",
  "status": 400
}
```
