### ISSUE TITLE
"Description" - what even is? - Search Channels

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#516]
**Brief description**

The docs for Search Channels refers to "description"
Which is a field not present in the output.

What does Twitch mean by "Description" is this actually the "title" of the stream (which is in the Output)

> Returns a list of channels (users who have streamed within the past 6 months) that match the query via channel name or description either entirely or partially. Results include both live and offline channels. Online channels will have additional metadata (e.g. started_at, tag_ids).

if it is "title" then #515 is a valid bug and https://twitch.uservoice.com/forums/310213-developers/suggestions/43079766-stream-title-searching is an invalid feature request (current tagged investigating)

**Expected documentation**

What does Twitch actually mean.

**Additional context or questions**

https://dev.twitch.tv/docs/api/reference#search-channels

**Comment by Xemdo** [comment]
Documentation has since been updated to make it less ambiguous:
> To match, the beginning of the broadcaster’s name or category must match the query string. The comparison is case insensitive. If the query string is angel_of_death, it matches all names that begin with angel_of_death. However, if the query string is a phrase like angel of death, it matches to names starting with angelofdeath or names starting with angel_of_death.
This still leaves #545 to be determined as a bug or something to be filed as a feature request.
