### ISSUE TITLE
Multi instance rig

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#517]
**Brief description**

The Rig is built in Electron
The Rig doesn't block a second instance startin
The Second instance is completely "buggered"

**How to reproduce**

Open the rig.
See you are authed and all your projects are there
Open the rig again
See you are not authed and if you do then all your projects are "gone"

Close all instances and open a single instance

**Expected behavior**

It either works fine as two instances/windows
Or blocks a second instance (which is done via an electron setup call)

**Comment by Xemdo** [comment]
Developer Rig has reached end-of-life as of January 31st, 2023. For more information see the announcement here:
https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995
