### ISSUE TITLE
Box Art Uploads Temporarily Disabled

### ISSUE THREAD

**Issue by BigBlueBubbleTV** [twitchdev/issues#518]
**Brief description**
Can't upload Box Art for two of our games My Singing Monsters Playground & Power Chord. Get an error "Box Art Uploads Temporarily Disabled"

**How to reproduce**

Seen in games box art section for the two titles.

**Expected behavior**
Should be able to upload art

**Screenshots**
![image](https://user-images.githubusercontent.com/93154250/138747488-347b6b04-90b8-4ff3-a7dd-f95048e9d6c4.png)

**Additional context or questions**

**Comment by jbulava** [comment]
Following up on individual posts and issues regarding cover art uploads, we wanted to make sure everyone has seen the following announcement. Please feel free to submit a cover art request via email until November 17, at which point they will be handled via IGDB contributions.

https://discuss.dev.twitch.tv/t/twitch-game-cover-art-to-be-powered-by-igdb/34346
