### ISSUE TITLE
Clips API time param handling silently changed, different from documentation now

### ISSUE THREAD

**Issue by willlllllio** [twitchdev/issues#52]
**Brief description**
The Get Clips documentation says for `started_at` and `ended_at`: `(Note that the seconds value is ignored.)` https://dev.twitch.tv/docs/api/reference#get-clips

However it seems the API behavior was silently changed to ignore the single digit value of the minute too and not just the seconds.

So for example a `started_at` value of `2020-01-29T22:57:39` seems to be treated like `2020-01-29T22:50:00` instead if `2020-01-29T22:57:00`, with minutes 57 being turned into minutes 50.

**How to reproduce**

`curl 'https://api.twitch.tv/helix/clips?broadcaster_id=23161357&started_at=2020-01-29T22:41:00Z&ended_at=2020-01-29T22:42:00Z&first=100' `

`22:41:00 - 22:42:00` => 0 results

`curl 'https://api.twitch.tv/helix/clips?broadcaster_id=23161357&started_at=2020-01-29T22:40:00Z&ended_at=2020-01-29T22:49:00Z&first=100'`

`22:40:00 - 22:49:00` => 0 results

`curl 'https://api.twitch.tv/helix/clips?broadcaster_id=23161357&started_at=2020-01-29T22:49:00Z&ended_at=2020-01-29T22:50:00Z&first=100' `

`22:49:00 - 22:50:00` => Many results with values from 22:41:26 to 22:49:59

**Expected behavior**
Expected it to work like the documentation says.

`22:41:00 - 22:42:00` => results with minutes 41 to 42, not no results
`22:40:00 - 22:49:00` => results with minutes 40 to 49, not no results
`22:49:00 - 22:50:00` => results with minutes 49 to 50, not minute 40 to 50

**Screenshots**

**Additional context or questions**

The API appears to have been silently changed in the last couple months, it used to only ignore the seconds value like documented. 

I couldn't find any announcement of functionality changes so I'm not sure if the change was intended and just the docs update was missed or if that was accidental but the API docs and actual behavior being different can lead to quite a lot of confusion right now. Would be very nice to have that fixed, on whatever side makes more sense. Thank you!

**Comment by mauerbac** [comment]
Thanks @willlllllio .Looks like an issue with the product first. Then we can update dev docs. Submitted internally HLX-1327

**Comment by jbulava** [comment]
Great catch and much appreciated. There was an update to internal services in the past year that intentionally truncated the timestamp to 10-minute intervals, but this was never announced as a change that would affect third party developers or updated in the documentation.  With this confirmed, a documentation request has been created to correctly reflect 10-minute intervals (DXDOC-259).
