### ISSUE TITLE
problem problem with the two-step authenticator

### ISSUE THREAD

**Issue by GonzalezNahuel** [twitchdev/issues#528]
**Brief description**
I try to do the authenticator and it sends me an error
(I'm speak Spanish for the imagen in spanish)

**How to reproduce**
I send my number the message arrives and it does not validate it

**Expected behavior**
I need to verify it to be able to use and test the twitch api a bit

**Screenshots**
![Sin título](https://user-images.githubusercontent.com/88909163/143718783-215162e4-b401-4174-8234-85594dde7792.png)

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
For help with first party issues please visit

https://help.twitch.tv/

You are in the wrong place and you cannot be helped here with this issue.

**Comment by GonzalezNahuel** [comment]
oh sorry, thanks for the help
