### ISSUE TITLE
Prime Gaming Bug

### ISSUE THREAD

**Issue by Itsdayez** [twitchdev/issues#529]
**Brief description** I have got prime gaming ( free teir 1 sub) but i cann't use it, everytime it runs out it automatically renews to a random person

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
This is not a bug tracker for the first party website/problems

It sounds like someone else is logged in to your account and using the prime

For further help

https://help.twitch.tv/
