### ISSUE TITLE
Get EventSub Descriptions - Example doesn't match the doc

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#531]
**Brief description**

https://dev.twitch.tv/docs/api/reference#get-eventsub-subscriptions

Use `webhook_callback_verification_pending` in the Response Fields table but `webhook-callback-verification-pending` in the example

**Expected documentation**

Which ever is correct (which iirc is the `_` version) to be applied in both places.

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-eventsub-subscriptions.
