### ISSUE TITLE
Get Soundtrack Current Track - 404 bug?

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#533]
**Brief description**

If $channel is not playing a song
You get a HTTP 404 with a payload

**How to reproduce**

Call a channel not playing a song

**Expected behavior**

HTTP 200 OK with the payload as is

**Additional context or questions**

This would match other helix endpoints (Get User)

**Comment by iProdigy** [comment]
This is particularly problematic since the docs explicitly state the behavior should be different:
`The list is empty if the broadcaster is not playing a track.`

Instead we get `{"error":"Not Found","status":404,"message":"Broadcaster is not currently playing any track on Soundtrack"}`

**Comment by Xemdo** [comment]
Soundtrack product and API has been deprecated:
https://discuss.dev.twitch.tv/t/withdrawal-of-twitch-api-endpoints-for-soundtrack/46021
