### ISSUE TITLE
Get Soundtrack Playlist: invalid ASIN with `data`?

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#534]
**Brief description**

Get Soundtrack by playlist ID has incosnsitent behaviour with the rest of helix when the ASIN/PlaylistID is invalid

**How to reproduce**

> twitch api get 'soundtrack/playlist?id=109bd24a-40d0-402d-9f52-bc46e19c9543'

```json
{
  "data": [],
  "error": "Bad Request",
  "message": "invalid ASIN",
  "status": 400
}
```

**Expected behavior**

No `data` in the response it is inconsistent with other Helix endpoints

**Comment by iProdigy** [comment]
`109bd24a-40d0-402d-9f52-bc46e19c9543` is a stationID, not a playlist ASIN

**Comment by BarryCarlyon** [comment]
@iProdigy correc but the problem here is:

> No data in the response it is inconsistent with other Helix endpoints

Not that I passed an invalid ASIN

**Comment by iProdigy** [comment]
> No `data` in the response it is inconsistent with other Helix endpoints

Thanks for the clarification - I see what you mean now

**Comment by Xemdo** [comment]
Soundtrack product and API has been deprecated:
https://discuss.dev.twitch.tv/t/withdrawal-of-twitch-api-endpoints-for-soundtrack/46021
