### ISSUE TITLE
Remove blocked Termds - double broadcaster_id

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#536]
**Brief description**

https://dev.twitch.tv/docs/api/reference#remove-blocked-term

has two broadcaster_id entries in the query params talbe

**Expected documentation**

Just the one

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/145601764-745ac313-f7c1-4871-89be-c1fb2f9f49b2.png)

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#remove-blocked-term.
