### ISSUE TITLE
SoundTrack API docs have multiple example/response table missmatches

### ISSUE THREAD

**Issue by Syzuna** [twitchdev/issues#538]
**Brief description**

The examples and the response field tables provided for the SoundTrack APIs have multiple missmatches.

**Expected documentation**

- Artists is an array in the examples but the response field table says its just an object called artist. In fact it really is an array as a track can have multiple artists ofc. So the response table needs to be updated to show it as an array and to call it artists instead of artist [Get Soundtrack Current Track] [Get Soundtrack Playlist]
- creator_channel_id is shown as empty string if the track was not created by a Twitch creator in the examples but the response table states that its null if thats the case. The correct behavior from tests with the API seems to be that its an empty string so the response field table needs to be updated [Get Soundtrack Current Track] [Get Soundtrack Playlist]
- Example says the field is named SoundtrackURL but the response table says its indeed soundtrack_url. The example needs to be changed to use "soundtrack_url" [Get Soundtrack Current Track]
- The example shows it as catalog_tracks the response field table only shows it as tracks. The API returns it as catalog_tracks like in the example so the table needs to be adjusted to name it catalog_tracks as well.  [Get Soundtrack Playlist]

**Comment by scott-a-white** [comment]
Thanks for reporting the issues. Fixed.
https://dev.twitch.tv/docs/api/reference#get-soundtrack-current-track 
https://dev.twitch.tv/docs/api/reference#get-soundtrack-playlist
