### ISSUE TITLE
extensions/live not a "fixed" order

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#539]
**Brief description**

In an extension of the issue in #524

**How to reproduce**

If you load live activated channels.
Then load it again

The order of results is different.

This is further seen by setting ?first=2 and just loading again and againm

**Expected behavior**

The order ot be consistent

**Comment by jbulava** [comment]
Created a ticket related to #540 to investigate.
HLX-2299

**Comment by jbulava** [comment]
The team has deployed the fix for this today.

**Comment by BarryCarlyon** [comment]
Looks good
