### ISSUE TITLE
Rig : Update Electron version

### ISSUE THREAD

**Issue by Djiit** [twitchdev/issues#54]
**Brief description**

The Twitch Developer Rig is using an outdated Electron version (using Chrome 68 according to the Developer Tools)

**How to reproduce**

Use a recent ECMAScript feature like Array#flatMap

**Expected behavior**

It shouldn't throw an error.

**Additional context or questions**

Maybe we should repackage the Rig with Electron 8 ? Right now it forces us to use shim when developing localy with the rig.

**Comment by mauerbac** [comment]
Thanks @Djiit. Submitted EXT-1159

**Comment by lleadbet** [comment]
We just updated the developer rig to Electron 9 to address this issue- thanks for the report!

**Comment by Djiit** [comment]
Thanks !
