### ISSUE TITLE
Get Stream Tags has reversed /tags/streams endpoint in example

### ISSUE THREAD

**Issue by rwxrob** [twitchdev/issues#542]
**Brief description**

Get Stream Tags documentation example is /tags/streams

**Expected documentation**

should be /streams/tags

**Screenshots**

![Screenshot from 2021-12-26 08-28-03](https://user-images.githubusercontent.com/3749067/147409587-3eb4540c-9e82-486a-9102-862a93b537fd.png)

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-stream-tags.
