### ISSUE TITLE
Channel Search does not search titles

### ISSUE THREAD

**Issue by caffeinewriter** [twitchdev/issues#545]
**Brief description**
According to the [v5 Migration Guide](https://dev.twitch.tv/docs/api/migration), I would expect the `search/channels` endpoint to search stream titles, especially with this wording in the migration notes.

> The v5 endpoint searched for the channel title and category. Use “Search Channels” to match channel name or title. Use “Search Categories” to match a category.

Although according to the [Search Channels API reference](https://dev.twitch.tv/docs/api/reference#search-channels), the title searching functionality is less clear. If this is the intended behavior for the new API, it can hardly be considered a replacement for how v5 functioned previously.

**How to reproduce**
Search for a term that is popularly contained in titles, such as `dixper` or `kappamon` (two popular third-party stream extensions), or the name of a GTA V RP server like `NewDayRP`. E.g. With the twitch CLI:

`twitch api get search/channels -q live_only=true -q query=dixper`
`twitch api get search/channels -q live_only=true -q query=NewDayRP`

**Expected behavior**
`search/channels` returns streams with titles matching the query. 

**Screenshots**
I've recorded a couple screen casts of the behavior:

[Search for `dixper`](https://streamable.com/ynm3gt)
[Search for `NewDayRP`](https://streamable.com/18nvzq)

**Additional context or questions**
I reported an exceedingly similar issue for v5 in #515, and the issue with the search not including titles persists to Helix.

**Comment by BarryCarlyon** [comment]
Yeah was gonna say 515 superseeds this based on the uservoice here

https://github.com/twitchdev/issues/issues/515#issuecomment-948619957

So 515 just needs moving to the helix label.

Or you can close 515 as you've made a duplicate

**Comment by Xemdo** [comment]
This is expected behavior. Any changes to this behavior are to be requested in the open User Voice:
https://twitch.uservoice.com/forums/310213-developers/suggestions/43079766-stream-title-searching
