### ISSUE TITLE
Twitch web chat scrollbar length error

### ISSUE THREAD

**Issue by haeyongE** [twitchdev/issues#546]
**Brief description**
When using Twitch Chat, a bug occurs in the calculation of the row variable of the chat's text area.
sorry for the poor english. I use Papago to submit this issue.
**How to reproduce**
I think a little bit of fix at the calculation of the row variable of the chat's text area will solve the bug.
**Expected behavior**
I just want to fix this
**Screenshots**
![화면 캡처 2021-12-29 175710](https://user-images.githubusercontent.com/96817594/147645103-9b935ef4-babb-428d-9a9e-ba723a4eadb5.jpg)
![화면 캡처 2021-12-29 175727](https://user-images.githubusercontent.com/96817594/147645107-3f3c1067-92c1-45df-a844-273f6a698617.jpg)
Sorry for another language
**Additional context or questions**
none

**Comment by BarryCarlyon** [comment]
It's a bug in chrome that resurfaced

Additionally as a first party bug/issue it can't be reported to this bug tracker as this tracker is for third party product issues, such as the API or eventsub. Not the actual website itself

**Comment by jbulava** [comment]
Closing this issue as it is not related to third-party developer products and, I assume, already addressed.  For future reference, bug reports for the main Twitch.tv can be supported through the following page: https://help.twitch.tv/s/article/how-to-provide-feedback
