### ISSUE TITLE
Cannot create new Extension in the rig

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#549]
**Brief description**

Cannot create a new Project in the rig, it errors but creates it on the console anyway

Regardless of the name or the name actually being taken of not

> *Sorry, this name is taken. Please try another name. Note: Twitch broadcasters installing your Extension see the name specified in the released version. This is only for API authorization use.

The rig reports that the name is taken and will create the Extension anyway. (or it actuallt errors as the user tries again with the same name)

**How to reproduce**

1. Add Project
2. Create Project
3. Select "New Extension" in the drop down
3. Enter a unique name
4. Select one or more types
5. Next
6. Recieve an error, saying the name is taken
7. Check https://dev.twitch.tv/console/extensions and find that it was created anyway

**Expected behavior**

It doesn't error.

**Additional context or questions**

Likely related to the new CSP fields that the rig can't handle properly

> main.c2a24fe7.chunk.js:1 Error: Variable "connectDomains" has invalid value null.
Expected type "[String!]!", found null.: {"response":{"errors":[{"message":"Variable \"connectDomains\" has invalid value null.\nExpected type \"[String!]!\", found null.","locations":[{"line":17874,"column":3}]},{"message":"Variable \"imageDomains\" has invalid value null.\nExpected type \"[String!]!\", found null.","locations":[{"line":17877,"column":3}]},{"message":"Variable \"mediaDomains\" has invalid value null.\nExpected type \"[String!]!\", found null.","locations":[{"line":17880,"column":3}]}],"extensions": REMOVED

**Comment by BarryCarlyon** [comment]
Still happening dispite updates made as per #568

**Comment by jbulava** [comment]
Closing with the end of support for the developer rig.
