### ISSUE TITLE
Information about config service unclear

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#55]
**Brief description**

https://dev.twitch.tv/docs/extensions/building#using-the-configuration-service

Doesn't mention the key bit of information regarding the size limit of 5kb

**Additional context or questions**

It's important to note here as people will start designing an extension and then discover the sizing limit late into construction of an extension. For clarity the limit should be noted here also

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848182-information-about-config-service-unclear
