### ISSUE TITLE
Get Channel Information documentation inconsistencies

### ISSUE THREAD

**Issue by Marenthyu** [twitchdev/issues#551]
The [Documentation for the Get Channel Information Endpoint](https://dev.twitch.tv/docs/api/reference#get-channel-information) has 2 notable inconsistencies I stumbled across during development over the weekend.

# What I found
* The ``Required Query Parameters`` Table lists ``ID of the channel to be updated`` as the Description for the ``broadcaster_id`` parameter.
* The ``Return Values`` Table does not list ``broadcaster_login``.

# What I expected
* The ``Required Query Parameters`` Table should reflect the purpose of the ``broadcaster_id`` parameter correctly, for Example with a Description of ``ID of the channel to be looked up``.
* The ``Return Values`` Table should list ``broadcaster_login``; Just as the example on the right hand side does.

**Comment by jbulava** [comment]
Thanks for pointing these out. Corrections are completed for an update later in the week.
