### ISSUE TITLE
All-time top Gifters displayes incorrectly

### ISSUE THREAD

**Issue by evgenia-shulha** [twitchdev/issues#555]
All-time top Gifters displayes incorrectly

**How to reproduce:**
1. Log in into twich account
2.  Take top 3 place of giffters 
3.  Delete an account/ get ban

**Actual result:** If account of the user in top 3 gifters, and their account banned/deleted "All-time top Gifters" names in the top displayed out of the box
**Expected result:** all names of other gifters should be fully visble, text should not be out of the box

![image](https://user-images.githubusercontent.com/68429520/149544881-a116b504-9e19-4ace-bc50-981677881250.png)
![image](https://user-images.githubusercontent.com/68429520/149545079-1fb6899b-d72b-4263-9b7a-645e07b8128c.png)
![image](https://user-images.githubusercontent.com/68429520/149545114-eed91c80-b0db-428a-8806-1d66ae9e7a9d.png)

OC: windows, browser: Opera GX

**Comment by BarryCarlyon** [comment]
First party issues need to be sent via support or uservoice.

Not via the API bug report tracker.

You have flagged this report in the wrong place

**Comment by jbulava** [comment]
Thanks for mentioning the issue.  I've sent this to the appropriate team in case the behavior needs attention.  As it is not related to third-party developer products though, I am closing the ticket with the message delivered.  Thanks.

**Comment by jbulava** [comment]
The team confirmed that the issue was addressed last week.
