### ISSUE TITLE
Helper: Actions - don't work in the rig

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#56]
**Brief description**

Documentation describes that there are functions such as `followChannel` and `requestIdShare` but the documentation doesn't mention that these functions don't work in the rig (at time of writing)

https://dev.twitch.tv/docs/extensions/reference#helper-actions

**Additional context or questions**

https://discordapp.com/channels/504015559252377601/523676096277905419/676767529666084864

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848185-helper-actions-don-t-work-in-the-rig
