### ISSUE TITLE
Translation error for french on new CSP rule

### ISSUE THREAD

**Issue by LirycMoaners** [twitchdev/issues#563]
**Brief description**
Each field for domain to add on the new CSP rule for Twitch extension say the domain will be added in connect-src.

**Expected behavior**
The first one should be img-src and the second one media-src.

**Screenshots**
![image](https://user-images.githubusercontent.com/11617732/151979623-b52a219c-a656-423a-8ac9-5a7717ec7f9c.png)

**Comment by TristanWiley** [comment]
Thanks for pointing this out! These translations have been updated.
