### ISSUE TITLE
Videos of banned users are getting returned

### ISSUE THREAD

**Issue by FloPinguin** [twitchdev/issues#566]
**How to reproduce**

Call https://api.twitch.tv/helix/videos?user_id=129502450&type=archive&first=100
This user is banned at the moment. You can see it at https://www.twitch.tv/iamnigro. 
"This channel is currently unavailable due to a violation of Twitch's Community Guidelines or Terms of Service." 
But the videos endpoint returns a video result.
When you try to open the video in the browser, it is not available.

**Expected behavior**

Do not return videos of banned users as they can't get watched anyway.

**Comment by Xemdo** [comment]
Tried to reproduce with 10 recently banned streamers, all whom had VODs enabled and streamed several times within the last week. Issue seems to be resolved.
