### ISSUE TITLE
Is the Rig Kraken Shutdown safe? Seems it's not!

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#568]
**Brief description**

The rig appears to use a number of "old" Extension endpoints

![image](https://user-images.githubusercontent.com/20999/153276710-0a863b31-5dad-4353-9ee1-427e3d1a2b93.png)

**How to reproduce**

Try to use the config service in the rig during one of the outages.

**Expected behavior**

It to fetch and set config

**Comment by maxcalvin** [comment]
The rig is how we currently update our global extension config, an updated & compatible version would be appreciated!

But thanks @BarryCarlyon for the tool, will give it a look too.

**Comment by BarryCarlyon** [comment]
The rig seems to have been updated for The config Service

![image](https://user-images.githubusercontent.com/20999/155856209-473c3bee-f28f-4541-b5d0-646da3f916f8.png)

But not the Bits/monetisation

Left being "my rig" right being the twitch rig.

![image](https://user-images.githubusercontent.com/20999/155856242-1532acbd-d234-4a46-adc9-cd59b59e1fd3.png)

**Comment by Xemdo** [comment]
Closing with the end of support for the developer rig.
