### ISSUE TITLE
Live Extension Activated Channels: weird pagination

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#57]
**Brief description**

it's an old issue but needs to be logged

https://dev.twitch.tv/docs/extensions/reference/#get-live-channels-with-extension-activated

The pagination/record count is weird

**How to reproduce**

Call the end point, and marvel how page 1 has 3 records, page 2 5 records, page 3 1 record, page 4 3 records....

**Expected behavior**

Fixed number of records on a page and/or a limit option to control records returned.

**Additional context or questions**

It's been like this for _ages_ even more so since the "Channels with extension installed on" broke and was removed

**Comment by Breci** [comment]
Somtimes you can even get an empty array of result with the pagination cursor, and next page you have results.

**Comment by mauerbac** [comment]
EXT-1158

**Comment by guanzo** [comment]
I'd appreciate a fix. My extension has tens of thousands of active channels, that means I have to basically make tens of thousands of api calls. 

count: number of api calls so far
pageSize: how many channels are returned per call. Some calls return zero results + a new token. I've seen 2 consecutive calls with zero results...??
numChannels: how many channels have been returned in total.

![](https://i.gyazo.com/7bc049302216f25c8a13ef3fdbed7ff9.png)

**Comment by BarryCarlyon** [comment]
This is mostly irrelevant now that it has been replaced by a new endpoint but other issues exist

the new endpoint is not gappy like the old
