### ISSUE TITLE
Can't delete extension projects

### ISSUE THREAD

**Issue by twitchtestbeast** [twitchdev/issues#570]
**Issue Title
Can't delete extension projects**

**Recreate issue
Go to https://dev.twitch.tv/console/extensions. 
click "Manage" next to a project.  
Click Extension Settings.  
Click Delete Extension.  
When popup appears, click Delete Extension.  
Nothing happens.  
The popup stays there.  
The extension never deletes. **

**Expectation: 
The extension would be deleted**

**Screenshots

![temp](https://user-images.githubusercontent.com/99563752/153730516-c901c570-1e80-4703-8c34-7149132fdf46.png)

**

**I've tried this on multiple browsers: Edge, Chrome, FireFox.   
I cleared my browser history.  
Still doesnt work**

**Comment by BarryCarlyon** [comment]
An extension must have at least one version.

If it has no versions then it can't be deleted. So add a version first. Then you can delete

If you delete an extension it will **NOT** release the name to be reused.

**Comment by twitchtestbeast** [comment]
Thank you sir.
