### ISSUE TITLE
Twitch prime

### ISSUE THREAD

**Issue by Maaaruu** [twitchdev/issues#574]
I hadthe free opportunity to subscribe to the channel on the Twitch platform, but this subscription was transferred without my participation, to a channel that is not even available.
![image](https://user-images.githubusercontent.com/99876089/154457167-d32032ec-e917-4418-8e94-984b23363d8a.png)
![image](https://user-images.githubusercontent.com/99876089/154457215-19ce6109-060e-4614-9d51-21787ad1f5aa.png)

**Comment by BarryCarlyon** [comment]
This bug tracker is for help with third party product issue.

For Twitch Prime and/or account support please visit https://help.twitch.tv/

You are in the wrong place, we cannot help you
