### ISSUE TITLE
Non useful error message on users/follows

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#575]
**Brief description**
The api returns
```json
{"error":"Bad Request","status":400,"message":"strconv.ParseInt: parsing \"!\": invalid syntax"}
```
When you give a non numeric value as the value of the `first` query param.
**How to reproduce**
Send a non numeric value as the value of the `first` query parameter
**Expected behavior**
Give an descriptive error like the api does when you send non numeric value as the value of one of the other query params
```json
{"error":"Bad Request","status":400,"message":"Param ! is not an integer."}
```

**Comment by Xemdo** [comment]
This API is set to be deprecated on September 12th 2023:
https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated/46769
