### ISSUE TITLE
[Docs] Incorrectly listed requirement for Send Extension Chat Message Endpoint

### ISSUE THREAD

**Issue by Marenthyu** [twitchdev/issues#577]
**Brief description**
In the Docs, it is written ``A signed JWT must include the role and channel_id fields`` for the [Send Extension Chat Message Endpoint](https://dev.twitch.tv/docs/api/reference#send-extension-chat-message). This is not true, as the ``channel_id`` field seems to be completely ignored when calling this Endpoint. Instead, the value of ``user_id`` seems to be required and used, as the Schema dictates. (Note that it does not need to match the broadcaster_id, as it just denotes the Extension owner, not the target broadcaster)

**Expected documentation**
It should list ``user_id`` as the required matching field and not mention ``channel_id``, as it is ignored.

**Screenshots**
https://lowee.de/chrome_2022-02-19_20-22-44.png

**Additional context or questions**
See also Discord Discussion: https://discord.com/channels/504015559252377601/523676096277905419/944671207909908610
@BarryCarlyon used [his testing code](https://github.com/BarryCarlyon/twitch_misc/blob/main/extensions/chat/send_chat.js#L22) to verify the above information.

**Comment by BarryCarlyon** [comment]
```
Authorization
Signed JWT created by an Extension Backend Service (EBS), following the requirements documented in [Signing the JWT](https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt). A signed JWT must include the role and channel_id fields documented in [JWT Schema](https://dev.twitch.tv/docs/extensions/reference/#jwt-schema). role must be set to "external" and channel_id must match the broadcaster ID in the request URL.
```

Should read _just_

```
Authorization
Signed JWT created by an Extension Backend Service (EBS), following the requirements documented in [Signing the JWT](https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt).
```

As the first linked to section is correct. And the second sentence is just superflous

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#send-extension-chat-message.
