### ISSUE TITLE
Missing maximum reward count

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#578]
**Brief description**

The manage/create channel rewards documentation doesn't note the maximum number of rewards a channel can have

https://dev.twitch.tv/docs/api/reference#create-custom-rewards

**Expected documentation**

Note the maximum number of rewards on `https://dev.twitch.tv/docs/api/reference#create-custom-rewards` and the help guide.

Add the error code for when you try to create a 51'st reward

also consider adding a note about the CP's AUP?

**Additional context or questions**

The help guide - https://help.twitch.tv/s/article/channel-points-guide doesn't note this either

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#create-custom-rewards.
