### ISSUE TITLE
Config view doesn't load if the extension is not active

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#579]
**Brief description**

Title

**How to reproduce**

Install an extension
Do not activate it
try to configure it

**Expected behavior**

Config veiw appears

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/155590263-9aca2dc4-30d7-4018-af31-2eb56d5add2f.png)

Original report https://discord.com/channels/504015559252377601/523676096277905419/946222512168124416

**Comment by jbulava** [comment]
Tristian confirmed the fix is a part of a release today.

**Comment by TristanWiley** [comment]
Closing this as it has been fixed
