### ISSUE TITLE
www.twitch.tv refused to connect.

### ISSUE THREAD

**Issue by CoolerTyp99** [twitchdev/issues#582]
When I start my website, "www.twitch.tv refused to connect"(in german "www.twitch.tv hat eine Verbindung verweigert.") appears in the text box of the chat.

I use this code:
`<iframe id="twitch-chat-embed"
        src="https://www.twitch.tv/embed/twitchdev/chat?parent=dev.twitch.tv"
        height="500"
        width="350">
</iframe>`

![image](https://user-images.githubusercontent.com/95053533/156892670-e9df7f6a-18a0-4a10-a64a-d2325c4e6d1d.png)

Can you pls help me?

**Comment by BarryCarlyon** [comment]
1) This is a bug tracker. Not a help and support route! Please try the forums https://discuss.dev.twitch.tv/latest (or the discord)
2) see https://discuss.dev.twitch.tv/t/the-great-big-im-using-wix-somewebsitemaking-tool-and-i-dont-know-how-to-fix-my-embed-thread/26297 your "parent" is incorrect. You have said that you are embedding the iframe/player/chat on the website `dev.twitch.tv` I am fairly sure you don't run `dev.twitch.tv`

**Comment by jbulava** [comment]
As Barry mentioned, you'll need to update the parent value to be your own site URL. For follow up questions, please refer to the forums linked above or join the Discord server at link.twitch.tv/devchat.
