### ISSUE TITLE
Extension Chat: "username" popup - can't dismiss/learn more incorrect

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#584]
**Brief description**

If you click on the "username" of an Extension Chat message.

The popup box cannot be dismissed.

No [x] appears and the "standard" keyboard shortcut of <esc> doesn't do anything, like a "regular" chat user dialog.

You have to reload thepage or click on another member of chat to dismissed.

Additionally the `Learn More` link doesn't go to a valid page, in the attached example the user is sent to https://www.twitch.tv/ext/xptunrxv6b9qmk5uyeg08iw1cm2i6o-0.0.7 which is a 404 - see notes in reply

**How to reproduce**

- Send an Extension Chat Message
- Click on the "username" of that message in chat

**Expected behavior**

- The dialog is dismissable
- Learn More goes to the extension details page on dashboard.twitch.tv

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/158023341-b222d9ed-d079-4a18-953b-1f74ade0592f.png)

**Comment by BarryCarlyon** [comment]
If you click the learn more this is the result:

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/20999/158023509-8ecd6623-8112-4dcc-986c-0c16b72a8d87.png">

If you visit the link _directly_ or reload the above page, you then get redirected to dashboard.twitch.tv.

So this seems to be an issue in the frontend router handling?

**Comment by jbulava** [comment]
Tagging as "deferred." This bug has been acknowledged, but it not actively being addressed at this time.

**Comment by TristanWiley** [comment]
This has been resolved and will be released tomorrow.

**Comment by BarryCarlyon** [comment]
I DON'T BELIEVE YOU @TristanWiley 

![image](https://github.com/twitchdev/issues/assets/20999/6e0c6e36-0035-45ae-b0a1-c9f3e87e0c48)

**Comment by BarryCarlyon** [comment]
![image](https://github.com/twitchdev/issues/assets/20999/8cb69f95-50a3-4491-a09a-c883ddf61e7f)

I BELIVE YOU NOW
