### ISSUE TITLE
Extension discovery: Newly released extension does not appear in search results

### ISSUE THREAD

**Issue by mgway** [twitchdev/issues#585]
**Brief description**
On 3/23 5PM PST I released the very first version (0.0.1) of my public extension. Now, approximately a day later, it still does not appear either by searching for the extension by name ("Chat Libs") or in the category page that the extension belongs to (Games in Extensions). Navigating directly to the extension page shows the extension details and allows it to be installed, even for users who are not on the testing allow list. 

**How to reproduce**
Search for "Chat Libs" on the [extension discovery page](https://dashboard.twitch.tv/extensions), observe no results. Navigate to the [Games in Extensions](https://dashboard.twitch.tv/extensions/categories/bb7763ca-d2d5-4b97-b202-c4785b729681) category page and observe that Chat Libs! is not in the list of results. 

**Expected behavior**
Fully released public extensions show up in search results

**Screenshots**
![image](https://user-images.githubusercontent.com/556514/159986871-fdf13133-8690-4aa3-a0df-fd357367ab43.png)
![image](https://user-images.githubusercontent.com/556514/159987335-c2cc21d3-d2cc-4bcd-91ad-55cc0847f007.png)

**Comment by marcandrews** [comment]
My extension is also affected by this issue. It is approved/released from my console, and installable from the details page, but it is "in review" from the discovery page, preventing broadcasters from finding it.

![159095035-a29d3ccd-c968-41d2-8616-7e2b63314e07](https://user-images.githubusercontent.com/3518829/160005075-64124aa5-1d43-4f95-b095-23f3eaf85094.png)

![Screen Shot 2022-03-24 at 4 33 26 PM](https://user-images.githubusercontent.com/3518829/160005674-2aa8c657-0732-4a3c-8ef6-937e94bb8d31.png)

![Screen Shot 2022-03-18 at 7 10 06 PM](https://user-images.githubusercontent.com/3518829/160004758-e0212289-5b74-4284-a90e-4ca0216e8d8b.png)

![Screen Shot 2022-03-18 at 7 10 35 PM](https://user-images.githubusercontent.com/3518829/160004764-e19de7e0-fd90-4fa2-8383-6a5685761e98.png)

RE: overlay-expert/help-desk#323

**Comment by BarryCarlyon** [comment]
Same problem emote meter - 6p9e8egy554snkz0mrinyva4jngf44 - 0.1.2

**Comment by marcandrews** [comment]
My extension is still affected after an update.

**Comment by jbulava** [comment]
@marcandrews A fix for this issue was introduced later in the day on Monday. Can you confirm if you are still seeing issues today?

**Comment by marcandrews** [comment]
This is resolved on my end. Thanks @jbulava.

Closes https://github.com/overlay-expert/help-desk/issues/323.

**Comment by mgway** [comment]
Resolved for me as well.

**Comment by TonyXdddd** [comment]
Also faced a similar problem.
The extension is not available in the search results for users.

ClientID: gg38jg2zoibgcx7734sdgrs0nnhqvw.
Ext: PLINK Stats for Apex Legends 0.2.3

Status:
![_1](https://user-images.githubusercontent.com/54737881/189623968-851c6e01-15af-4479-92b7-478399acf15b.png)


Response object related to this extension in the 'my extensions' tab:
![_2](https://user-images.githubusercontent.com/54737881/189624468-6ac20cbb-e2d9-45ca-9764-0f7620f3006b.png)


Search result display:
![_3](https://user-images.githubusercontent.com/54737881/189624849-5f57a190-1899-472f-960a-5e23fd6f8c8b.png)

**Comment by BarryCarlyon** [comment]
You probably want to add this to #652 as this issue is closed for visiblity @TonyXdddd

**Comment by TonyXdddd** [comment]
Thank you very much, I didn't notice. I saw that you mentioned this problem in 652.
Thank you. Just in case, I will duplicate the description.
