### ISSUE TITLE
Extensions with mobile support do not appear on Android as of v12.6.0

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#586]
**Brief description**

Extensions have stopped appearing/being usable by viewers in the latest version of the Twitch app (v12.6.0) on Android.

It worked as expected under v12.5.2 (the previous version)

However, this only effects extensions that are not iOS allow listed.

**How to reproduce**

Visit a channel page with a non iOS allowlist extension installed. See it doesn't appear

**Expected behavior**

Extensions to show on Android regardless of iOS allowlist status.

**Additional context or questions**

Probably related to #585

**Comment by BarryCarlyon** [comment]
Also an addemdum:

on android

on my channel

I can see _EVERY SINGLE EXTENSION_ including ones that are not acitve.

**Comment by jbulava** [comment]
A fix for this issue was released on Monday.  @BarryCarlyon, if you still see the issue in your later comment, please copy-pasta to a dedicated issue.  Otherwise I will not it on the ticket mentioned above.
