### ISSUE TITLE
I don't know what is problem 

### ISSUE THREAD

**Issue by Kekkoloffredo7** [twitchdev/issues#587]
**Brief description**
I put (https://twitchapps.com/tokengen/ ) on urls, beacouse I look the tutorial on yt but I don't have link .
I put (http://localhost) is don't work why
**How to reproduce**

**Expected behavior**
This is the text 
![Screenshot_20220327-061418_Chrome](https://user-images.githubusercontent.com/102452740/160266524-a49adc57-bec3-4760-9256-7125340dd815.jpg)
{**You must have two factor enabled to manage applications**}
**Screenshots**
https://media.discordapp.net/attachments/957473568243994684/957493479481671690/Screenshot_20220327-061418_Chrome.jpg
(I put image if you don't have dsc.gg)

**Additional context or questions**

**Comment by Emilgardis** [comment]
https://help.twitch.tv/s/article/two-factor-authentication?language=en_US

this is a bug tracker, the user forums or twitchdev discord would be a better place for this.

https://dev.twitch.tv/support/
