### ISSUE TITLE
Bits usage not working on Android anymore

### ISSUE THREAD

**Issue by Altoar** [twitchdev/issues#588]
**Brief description**
Since the Twitch Android v12.6 update, when calling the Twitch extension function ``Twitch.ext.bits.useBits(sku)`` inside Twitch extensions, the Bits confirmation dialog is not showing anymore.  It also invokes the ``window.Twitch.ext.onError`` callback.

This completely breaks Bits usage inside Twitch extensions on Android devices.

**How to reproduce**
Call Twitch extension function ``Twitch.ext.bits.useBits(sku)`` inside Twitch extensions on mobile Twitch app v12.6 on Android.

**Expected behavior**
A Bits confirmation dialog should appear where the user can confirm their Bits usage within the Twitch extension

**Comment by hazhirg** [comment]
I'm able to reproduce this issue using the beta Android app with the following build:
```
v12.7.0_BETA (c)
March 25, 2022 at 15:35
```

**Comment by jbulava** [comment]
Thanks for reporting and sharing details. This is being tracked internally on INC-2101.

**Comment by jbulava** [comment]
Please confirm that the issue as been resolved. It may take some time for changes to propagate, but folks believe this to be corrected.

**Comment by hazhirg** [comment]
Can confirm this is resolved on my build (Android app didn't update, still on the same version as mentioned above), thank you for passing this on and to the devs for the prompt resolution!

**Comment by Altoar** [comment]
Can confirm too it's working again on 12.6. Bits confirmation window appears again. Thank you very much for resolving this so quickly!
