### ISSUE TITLE
Style runs incorrect in Safari comparing with Chrome

### ISSUE THREAD

**Issue by MankiNGAI** [twitchdev/issues#589]
**Brief description**
There is a `margin-right: 15px` in class `simplebar-content` with Safari, but not in Chrome, so you will see the sidebar is a little overlap.

**How to reproduce**
Using Safari to open twitch.tv side

**Expected behavior**

**Screenshots**
Before:
<img width="1815" alt="Screenshot 2022-04-02 at 1 58 39 AM" src="https://user-images.githubusercontent.com/6347196/161318578-1c51d3cd-299d-4d01-bd69-23507faefee9.png">

Comment style:
<img width="1815" alt="Screenshot 2022-04-02 at 1 58 28 AM" src="https://user-images.githubusercontent.com/6347196/161318586-635ef1d3-f594-4804-b8a1-0e8327b0728f.png">

**Additional context or questions**
Safari is my prefer browser, and I believe quite a lot users are using safari too, so please help to fix it if can.

**Comment by BarryCarlyon** [comment]
This is a problem with the first party website.

So you need to file this as a uservoice https://twitch.uservoice.com/ not a Third Party Developer bug report.
