### ISSUE TITLE
Webhooks topic(s) don't note required oAuth

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#59]
**Brief description**

Mod Change and Channel ban Change events don't note the required oAuth scope needed for the topic

https://dev.twitch.tv/docs/api/webhooks-reference#topic-moderator-change-events
https://dev.twitch.tv/docs/api/webhooks-reference#topic-channel-ban-change-events

**Expected documentation**

Add, (similar to `Topic: User Changed`)

```
Authentication
User Access Token must have the `moderation:read` for the user in question
```

**Additional context or questions**

https://discuss.dev.twitch.tv/t/webhook-topic-for-channel-ban-change-events-and-moderator-change-events-doesnt-require-oauth-scope/24105

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848203-webhooks-topic-s-don-t-note-required-oauth
