### ISSUE TITLE
Extension/Games Analytics on the Console are not working

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#590]
**Brief description**

Viewing Extension or Games Analytics on the Dev Console results in no graph and the "Export All" button being greyed out

**How to reproduce**

- Dev Console
- Visit `Extensions`
- Click `View Analytics` of a released extension
- Be sad at no graph appearing or easy download button being available

**Expected behavior**

A graph to appear and the download button to be availble for use for downloading.

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/161382030-ee4a05fc-bcf6-4db8-aa2d-d5c6b526baa5.png)

![image](https://user-images.githubusercontent.com/20999/161382178-25a2e229-e3a5-4160-b803-b1bcd77c2395.png)

**Additional context or questions**

The API [Get Extension Analytics](https://dev.twitch.tv/docs/api/reference#get-extension-analytics) seems to be working OK however

**Comment by Marenthyu** [comment]
The same reported behaviour can be seen at ``https://dev.twitch.tv/org/<orgid>/console/games/<gameid>/analytics``

**Comment by jbulava** [comment]
Resolving the issue and also sharing with the dev console team in case it wasn't something that was actively addressed over the weekend.
