### ISSUE TITLE
EventSub `channel.hype_train.end` - `top_contributions` can be unexpectedly null

### ISSUE THREAD

**Issue by AlcaDesign** [twitchdev/issues#594]
**Brief description**

EventSub `channel.hype_train.end` event sent `null` for the `top_contributions` property despite the `channel.hype_train.begin` event having that property populated. The documentation describes `top_contributions` as being an array and does not mention it can be `null`, whether it was intentional or not. Progress events were not sent before or during the hype train.

**How to reproduce**

Subscribe to Hype Train events: `channel.hype_train.begin` `channel.hype_train.progress` `channel.hype_train.end`

Here's the data sent by Twitch for example. No progress event was sent for this hype train instance despite being subscribed to those events. The service crashed on the end event so perhaps progress events were sent _after_ the end, but I have no way to know that.
<details>
<summary>channel.hype_train.begin</summary>

Note `top_contributions` and `last_contribution` having actual values. These original users were not timed out/banned during the hype train and the accounts are still active, not banned from Twitch.

```json
{
    "subscription": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "status": "enabled",
        "type": "channel.hype_train.begin",
        "version": "1",
        "condition": {
            "broadcaster_user_id": "1111"
        },
        "transport": {
            "method": "webhook",
            "callback": "https://.../event/channel.hype_train.end.1111"
        },
        "created_at": "2022-04-21T09:41:53.07509807Z",
        "cost": 0
    },
    "event": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "broadcaster_user_id": "1111",
        "broadcaster_user_login": "oneoneoneone",
        "broadcaster_user_name": "OneOneOneOne",
        "total": 400,
        "top_contributions": [
            {
                "user_id": "2222",
                "user_login": "twotwotwotwo",
                "user_name": "twotwotwotwo",
                "type": "bits",
                "total": 200
            }
        ],
        "started_at": "2022-04-24T09:00:00.991366713Z",
        "last_contribution": {
            "user_id": "3333",
            "user_login": "threethreethreethree",
            "user_name": "ThreeThreeThreeThree",
            "type": "bits",
            "total": 100
        },
        "goal": 2000,
        "progress": 400,
        "expires_at": "2022-04-24T09:05:00.991366713Z"
    }
}
```
</details>

<details>
<summary>channel.hype_train.end</summary>

Note `top_contributions` being `null`:

```json
{
    "subscription": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "status": "enabled",
        "type": "channel.hype_train.end",
        "version": "1",
        "condition": {
            "broadcaster_user_id": "1111"
        },
        "transport": {
            "method": "webhook",
            "callback": "https://.../event/channel.hype_train.end.1111"
        },
        "created_at": "2022-04-21T09:41:53.408851211Z",
        "cost": 0
    },
    "event": {
        "id": "XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX",
        "broadcaster_user_id": "1111",
        "broadcaster_user_login": "oneoneoneone",
        "broadcaster_user_name": "OneOneOneOne",
        "total": 400,
        "top_contributions": null,
        "started_at": "2022-04-24T09:00:00.991366713Z",
        "level": 1,
        "ended_at": "2022-04-24T09:05:01.359285382Z",
        "cooldown_ends_at": "2022-04-24T10:05:01.359285382Z"
    }
}
```
</details>

Here are the original `Twitch-Eventsub-Message-Id` header values for these requests in case they can be validated:
| Event type | Header value |
|---|---|
| channel.hype_train.begin | `1Yf345h3N7LIGlSETDPsaqka72xAt_qFM0Vk9fo7EN8=` |
| channel.hype_train.end | `Gg75olxHgA4pDxcrHu0WlrJandO7l8OIeADu_O1LOcs=` |

I can supply the full original events if needed.

**Expected behavior**

The value of `top_contributions` should at least be an empty array or it should be documented that this value can be `null`.

**Screenshots**

N/A

**Additional context or questions**

Documentation: <https://dev.twitch.tv/docs/eventsub/eventsub-reference/#hype-train-end-event>

**Comment by belliapptw** [comment]
We are taking a look at this and will get back to you. Thank you for reporting.
