### ISSUE TITLE
Cannot invite user to organisation

### ISSUE THREAD

**Issue by SamGuthrie** [twitchdev/issues#596]
**Brief description**
I'm trying to invite another developer to an organisation in order to collaborate on a twitch extension, however I just get "an error occured"

**How to reproduce**
Head to "Role Management" for your organisation, then invite member. Tried to invite both via twitch username and twitch ID, The user has 2FA enabled, and I get the same error trying to invite someone else

**Expected behavior**
User should receive an invite to join the organisation

**Screenshots**
![image](https://user-images.githubusercontent.com/61413285/166266344-58d27ceb-e6c2-4ac1-bd6e-a1ecaa787ecc.png)

**Additional context or questions**
Inspecting the network tab in chrome gives me this response:

`[{"data":{"createOrganizationInvite":{"error":{"code":"INTERNAL_ERROR","__typename":"CreateOrganizationInviteError"},"__typename":"CreateOrganizationInvitePayload"}},"extensions":{"durationMilliseconds":28,"operationName":"AddOrgInvite","requestID":"01G22NGSZ3N04TZSDZN3K4702S"}}]
`

Here is the payload (org name is MetaTFT):
```
inviteeTwitchID: "32694275"
inviterTwitchID: "39112364"
organizationID: "cadb4c84-f261-4dec-b35f-5235f046356f"
role: "DEVELOPER"
```

**Comment by Marenthyu** [comment]
The duplicate #599 has been closed as fixed, so this issue should be closed as well.
