### ISSUE TITLE
Get videos endpoint responds with empty list

### ISSUE THREAD

**Issue by kmrozek-shareablee** [twitchdev/issues#598]
**Brief description**
When I request for the first 100 videos for a game, I get an empty list.

**How to reproduce**
Execute query with appropriate headers (Authorization, Client-ID):

```sh
curl -X GET https://api.twitch.tv/helix/videos?first=100&period=day&sort=time&game_id=GAME_ID
```

**Expected behavior**
It should return a list of videos in the format described here (https://dev.twitch.tv/docs/api/reference#get-videos), but the list is empty:

```json
{
  "data": [],
  "pagination": {}
}
```

**Screenshots**
No

**Additional context or questions**

**Comment by jbulava** [comment]
It looks like this issue is specific to providing a `game_id`.  Passing this along to be investigated, thanks.

**Comment by DozeX** [comment]
have same prob

**Comment by DozeX** [comment]
can someone confirm this is under investigation

**Comment by iProdigy** [comment]
> Tracking on HLX-2520.

yes, it's under investigation

**Comment by DozeX** [comment]
> > Tracking on HLX-2520.
> 
> yes, it's under investigation

ok, ty

**Comment by jbulava** [comment]
This issue has been fixed. Videos are now returned once again when providing a `game_id`.

**Comment by DozeX** [comment]
> This issue has been fixed. Videos are now returned once again when providing a `game_id`.

Yes, Works :) ty
