### ISSUE TITLE
Bug or Feature request: multiple callbacks onContext/onAuth

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#60]
**Brief description**

Currently you cannot call onContext/onAuth and similar functions/create a handler more than once, and the last bound callback "wins"

This isn't documented as a thing. So not sure if bug or needs to be a feature request

**How to reproduce**

```
window.Twitch.ext.onContext(ctx=>{
    console.log("Context 1", ctx)
}
window.Twitch.ext.onContext(ctx=>{
    console.log("Context 2", ctx)
}
```

It only logs `"Context 2", and the object`

**Expected behavior**

Both callback functions are called.

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/74466176-aa6fd600-4e8e-11ea-9ef8-d2e866d7de98.png)

**Comment by mauerbac** [comment]
doesn't seem to be supported currently. Will put as a FR. Thanks Barry!
