### ISSUE TITLE
Get Users endpoint has stale view_count for all users

### ISSUE THREAD

**Issue by dmill** [twitchdev/issues#602]
**Brief description**
We are using the [Get Users](https://dev.twitch.tv/docs/api/reference#get-users) endpoint to poll channel view counts across a number of channels daily. We have noticed that these view counts have not changed for any channel since 4/19/22. Starting on 4/20/22, the `view_count` has been unchanged.

**How to reproduce**
Poll Get Users, notice that the view count is unchanged.

**Expected behavior**
The view_count should update at least daily, as it did prior to 4/20/22.
**Screenshots**

**Additional context or questions**
Thanks for your help and for maintaining a great public API!

**Comment by iProdigy** [comment]
This is an intentional deprecation: https://discuss.dev.twitch.tv/t/get-users-api-endpoint-view-count-deprecation/37777/1
