### ISSUE TITLE
/clear is utterly broken

### ISSUE THREAD

**Issue by Mm2PL** [twitchdev/issues#604]
**Brief description**
`/clear` doesn't cause the chat to be cleared.

**How to reproduce**
Do /clear from IRC or webchat or whatever client you use.

**Expected behavior**
CLEARCHAT and the chat being cleared.

**Current behavior**
Pubsub sent but no CLEARCHAT irc message.

**Screenshots**
![2022-05-10_19-49](https://user-images.githubusercontent.com/25011746/167690987-92752c6c-a8c0-46c7-bcb8-962a279c7201.png)

I won't screenshot ncat cause it's ugly but there is no CLEARCHAT.

**Additional context or questions**

This person reported this as a Chatterino :---)
![2022-05-10_19-50](https://user-images.githubusercontent.com/25011746/167691250-d2c00997-727d-4466-b21c-e034a074b105.png)

**Comment by iProdigy** [comment]
can confirm:

* as a moderator, nothing happens over irc (but pubsub works) -- by extension, normal users don't get anything over irc
* as the broadcaster, a malformed message is received: `@room-id=53888434;tmi-sent-ts=1652206429374 :!@.tmi.twitch.tv CLEARCHAT ogprodigy` (host part should just be `:tmi.twitch.tv`, and `#` is missing)

**Comment by Mm2PL** [comment]
Looks like it's been fixed
