### ISSUE TITLE
Client capability negotiation ends prematurely

### ISSUE THREAD

**Issue by ori-sky** [twitchdev/issues#605]
**Brief description**

According to the IRCv3 specification, client capability negotiation should not end until the client has sent the `CAP END` sub-command. Quoting from the relevant portion of the spec:

> Upon receiving either a CAP LS or CAP REQ command during connection registration, the server MUST not complete registration until the client sends a CAP END command to indicate that capability negotiation has ended. This allows clients to request their desired capabilities before completing registration.

**How to reproduce**

Connect to the Twitch IRC server and send the following sequence of messages:

```
CAP LS
PASS oauth:ValidOAuthToken
NICK ValidTwitchName
```

The server will prematurely accept the credentials and end client registration before `CAP END` has been sent, which runs counter to the spec.

**Expected behavior**

The server should not accept client registration -- therefore should not send `001 RPL_WELCOME` -- until `CAP END` has been received or alternatively some timeout threshold has presumably been exceeded.

**Screenshots**

![image](https://user-images.githubusercontent.com/4142775/167757136-afb4b352-2bde-4385-96a2-96476fca3c11.png)

**Comment by BarryCarlyon** [comment]
This seems more like a "Twitch TMI is IRC compatible not IRC compliant"

so it doesn't "follow the spec" just borrows from it.

Since neither `CAP LS` or `CAP END` are documented https://dev.twitch.tv/docs/irc/capabilities#requesting-twitch-specific-capabilities so surprised `CAP LS` itself works,

**Comment by Mm2PL** [comment]
as someone on the forum once said:
> Twitch doesn’t follow the RFC. TMI is a bunch of go scripts wearing a trench coat pretending to be IRC and speaking French. 

It's stupid but no one cares enough to change it
