### ISSUE TITLE
[Docs] Update Chat Settings broadcaster_id description incorrect

### ISSUE THREAD

**Issue by Marenthyu** [twitchdev/issues#606]
**Brief description**
The description for [Update Chat Settings](https://dev.twitch.tv/docs/api/reference#update-chat-settings)' ``broadcaster_id`` field lists ``This ID must match the user ID associated with the user OAuth token.`` - this is not true when using a moderator's Token, which will match the User ID specified as ``moderator_id`` instead.
**Expected documentation**
The mentioned sentence should be omitted from the documentation.
**Screenshots**
![https://lowee.de/chrome_2022-05-11_14-12-10.png](https://lowee.de/chrome_2022-05-11_14-12-10.png)
**Additional context or questions**
See also on Discord: [https://discord.com/channels/504015559252377601/523675960797691915/973918256224174131](https://discord.com/channels/504015559252377601/523675960797691915/973918256224174131)

**Comment by scott-a-white** [comment]
Thanks for reporting the issue: Fixed: https://dev.twitch.tv/docs/api/reference#update-chat-settings.
