### ISSUE TITLE
broadcaster_type = '' (empty string)

### ISSUE THREAD

**Issue by marcandrews** [twitchdev/issues#61]
**Brief description**

Anyone else noticing `GET https://api.twitch.tv/kraken/streams/<channel ID>`  and `GET https://api.twitch.tv/kraken/channels/<channel ID>` incorrectly returning `broadcaster_type: ''` (empty string) instead of should be `broadcaster_type: 'affiliate'`.

Or is `broadcaster_type` now only available via elevated `GET https://api.twitch.tv/kraken/channel` endpoint?

**How to reproduce**

Call `GET https://api.twitch.tv/kraken/streams/<channel ID>` or `GET https://api.twitch.tv/kraken/channels/<channel ID>`.

**Expected behavior**

For affiliated channels, `broadcaster_type = 'affiliate'`.

**Screenshots**

n/a

**Additional context or questions**

`broadcaster_type = 'partner'` may also be affected.

**Comment by BarryCarlyon** [comment]
Also also affects "partners"

![image](https://user-images.githubusercontent.com/20999/77353637-3cde8180-6d39-11ea-8105-6ee508b32ef2.png)

**Comment by mauerbac** [comment]
Thanks @marcandrews. This is a weird one and is empty for both partner and affiliate. I put the ticket in but it's tough since we are moving to Helix, so not sure if v5 will get bug fixes like this. GQL-940

**Comment by jbulava** [comment]
Closing as this was related to v5.
