### ISSUE TITLE
No documentation for the USERNOTICE `submysterygift`

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#611]
**Brief description**

In the chat docs update the documentation for the USERNOTICE of `msg-id` of `submysterygift` is missing

**Expected documentation**

The documentation for the "gift bomb header" to be existing

**Comment by zneix** [comment]
While we're at it, the `msg-param-fun-string` tag in these USERNOTICEs is totally undocumented as well, maybe it's worth adding a little note about what it does. From my observations it only has values `FunString{One,Two,Three,Four,Five}`.

**Comment by BarryCarlyon** [comment]
Twitch probably won't documented it as it's not intended for third party user. hence us not knowing what it does. Twitch will add/remove things all the time that helps power the front end that they don't intend for us to use. (similar to the new cheer experiment and it's data)

**Comment by zneix** [comment]
While for third party use or not, it is still present in the message that third party gets. My point was rather that it's weird to receive and parse random things that we're supposed to ignore on purpose :shrug: it's just a weird approach but I guess you're right.

**Comment by BarryCarlyon** [comment]
Generally since they stick to the IRCv3 format it shouldn't break any parsers, so you can just ignore tags you are not expecting or doing work on. (/me looks at the `flags` tag)

If I was to harzard a guess, fun string refers to the emotes/animation that can be put on top of giftbombs "to make them look pretty".

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/irc/tags#usernotice-tags
