### ISSUE TITLE
Get Banned Users - refers to /events in the optional query parameters

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#613]
**Brief description**

https://dev.twitch.tv/docs/api/reference#get-banned-users

```
user_id | string | Filters the results and only returns a status object for users who are banned in the channel and have a matching user_id.Multiple user IDs can be provided, e.g. /moderation/banned/events?broadcaster_id=1&user_id=2&user_id=3
```

**Expected documentation**

```
user_id | string | Filters the results and only returns a status object for users who are banned in the channel and have a matching user_id.Multiple user IDs can be provided, e.g. /helix/moderation/banned?broadcaster_id=1&user_id=2&user_id=3
```

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/168584770-d5b62cc2-cc64-45ff-b58d-c4731d289915.png)

**Additional context or questions**

https://discuss.dev.twitch.tv/t/undocumented-helix-moderation-banned-modification/38473

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-banned-users.
