### ISSUE TITLE
Incorrect/misleading description of `/disconnect` chat command

### ISSUE THREAD

**Issue by zneix** [twitchdev/issues#615]
**Brief description**

As seen on <https://dev.twitch.tv/docs/irc/chat-commands>:
<table>
<tr>
	<td>/disconnect
	<td>chat:edit
	<td>Disconnects the bot from the IRC server. This is the same as sending a PART message.
</table>

This is incorrect because `PART #channel` makes bot leave a channel and just `PART` doesn't do anything.

**Expected documentation**

I sense that `QUIT` was meant to be there instead of `PART`. So that'd be:
<table>
<tr>
	<td>/disconnect
	<td>chat:edit
	<td>Disconnects the bot from the IRC server. This is the same as sending a <b>QUIT</b> message.
</table>

On another note though, I don't see `QUIT` documented on neither <https://dev.twitch.tv/docs/irc#supported-irc-messages> or <https://dev.twitch.tv/docs/irc/commands> so I suppose that `QUIT` is still deemed non existant (because undocumented :man_shrugging:). So if we were to follow this path, just consider second sentence unnecessary and remove it:
<table>
<tr>
	<td>/disconnect
	<td>chat:edit
	<td>Disconnects the bot from the IRC server.
</table>

**Screenshots**
The very bottom of <https://dev.twitch.tv/docs/irc/chat-commands>:
![don'treleasemisleadingdocsupdatespls](https://cdn.zneix.eu/JRLlfb8.png)

**Additional context or questions**
I've reported this 1 week ago in [TwitchDev Discord Server](https://link.twitch.tv/devchat) in `#docs-feedback` channel ([link to the message](https://discord.com/channels/504015559252377601/523675755503157248/975526769094455296)).

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/irc/chat-commands.
