### ISSUE TITLE
Managing event subscriptions

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#616]
**Brief description**

https://dev.twitch.tv/docs/eventsub/manage-subscriptions

has a broken link to auth docs in step 1

Also probably change the example to streams online or channel info changed instead of follow?

**Comment by scott-a-white** [comment]
Thanks for reporting the broken link. Fixed: https://dev.twitch.tv/docs/eventsub/manage-subscriptions#subscribing-to-events.
