### ISSUE TITLE
Create Prediction - Example JSON invalid

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#617]
**Brief description**

The exmaple in Create Prediction is invalid

Errant `,` on the end of the prediction window

**Expected documentation**

```
curl -X POST 'https://api.twitch.tv/helix/predictions' \
-H 'Authorization: Bearer cfabdegwdoklmawdzdo98xt2fo512y' \
-H 'Client-Id: uo6dggojyb8d6soh92zknwmi5ej1q2' \
-H 'Content-Type: application/json' \
-d '{
  "broadcaster_id": "141981764",
  "title": "Any leeks in the stream?",
  "outcomes": [
    {
      "title": "Yes, give it time."
    },
    {
      "title": "Definitely not."
    }
  ],
  "prediction_window": 120
}'
```

**Additional context or questions**

I did not check other examples to see if they have the same error

**Comment by scott-a-white** [comment]
Thanks for reporting the issue: Fixed https://dev.twitch.tv/docs/api/reference#create-prediction.
