### ISSUE TITLE
Error with uploading the extension bundle

### ISSUE THREAD

**Issue by anddorua** [twitchdev/issues#619]
I'm trying to upload a zipped twitch extension bundle, but after pressing the "Upload Assets" button I get the error message **File upload failed. Please try again. If you need additional support, please visit this page to submit a ticket.**

That is started at June 09, 2022. I didn't encounter this error before. I see this error on different Twitch accounts.

The bundle zip size is 3,033,967 bytes. I tried to upload smaller size bundle (638K) and get the same error

**How to reproduce**

Try to upload zipped extension bundle.

**Expected behavior**

Bundle successfully uploaded, no error messages.

**Screenshots**

[Screenshot](https://prnt.sc/JkIbltwduLgX)

**Additional context or questions**

No

**Comment by jbulava** [comment]
There was a recent update that may have caused this issue.  The team is investigating.  Thanks for the report.

**Comment by jbulava** [comment]
A fix was deployed in the last hour and tested to confirm uploads are successful.  Please let us know if you are still having an issue though.

**Comment by anddorua** [comment]
Just confirm, not facing this issue anymore, thanks.

**Comment by anddorua** [comment]
Thanks for a quick fix.
