### ISSUE TITLE
Getting 401 Error while testing twitch in Azure AD b2C 

### ISSUE THREAD

**Issue by vpbadoni2022** [twitchdev/issues#620]
**Brief description**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
Your issue report is kinda empty.

So don't know if an error if your code or on twitch's side.

For support with authentication you probably want the forums https://discuss.dev.twitch.tv/ as this issue tracker is a bug tracker not an support vector really
