### ISSUE TITLE
Error uploading images to extensions

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#621]
**Brief description**

Looks like a recurrence of #619 but effecting image uploads as a minimum

**How to reproduce**

Try to upload an image to image assets

**Expected behavior**

it succeeds

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/173603675-f408bef0-2f86-4017-b1c7-72377f3b6d01.png)

**Additional context or questions**

It does correctly check the dimensions of an image though

**Comment by jbulava** [comment]
Team is actively investigating.

**Comment by jbulava** [comment]
The fix had been confirmed.
