### ISSUE TITLE
SMS codes are not received in Russian Federation

### ISSUE THREAD

**Issue by artstylee** [twitchdev/issues#624]
**Brief description**
im trying to remove 2FA. twitch asks for sms code which is not received.
same with login into twitch app(android). cant receive sms code
**How to reproduce**
login in twitch app(android) and ask for sms code in Russian Federation
**Expected behavior**
sms code should been received
**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
The third party products bug tracker is not an appropriate place for this issue.

For further help please visit https://help.twitch.tv/
