### ISSUE TITLE
Helix API - Get Extension Transactions - Example Response JSON is invalid

### ISSUE THREAD

**Issue by michaelmcneilnet** [twitchdev/issues#625]
**Brief description**
The Example Response for https://dev.twitch.tv/docs/api/reference#get-extension-transactions is invalid. 

- `inDevelopment` is missing a comma at the end on the first item.
- `broadcaster_name` is missing a comma at the end on the second item.

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-extension-transactions.
