### ISSUE TITLE
Creating a Schedule Segment In The Future Fails With Error Saying 'FirstOccurenceDate' Cannot Be In The Past

### ISSUE THREAD

**Issue by propertunist** [twitchdev/issues#626]
**Brief description**

I am using Twurple to attempt to retrieve and create/update the schedule for a Twitch account. I have not been able to create a new schedule segment because the API returns the following error:

` {"error":"Bad Request","status":400,"message":"FirstOccurrenceDate can't set FirstOccurrenceDate to a time in the past"}`

I have tried various dates for the start_date but I always receive this error. I asked in the Discord community and was told it was probably a bug with the API.

**How to reproduce**

1. Authorise with Twitch API token system.
1. Send an API call to [Create Channel Stream Schedule Segment](https://dev.twitch.tv/docs/api/reference#create-channel-stream-schedule-segment). Include a date that is in the future and other relevant data. Example data sent to API:
```
updateData['start_time'] = "2022-07-05T19:00:00Z";
updateData['timezone'] = 'UTC';
updateData['duration'] = 120;
updateData['is_recurring'] = true;
```

**Expected behavior**

New schedule segment should be created for the Twitch channel associated with the broadcast ID provided with the API call.

**Comment by BarryCarlyon** [comment]
I plumbed your entries into a regular curl request and was unable to replicate this issue.

![image](https://user-images.githubusercontent.com/20999/176675253-10f23850-0601-4bd4-8208-788751cb31be.png)

What is Twurple actually sending?

**Comment by propertunist** [comment]
Thanks, ok. The problem is that I had missed the relevant part of API reference on the Twurple website. Twurple uses different names for key variables to the names used by Twitch itself and was not producing useful error data to show that the wrong variable name was being used for the start date.
