### ISSUE TITLE
Doc / API mismatch for Pagination with Get Soundtrack Playlists and Playlist

### ISSUE THREAD

**Issue by Dukmos** [twitchdev/issues#627]
**Brief description**
Both `Get Soundtrack Playlists` and `Get Soundtrack Playlist` Endpoints respond with Pagination and respond to `first` and `after` Parameters
Its not Mentioned in the Doc for `Playlists` but needed because there seems to be 60 Playlists atm and only 20 are returned by default

Both endpoints only allow the `first` Parameter to be 50 or lower, but the Doc mentions 100 for  `Get Soundtrack Playlist` 
**Expected documentation**

adding the Pagination Documentation to the `Get Soundtrack Playlists` Endpoint and specifying the max value that is enforced in the API for both

**Screenshots**

![image](https://user-images.githubusercontent.com/1273625/176938968-23669823-a99e-4237-9485-11a39bb60711.png)
![image](https://user-images.githubusercontent.com/1273625/176938525-eaf72011-3167-44ab-95ce-9e4beb638a1e.png)
![image](https://user-images.githubusercontent.com/1273625/176939311-0fdb622d-008a-4e5e-bb2f-07546d7d7246.png)

**Additional context or questions**
I know that the Endpoints are still in Beta, so im not sure if im supposed to post this in here already....

**Comment by Xemdo** [comment]
Soundtrack product and API has been deprecated:
https://discuss.dev.twitch.tv/t/withdrawal-of-twitch-api-endpoints-for-soundtrack/46021
