### ISSUE TITLE
Missing scope

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#63]
**Brief description**
The channel:read:redemptions scope is required by the Channel Points PubSub topic (https://dev.twitch.tv/docs/pubsub#topics) but not mentioned in the scopes overview (https://dev.twitch.tv/docs/authentication#scopes)

**Expected documentation**
The channel:read:redemptions listed on the overview page (https://dev.twitch.tv/docs/authentication#scopes)

**Comment by jbulava** [comment]
Hmm, it's not the only scope that is mentioned in the PubSub docs and not listed in the general scopes in authentication. In fact, only `bits:read` is in both.  Will check with the PubSub team if this is intentional, which is possible if they do not apply to v5/helix.

**Comment by Dkamps18** [comment]
The others do, channel_subscriptions is under v5 and channel:moderate/whispers:read are under Chat and PubSub.

**Comment by BarryCarlyon** [comment]
I suppose logically the same scope will be used for helix endpoints that may exist at somepoint for CRUDing Rewards. So I'd expect it to be on the summary page even if it's pubsub only…

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848224-missing-scope
