### ISSUE TITLE
Localhost causes redirect mismatch

### ISSUE THREAD

**Issue by jacobrossdev** [twitchdev/issues#630]
When setting a localhost:5001 (for example) as a redirect URI in the dev console, i get redirect_mismatch error when trying to use the Authorization code grant flow. 

I have two bots that use the http://localhost as the redirect and both stopped working.

**Comment by BarryCarlyon** [comment]
Are you URI Encoding your redirect URI when you construct the link for users to click on to be redirected to Twitch?

**Comment by jacobrossdev** [comment]
Yes that was it. Thanks!
