### ISSUE TITLE
Error When Changing Schedule Start Date via API: FirstOccurrenceDate can't set FirstOccurrenceDate on recurring segments

### ISSUE THREAD

**Issue by propertunist** [twitchdev/issues#631]
**Brief description**

I am using the [Update Channel Stream Schedule Segment](https://dev.twitch.tv/docs/api/reference#update-channel-stream-schedule-segment) command to try to update an existing schedule segment via a channel management app I am creating. I am successfully able to update all parameters of an existing segment except the 'start_time' parameter. If I try to change the start_time parameter I receive a 400 error: 

``` {"error":"Bad Request","status":400,"message":"FirstOccurrenceDate can't set FirstOccurrenceDate on recurring segments"}] ```

I have tested this using Twurple in Node and also using CURL to access the API directly. I receive the same error using both methods. 
The schedule segments I am testing with are set to recur and I presume that perhaps this command hasn't been used or tested enough yet for people to realise that it consistently fails

**How to reproduce**

1. Create a schedule segment that recurs and save it's ID.
2. Pass the segment ID to the 'Update Channel Stream Schedule Segment' command in the API and also pass in a changed start_time for the schedule.
3. Receive Error. 

**Expected behavior**

The segment and all connected, recurring segments should be updated to include the changed start_time parameter.

**Comment by scott-a-white** [comment]
Hello. Sorry for the trouble. The [doc](https://dev.twitch.tv/docs/api/reference#update-channel-stream-schedule-segment) has been updated to mention that you may only update the start time of non-recurring segments.

**Comment by propertunist** [comment]
ok thanks for clarifying
