### ISSUE TITLE
Get Stream Makers: Example wrong

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#633]
**Brief description**

Get Stream Markers example is wrong for the URL of a marker

**Expected documentation**

Update the example on

https://dev.twitch.tv/docs/api/reference#get-stream-markers

in line with the one from the new guide

https://dev.twitch.tv/docs/api/markers

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-stream-markers.
