### ISSUE TITLE
get predictions documentation has incorrect keys for top_predictors

### ISSUE THREAD

**Issue by chillymosh** [twitchdev/issues#637]
**Brief description**
get predictions documentation (https://dev.twitch.tv/docs/api/reference#get-predictions) has incorrect keys for top_predictors in the return values section.
Currently shows `outcome.top_predictors.user.id`, `outcome.top_predictors.user.login`, `outcome.top_predictors.user.name`

There is also a typo for `outcome.users`
Number of unique **uesrs** that chose the outcome.

**Expected documentation**
outcome.top_predictors.user.user_id
outcome.top_predictors.user.user_login
outcome.top_predictors.user.user_name

Number of unique users that chose the outcome.

**Screenshots**

**Additional context or questions**

Example snippet from curl command
```
'outcomes': [{'id': '7d327d3a-e6c9-47df-a17c-c3fb2daa2871', 'title': 'Yes', 'users': 1, 'channel_points': 10, 'top_predictors': [{'user_id': '526979188', 'user_login': 'randyriker', 'user_name': 'randyriker', 'channel_points_used': 10, 'channel_points_won': 10}], 'color': 'BLUE'}
```

**Comment by scott-a-white** [comment]
Thanks for reporting the issues. Fixed: https://dev.twitch.tv/docs/api/reference#get-predictions.
