### ISSUE TITLE
Cannot delete some extensions

### ISSUE THREAD

**Issue by gabrielblake28** [twitchdev/issues#640]
**Brief description**
When the "delete extension" button is clicked on the confirm deletion modal the extension is not deleted.

**How to reproduce**
- log into console
- navigate to the extension page and click manage on an extension
- go into the extension settings at the top right of the page
- scroll to bottom of the settings page and click delete extensions. This should trigger a modal.
- when you click delete extension the second time nothing happens.
- server error is thrown
**Expected behavior**
after confirming you want to delete an extension the extension is deleted
**Screenshots**

![Screenshot (7)](https://user-images.githubusercontent.com/61571088/187089734-76cce83a-59d1-496a-86a5-725a56095955.png)

![Screenshot (6)](https://user-images.githubusercontent.com/61571088/187089800-7dfe8c17-4362-4c3e-926f-056b9553681c.png)

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
dulicate of #46 

Your extension doesn't have a version
