### ISSUE TITLE
i found a mini bug

### ISSUE THREAD

**Issue by jordanmsf** [twitchdev/issues#641]
**Brief description**

I found a bug with you, it's in the soundbar's graphical interface in steams, it becomes a wording if you select it

**How to reproduce**

when i hide my sond with my mouse 

**Expected behavior**

that it is selected normally

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
First party issues affecting the website should be reported to the relevant product on uservoice - https://twitch.uservoice.com/

**Comment by Xemdo** [comment]
Closing as this is not a bug related to Twitch's developer products, assuming this issue is still persisting.
