### ISSUE TITLE
`channel.charity_campaign.donate` subscription event uses `target_amount` instead of `amount`

### ISSUE THREAD

**Issue by fancy-plants** [twitchdev/issues#642]
**Brief description**

The [charity donation eventsub documentaiton](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#charity-donation-event) lists the event has having an `amount` field, however testing with a real donation produced an event with a `target_amount` field instead.

**How to reproduce**

- Set up an eventsub subscription for `channel.charity_campaign.donate`
- Donate to the channel's active charity campaign
- Observe that the received message's `event` object contains a `target_amount` key and no `amount` key

For reference, here's the parsed object I received from the event that prompted this
```js
{
    subscription: {
        id: ...,
        status: "enabled",
        type: "channel.charity_campaign.donate",
        version: "beta",
        condition: {
            broadcaster_user_id: ...,
        },
        transport: {
        method: "webhook",
            callback: ...,
        },
        created_at: "2022-08-31T03:39:38.616061411Z",
        cost: 0,
    },
    event: {
        id: ...,
        broadcaster_user_id: ...,
        broadcaster_user_login: ...,
        broadcaster_user_name: ...,
        user_id: ...,
        user_login: ...,
        user_name: ...,
        target_amount: {
            amount: 100,
            decimal_places: 2,
            currency: "USD",
        },
    },
}
```

**Expected behavior**

The amount donated is passed in the `amount` field as documented

**Screenshots**

n/a

**Additional context or questions**

Possible this is just incorrect documentation? However it doesn't seem like `target_amount` would be the intended name for this field since it's also used in the [Get Charity Campaign](https://dev.twitch.tv/docs/api/reference#get-charity-campaign) response with a different meaning.

**Comment by fancy-plants** [comment]
Also just noticed that the _inner_ fields here (and in the `current/target_amount` returned by the `charity/campaigns` endpoint) use the name `amount` instead of the documented `value`.

ie.
```js
target_amount: {
    amount: 10000,
    currency: "USD",
    decimal_places: 2,
}
```
as opposed to
```js
target_amount: {
    value: 10000,
    currency: "USD",
    decimal_places: 2,
}
```

https://dev.twitch.tv/docs/api/reference#get-charity-campaign
https://dev.twitch.tv/docs/eventsub/eventsub-reference/#charity-donation-event

**Comment by AdrianGonz97** [comment]
I just tested to see what the shape of the event looks like now and this is what I got:

```json
{
    "subscription": {
            "id": ...,
            "type": "channel.charity_campaign.donate",
            "version": "beta",
            "status": "enabled",
            "condition": {
                    "broadcaster_user_id": ...,
            },
            "transport": {
                    "method": "webhook",
                    "callback": ...,
            },
            "created_at": "2022-10-28T19:20:10.223782644Z",
            "cost": 0
    },
    "event": {
            "campaign_id": ...,
            "charity_name": ...,
            "charity_logo": ...,
            "broadcaster_user_id": ...,
            "broadcaster_user_login": ...,
            "broadcaster_user_name": ...,
            "user_id": ...,
            "user_login": ...,
            "user_name": ...,
            "amount": {
                    "value": 100,
                    "decimal_places": 2,
                    "currency": "USD"
            }
    }
}
```

Looks like they changed the following:
- `amount` --> `value`
- `id` --> `campaign_id` (as they said they would change [here](https://dev.twitch.tv/docs/change-log)) 

It appears that they also added `charity_name` and `charity_logo` to the `event` object.

Despite these changes, the [documentation](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#charity-donation-event) is still wrong. 

The docs say we should expect `broadcaster_id`, `broadcaster_login`, `broadcaster_name`, but instead we receive `broadcaster_user_id`, `broadcaster_user_login`, `broadcaster_user_name`, respectively. 

`charity_name` and `charity_logo` fields are not included in the docs as well.

**Comment by belliapptw** [comment]
fixed

**Comment by Emilgardis** [comment]
I presume the fix is not staged yet to docs? because it still looks the same
