### ISSUE TITLE
`charity/campaigns` endpoint returns 404

### ISSUE THREAD

**Issue by fancy-plants** [twitchdev/issues#643]
**Brief description**

Attempting to use the [Get Charity Campaign](https://dev.twitch.tv/docs/api/reference#get-charity-campaign) endpoint seemingly always returns a 404 response when following the pattern used in the documentation.

**How to reproduce**

- Send a request to `https://api.twitch.tv/helix/charity/campaigns` with a broadcaster_id and valid user oauth token (for a user that has an active charity campaign)
- Observe that the returned object is `{"error":"Not Found","status":404,"message":""}`

Note that this behavior is consistent when making the request from my application and via curl using the example in the documentation
```
curl -X GET "https://api.twitch.tv/helix/charity/campaigns?broadcaster_id=..." -H "Authorization: Bearer ..." -H "Client-Id: ..."
```

**Expected behavior**

API response has data or an error specific to this request

**Screenshots**

n/a

**Additional context or questions**

Possible this is user error, though I've double checked all the relevant fields, and accessing other api endpoints is working correctly (including subscriptions, which is using the same user token). Happy to be proven wrong, though 🙂

**Comment by BarryCarlyon** [comment]
Does the target channel identified by `broadcaster_id` have a campaign running

**Comment by Emilgardis** [comment]
I also get this on a channel with no charity campaign with a correctly scoped token

**Comment by BarryCarlyon** [comment]
> I also get this on a channel with no charity campaign with a correctly scoped token

That would make it a data bug where is should empty array rather than "404 - No Campaign Found"

**Comment by BarryCarlyon** [comment]
In a spot test looks like the endpoint is broken!

**Comment by Emilgardis** [comment]
Oh yeah, I missed that detail, the token is not authorized for broadcaster_id, I suspect that's the issue then, just bad error reporting

**Comment by prbsingh1** [comment]
Hello folks, This issue has been address in Helix production and you shouldn't be seeing 404s any longer. I'll watch this issue for a while in case related issues pop up

**Comment by fancy-plants** [comment]
Just tried again with my setup and looks like it's able to get data now 🎉

Thanks for the quick turnaround on this!
