### ISSUE TITLE
channel.charity_campaign.donate subscription event sub payload to have 'charity_campaign_id' json field added!

### ISSUE THREAD

**Issue by jackmcguire1** [twitchdev/issues#646]
**Brief description**
Isit possible to add the referenced charity campaignID that was donated too.

**How to reproduce**
The channel.charity_campaign.donate event subscription payload does not contain a reference to which
charity champaignId was donated too by a viewer.

`{
    subscription: {
        id: ...,
        status: "enabled",
        type: "channel.charity_campaign.donate",
        version: "beta",
        condition: {
            broadcaster_user_id: ...,
        },
        transport: {
        method: "webhook",
            callback: ...,
        },
        created_at: "2022-08-31T03:39:38.616061411Z",
        cost: 0,
    },
    event: {
        id: ...,
        broadcaster_user_id: ...,
        broadcaster_user_login: ...,
        broadcaster_user_name: ...,
        user_id: ...,
        user_login: ...,
        user_name: ...,
        target_amount: {
            amount: 100,
            decimal_places: 2,
            currency: "USD",
        },
    },
}`
**Expected behavior**

A unique identifier for the charity campaign donated too.

`"charity_campaign_id": "1234"`

**Comment by iProdigy** [comment]
The `id` field in the event *is* the campaign id

**Comment by jackmcguire1** [comment]
not really documented, couldn't tell if it's just a donationID or something.

on an additional note, it would be cool to supply charity info in the event also so I don't have to 
do a look up!

**Comment by BarryCarlyon** [comment]
This would be better solved by additional eventsub topics such as "charity goal started", "charity goal ended". (even if it's a no target goal it's still a goal in the dashboard :-P )

I wouldn't expect Twitch to add the charity information/goal information in each donation as if you get a huge run on donations thats a lot of wasted data being sent to subscribers on eventsub. (Like how a profile pictures are not in follow events/etc)

So best solution is to fetch and cache the charity data periodically. But I **expect** there are more API's and EventSub topics on the way which better solve the issue.

I'd of thought the ID in the eventsub payload is the donation unique ID, sicne theres no reason to send the campaign ID as only one campaign can be active on the channel at once.

**Comment by iProdigy** [comment]
`id | String | An ID that uniquely identifies the charity campaign.` is documented in the event reference, but could be made more obvious / named better https://dev.twitch.tv/docs/eventsub/eventsub-reference/#charity-donation-event

**Comment by iProdigy** [comment]
> but could be made more obvious / named better 

resolved:
```
Breaking change to the Beta channel.charity_campaign.donate EventSub subscription type:

The `id` field of the Charity Donation Event object will change to `campaign_id` to better reflect its content on Tuesday, September 20 at 1:00pm PDT.
```

https://dev.twitch.tv/docs/change-log

**Comment by jackmcguire1** [comment]
addressed
