### ISSUE TITLE
Missing event/data for user.*_image_url?

### ISSUE THREAD

**Issue by Dryzler** [twitchdev/issues#647]
Hello,

when an user changes his profile or offline image, i think there is no event or event payload that gives me that information by webhook call.

**Comment by Emilgardis** [comment]
Suggestions or feedback are better directed towards [UserVoice](https://twitch.uservoice.com/forums/310213-developers). 
See the readme https://github.com/twitchdev/issues#how-to-provide-general-feedback-and-suggestions
