### ISSUE TITLE
Invalid JSON in `GET /extensions/transactions`

### ISSUE THREAD

**Issue by kevinrpb** [twitchdev/issues#649]
**Brief description**
Lines 20 and 31 of the JSON example for the endpoint are missing a comma at the end of the line, which makes the JSON invalid.

**Additional context or questions**
I know this is a silly issue, but someone may or may not be relying on the code examples being correct. In any case, the fix should be very easy! 😄 

Cheers!

**Comment by Xemdo** [comment]
This seems to have been corrected, as I can't identify where this issue is.
If it still persists, please reopen and confirm which lines are affected.
