### ISSUE TITLE
Webhooks limits: ambiguous

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#65]
**Brief description**

https://dev.twitch.tv/docs/api/webhooks-guide

> Limits: By default, each client ID can have at most 10,000 subscriptions. Also, you can subscribe to the same topic at most 3 times. 

Seems to be ambiguous to a lot of developers, they seem to think the that "3 times" means they can renew it 3 times then they are SOOL

**Expected documentation**

> Limits: Each client ID can have at most 10,000 subscriptions. Where you can have 3 active subscriptions to a topic at the same time. Where an active subscription is defined as a topic/callback pair.

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848251-webhooks-limits-ambiguous
