### ISSUE TITLE
Cant log in 

### ISSUE THREAD

**Issue by ZappyGGs** [twitchdev/issues#650]
**Brief description**
When i try to log in it tells me to enter a code but my twitch isnt connected the the authenticator app and i dont have a phone number associated with my twitch 
**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by LosFarmosCTL** [comment]
This repo is meant for 3rd party development related issues (Extensions, API Usage, IRC, etc), not issues with the 1st part twitch website.

Regardless, if there is no phone number or authenticator app connected, twitch should send the verification code vie e-mail.

**Comment by BarryCarlyon** [comment]
For further help you'll need https://help.twitch.tv/ not this issue tracker
