### ISSUE TITLE
Extension discovery, Extensions dev dashboard, Extensions Caster Dashboard Search

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#652]
**Brief description**

Issue #585 has reoccured.

New issue to track the issue

**Additional context or questions**

- Dashboard extension categories seem to be in reverse alphabetic order rather than whatever they normally are
- Extehsnion Settings "banner bar" for accessing CID/Secret and analytics has gone missing from the Dashboard
- New Released extensions with no allowlist can't be installed
- New Released extensions with no allowlist don't show in search

**Comment by TonyXdddd** [comment]
The extension was released but is not available in the search results for users.

ClientID: gg38jg2zoibgcx7734sdgrs0nnhqvw.
Ext: PLINK Stats for Apex Legends 0.2.3

Status:
![_1](https://user-images.githubusercontent.com/54737881/189623968-851c6e01-15af-4479-92b7-478399acf15b.png)


Response object related to this extension in the 'my extensions' tab:
![_2](https://user-images.githubusercontent.com/54737881/189624468-6ac20cbb-e2d9-45ca-9764-0f7620f3006b.png)


Search result display:
![_3](https://user-images.githubusercontent.com/54737881/189624849-5f57a190-1899-472f-960a-5e23fd6f8c8b.png)

**Comment by BarryCarlyon** [comment]
Follow up: this issue may also be preventing people from uploading Zip Files in order to go for Hosted Test

**Comment by jbulava** [comment]
> Dashboard extension categories seem to be in reverse alphabetic order rather than whatever they normally are

This has been fixed.

> Extehsnion Settings "banner bar" for accessing CID/Secret and analytics has gone missing from the Dashboard

A developer site update should have fixed this or will be deployed soon.

> New Released extensions with no allowlist can't be installed
> New Released extensions with no allowlist don't show in search

The Extensions team confirmed that PLINK Stats 0.2.3 has an allowlist and would be the reason for this behavior. @TonyXdddd, if that doesn't seem to be right or if 0.2.3 is not the version to look at, please let us know.

> Follow up: this issue may also be preventing people from uploading Zip Files in order to go for Hosted Test

If this still exists, can we open a dedicated issue with an example? We are unable to reproduce this issue currently.

**Comment by TonyXdddd** [comment]
Thanks for your reply. Whitelist is empty.
https://postimg.cc/xc1PNfpM

![Uploading WL.png…]()
