### ISSUE TITLE
Get Moderators does not state `channel:manage:moderators` can be used in replacement of `moderation:read`

### ISSUE THREAD

**Issue by Felanbird** [twitchdev/issues#653]
## Brief description

With the implementation of documentation surrounding Get VIPs, a section explaining that `channel:manage:vips` can be used in replacement of `channel:read:vips` was implemented. 

Similar to `channel:manage:vips` - `channel:manage:moderators` was also added, but the documentation surrounding Get Moderators was not updated, despite the fact that `channel:manage:moderators` can be used as a replacement for `moderation:read`.

## Expected documentation
![image](https://user-images.githubusercontent.com/41973452/189310661-e545dc47-d5c0-4ee5-9e86-fe67db2991d8.png)
After Inspect Element changes

## Screenshots
![image](https://user-images.githubusercontent.com/41973452/189310744-1258b95a-8a43-4654-af51-9ea9e8dc276d.png)
When missing the required scopes, the error specifically states OR, which prompted me to test if `channel:manage:moderators` worked, which it does.

**Comment by scott-a-white** [comment]
Thanks for reporting the issue. Fixed: https://dev.twitch.tv/docs/api/reference#get-vips.
