### ISSUE TITLE
Announcement in chat is always issued twice

### ISSUE THREAD

**Issue by Dryzler** [twitchdev/issues#654]
**Brief description**
As the title says, i use https://api.twitch.tv/helix/chat/announcements? to post a message as moderator, and the message is always shown twice in the target chat.

**How to reproduce**
1) Get the target user's channel-manage-moderators scope
2) Add the own moderator account to to the target's channel moderators
3) Post an announcment with https://api.twitch.tv/helix/chat/announcements

**Expected behavior**
Only 1 announcement, not 2

**Screenshots**
[https://letsraid.com/images/twitch-chat-announcement-twice.png](https://letsraid.com/images/twitch-chat-announcement-twice.png)

**Additional context or questions**
I have seen that behavior before on twitch at other bots.

**Comment by iProdigy** [comment]
This likely isn't an announcements issue, but a matter of responding to both the raid & host event

**Comment by Dryzler** [comment]
> This likely isn't an announcements issue, but a matter of responding to both the raid & host event

I have a table where i store all webhook calls from twitch, no matter what the content is. And in this table i only see 1 webhook call for the raid, so it is definitely impossible that I execute the announce twice.

**Comment by Dryzler** [comment]
> > This likely isn't an announcements issue, but a matter of responding to both the raid & host event
> 
> I have a table where i store all webhook calls from twitch, no matter what the content is. And in this table i only see 1 webhook call for the raid, so it is definitely impossible that I execute the announce twice, but i will log my announce function, to be sure..

I have logged my announce function and it gets called exactly 1 time.

**Comment by iProdigy** [comment]
Just tested the helix endpoint & only got 1 announcement; if you're using eventsub for raids, I'd make sure you're not attaching a handler for the raid event sent over irc as well

**Comment by Dryzler** [comment]
> Just tested the helix endpoint & only got 1 announcement; if you're using eventsub for raids, I'd make sure you're not attaching a handler for the raid event sent over irc as well

I do not interact with IRC in any way.

**Comment by BarryCarlyon** [comment]
I wonder if you have a dev or second instance of the service running _somewhere._ And thats triggering the second announcment.

And that second instance isn't connected to the DB you are looking at and/or is on a different server.

You could try diconnecting the application from the user you are operating as, which will kill all access and refresh tokens. Reconnect and retest.

Or your primary task has a low timeout is timeing out and retrigging/retrying but you DB log only the final success?

In my own tests (and the bot I ported from IRC commands to API calls) I have no duplicates reported.

**Comment by Dryzler** [comment]
Thanks @BarryCarlyon. I actually have a 2nd instance that caused the second announcement.
