### ISSUE TITLE
Not all documented api endpoint headers are allowed on localhost

### ISSUE THREAD

**Issue by LievenPetersen** [twitchdev/issues#656]
**Brief description**
Headers are missing from api endpoints, when running on a localhost server.
Requests are blocked, since the headers are not allowed according to the cors preflight response.
I assume this is limited to localhost.

**How to reproduce**
paste this into an html file, change client_id & client_secret to valid values for a registered app.
```html
<!DOCTYPE html>
<html>
    <body>
        <script type="text/javascript">
            fetch("https://id.twitch.tv/oauth2/token", {
                method: "POST",
                body: new URLSearchParams({
                    client_id: "<your id>",
                    client_secret: "<your secret>",
                    grant_type: "client_credentials"
                })
            })
            .then(response => response.json())
            .then(token => {
                fetch("https://api.twitch.tv/helix/videos",{
                    headers: {
                        Authorization: "Bearer "+token.access_token,
                        "id": "XXXXXXXX",
                    }
                })
            })
        </script>
    </body>
</html>
```
Run this in the same directory and open a browser (Firefox) with `localhost:8000` 
```python3 -m http.server```

the request will be blocked, since `id` is not allowed in the preflight response.
Inspect network traffic to find a blocked OPTION, where the response header includes:
`access-control-allow-headers: Accept, Accept-Language, Authorization, Client-Id, Twitch-Api-Token, X-Forwarded-Proto, X-Requested-With, X-Csrf-Token, Content-Type, X-Device-Id, X-Twitch-Vhscf`

Notably, the headers from the documentation are missing.

(the request goes through with the client-id header, but this is useless because because one cannot find out a client_id since /helix/users blocks the login header)

**Expected behavior**
access-control-allow-headers should include the items specified in the documentation:
`id, user_id, game_id`
docs: https://dev.twitch.tv/docs/api/reference#get-users

this also applies to other endpoints, like /helix/users

**Comment by Emilgardis** [comment]
The `id` in [`Get Users`](https://dev.twitch.tv/docs/api/reference#get-users) is a query parameter, not a header.

**Comment by LievenPetersen** [comment]
Thank you :) , I'm new to this and didn't know the difference.
Sorry for any inconvenience.
