### ISSUE TITLE
Start Commercial doesn't clearly document that only the broadcaster can start commercials

### ISSUE THREAD

**Issue by pajlada** [twitchdev/issues#658]
**Brief description**
Reading through the [Start Commerical documentation](https://dev.twitch.tv/docs/api/reference#start-commercial) it doesn't clearly state that it must be a User Access Token and that the User Access Token must match with the `broadcaster_id` parameter. This clarification is expected since the v5 Start Commercial API allowed users to Start Commercials for channels in which they were editors.

[Uservoice requesting the old functionality back](https://twitch.uservoice.com/forums/310213-developers/suggestions/44183481-helix-start-commercial-endpoint-should-be-usable)
[GitHub issue showing off the confusion](https://github.com/twitchdev/issues/issues/544)

**Expected documentation**
The *Authorization* header should cleary define the restrictions (See https://dev.twitch.tv/docs/api/reference#update-user-chat-color for a good example)

**Screenshots**
![image](https://user-images.githubusercontent.com/962989/190858569-ac109f6b-76f5-444f-a4cd-eeccdfca1ce1.png)
:point_up: This documentation reads to me as if you can start a commercial for any user you have permission to start commercials for, not just your own user.

![image](https://user-images.githubusercontent.com/962989/190858625-a627d8e7-24c0-4863-887e-e013ee4538bd.png)
:point_up: Unclear description for the `broadcaster_id` parameter

**Additional context or questions**

**Comment by Xemdo** [comment]
Docs have since been updated to be more clear about token and broadcaster_id requirements.
