### ISSUE TITLE
Delete Chat Messages 

### ISSUE THREAD

**Issue by aidenwallis** [twitchdev/issues#660]
**Brief description**
The [Delete Chat Messages](https://dev.twitch.tv/docs/api/reference#delete-chat-messages) Helix API endpoint returns 400 if the caller is trying to delete another moderators' message.

**Expected documentation**
"Response Codes" should include 400 with the description "User is trying to delete a message they don't have access to", or maybe the actual downstream error of "You cannot delete messages from another moderator <moderator>."

The API response when receiving the 400 error:
```
{"error":"Bad Request","status":400,"message":"You cannot delete messages from another moderator <moderator>."}
```

**Comment by jbulava** [comment]
400 error added to docs.
