### ISSUE TITLE
Documentation for Send Chat Announcement helix endpoint doesn't mention 403 status

### ISSUE THREAD

**Issue by Mm2PL** [twitchdev/issues#661]
**Brief description**
Send Chat Announcement helix endpoint returns 403 when trying to send an announcement to a channel where the sender doesn't have permissions.

**Expected documentation**
I'd expect to have all statuses the endpoint can return listed in the doc not a subset.

**Screenshots**
n/a
![image](https://user-images.githubusercontent.com/25011746/191049788-2bca7daa-f392-4ad4-b41f-c97f1f6d942c.png)

**Additional context or questions**
#659

**Comment by jbulava** [comment]
403 error code and description added to docs.
