### ISSUE TITLE
Unable to send SMS because phone number is disabled for reuse, please use a different phone number to continue

### ISSUE THREAD

**Issue by HeyHantz** [twitchdev/issues#662]
I don't know why I can't verify my number on my account I've never used this number before but it say's this. 

_Staff edit: removed screenshot that included a phone number. The image was showing the "Account Verification" modal dialog, the form to enter a phone number, and the error message "Error: Unable to send SMS because phone number is disabled for reuse, please use a different phone number to continue."_

**Comment by Emilgardis** [comment]
This repository provides a means for third party developers to report bugs related to Twitch developer products such as the API, Extensions, and PubSub. Please file a [Twitch Support ticket](https://help.twitch.tv/s/contactsupport).

See https://github.com/twitchdev/issues#off-topic-bug-reports and https://help.twitch.tv/

You may have success with this method: https://www.reddit.com/r/Twitch/comments/rdm8zb/phone_number_disabled_for_reuse/hts1mlp/

**Comment by Emilgardis** [comment]
ps, you may want to remove the picture as it seems to contains your phone number

**Comment by jbulava** [comment]
Confirming @Emilgardis's comment, a Twitch support ticket is the best action. Reports here are for third-party developer products.
