### ISSUE TITLE
`/helix/channels` endpoint broken: it has started to return 500 status codes, as well as false 429 status codes

### ISSUE THREAD

**Issue by bastimeyer** [twitchdev/issues#664]
**Brief description**

Starting a couple of minutes ago, maybe an hour or so, not exactly sure, the `/helix/channels` Helix API endpoint has started to return errors:

1. Status code 500 - Internal Server Error
2. Status code 429 - Too many requests
   However, the `ratelimit-limit`, `ratelimit-remaining` and `ratelimit-reset` response headers indicate that it's not a rate limiting issue.

These errors are especially a problem when querying lots of `broadcaster_id`s.

The responses are also unusually slow and take a couple of seconds.

**How to reproduce**

```
$ curl -s -H 'Client-ID: MY-CLIENT-ID' -H 'Authorization: Bearer MY-OAUTH-TOKEN' 'https://api.twitch.tv/helix/channels?broadcaster_id=31239503'
{"error":"Internal Server Error","status":500,"message":""}
```

```
$ curl -s -H 'Client-ID: MY-CLIENT-ID' -H 'Authorization: Bearer MY-OAUTH-TOKEN' 'https://api.twitch.tv/helix/channels?broadcaster_id=31239503'
{"error":"Too Many Requests","status":429,"message":"The application exceeded the number of calls it may make. For details, see Rate Limits in the Twitch API documentation."}
```

```
$ curl -s -I -H 'Client-ID: MY-CLIENT-ID' -H 'Authorization: Bearer MY-OAUTH-TOKEN' 'https://api.twitch.tv/helix/channels?broadcaster_id=31239503&broadcaster_id=52345220&broadcaster_id=64342766&broadcaster_id=45044816&broadcaster_id=52091823&broadcaster_id=93869876&broadcaster_id=833639984&broadcaster_id=108268890&broadcaster_id=72550899&broadcaster_id=19571641&broadcaster_id=26610234&broadcaster_id=128293484'
HTTP/2 429 
content-type: application/json; charset=utf-8
access-control-allow-origin: *
ratelimit-limit: 800
ratelimit-remaining: 799
ratelimit-reset: 1664382847
timing-allow-origin: https://www.twitch.tv
fastly-restarts: 1
date: Wed, 28 Sep 2022 16:34:07 GMT
x-served-by: cache-sea4422-SEA, cache-hhn11561-HHN
x-cache: MISS, MISS
x-cache-hits: 0, 0
x-timer: S1664382843.066028,VS0,VS0,VE4394
vary: Accept-Encoding
strict-transport-security: max-age=300
content-length: 174
```

**Comment by bastimeyer** [comment]
Other *commonly used* endpoints (streams, users) appear to be working fine.

When querying only a single `broadcaster_id` on the channels endpoint, the errors are less common, but when querying more, the response is always 500 or 429, which is completely breaking my application right now, as it coalesces multiple API queries on the same endpoint into one.

**Comment by bastimeyer** [comment]
The devstatus page unfortunately doesn't monitor the channels endpoint
https://devstatus.twitch.tv/

**Comment by bastimeyer** [comment]
The same issue already occured in April, see #592

**Comment by bastimeyer** [comment]
A quick comment or acknowledgement from the Twitch devs would be appreciated, [like last time](https://github.com/twitchdev/issues/issues/592#issuecomment-1095448484), so we know that this is being looked into.

**Comment by BarryCarlyon** [comment]
AWS is having an outage

https://health.aws.amazon.com/health/status

This is effecting a LOT of Twitch Services including the API

https://twitter.com/TwitchSupport/status/1575200616925773826

**Comment by bastimeyer** [comment]
Issue seems to be resolved now...
