### ISSUE TITLE
Unable to change OAuth Redirect URLs due to GraphQL error

### ISSUE THREAD

**Issue by codesalatdev** [twitchdev/issues#665]
Every attempt to try to change the OAuth Redirect URL for any application results in the site doing nothing when clicking "Save". In the console, there are errors reported by GraphQL (service error and failed integrity check):

![image](https://user-images.githubusercontent.com/10341765/193110719-8d9a03d1-14dc-4928-ba33-74a46ae311e0.png)

I am therefore unable to modify my application's redirect URLs in any way. This happens regardless of browser or version.

**Comment by hudbuddy** [comment]
I am encountering a similar issue when updating redirect URLs (error: `service error`)

![image](https://user-images.githubusercontent.com/8524633/193137605-20f1906b-5c98-475c-bbe1-e39c269c9e54.png)

**Comment by codesalatdev** [comment]
@hudbuddy got that message too at the start, but then it switched to the integrity error. Don't know why, but we're definitely talking about the same issue here.

**Comment by RobbiePlata** [comment]
```{
    "operationName": "UpdateOauthApp",
    "variables": {
        "input": {
            "name": "PubSub",
            "redirectURIs": [
                "https://localhost:3001",
                "http://localhost:3000"
            ],
            "categoryID": "8",
            "categoryOther": "",
            "groupID": "",
            "id": "jw08wg5efyttyep4rjzhvq3g37wx26"
        }
    },
    "extensions": {
        "persistedQuery": {
            "version": 1,
            "sha256Hash": "01a86b1a5d2d214259a86eb0a28526f78b39f784d4b7f89f4b68638874fdb474"
        }
    }
}```

2nd redirect URI does not save, response is 200.

Repro: 
Type redirect_uri
Add redirect_uri
Save

**Comment by JorisKok** [comment]
Seems to be working again for me.

**Comment by codesalatdev** [comment]
@JorisKok same. I'm closing this. If anyone still has the issue, feel free to open it up again.

**Comment by BarryCarlyon** [comment]
For anyone that stumbles over this issue:

This is superseeded by #665 and anyone having an issue crate or editing an application should also check they are

1) using a supported browser (Chrome/Firefox/Edge/Safari) Brave or operaGX users may have issues
b) ensure your application is using a unique name that adequately identifies your application.

**Comment by ilya-zlobintsev** [comment]
I've also encountered this issue, and the solution was changing the app name. Which is weird, because I've had the old app name for years at this point. If I change back to the old name, it breaks again.

**Comment by Omsad** [comment]
The issue looks to have re-appeared as I'm unable to add an additional redirect url.
![Example](https://user-images.githubusercontent.com/18362326/204101561-54533bbe-2e84-4d58-958a-1e8db58926d4.PNG)

**Comment by domsson** [comment]
I can neither create a new, nor edit an existing application. Have tried with two different browsers and two different users (one combination of which was previously able to create and edit applications). Getting GraphSQL error in the console.

**Comment by Lowgy** [comment]
I am getting the same issue when trying to update my redirect urls from localhost to actual domain

**Comment by BarryCarlyon** [comment]
@Lowgy https://help.twitch.tv/s/article/supported-browsers?language=en_US#troubleshooting
