### ISSUE TITLE
`Update Chat Settings` doesn't list possible response codes

### ISSUE THREAD

**Issue by Nerixyz** [twitchdev/issues#667]
**Brief description**

Most endpoints in the Twitch API docs mention the possible HTTP response codes. [Update Chat Settings](https://dev.twitch.tv/docs/api/reference#update-chat-settings) doesn't mention any response codes. 

**Expected documentation**

A table like 

| Code | Meaning |
|---|---|
|200|Success.|
|400| Malformed request. |
|401|Authentication failure.|
|403|Forbidden. [...] |

**Screenshots**

\-

**Additional context or questions**

\-

**Comment by Xemdo** [comment]
This has since been added to the documentation
