### ISSUE TITLE
VIP boolean tag is inconsistent with mod and other "common" tags 

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#668]
**Brief description**

`VIP` tag do not appear with =0 only =1

This is inconsistent with the `mod` tag for example

"Common" tags = tags usually sent with most normal chat messages.

**How to reproduce**

Observe a vip, and non VIP messages

**Expected behavior**

Not sure

**Additional context or questions**

https://discuss.dev.twitch.tv/t/boolean-privmsg-tags-should-not-be-included-if-they-are-false-0/40992

**Comment by pajlada** [comment]
As a reference, the documentation for the tags can be found here: https://dev.twitch.tv/docs/irc/tags#privmsg-tags

The wording for the three boolean tags are

## VIP
> A Boolean value that determines whether the user that sent the chat is a VIP. The message includes this tag if the user is a VIP;  otherwise, the message doesn’t include this tag (check for the presence  of the tag instead of whether the tag is set to true or false).

## Moderator
> A Boolean value that determines whether the user is a moderator. Is true (1) if the user is a moderator; otherwise, false (0).

## Subscriber
> A Boolean value that determines whether the user is a subscriber. Is true (1) if the user is a subscriber; otherwise, false (0).

All three documented values are fairly strongly worded.

**Comment by BarryCarlyon** [comment]
> The subscriber tag does actually show up with a 0 value if a user is not subscribed as opposed to the initial issue text

In a quick _skim_ of some raw logs I didn't see it. So likely correct I jsut missed it whilst quick skimming

**Comment by Felanbird** [comment]
> Expected behavior
> Not sure

This approach to the VIP tag seems more correct than the prior implementations, I have this feeling the only reason they don't update the former implementations is they've been around too long and changing it will effect way too much code 3p code (and probably some 1p).

**Comment by BarryCarlyon** [comment]
Closing since if forum op really things it's a issue they can user voice it
