### ISSUE TITLE
GET Request Timeout on connection

### ISSUE THREAD

**Issue by Nollknolle** [twitchdev/issues#673]
**Brief description**
Connection Timeout API Request.

I make a request to the Twitch API every 5 minutes for a certain number of streamers to find out if they are online and then notify people via a Discord bot. Is there a limit to this because I've been getting timeouts for quite some time.
**How to reproduce**
Axios GET Request: https://api.twitch.tv/helix/streams?user_login=xyz
**Expected behavior**
Getting data back from the streamer
**Screenshots**
N/A
**Additional context or questions**
Error Log:
```
Error: connect ETIMEDOUT 199.232.138.214:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
```

Code Request:
```js
var config = {
            method: "get",
            url: `https://api.twitch.tv/helix/streams?user_login=${streamer.name}`,
            headers: {
              "client-id": "xxx",
              Authorization: `Bearer ${token}`,
            },
          };
```

**Comment by BarryCarlyon** [comment]
This is a sparadoic problem with any API

This is likely an issue with fast.ly and/or the route between you and the server.

If you get a timeout just retry the request.

it's popped up a little more common recently as an issue (in Discord/forums), but it's not a "Twitch API" problem really. It's any number of issues between you and Twitch itself.

So jsut retry the request
