### ISSUE TITLE
Creating a Drop still has an option for the decommissioned Event Based Drops

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#675]
**Brief description**
The dialog box to create a Drop for a Drop campaign includes a `Rule Type` toggle, with options for `Time-Based` or `Event-Based`, with the latter not being selectable due to availability being limited to allowlisted testers at the time when Event Based drops was a thing.

Event Based Drops relied on Enhanced Experiences (E2), a product which was decommissioned on April 12, 2022 [https://discuss.dev.twitch.tv/t/enhanced-experiences-deprecation/37908](https://discuss.dev.twitch.tv/t/enhanced-experiences-deprecation/37908)

**How to reproduce**
1. From the Developer Console of an Organisation, select a Drops campaign.
2. Select the 'Drops' tab.
3. In the `Time-Based Drops` panel, click the `Create New Drop` button.
4. The `Create Drop` modal window has a `Rule Type` section, containing the now-decommissioned `Event-Based` option.

**Expected behavior**
The modal window displayed in step 4 of the reproduction steps should only have `Time-Based` as a `Rule-Type`.

**Screenshots**
![eventBasedDrop](https://user-images.githubusercontent.com/12213790/196446757-8bb68a3f-bc63-445c-9ef1-b940c1cecaf1.png)

**Additional context or questions**
Event Based Drops was an awesome concept! Lack of adoption wasn't helped by a tiny allowlist and over-engineered E2 system. It'd be incredible to have more rule types for Drops.

**Comment by thedist** [comment]
When editing a Drop, the rules tab also shows `Event-Base Rule` as an option in a dropdown box.

![Uploading eventBasedDrop2.png…]()

**Comment by Xemdo** [comment]
This is no longer an issue with the new Drops system, only the legacy system (which should not allow you to create campaigns/drops for it anymore).
