### ISSUE TITLE
Uncaught error when trying to toggle the Drop Condition of a Drop

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#676]
**Brief description**
The toggle to change a Drop Condition from working independently or consecutively with another Drop throws an uncaught error if the toggle is clicked when there are no other Drops available to select.

**How to reproduce**
1. Edit a Drops Campaign
2. in the Drops tab create a single Drop
3. Edit that Drop, go to its Rules tab, and attempt to click the `Drop Condition` toggle.
4. An error will be thrown in the console, `[ERROR] Uncaught error. TypeError: Cannot read properties of undefined (reading 'id')`

**Expected behavior**
The toggle should be disabled if there is only 1 Drop for the campaign as that toggle isn't applicable in that situation.

**Comment by Xemdo** [comment]
This should not occur anymore, as the new Drops system does not support Drop Conditions.
