### ISSUE TITLE
Category Box Art is missing from games in the Developer Console for Organisations

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#677]
**Brief description**
Various pages throughout the Developer Console for Orgs has box art of various resolutions for games claimed by the org, but in most places it has the default placeholder image.

This lack of box art has at times lead to confusion for game developers who have updated the box art on IGDB but that is not reflected on their organisations Developer Console pages. Example of the issues this has caused for developers: [https://discuss.dev.twitch.tv/t/game-box-art-not-being-pulled-from-igdb-to-twitch/41244](https://discuss.dev.twitch.tv/t/game-box-art-not-being-pulled-from-igdb-to-twitch/41244)

One area of the Developer Console where box art is correctly displayed is Campaign Details page of a Drops Campaign, where on the left panel the placeholder box art is used under the game selection dropdown, but on the right panel showing what streamers will see it does correctly display the games box art.

**How to reproduce**
Browse the Developer Console for an org that has claimed games, they will not have box art.

**Expected behavior**
After box art has been pulled from IGDB the box art should be updated throughout the Developer Console

**Screenshots**
![boxArt2](https://user-images.githubusercontent.com/12213790/196472118-bb08584a-d0f4-486c-94a1-fc7413e0886d.png)

**Comment by Xemdo** [comment]
This should be fixed as of today
