### ISSUE TITLE
Redirect from implicit grant flow violates URI RFC

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#678]
**Brief description**
When using the implicit grant flow, after authenticating with Twitch, the user is sent to a constructed redirect uri that violates the [URI RFC](https://www.rfc-editor.org/rfc/rfc3986#section-3) because the `#access_token` hash fragment comes before the query params

**How to reproduce**
Go through the implicit grant flow and notice the redirect url becomes: `http://localhost:3000/login#access_token=censored&scope=channel%3Aread%3Apolls&state=dank&token_type=bearer`

**Expected behavior**
To comply with the RFC, the user should've been redirected to `http://localhost:3000/login?scope=channel%3Aread%3Apolls&state=dank&token_type=bearer#access_token=censored`

**Additional context or questions**
This would also help streamers going through this flow while live (yes, a bad idea) to reduce the likelihood of leaking their token

**Comment by Emilgardis** [comment]
This wouldn't hinder the security aspect of using a fragment, as the access token would still be behind the fragment and not be gettable in browser history.

it would however be a bit breaking as the granted scopes and state token would be a query and not a fragment

**Comment by Dkamps18** [comment]
They're not query params, the fragment is a string following the "application/x-www-form-urlencoded" standard following the OAuth 2.0 RFC https://www.rfc-editor.org/rfc/rfc6749#section-4.2.2
