### ISSUE TITLE
msg-id tags page outdated/incorrect

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#68]
Docs location: https://dev.twitch.tv/docs/irc/msg-id

bad_ban_global_mod & bad_timeout_global_mod are gone for as far as i know (ref: https://blog.twitch.tv/en/2018/12/13/thank-you-global-moderators-4d44cfccf22/)

Missing notices for vip events (vip_success, unvip_success, no_vips, bad_vip_grantee_banned, bad_vip_grantee_already_vip, usage_vip & bad_unvip_grantee_not_vip) Might have missed some.

First line says "These tags apply to both the" and than only names one thing.

usage_untimeout has "/raid <username>" in the message.

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848266-msg-id-tags-page-outdated-incorrect

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: 
 https://twitch.uservoice.com/forums/310213-developers/suggestions/39848266-msg-id-tags-page-outdated-incorrect
