### ISSUE TITLE
Live extensions not able to use bits - beginUseBitsInExtension service error

### ISSUE THREAD

**Issue by JorisKok** [twitchdev/issues#681]
**Brief description**

On our extensions we are not able to purchase bits on some channels. 

Our guess is that it's not possible for the accounts that we have in the extensions `Testing Account Allowlist`. All other accounts seem to work.

**How to reproduce**

Try to use bits on the following channel, for the infinite album extension: https://www.twitch.tv/infinitealbum

![image](https://user-images.githubusercontent.com/3580974/197186982-3c903b07-b4f5-47af-8892-bb8f7a977c52.png)

![image](https://user-images.githubusercontent.com/3580974/197186684-5ac73c52-75dc-4b89-bdd3-85d5484ce443.png)

**Note:** We are able to use bits on some other channels, for example:
https://www.twitch.tv/xidik_uk
With the infinite album overlay.

**Expected behavior**

We should be able to use bits for ALL channels.

**Screenshots**

**Additional context or questions**

We have the same issues with another extension called Pando. Where it also works for all channels, except for for example: https://www.twitch.tv/pando_dev

**Comment by BarryCarlyon** [comment]
sounds like a duplicate of https://github.com/twitchdev/issues/issues/359

The `Testing Account Allowlist` has the test version of the extension installed
You released your extension
And the permissions for the extension _reset_

**Comment by JorisKok** [comment]
Closed because of duplicate.
