### ISSUE TITLE
Hype train Begin/End/Progress has a minor typo

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#682]
**Brief description**
Hype train Begin/End/Progress has a minor typo

**Expected documentation**
<img width="974" alt="image" src="https://user-images.githubusercontent.com/1502855/197348242-e8a0ab8d-b994-414b-ae88-1e17e3fbfbe0.png">

**Screenshots**
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1502855/197348281-d4ed969d-6200-499b-a6dc-8b994c9fb4f8.png">

**Additional context or questions**

**Comment by Emilgardis** [comment]
should maybe be "want to get"

but actually, rereading this, it seems correct, may be just my non-native english 😅

**Comment by scott-a-white** [comment]
Hello. Thanks for raising the issue. You're correct, it's missing 'get'. We'll fix it in the next doc update. Thanks again!

**Comment by Emilgardis** [comment]
This has been fixed
