### ISSUE TITLE
Shoutout to streamers with non-Western display name

### ISSUE THREAD

**Issue by GyrosGeier** [twitchdev/issues#683]
**Brief description**

I just tried to `/shoutout` a streamer with a Korean display name. I used "/shoutout juliday97" in the chat window, and viewers got an unusable link, both for going to the channel and for following.

**How to reproduce**

Use `/shoutout` with any streamer whose display name is just a different capitalization of their user name.

**Expected behavior**

I would have expected working links. :P

**Comment by gmt2001** [comment]
You should file issues with first-party products as a [Twitch Support Ticket](https://help.twitch.tv/s/contactsupport)

**Comment by BarryCarlyon** [comment]
Better place to report this is the uservoice for shoutouts - https://twitch.uservoice.com/forums/310201-chat?category_id=446944
