### ISSUE TITLE
Processing an event - Eventsub guide wrong example

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#684]
**Brief description**
https://dev.twitch.tv/docs/eventsub/handling-webhook-events#processing-an-event

example does not contain field `followed_at`

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1502855/199353193-3a3e4f32-1e7e-4270-9130-33f740cad329.png">

**Comment by Emilgardis** [comment]
same goes for the websocket docs https://dev.twitch.tv/docs/eventsub/handling-websocket-events#notification-message

**Comment by BarryCarlyon** [comment]
ha I guess no one updated the docs when the extra field was added lol

**Comment by scott-a-white** [comment]
Hello. Thanks for bringing the issue to our attention. We'll add the field in the next doc update. Thanks again!

**Comment by Emilgardis** [comment]
change is live
