### ISSUE TITLE
Replace Stream Tags returns incorrect status code or message

### ISSUE THREAD

**Issue by adleong** [twitchdev/issues#687]
When calling the Replace Stream Tags API, I get a status code 400 response with the message "The ID in broadcaster_id must match the user ID found in the request's OAuth token."

According to the [documentaion](https://dev.twitch.tv/docs/api/reference#replace-stream-tags), that message should correspond to status code 401.

Therefore, I'm unsure if the tags are invalid (as suggested by the status code 400) or if my broadcaster_id doesn't match my token (as suggested by the message).

```
[HttpStatusCodeError: Encountered HTTP status code 400: Bad Request

Body:
{
  "error": "Bad Request",
  "status": 400,
  "message": "The ID in broadcaster_id must match the user ID found in the request's OAuth token."
}] {
  _statusCode: 400,
  _body: {
    error: 'Bad Request',
    status: 400,
    message: "The ID in broadcaster_id must match the user ID found in the request's OAuth token."
  }
}
```

**Comment by BarryCarlyon** [comment]
This API is _dead_ as it has not been updated to support Tiwtch's new freeform stream Tags system.

So this is unlikely to be resolved without the new Steam Tags API arriving to replace it
