### ISSUE TITLE
HTTP Response codes unclear

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#69]
**Brief description**

Some endpoints return a 204 code no content.
But this is only highlighted in the example responses and not in the "main documentation"

For example

https://dev.twitch.tv/docs/extensions/reference#send-extension-pubsub-message
https://dev.twitch.tv/docs/extensions/reference#send-extension-chat-message

Each endpoint documented could be extended to include usual HTTP response codes.

**Expected documentation**

The expected response code for success when theres no body response
Common non 2xx codes for the endpoints

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: 
 https://twitch.uservoice.com/forums/310213-developers/suggestions/39848299-http-response-codes-unclear
