### ISSUE TITLE
Get Chatters - missing cursor

### ISSUE THREAD

**Issue by JorisKok** [twitchdev/issues#692]
**Brief description**

I'm testing my code that uses Get Chatters, to see if my pagination works. 

Calling the GET Chatters endpoint, with a `first` of 1, I am getting a list with 1 user, but a total of 2 users in chat. But there is no `cursor` in the response. So I can't get the second page.

**How to reproduce**

GET `https://api.twitch.tv/helix/chat/chatters?broadcaster_id=xxxx&moderator_id=xxxx&first=1`

Response:
```
{
    "data": [
        {
            "user_id": "xxx",
            "user_login": "xxx",
            "user_name": "xxx"
        }
    ],
    "pagination": {},
    "total": 2
}
```

**Expected behavior**

Should get the following response
```
{
    "data": [
        {
            "user_id": "xxx",
            "user_login": "xxx",
            "user_name": "xxx"
        }
    ],
    "pagination": {
         "cursor": "xxxxxxxxxx"
    },
    "total": 2
}
```

**Screenshots**

**Additional context or questions**

**Comment by Xemdo** [comment]
Was internally ticketed as CFC-8597

This should have been fixed in a release during February of 2023.
