### ISSUE TITLE
OAuth app fails to update

### ISSUE THREAD

**Issue by davidzoltan** [twitchdev/issues#693]
**Brief description**
A certain application does not update when trying to add a new oauth redirect url.
A service error is returned in the response of the request to https://gql.twitch.tv/gql.
Nothing else happens and changes are not saved.
Other applications can be updated.

**How to reproduce**
Add a new redirect url to an existing application.

**Expected behavior**
The save button changes to "Success" and changes are saved.

**Additional context or questions**
The application was created on 02/02/2017 and was last updated on 05/19/2022.
There are less than 10 redirect urls (including the one we try to add).
We tried making the change with Chrome and with Edge, both have the same result.
A sample of a response:
```
[
    {
        "errors": [
            {
                "message": "service error",
                "path": [
                    "updateOauthApp"
                ]
            }
        ],
        "data": {
            "updateOauthApp": null
        },
        "extensions": {
            "durationMilliseconds": 49,
            "operationName": "UpdateOauthApp",
            "requestID": "01GJHMX5VQGSRDVQ8XKHP2HPF2"
        }
    }
]
```

**Comment by iProdigy** [comment]
Try changing the app name & try again

**Comment by davidzoltan** [comment]
Hi, 
thank you for the quick response.
would I be able to change it back afterwards? (it's a user facing application so the name is important)

**Comment by iProdigy** [comment]
It depends.

One possible reason for your redirect url request to fail is if there exists an app with the same name. So, if you rename the app, you should be able to add the redirect url, assuming this is the issue. However, you wouldn't be able to change it back, as the name is taken by someone else.

If a name duplicate is not the issue, changing the name won't fix the redirect url issue, but you'll be able to revert the name change.

**Comment by davidzoltan** [comment]
Thank you.
After changing the name we're able to add a new redirect url but can't revert to the old name, which is odd since we were able to add another url a few months ago.
