### ISSUE TITLE
Some minor mistakes and typos in the docs

### ISSUE THREAD

**Issue by DmitryScaletta** [twitchdev/issues#695]
## Response code is 204 instead of 200

![image](https://user-images.githubusercontent.com/5096735/204105120-62242cb8-3bc9-4b54-a7ab-9b1348796d69.png)

https://dev.twitch.tv/docs/api/reference#get-vips

## Property name "reward" instead of "cost" like in the example

![image](https://user-images.githubusercontent.com/5096735/204115585-0e83a6bb-1570-4b92-9e24-a3bdd24785f5.png)

![image](https://user-images.githubusercontent.com/5096735/204115596-37b46d30-b852-4069-8b97-8f107076108e.png)

https://dev.twitch.tv/docs/api/reference#get-custom-reward-redemption

## All other endpoints doesn't have Response Example if response is empty (204)

![image](https://user-images.githubusercontent.com/5096735/204104720-5bdf5baf-0499-4a97-a2bd-4d36cfb8e2fb.png)
![image](https://user-images.githubusercontent.com/5096735/204104775-c6010ea8-432c-4212-afae-70af6df1f3b5.png)

https://dev.twitch.tv/docs/api/reference#modify-channel-information
https://dev.twitch.tv/docs/api/reference#delete-custom-reward
https://dev.twitch.tv/docs/api/reference#delete-eventsub-subscription

## Not full URL

Should be `GET https://api.twitch.tv/helix/search/channels`

![image](https://user-images.githubusercontent.com/5096735/204104093-874e4cdf-83f5-4464-aa0f-2991bff63f9a.png)

https://dev.twitch.tv/docs/api/reference#search-channels

## Missing GET method

Should be `GET https://api.twitch.tv/helix/streams/key`

![image](https://user-images.githubusercontent.com/5096735/204630878-c7c15b1d-fdd3-4c05-8913-db5a7197558f.png)

https://dev.twitch.tv/docs/api/reference#get-stream-key

## "URLs" instead of "URL"

In all other places it's "URL"

![image](https://user-images.githubusercontent.com/5096735/204104019-14e6b931-89df-4424-88ac-15f5863e8b15.png)

https://dev.twitch.tv/docs/api/reference#get-users-follows

## "Request Body Fields" instead of "Request Body"

In all other places it's "Request Body"

![image](https://user-images.githubusercontent.com/5096735/204104533-48152d00-541a-4d5e-aab8-aa9c0b0a8a86.png)

https://dev.twitch.tv/docs/api/reference#update-drops-entitlements

## "Required Query Parameters" instead of "Request Query Parameters"

In all other places it's "Request Query Parameters"

![image](https://user-images.githubusercontent.com/5096735/204104540-3d73c785-23fa-4f32-b842-8f8f33c236cc.png)

https://dev.twitch.tv/docs/api/reference#get-users

## "Response codes" instead of "Response Codes" (with capital "C")

In all other places it's "Response Codes"

![image](https://user-images.githubusercontent.com/5096735/204104448-8e252799-bc59-4b77-bfa9-5f1c5436644c.png)

https://dev.twitch.tv/docs/api/reference#start-commercial
https://dev.twitch.tv/docs/api/reference#get-extension-analytics
https://dev.twitch.tv/docs/api/reference#get-game-analytics
https://dev.twitch.tv/docs/api/reference#get-bits-leaderboard
https://dev.twitch.tv/docs/api/reference#get-cheermotes

## Missing "Example Request" header

![image](https://user-images.githubusercontent.com/5096735/204104625-21d8e75a-e1eb-41d5-ba8b-e3388487ac1c.png)

https://dev.twitch.tv/docs/api/reference#get-soundtrack-playlists

## "Example Request" is actually "Example Response"

![image](https://user-images.githubusercontent.com/5096735/204104652-5e9a2d91-5461-4f07-9910-4abb6253d65e.png)

https://dev.twitch.tv/docs/api/reference#get-vips

## Incorrect table formatting

See https://github.com/twitchdev/issues/issues/691

## 6 spaces instead of 3 that represents nested object

![image](https://user-images.githubusercontent.com/5096735/204104948-4036281c-4284-4d87-a335-aaa4ec1f57ea.png)

https://dev.twitch.tv/docs/api/reference#create-stream-marker

## Table without header (`thead` tag). The head is just a regular row inside `tbody`

![image](https://user-images.githubusercontent.com/5096735/204105012-6b6cb610-9030-4320-b2cd-0674b46c7b50.png)

https://dev.twitch.tv/docs/api/reference#get-channel-information

**Comment by scott-a-white** [comment]
Great catches! Thanks much for the feedback. We'll include these changes in the next doc update.

**Comment by jbulava** [comment]
Updates have been deployed.
