### ISSUE TITLE
Update Shield Mode Status - Incorrect PUT Body and Headers in Documentation

### ISSUE THREAD

**Issue by gmt2001** [twitchdev/issues#698]
**Brief description**
The PUT body and headers in the documentation for [Update Shield Mode Status](https://dev.twitch.tv/docs/api/reference/#update-shield-mode-status) is incorrect

**Incorrect documentation**
```
curl -X PUT 'https://api.twitch.tv/helix/moderation/shield_mode?broadcaster_id=12345&moderator_id=98765' \
-H 'Authorization: Bearer kpvy3cjboypmiacwr0c19hotn5s' \
-H 'Client-Id: hof5gwx0su6owfn0yan9c87zr6t' \
-H 'Client-Type: application/json' \
-d '{"data":{"is_active":false}}'
```

**Expected documentation**
```
curl -X PUT 'https://api.twitch.tv/helix/moderation/shield_mode?broadcaster_id=12345&moderator_id=98765' \
-H 'Authorization: Bearer kpvy3cjboypmiacwr0c19hotn5s' \
-H 'Client-Id: hof5gwx0su6owfn0yan9c87zr6t' \
-H 'Content-Type: application/json' \
-d '{"is_active":false}'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3355471/205425867-dda07f79-36ab-4419-8804-a388722bb75a.png)

**Additional Observation**
The endpoint will return _200 OK_ and the body showing the current state (before the attempted state change) of Shield Mode if using the incorrect body defined in the documentation.

I would expect this to return _400 Bad Request_

**Comment by iProdigy** [comment]
I'm able to reproduce the endpoint not doing anything if the body follows the documentation (i.e., `{"is_active": true}` is correct).

Also, to get the endpoint to work, `Content-Type` header needs to be present (docs mistakenly do `Client-Type`)

**Comment by gmt2001** [comment]
> Also, to get the endpoint to work, `Content-Type` header needs to be present (docs mistakenly do `Client-Type`)

Good catch, didn't notice since I was using my bot lib which already did that. Updating OP and forums post

**Comment by scott-a-white** [comment]
Thanks for letting us know about the issues. The fix will go out in the next doc release.
