### ISSUE TITLE
Missing status `websocket_disconnected` in response and request for Get Eventsub Subscriptions and 

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#699]
**Brief description**
Get Eventsub Subscriptions does not document `websocket_disconnected` as a possible response, it seems it's possible to also filter by this status

**Expected documentation**
Docs should mention this status

**Screenshots**
returned data:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/1502855/205494725-1bfae416-db94-4c7c-b28c-0a43f028e690.png">
documentation:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1502855/205494679-debe9d15-f9a1-4214-96f1-256a1e4b5e79.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/1502855/205494697-67c7da37-a15c-4133-a6a2-8270ce4e69ba.png">

**Additional context or questions**

**Comment by scott-a-white** [comment]
Thanks for letting us know about the issue. The fix will be in the next doc update.

**Comment by jbulava** [comment]
Scott's updates are in the process of being published.
