### ISSUE TITLE
User/Channel ID needs to be a string

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#70]
**Brief description**

The documentation for creating signing JWT's don't explicitly state that user_id/channel_id in JWT's need to be an explicit string literal 

https://dev.twitch.tv/docs/extensions/building/#signing-the-jwt
https://dev.twitch.tv/docs/extensions/reference#send-extension-pubsub-message

**Expected documentation**

```
Where:

exp is the Unix epoch timestamp when the payload will expire. Be sure to provide a buffer, to allow potential positive time drift.
user_id is the Twitch user ID that owns the extension, where the user ID is cast as a string literal.
role is set to external.
```

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39848317-user-channel-id-needs-to-be-a-string
