### ISSUE TITLE
receiving online/offline events for user i am not subscribed to events for

### ISSUE THREAD

**Issue by goproslowyo** [twitchdev/issues#701]
**Brief description**
I noticed my code behaving strangely.  While looking over logs to determine why I think it might be because I am not properly handling EventSub notifications from Twitch for users I no longer am "following" for online/offline events.

However, what was weird to me was I remembered unsubscribing/deleting EventSub notifications for this user. 
![image](https://user-images.githubusercontent.com/68455785/206662839-54994813-6f14-4c4f-935c-c08d80796b3d.png)

So... why did Twitch send me a notification today for them? I think I've noticed this behavior for a few other users too that I believe I unsubscribed from notifications from.
![image](https://user-images.githubusercontent.com/68455785/206662108-df7ae70f-bdd5-4b54-908f-5a399f9e11d1.png)

**How to reproduce**
Delete EventSubs for a user and you might still get them?

**Expected behavior**
I should not receive online/offline (that's the typed I had previously subscribed to) event notifications for users I not longer have EventSubs for.

**Screenshots**
provided above

**Additional context or questions**
Happy to provide any more information needed.

**Comment by BarryCarlyon** [comment]
Did you perchance create an eventsub for that user using _another_ clientID which differs from the clientID you are using in the TwitchCLI currently?

When a notification comes in you can pull the `id` from the `subscription` block and then attempt to delete that subscription, and see if it errors out with a useful message?

if it's a retry (check the retry header) I'm wondering if it's an older retry for a now deleted subscription. As a delete might not clear the queued messages to retry.

**Comment by goproslowyo** [comment]
Yes, it's possible these are from another clientID but I only have one that
I use for this purpose in my Twitch Dev account (and the other is the
"prod" one) when looking so that miiiight be exactly the problem.

I can augment the code to log out the JSON I receive from the webhook to
get the client ID so as to debug further, thanks!

**Comment by goproslowyo** [comment]
Hey sorry for the delay, this is still on my radar but might get pushed
until after the new year.

**Comment by goproslowyo** [comment]
Hah, phantom client indeed found and purged... thanks.
