### ISSUE TITLE
EventSub Subscription Types that don't work on WebSocket Transport

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#703]
**Brief description**

Topics like auth grant/revoke, drops and extensions bits transactions do not work on EventSub Websockets but the documentation doesn't state this

**Expected documentation**

Add badges to each Sub Type on https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types to ID the transports a given topic works on.

**Comment by starrrsky** [comment]
Updated the docs to note which subscription types aren't supported by WebSockets. [ASYNC-3317]
