### ISSUE TITLE
Seemingly improper response from /search/channels

### ISSUE THREAD

**Issue by skinmaker1345** [twitchdev/issues#705]
**Brief description**
Some Queries(explained below) gives 400 response with message saying:
``Empty StreamsByChannelIDsRequest.ChannelIds is required.``

**How to reproduce**
Any queries that do not have any results seems to cause the issue.
- Example of queries not causing the issue
```
https://api.twitch.tv/helix/search/channels?query=Overwatch
https://www.twitch.tv/search?term=Overwatch
```

- Query causing the issue
```
https://api.twitch.tv/helix/search/channels?query=querythatdoesnothaveanyresult
https://www.twitch.tv/search?term=querythatdoesnothaveanyresult
```

**Comment by iProdigy** [comment]
Able to replicate this for `/search/channels`:
```json
{
  "data": [],
  "error": "Bad Request",
  "message": "Empty StreamsByChannelIDsRequest.ChannelIds is required",
  "status": 400
}
```

&nbsp;

`/search/categories` does not suffer from the same issue

**Comment by Xemdo** [comment]
This doesn't seem to be happening anymore. Am getting an empty array:
```
> curl -X GET "https://api.twitch.tv/helix/search/channels?query=querythatdoesnothaveanyresult"
{"data":[],"pagination":{}}
```

If this pops back up, or can be replicated somehow else, let me know and I'll reinvestigate this.
