### ISSUE TITLE
an advertising problem

### ISSUE THREAD

**Issue by bangho486** [twitchdev/issues#706]
**Brief description**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by bangho486** [comment]
I'm definitely subscribing to the broadcast I'm watching, and my manager is also wearing it. But when I watch the show, there are commercials in the middle

**Comment by bangho486** [comment]
I'm definitely subscribing to the broadcast I'm watching, and my manager is also wearing it. But when I watch the show, there are commercials in the middle

**Comment by thedist** [comment]
This is for Twitch Developer issues, not first party issues. Please use [https://help.twitch.tv/](https://help.twitch.tv/) for your issue,.

**Comment by Emilgardis** [comment]
creators can choose if subscribers should see scheduled/manual ads or not, this might be what you're experiencing. See https://help.twitch.tv/s/article/partner-settings-guide#subscriptions
