### ISSUE TITLE
Verified bots can't use bit reward emotes

### ISSUE THREAD

**Issue by cineafx** [twitchdev/issues#71]
**Brief description**
Two verified bots in my own twitch channel cannot use the 1k bit reward emote while my normal viewers who have reached this bit reward tier are able to use the emote.

**How to reproduce**
1. Have a verified bot reach a bit reward tier which got an emote.
2. Make the bot type the emote.

**Expected behavior**
The emote appears in chat.

**Screenshots**
_Bit Badge Reward Tier_ settings:
![image](https://user-images.githubusercontent.com/7873738/75613015-3c334080-5b29-11ea-9228-c276c2deafcb.png)

The 1k bit emote works for normal users: 
![image](https://user-images.githubusercontent.com/7873738/75612956-b0b9af80-5b28-11ea-9f7e-a518a706a058.png)

Both verified bots have the 1k bit badge but can't use the emote:
![image](https://user-images.githubusercontent.com/7873738/75612961-b57e6380-5b28-11ea-905a-c693f1ecbc33.png)

**Additional context or questions**
Both bots reached the 1k tier through the HuntersCheer +20% bit event. 
(`HuntersCheer834 bonus166` = 1000 bits)
Even giving 166 bits separately (so the 1k bits are reached without the bonus) didn't unlock the emote.
![image](https://user-images.githubusercontent.com/7873738/75613173-e2337a80-5b2a-11ea-9b5b-2b80b5340837.png)

**Comment by mauerbac** [comment]
Thanks for the report @cineafx . Submitted internally as MES-5172

**Comment by cineafx** [comment]
The issues seems to be resolved since the full roll out of emote rewards for bits tiers 
![image](https://user-images.githubusercontent.com/7873738/78422577-88116200-7660-11ea-9225-56261ac0bbef.png)

Thank you very much!
