### ISSUE TITLE
Shoutout Create/Recieve - broadcaster_user_id not actually optional?

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#710]
**Brief description**

The docs state that `broadcaster_user_id` is optional.

However the result is `unknown validation error: Key: SubscriptionCondition.broadcaster_user_id' Error:Field validation for 'broadcaster_user_id' failed on the 'required' tag` when omitting a caster ID

for both topics

**How to reproduce**

- Attempt to create a Subscriptiont to shoutout create or receive with _just_ a `moderator_user_id`
- Recieved a HTTP 400 and the above error message

**Additional context or questions**

First Report: https://discuss.dev.twitch.tv/t/new-shoutouts-api-and-eventsub-subscription-types-are-now-in-open-beta/42906/3

**Comment by ecressey** [comment]
Thanks for reporting this. It's a documentation issue - both fields are required. We'll update the docs shortly.

**Comment by jbulava** [comment]
Docs have been updated, thanks!
