### ISSUE TITLE
Start Commercial indicates multiple status codes for the same error

### ISSUE THREAD

**Issue by gmt2001** [twitchdev/issues#712]
**Brief description**
[Start Commercial](https://dev.twitch.tv/docs/api/reference/#start-commercial) lists both **HTTP 400 Bad Request** and **HTTP 429 Too Many Requests** as the response codes for attempting to run a commercial before the cooldown period in _retry\_after_ has expired.

**Expected documentation**
The documentation should only state a single response code for this error, and the API should be set to only return a single response code for this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/3355471/213867951-f2d5309f-2d1e-4688-86c3-847f18f7bc27.png)
![image](https://user-images.githubusercontent.com/3355471/213867959-ddf5d95e-1916-4d8f-9d3f-c37a65472a09.png)

**Comment by Xemdo** [comment]
This is confusing, but correct as far as the API is implemented.
The Start Commercial API calls another service, which can return both 429 and 400 depending on internal context.
