### ISSUE TITLE
google translate chrome-extension can't work well when used alt+t mode

### ISSUE THREAD

**Issue by 01bbbbb** [twitchdev/issues#719]
when i watch with alt+t mode, google translate chrome-extension can't show chat translate.
normal mode it worked well.
i don't know this issue up to you twitch or google chrome or google translate-extension.
if i went wrong place, forgive me, thank you.
![normal mode](https://user-images.githubusercontent.com/121287831/215364978-319217d3-3ba5-4a4a-9768-387b41fbc5e8.PNG)
![google translate option](https://user-images.githubusercontent.com/121287831/215364982-2ad0d70f-b661-46f2-9b38-35e9ea92b783.PNG)

**Comment by BarryCarlyon** [comment]
Sounds like a google translate issue.
Or a twitch first party issue.

Neither of which are handled here on this bug tracker

**Comment by 01bbbbb** [comment]
> Sounds like a google translate issue. Or a twitch first party issue.
> 
> Neither of which are handled here on this bug tracker

so sad.
but i didn't find the way report to twitch first part.
i went to dev.twitch.tv, and it takes me here.

**Comment by Emilgardis** [comment]
https://help.twitch.tv/s/contactsupport

is most likely the place for you

**Comment by BarryCarlyon** [comment]
Twitch will likely bounce it as the problem is a plugin accessing Twitch. Not Twitch itself.

If google finds a problem with how they work and it's a Twitch issue then they'll need to reach out to Twitch. As they are the authors/owners of the project.
