### ISSUE TITLE
Extension popout "by default"

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#72]
**Brief description**

> By default, pop-out control is enabled for panel Extensions and for extension “live configuration views” (see the Live Config Path setting on the Asset Hosting tab in the Extensions manager). 

https://dev.twitch.tv/docs/extensions/required-technical-background

The documentation suggests that extension developers can disable pop-outs. Which is not the case

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: 
 https://twitch.uservoice.com/forums/310213-developers/suggestions/39848359-extension-popout-by-default
