### ISSUE TITLE
Can not register or change applications

### ISSUE THREAD

**Issue by domsson** [twitchdev/issues#720]
**Brief description**

Registering an Application or changing the configuration of an existing application doesn't work anymore. Clicking the `Create` or `Save` button, respectively, doesn't seem to have any effect. The developer console shows a GraphQL related error.

**How to reproduce**

Try to register an application or make a change to an existing application.

**Expected behavior**

The application can be registered/ saved.

**Screenshots**

![image](https://user-images.githubusercontent.com/7917999/215967846-5dbc5659-c085-441d-8948-81f44e0c367a.png)
![image](https://user-images.githubusercontent.com/7917999/215967898-d2d5ed73-1929-4e2e-8486-12ee95ad85dc.png)

**Additional context or questions**

Tried with two different browsers and two different accounts. One combination was previously able to create and edit applications. Issue persists.

**Comment by domsson** [comment]
Sorry, just figured out that this is a duplicate of #634 - closing this one.

**Comment by domsson** [comment]
Actually, just realized the other issue has been closed. so I'm reopening this issue as the error has either resurfaced or not been fixed in the first place.

**Comment by domsson** [comment]
Update: I finally managed to create an application, but it required two steps that are problematic:

- Change category from "Game Integration" to "Website Integration"
- Try different names/titles until I finally go it to work with "Simple But Surely Very Unique Title"

While I personally don't care about the category, needles to say, I don't want to go into production with a title like that. This is therefore _not_ solved. I merely found a _workaround for development_.

**Comment by StEaLtHmAn** [comment]
I am getting the same issue, I was able to create a new application yesterday but today it just returns server error.

**Comment by Xemdo** [comment]
Yes, Twitch cannot be included in the title.
This issue seems related to #735, which was around the same timeframe as this issue. That issue has been resolved, so I'm assuming this has too.

If its still having the same issue please post here and I'll reopen and investigate.
