### ISSUE TITLE
API Endpoint /helix/streams/followed?user_id=<id> returns status code 500 when the user does not follow anyone

### ISSUE THREAD

**Issue by diogoizele** [twitchdev/issues#721]
**Brief description**

When calling the endpoint  /helix/streams/followed?user_id=<**id**>  using the account **id** of a user who does not follow any channel, the api returns 500, this case is not handled

**How to reproduce**

Call the api  /helix/streams/followed?user_id=<id> for a user who doesn't follow any channels

Or simply run this on bash:

```BASH
https -A bearer -a <your access_token> https://api.twitch.tv/helix/streams/followed\?user_id\=<your id account> \
Client-Id:<your client id>
```
**Expected behavior**

It is expected that even if the user is not following any channels, the API will handle this case and return an appropriate message.

**Screenshots**

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/65031832/216776193-76e8b5b0-df17-4637-931e-a216c2b318c6.png">

**Comment by Xemdo** [comment]
This should be fixed now. Closing.
