### ISSUE TITLE
Alot of status code 500 today.. Is it on twitch side?

### ISSUE THREAD

**Issue by DozeX** [twitchdev/issues#725]
Today i getting alot of 500 status code from twitch api. is status code 500 on twitch side?

Itsn't appear everytime, but often, It's appear when i call api for streamers or games from twitch. 

Screenshot attached 

Did developers know this issue already?

![This is an image](<a href="https://imgbb.com/"><img src="https://i.ibb.co/b3VXNTp/status-500-code.png" alt="status-500-code" border="0"></a>)

**Comment by BarryCarlyon** [comment]
Which API endpoints are you calling?

It's unclear from the screenshot if this is a TwitchAPI call failing or the tool/product you are using failing and throwing a 500 back.

The respinse headers do not seem correct for calling the TwitchAPI

**Comment by Xemdo** [comment]
Closing as there's no additional info to this issue. If the issue persists, please reopen with info regarding what API endpoints you are calling,
