### ISSUE TITLE
Unable to create or import extension project in Developer Rig

### ISSUE THREAD

**Issue by larskendall** [twitchdev/issues#727]
**Brief description**
Regardless of whether I try to select and existing extension or create a new one, I get the following error:
`*Sorry, this name is taken. Please try another name. Note: Twitch broadcasters installing your Extension see the name specified in the released version. This is only for API authorization use.`

**How to reproduce**
- Open Developer Rig
- Click "Create Project"
- Select either "New Extension" or an existing extension
- Enter required fields
- Click "Next"
- Observe error

**Expected behavior**
It should advance to the next screen successfully.

**Screenshots**
![Screenshot 2023-02-13 093118](https://user-images.githubusercontent.com/3220897/218529889-708bca3b-1c04-41ed-b412-23419fba80b1.jpg)

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
The developer rig is deprecated.

So Creating is dead and importing mileage may vary

read more: https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995

**Comment by larskendall** [comment]
Got it. Thanks for the quick response!

It would be good to remove the Developer Rig links from the developer console and sample repos at some point,, since they're very misleading right now.

**Comment by jbulava** [comment]
Thanks for the comment and apologies for the confusion.  We should be removing reference of the Developer Rig soon in the documentation and the console.
