### ISSUE TITLE
Developer rig gets 404 when "next" option after selecting extension in the "Create new project" screen

### ISSUE THREAD

**Issue by abenjaminov** [twitchdev/issues#728]
**Brief description**
While i try to create a new project in the rig, after selecting an extension i have already created in the developer console i get an error "name already exists" and when i look in the console i see that a request to the api.twitch.tv got 404

**How to reproduce**
Login in with your twitch credentials to the developer rig
Create a new project
Click "Next"

**Expected behavior**
Will continue to next step

**Screenshots**
![image](https://user-images.githubusercontent.com/9019104/218998222-4875724a-6e36-4163-a294-3de557568752.png)

**Additional context or questions**

**Comment by Emilgardis** [comment]
See https://github.com/twitchdev/issues/issues/727#issuecomment-1428468855

https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995

**Comment by jbulava** [comment]
We will soon be removing mention of the developer rig in the documentation and console as well.  Thanks for adding the context above.
