### ISSUE TITLE
Can't open my last project, can't create a new project, can't delete generated extensions.

### ISSUE THREAD

**Issue by alex-ohadi** [twitchdev/issues#729]
**Brief description**

Hi Im using the developer rig and I can't open my last project with the .json file. It rejects my secret key. Yes i've selected the entire thing and copied in.

 I even tried to create a new project, but each time I create a new project, it says the name of the extension already exists, even if I try some random name with a whole bunch of random letters. Then it will generate that extension in the console somehow.

I even tried to delete this generated extension that was created using the 'new project' button in the developer rig, but now it won't even delete them.

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by alex-ohadi** [comment]
Cant create a new project
<img width="830" alt="Screen Shot 2023-02-17 at 4 45 59 PM" src="https://user-images.githubusercontent.com/16654922/219822120-740c6638-8599-4514-8f8c-fce9969e8ea0.png">

This errors on my secret key
<img width="492" alt="Screen Shot 2023-02-17 at 4 46 31 PM" src="https://user-images.githubusercontent.com/16654922/219822148-5b70fcdc-dbca-467a-b46c-02230cae0f60.png">

It generated it even tho it says I can't use this new extension, and I can't delete it either.
<img width="950" alt="Screen Shot 2023-02-17 at 4 47 59 PM" src="https://user-images.githubusercontent.com/16654922/219822239-4b03aa32-e9ab-43f6-9568-dc530c78f0f0.png">

**Comment by BarryCarlyon** [comment]
The developer rig is deprecated and shouldn't be used.

To delete the new extension, you need to hit manage and give it a version.
Extensions cannot be deleted if the "setup wizard" wasn't completed to give it a version

**Comment by Xemdo** [comment]
Developer Rig has reached end-of-life as of January 31st, 2023. For more information see the announcement here:
https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995
