### ISSUE TITLE
NOTICE display name instead of userlogin

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#73]
**Brief description**

Issues with NOTICE returning display name instead of userlogin

Issue with the following

- VIP a user
- UnVIP a user
- Mod a User
- UnMod a user
- Host notification

Will return the DiSpLaYNaMe instead of login in the success message/notice

**How to reproduce**

VIP a user via not Browser Client and read the result via not Browser Client

Send

> :tmi.twitch.tv PRIVMSG #bluelava :.vip sauyri

Result:

> :tmi.twitch.tv NOTICE #bluelava :You have added 水樹さゆり as a vip of this channel.

**Expected behavior**

> :tmi.twitch.tv NOTICE #bluelava :You have added sauyri as a vip of this channel.

**Additional context or questions**

If you VIP someone, you get the Displayname in the notice.
If you call `.vips` to load all VIPS you get the userlogins
Ditto for mods. So you get a disparity if you are using the success events to add/remove and not periodic checks/reloads of all data

Extent the NOTICE's to include the UserID then it just doesn't matter what name is displayed

Modding `sauyri` via IRC, results in this visible to another mod (ie me):

![image](https://user-images.githubusercontent.com/20999/75802126-19489c80-5d74-11ea-920d-3c48afe2d10d.png)

So the name isn't even shown

**Comment by mauerbac** [comment]
Nice use of @jbulava ! MES-5171

**Comment by TETYYS** [comment]
Same for @msg-id=already_banned, it's impossible to tell if user is already banned

**Comment by BarryCarlyon** [comment]
`.vips` (via TMI) is returning dISPLAy_Names instread of login

`.vips` via Chat (GQL relay) returns logins correctly.

`.mods` is unaffected.

**Comment by Xemdo** [comment]
This issue seemed to only appear when using chat commands over IRC. Since the removal of chat commands over IRC, there appears to be no other NOTICE messages that contain a user's login or display name. Because of that I'll close this out.
