### ISSUE TITLE
Extension Analytics is broken

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#730]
**Brief description**

Theres no graph!
And the [Export All] button is disabled!

**How to reproduce**

Open Dev Console
Click [View Analytics] on a reeleased extension

**Expected behavior**

A Graph!
Ability to download stats from the dashboard

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/219954236-32e19a51-8f04-45ed-9648-71078f2bf420.png)

**Additional context or questions**

I suspect this affects the game dev side of the console as well

**Comment by BarryCarlyon** [comment]
https://dev.twitch.tv/docs/api/reference/#get-extension-analytics

is also HTTP 500-ing

**Comment by Jeroenskii** [comment]
I've the same issue, and it's also reported to happen with the Drops section
