### ISSUE TITLE
Can't access my tax forms

### ISSUE THREAD

**Issue by Jeroenskii** [twitchdev/issues#731]
**Brief description**

Can't access my tax forms anymore. Used to work, but now it doesn't.

**How to reproduce**

Go to https://dashboard.twitch.tv/analytics/revenue-payouts with your financial organization account

**Expected behavior**

We would normally see a dashboard to export our revenue payouts

**Screenshots**

**Additional context or questions**

Your financial account is not a streaming account so it isn't affiliated, so the form is hidden

**Comment by Emilgardis** [comment]
Please file a [Twitch Support ticket](https://help.twitch.tv/s/contactsupport).

This github repository is for third party developers to report bugs, errors and flaws in developer products.

**Comment by Jeroenskii** [comment]
This is a problem that is only occurring for third-party developers. It's really specific. 

A financial organizational account is a mandatory account for third-party developers.
However, the tax form is only visible on the creator dashboard.

Basically, the support team is telling me, this is a developer issue.
And now you are telling me, this is not a developer issue. 

How about working towards a solution? 

You as a third-party developer have the same issue as it's a GLOBAL problem. 

So, maybe help me out and increase the urgency by addressing this issue.

**Comment by Jeroenskii** [comment]
And because the finance organization account is not affiliated, you can't access the right support team.

So I've used my partner account which has access to direct chat support, sending me to the developer support site.

**Comment by Breci** [comment]
I can confirm this issue as well
I do not have an affiliate account so I can't access any of my tax documents anymore as well.

This is only happening to developers, since the change on the dashboard to display the tax info page on the side-menu (dated around February 9)

**Comment by Emilgardis** [comment]
That was not clear to me, but with that context then sure this does maybe belong here.

**Comment by jbulava** [comment]
Hi folks, confirming we see this issue and are inquiring with the creator dashboard team. Most likely a minor logic bug when introducing the new payouts tab to view that page.  Will update when we have more info.

**Comment by jbulava** [comment]
The team has a fix prepared for this issue an we will provide an update here when it is in production. Thanks for your patience.

**Comment by jbulava** [comment]
This issue should now be resolved; please confirm that you can now access https://dashboard.twitch.tv/analytics/revenue-payouts.
