### ISSUE TITLE
View email etc

### ISSUE THREAD

**Issue by YLH-5** [twitchdev/issues#733]
**Brief description** i can't view the epic games gmail that i linked with twitch.

**How to reproduce** i cannot see the gmail i linked to my acount inwhere i can't take actions without knowing the gmail.

**Expected behavior** tips or service on seeing the full email that is linked to my epic games acount which i linked to twitch.

**Screenshots**
![image](https://user-images.githubusercontent.com/126236975/221135737-7bf15247-e576-4a07-97ad-f3e0a7878b10.png)
![Screenshot_20230224_095452](https://user-images.githubusercontent.com/126236975/221135756-4a89a771-e9a2-411e-b394-4bf3646a6c64.png)

**Additional context or questions** How am i able to see the full gmail so i can log into it and take actions

**Comment by BarryCarlyon** [comment]
This is not a problem that the third party bug tracker can help with.

And this is not Epic Games support.

**Comment by Xemdo** [comment]
Closing as this is not a bug related to Twitch's developer products
