### ISSUE TITLE
Can't create secrets

### ISSUE THREAD

**Issue by aSel1x** [twitchdev/issues#734]
**Brief description**
I got error on any changes with extension.
**How to reproduce**

**Expected behavior**
None error on setup, ofc.
**Screenshots**
<img width="1285" alt="Снимок экрана 2023-02-26 в 02 38 06" src="https://user-images.githubusercontent.com/67968946/221384579-44665ef6-9e03-41aa-af91-ca7ccfa78b16.png">
**Additional context or questions**

**Comment by BarryCarlyon** [comment]
Does this extension have at least one version?

**Comment by jbulava** [comment]
As Barry's comment suggests, this issue occurs when an Extension does not have at least one version.  A ticket has been created internally to address this behavior and/or updating the error messaging.
