### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by ai-compatible** [twitchdev/issues#736]
**Brief description**
Slash commands (like /ban, /slow, /subscribers) no longer work. Chat text works fine.

**How to reproduce**
Using the very old IRC way of communicating to the channel.  Not sure how to explain to reproduce short of writing code?

**Expected behavior**
That the / commands worked as before. They have always worked, worked as of 4 days ago (2/22/.23) and since at least 2/25/23, have not.

**Screenshots**

**Additional context or questions**
Apologies for not being savvy about Github.  I was trying to do a search for a recent change at Twitch but ended up starting this report.

**Comment by iProdigy** [comment]
See https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc
