### ISSUE TITLE
channel.charity_campaign.donate - malformed notification payload example

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#738]
**Brief description**
https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelcharity_campaigndonate event payload has fields named `broadcaster_user_*` instead of `broadcaster_*`

the [event spec](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#charity-donation-event) uses `broadcaster_*`

**Screenshots**
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1502855/222927594-1368ac6c-1f13-4909-89b4-4d3a7c41f314.png">

**Additional context or questions**

**Comment by iProdigy** [comment]
Event spec is likely wrong rather than the example notification... CLI thinks the same: https://github.com/twitchdev/twitch-cli/blob/main/internal/models/charity.go#L14

**Comment by Xemdo** [comment]
Noticed this while going through everything for the CLI again.
broadcaster_user_id is correct. Docs are incorrect.

**Comment by Xemdo** [comment]
Documentation has been corrected
