### ISSUE TITLE
requestIdShare/manage access broken on video Extensions

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#74]
**Brief description**

At some point between March 3rd 2:30pm UTC and now.

requestIdShare and manage access stopped working for Video Extensions.

Viewers cannot grant or revoke ID sharing to an extension

Issue confirmed for extensions in

- Localtest
- Hosted test
- In review
- LIVE/released

In some cases Manage Access doesn't even appear

**How to reproduce**

Have a video extension in any state, that uses request ID sharing from the user

**Expected behavior**

it to allow the user to grant/revoke access to their ID

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/75878932-52cfe500-5e12-11ea-8710-273c3555192b.png)

**Additional context or questions**

Initial report

https://discordapp.com/channels/504015559252377601/523676096277905419/684627058445516850

Probably broke with a deploy at midnight UTC as it was working when I submitted an extension for review yesterday, but not today/time of writing

**Comment by jbulava** [comment]
The issue has been found and a fix should be going into today's deployment. Will follow up when in production.

**Comment by BarryCarlyon** [comment]
Twitch have now fixed this issue!
