### ISSUE TITLE
Can't subscribe to `channel.follow` events for specific user

### ISSUE THREAD

**Issue by adamelmore** [twitchdev/issues#740]
**Brief description**
I can't subscribe to `channel.follow` events for my user (adamdotdev) despite being positive that I've gone through all of the necessary steps (including going through the oauth flow for this user to grant all scopes for this clientId). I can subscribe to any other event, but `channel.follow` returns with `{"error":"Forbidden","status":403,"message":"subscription missing proper authorization"}`. I've tried multiple apps/clientIds and it fails with the same error for both webhook vs web socket connections.

**How to reproduce**
Try to create a `channel.follow` event subscription for user `807917692` (adamdotdev).

**Expected behavior**
Should create the subscription successfully.

**Screenshots**

**Additional context or questions**

**Comment by iProdigy** [comment]
You will need to use version 2 of `channel.follow` (which requires the target user to auth with your application with the `moderator:read:followers` scope). Twitch shutdown version 1 access without prior notice for all client_id's that were not using `channel.follow` on the arbitrary date of February 17th.
