### ISSUE TITLE
extension analytics page is bugged

### ISSUE THREAD

**Issue by Jeroenskii** [twitchdev/issues#742]
**Brief description**

The extension analytics page is bugged, showing an incorrect display of the data

**How to reproduce**

At first sight, there is an immediate visual change as the graphs are replaced by dots (but this could also be a recent update).
If you change the date range, e.g. 30 days, the data gets weird and incorrect (where was the amount of viewers is now USD)

**Expected behavior**

Show me data

**Screenshots**

![image](https://user-images.githubusercontent.com/115532548/223640034-aac61c81-bd7b-4187-a5c6-e2511358420e.png)

**Additional context or questions**

started on 06-03-2023

**Comment by streamstickers** [comment]
Also seeing mismatches where you select data points like 'Bits Revenue' and the hover overlay shows as 'Unique Viewers'

![image](https://user-images.githubusercontent.com/64783296/225027244-efa5a9b7-b394-4866-af4a-ba1157333350.png)

**Comment by Jeroenskii** [comment]
This problem is still ongoing and it's annoying. @jbulava

**Comment by Ravenbtw** [comment]
Same issue here!

**Comment by Xemdo** [comment]
Tracking internally as ANC-3173.

**Comment by Xemdo** [comment]
Resolved as of today
