### ISSUE TITLE
Creating / Using projects with Developer Rig is broken

### ISSUE THREAD

**Issue by mrgmnn** [twitchdev/issues#745]
**Brief description**
I tried using existing extensions and tried creating a new one from the developer rig. 
When trying to use an existing one I receive the following error message: *Sorry, this name is taken. Please try another name. Note: Twitch broadcasters installing your Extension see the name specified in the released version. This is only for API authorization use.

When creating a new one from the rig I receive the same error message but the extension has been created in my dev console while not being able to remove it again, leaving me with broken extensions

**How to reproduce**
See above

**Expected behavior**
Using extensions should be possible and creating new ones should not leave me with broken extensions in my dev console

**Screenshots**
![image](https://user-images.githubusercontent.com/55926442/226471971-1cfa0179-9eed-49cb-bb0a-2e69587bf190.png)

**Additional context or questions**

**Comment by Emilgardis** [comment]
the rig is eol, which is why this is happening
https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995

> New projects will no longer be able to be created for an existing Twitch Extension.

**Comment by BarryCarlyon** [comment]
> When creating a new one from the rig I receive the same error message but the extension has been created in my dev console while not being able to remove it again, leaving me with broken extensions

An extension requires _at least_ one version before it can be deleted.
And the Rig is failing on step 2 of the wizard to create an extension. Which is what you have observed.

**Comment by Xemdo** [comment]
Developer Rig has reached end-of-life as of January 31st, 2023. For more information see the announcement here:
https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995
