### ISSUE TITLE
Non user_id's to /moderation/bans returns status code 500

### ISSUE THREAD

**Issue by MrAuro** [twitchdev/issues#746]
**Brief description**
If anything but a user id is sent to /moderation/bans for banning a user, an error 500 is returned.

**How to reproduce**
`POST /moderation/bans?broadcaster_id=12345&moderator_id=12346`
```json
{
	"data": {
		"user_id": "anything",
		"reason": "this will return 500"
	}
}
```

returns

```json
{
    "error": "Internal Server Error",
    "status": 500,
    "message": ""
}
```

**Expected behavior**
Should return status code 400, stating the user_id is not a user_id

**Screenshots**
![image](https://user-images.githubusercontent.com/35087590/227752768-2bbe2bae-a5e0-4b7c-bb0f-444275273424.png)

**Comment by Xemdo** [comment]
Seems to be working fine now, and returns HTTP 400:

```
> curl -X POST "https://api.twitch.tv/helix/moderation/bans?broadcaster_id=57047445&moderator_id=57047445" \
-H "Content-Type: application/json" \
-d '{"data": {"user_id":"anything","duration":300}}'
{"error":"Bad Request","status":400,"message":"One of broadcaster ID, user ID or the moderator ID is invalid."}
```
