### ISSUE TITLE
Clicking submit button multiple times when creating a reward creates multiple 'ghost' rewards with 0 minute watch time

### ISSUE THREAD

**Issue by DeviNoles** [twitchdev/issues#752]
**Brief description**
I was creating a new campaign for my org's drops on the dev.twitch.tv site and the create drop was taking a little while so I spammed the button and created multiple drops at once.
**How to reproduce**
Create a new drop and click the submit button rapidly.
**Expected behavior**
I expected it to create 1 drop 'Draken Wings' as a conditional drop but it also created multiple independent drops with 0 minute watch time.
**Screenshots**
![image](https://user-images.githubusercontent.com/24501975/231209933-65329e51-8968-4a47-8eab-b3542b098310.png)

**Additional context or questions**
It was set to be a conditional drop.

**Comment by Xemdo** [comment]
This shouldn't happen anymore as conditional drops were removed, but if it reappears we can reinvestigate this.
