### ISSUE TITLE
404's that masquerade as 503's loop detected

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#758]
**Brief description**

It seems to do a recent change, that if you call an invalid root url of the API sub domain
You get a 5xx error instead of a 404
Or you can the olde

> Same machine same service in the most recent hop on cache-bfi-kbfi7400082-BFI: SGj18tAbbQbdBUVl12BG1r55Xu0ftmhaE24xEEYlLDo!LCY!cache-lcy-eglc8600047-LCY, SGj18tAbbQbdBUVl12BG1r55Xu0ftmhaE24xEEYlLDo!BFI!cache-bfi-kbfi7400082-BFI

**How to reproduce**

Call - https://api.twitch.tv/fred/
Call - https://api.twitch.tv//helix/streams

**Expected behavior**

404 Not Found

**Additional context or questions**

https://discord.com/channels/504015559252377601/523675960797691915/1096344720650809395

**Comment by Xemdo** [comment]
This is expected behavior and is not planned to change.
