### ISSUE TITLE
hlsLatencyBroadcaster on IOS

### ISSUE THREAD

**Issue by cylwin** [twitchdev/issues#76]
**Brief description**
On IOS only, it's impossible to get the hlsLatencyBroadcaster value. It's working on desktop and Android.
**How to reproduce**
window.Twitch.ext.onContext(function(context){
and display context on IOS.
**Expected behavior**
onContext should return hlsLatencyBroadcaster in the context object.
**Screenshots**
![Screenshot_20200309-193449](https://user-images.githubusercontent.com/6231358/76261154-ae0e3700-6259-11ea-8f22-e0f3ff19e87a.png)

**Additional context or questions**

**Comment by mauerbac** [comment]
Thanks @cylwin - submitted under GQL-939

**Comment by squirelo** [comment]
Hi @mauerbac, any news on this? I work with @cylwin. It has been now 3 months that our product is not working on mobile because of this, and our client Red Bull start loosing patience. Thanks a lot

**Comment by matthewiiv** [comment]
@cylwin @squirelo did you find an alternative?

**Comment by cylwin** [comment]
@matthewiiv No we didn't. We put a 10s timeout instead...

**Comment by Xemdo** [comment]
This was fixed in the Twitch iOS app release on November 4th 2020.
Closing as it seems to never have come back up since then.
