### ISSUE TITLE
Attempting to delete a deleted video 401's instead of 404's

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#77]
**Brief description**

I deleted video of ID `525742355` forgot that I had done this so went to delete it again.

The API returned a 401 instead of a 404

(I then went off and started debugging my token and code, and of course there was none)

```
401
{"error":"Unauthorized","status":401,"message":"{\"error\":\"You are not authorized\",\"message\":\"You are not authorized\",\"status\":401}"}
```

**How to reproduce**

Try Delete a video you already deleted

**Expected behavior**

Don't throw a 401.

**Additional context or questions**

https://dev.twitch.tv/docs/v5/reference/videos#delete-video

**Comment by h1z1** [comment]
Funny little error, I've hit this before and with other endpoints.  Just assumed it was because the operations are not atomic and were hitting different cluster nodes?

**Comment by mauerbac** [comment]
thanks! submitted -> GQL-939

**Comment by jbulava** [comment]
Closing since v5 is no longer available.
