### ISSUE TITLE
low_trust_user_treatment_update is missing usernames

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#775]
**Brief description**

In `low_trust_user_treatment_update`, `target_user_id` is populated, but **`target_user` is just an empty string**.

Similarly, `updated_by.id` is populated, but `updated_by.login` & `updated_by.display_name` are empty strings, which also applies to `low_trust_user_new_message`.

This regression appears to have started in the last couple days

**How to reproduce**

1. Listen to `low-trust-users` pubsub topic
2. Restrict/monitor a user
3. Observe that `low_trust_user_treatment_update` message does not contain usernames

**Expected behavior**

`target_user`, `updated_by.login`, `updated_by.display_name` should be populated with the relevant names, not empty strings.

**Additional context or questions**

Example payload I received upon doing `/monitor djclancy`:

```json
{"type":"MESSAGE","data":{"topic":"low-trust-users.53888434.53888434","message":"{\"type\":\"low_trust_user_treatment_update\",\"data\":{\"low_trust_id\":\"53888434.268669435\",\"channel_id\":\"53888434\",\"updated_by\":{\"id\":\"53888434\",\"login\":\"\",\"display_name\":\"\"},\"updated_at\":\"2023-05-14T01:42:09Z\",\"target_user_id\":\"268669435\",\"target_user\":\"\",\"treatment\":\"ACTIVE_MONITORING\",\"types\":[\"MANUALLY_ADDED\"],\"ban_evasion_evaluation\":\"\",\"evaluated_at\":\"0001-01-01T00:00:00Z\"}}"}}
```

&nbsp;

Beyond annoying third parties, this bug also has ramifications for first-party chat; now mods looking at chat don't see when other mods restrict/monitor/unrestrict/unmonitor another user. (they *can* however see these events in the moderator view activity feed, which uses a separate undocumented pubsub topic)

**Comment by Xemdo** [comment]
This should be resolved now. If the issues pops up again at all please reopen.
