### ISSUE TITLE
Get Extension Analytics is dead - HTTP 500

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#776]
**Brief description**

My daily job for collecting analytics is recieving a HTTP 500 instead of data

**How to reproduce**

Call Get Extension Analtics for a released extension

**Expected behavior**

Links to CSV's

**Additional context or questions**

First report: https://discuss.dev.twitch.tv/t/error-500-internal-server-error/45698/

Also may have been broken since February 23rd....

**Comment by MeloFuccio** [comment]
How am i supposed to get some analytics if not in this way? 

How is this a problem since February 23rd ?

**Comment by BarryCarlyon** [comment]
If no one noticed, then no one reported.
My system that pulls data, doesn't have a "oh it's broken" thing.

> How am i supposed to get some analytics if not in this way?

Manually from, the Dev Console: https://dev.twitch.tv/console/extensions

The "Export All" button:

![image](https://github.com/twitchdev/issues/assets/20999/bd56e9d9-0771-46b9-8c9e-78e1cbd146f2)

**Comment by MeloFuccio** [comment]
Im the same guy who did the forum post.

Btw, i need to take files automatically and constalty , becouse im doing a university project of data ingestion,streaming etc.. ( Logstash, Kafka, Spark, ESC, etc..)

Cant do it manually, or even tho it sucks a lil bit.

**Comment by BarryCarlyon** [comment]
> Btw, i need to take files automatically and constalty , becouse im doing a university project of data ingestion,streaming etc.. ( Logstash, Kafka, Spark, ESC, etc..)

This endpoint only works if you _own_ the extension.

If you don't own the extension(s) you cannot get the analytics

**Comment by jbulava** [comment]
Tracking internally as HLX-3087.

**Comment by Xemdo** [comment]
This has since been resolved.
