### ISSUE TITLE
Update Guest Star Slot Settings URL is wrong

### ISSUE THREAD

**Issue by Katzen48** [twitchdev/issues#778]
**Brief description**
The URL for [``Update Guest Star Slot Settings``](https://dev.twitch.tv/docs/api/reference/#update-guest-star-slot-settings) in the docs is wrong.
It seems to have been copy-pasted from [``Update Guest Star Slot``](https://dev.twitch.tv/docs/api/reference/#update-guest-star-slot).

**Expected documentation**
The documented URL for [``Update Guest Star Slot Settings``](https://dev.twitch.tv/docs/api/reference/#update-guest-star-slot-settings) should be corrected to ``https://api.twitch.tv/helix/guest_star/slot_settings``.

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/19516002/f7deb9a9-0836-4642-9119-0be2e0102b9b)
[*Update Guest Star Slot Settings*](https://dev.twitch.tv/docs/api/reference/#update-guest-star-slot-settings)

![image](https://github.com/twitchdev/issues/assets/19516002/5a0cfb2e-7a87-46b6-8d92-528c68c7c8e9)
[*Update Guest Star Slot*](https://dev.twitch.tv/docs/api/reference/#update-guest-star-slot)

**Additional context or questions**

**Comment by starrrsky** [comment]
Fixed in ASYNC-3719
