### ISSUE TITLE
`500` response on unauthorized Shoutout request

### ISSUE THREAD

**Issue by Felanbird** [twitchdev/issues#779]
**Brief description**
When sending a shoutout request on behalf of a user you do not moderator for, Helix returns a 500 with no error.

**How to reproduce**
1. Set the `from_broadcaster_id` to a user you are not a moderator for
2. Set the `to_broadcaster_id` to whoever and the `moderator_id` to your id
3. Send request
4. `500`

**Expected behavior**
`403`

**Screenshots**
![EpicPen_2023-05-15_11-04-47](https://github.com/twitchdev/issues/assets/41973452/63eee1a3-e3cd-467e-b4b6-3554ecdfd967)

**Additional context or questions**

I made sure to test this while using a `to_broadcaster_id` who was actually live, same result.

**Comment by Xemdo** [comment]
Cant reproduce this. Was this still occurring on your end?

My test:
```
> curl -X POST "https://api.twitch.tv/helix/chat/shoutouts?from_broadcaster_id=105458682&to_broadcaster_id=11148817&moderator_id=57047445"
{"error":"Bad Request","status":400,"message":"The requesting user must be a channel moderator."}
```

**Comment by Felanbird** [comment]
Seems it was fixed, I just ran that same script again and it returns a 400 now 👍
