### ISSUE TITLE
"users/blocks" service corruption - episode 2

### ISSUE THREAD

**Issue by Durss** [twitchdev/issues#787]
**Brief description**
Basically the same as what's described on this previously fixed issue, but it's crashing again
https://github.com/twitchdev/issues/issues/639

**How to reproduce**
Call the endpoint `helix/users/blocks` in PUT with `target_user_id=blablabla`. _(i get a 200 as if everything went fine)_
Call the endpoint `helix/users/blocks` in GET, you'll get a 500.
To make the service back we need to call the endpoint with DELETE method and the exact same wrong `target_user_id` provided before. Only then the GET endpoint will work again.
If, like I, you forgot which wrong data you sent before, you basically cannot get the service working back.

Query example that corrupts the service
```javascript
fetch("https://api.twitch.tv/helix/users/blocks?target_user_id=427acf39-21dc-4a5f-b6dd-bbfd5456a41d", {
  "headers": {
    "authorization": "Bearer {BEARER_TOKEN}",
    "client-id": "{YOUR_CLIENT_ID}",
    "content-type": "application/json",
  },
  "body": null,
  "method": "PUT",
});
```

**Expected behavior**
Calling the endpoint with a wrong user ID should yield an error.

**Screenshots**

**Additional context or questions**

**Comment by Durss** [comment]
If that can be of any interest, i no longer have a 500 when calling the GET users/blocks endpoint.

**Comment by brian6932** [comment]
I am no longer getting this either, seems like it's fixed

**Comment by Durss** [comment]
I made some test trying to block wrong user IDs, the PUT service returns a 204 like everything went OK which doesn't feel right, but the GET endpoint isn't corrupt anymore after that.

Documentation does not specifies what the HTTPS status response should be if the target_user_id isn't valid so technically, even though I believe it would make sense to return a 400, it works the expected way.
