### ISSUE TITLE
Wrong shoutout cooldown

### ISSUE THREAD

**Issue by Durss** [twitchdev/issues#788]
**Brief description**
The documentation states that:
```
Rate Limits: The broadcaster may send a Shoutout once every 2 minutes. They may send the same broadcaster a Shoutout once every 60 minutes.
```
But the 60min limit doesn't seem to be reflected on the API.
This limitation seems to be set only by the twitch chat client, but even there, i managed to send a second SO to the same user like 8min after the first one instead of 60min.

**How to reproduce**
Send a SO to user 123456, wait 2min, send another SO to 123456, the shoutout is properly sent.
Twitch client shows the SO popup and an event is received from eventsub.

**Expected behavior**
The 2nd SO shouldn't be sent and the API should return a 429 status code

**Comment by Xemdo** [comment]
Ticketed internally as VXD-3242

**Comment by Xemdo** [comment]
Issue has been resolved. You shouldn't be able to run helix/chat/shoutouts as frequently anymore. Both the 2 minute cooldown and the 60 minute cooldown apply.
