### ISSUE TITLE
Broadcast URLs and Stream Keys - improve clarity

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#790]
**Brief description**

Add a link to the refrence guide for Get Ingest Servers from the _base_ Guide to improve clarity

**Expected documentation**

- <ingest-server> identifies a specific Twitch server that receives this broadcast stream; e.g., sfo.contribute.live-video.net. [Reference](https://dev.twitch.tv/docs/video-broadcast/reference/#get-ingest-servers)

**Comment by Xemdo** [comment]
Updated it as requested.
Also while I was there I updated the broadcast test documentation.
