### ISSUE TITLE
Смена почты

### ISSUE THREAD

**Issue by mortemfake** [twitchdev/issues#796]
I have an account on the mortemfake twitch, on the mail roffles.zhuk.228@mail.ru , I want to change this mail to my main one kiril.zhuk.03@mail.ru , but an account is registered to this mail, this mail is 100% mine, so I ask you to delete that account or change my mail from roffles.zhuk.228@mail.ru on kiril.zhuk.03@mail.ru .

**Comment by thedist** [comment]
This is a developer Github repo, no one here can assist you with account related issues. Please contact Twitch Support [http://link.twitch.tv/help](http://link.twitch.tv/help)
