### ISSUE TITLE
Documentation Issue in Twitch API's Charity Campaign EventSub Subscription

### ISSUE THREAD

**Issue by MrSniFo** [twitchdev/issues#799]
When creating an EventSub subscription for a charity campaign, the documentation states that the version parameter should be set to "1". However, the correct value for the version parameter is "beta" to ensure compatibility with the subscription request.

**Screenshots**
https://i.imgur.com/EYBrItY.png
https://i.imgur.com/yFIZEZf.png

**Edit**
Using: twitch-cli/1.1.19

**Comment by Emilgardis** [comment]
I think this is backwards, the event is not in beta anymore, so the field should be set to `1`

`channel.charity_campaign.donate.version` should be `1` not `beta`

<img width="960" alt="image" src="https://github.com/twitchdev/issues/assets/1502855/83761d9b-4d7c-4700-b652-19fb914ae7a8">

<img width="517" alt="image" src="https://github.com/twitchdev/issues/assets/1502855/699a7880-cdb7-4326-be31-6981a2e0b05a">

**Comment by MrSniFo** [comment]
I'm getting BadRequest error if I use version 1

**Comment by Xemdo** [comment]
This was an issue with Twitch CLI that should be resolved in 1.1.20
