### ISSUE TITLE
Get Broadcaster Subscriptions Events

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#8]
**Brief description**

The subscription events API is documented as a Webhook topic. but not as a API Endpoint

https://dev.twitch.tv/docs/api/webhooks-reference#topic-subscription-events

It used to be in the documentation but is missing

**Expected documentation**

https://dev.twitch.tv/docs/api/reference#get-broadcaster-subscriptions

But for 
https://dev.twitch.tv/docs/api/reference#get-broadcaster-subscriptions-events

**Comment by jbulava** [comment]
Moved to UserVoice as the preferred feedback method for docs: https://twitch.uservoice.com/forums/310213-developers/suggestions/39847468-get-broadcaster-subscriptions-events

**Comment by jbulava** [comment]
Checking if this is intended.

**Comment by BarryCarlyon** [comment]
Given the announced "death" of websub this issue is no longer relevant (or worth fixing)

Superseeded by eventsub 🎊
