### ISSUE TITLE
Allowlist for URL Fetching Domains are not saved correctly

### ISSUE THREAD

**Issue by Stas-Buzunko** [twitchdev/issues#800]
**Brief description**
i set Allowlist for URL Fetching Domains to my URLs click on save changes -> Save button turns green, network request returns 200 but when I click on Status "Your change has not been saved. Are you sure you want to leave?" pops up. and when I load my extension I get Content Security Policy error as if my URL wasn't saved.
**How to reproduce**

**Expected behavior**

**Screenshots**
<img width="817" alt="Screenshot 2023-06-19 at 12 30 04 PM" src="https://github.com/twitchdev/issues/assets/12331100/eaea6c1c-7a33-4314-a8f9-d5eefc1a8ff7">
<img width="1440" alt="Screenshot 2023-06-19 at 12 29 33 PM" src="https://github.com/twitchdev/issues/assets/12331100/da8bc3ac-fc4c-4b3e-a1f9-0916312f4210">
<img width="1440" alt="Screenshot 2023-06-19 at 12 29 05 PM" src="https://github.com/twitchdev/issues/assets/12331100/4f818fdf-a13c-48e8-9506-2d6c41c54ac7">

**Additional context or questions**
Extension ID ig8msgak1swodrdilr3y0zhggbz9gk

**Comment by Stas-Buzunko** [comment]
if Allowlist for URL Fetching Domains is empty -> local test produces error
if I fill in URLs -> local test works fine
if I move to hosted test -> I get the same error as when allowlist is empty

**Comment by Stas-Buzunko** [comment]
It behaves differently when using localhost and when hosted on a test server. it works totally fine on a local server and doesn't work when moved to a hosted one. That's what makes it super confusing. @BarryCarlyon

**Comment by Stas-Buzunko** [comment]
for other firebase people coming here if you use Realtime database then you need to **forceWebSockets(true)**
if you use firebase auth then there is no way to get it working from what I've read on twitch forum and their discord server

**Comment by BarryCarlyon** [comment]
Localhost doesn't apply the CSP unless your configure your "server" to apply CSP headers.

I use nodeJS middleware for my static express server that hosts my extensions in localhost to inject CSP for optimal testing, as then I also have the middleware spit out a CSP report when CSP is violated.

https://github.com/BarryCarlyon/twitchextensioncsp

For CSP the "server" sets the CSP, in localhost the server is controlled by you so CSP doesn't exist unless you make it exist.
In hosted and above it's Twitch's server so CSP is applied by Twitch.

I also wrote about CSP here -> https://barrycarlyon.co.uk/wordpress/2021/11/21/twitch-extensions-part-6-dev-environment-updates-content-security-policy/
