### ISSUE TITLE
New Content Restrictions - home button

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#802]
**Brief description**

if I open a stream that is mature in an embed, when I click go home you get a page of doom

**How to reproduce**

Embed a stream that has the new mature flag enabled
In this example Strippin is playing the Mature game FFXVI

![image](https://github.com/twitchdev/issues/assets/20999/8b177ab3-39aa-4517-8029-1f9bf4acb0ee)

Click [Go Home]

![image](https://github.com/twitchdev/issues/assets/20999/aacd4311-3d35-4a90-b36e-19bdec75e5df)

**Expected behavior**

No home button all

**Comment by jbulava** [comment]
Ticketed internally as VXD-3086.

**Comment by jbulava** [comment]
This issue should be fixed!
