### ISSUE TITLE
Incorrect information on Getting the broadcaster’s streaming schedule

### ISSUE THREAD

**Issue by ItsTeraBytes** [twitchdev/issues#805]
**Brief description**
The docs mention that when the broadcaster doesn't have anything scheduled, it will return a 404 Not Found HTTP status code. But during testing it returns a 200 OK HTTP status code and instead returns segments as null.

**Expected documentation**
Replace "the request returns an HTTP 404 Not Found status code." with "the JSON output will return segments as null."

**Screenshots**
![chrome_QmzkBjYwRL](https://github.com/twitchdev/issues/assets/88017555/0dda4726-bf88-4e99-b83b-1bfa90d82de3)
![Insomnia_DEokn2cS9t](https://github.com/twitchdev/issues/assets/88017555/9e3cd3bc-5c46-461f-a373-7ed39161a27d)

**Additional context or questions**
None

**Comment by Emilgardis** [comment]
this has been reported in #422 as a bug/error but this describes the inconsistency in the doc

**Comment by Xemdo** [comment]
Unable to replicate this. Seems to be returning 
```
$ twitch api get schedule -q broadcaster_id=57047445
{
  "data": [],
  "error": "Not Found",
  "message": "schedule was not found",
  "status": 404
}
```

If you can replicate it, please reopen this and leave the steps to reproduce.
