### ISSUE TITLE
Chat history is populated by chat done in channels with upper case characters in them

### ISSUE THREAD

**Issue by Varonth** [twitchdev/issues#807]
**Description**
As of now, all chats on twitch use all lower case for the IRC channel, and a IRC channel with upper case characters are different.
If a bot or another 3rd party application joins a channel with upper case letters, the messages are not going to show up in the chat on twitch. Neither viewer, nor moderators or streamers will see those messages.
These messages send to the wrong channel are still going to show up in the chat history if the chat is reloaded.
For example a chat message send to #varonth will show up in twitches chat as expected, a message to #Varonth will not, but the message send to #Varonth will show up in the history if the page is reloaded.

**Expected behavior**
Chat history should only use the original channels messages, not messages send to channels which have upper case characters in them.

**How to reproduce**

1. Have a twitch page with chat open
2. Have a third party application authenticate and join a chat channel with the same characters, where atleast on of them is in upper case
3. Send a message via the third party application as a normal PRIVMSG
4. Message should not show up in twitch chat
5. Reload the twitch page
6. Message should now show up in the chat history

**Additional context or questions**
This can be abused by bad actors to spam racists, homophobic, transphobic... you name it... messages that neither the streamer nor the moderators would be aware are visible to new people joining into the chat.
And even if, they have no actual way of handling this, as the spammer would technically not even be in their chat so they cannot even get banned from the channel.

**Comment by iProdigy** [comment]
This has been fixed (messages are forwarded to the lowercase chatroom)

**Comment by Varonth** [comment]
Can confirm that messages to permutation of different upper and lower case channels are now all send to the correct lowercase only channel.
