### ISSUE TITLE
Domain fon.bet doesn't work with embed

### ISSUE THREAD

**Issue by ttazhetdinov** [twitchdev/issues#810]
**Brief description**
I'm trying to use the following link (as an example) to embed video on my website:
https://player.twitch.tv/?autoplay=true&channel=blastpremier&controls=false&muted=false&parent=fon.bet
And I'm getting an error: [FailedAttributeCheck] mandatory requirements were not met
So, this link doesn't work even if I try to open it directly in web-browser
But if I replace domain to anything else - the link starts working. For example:
https://player.twitch.tv/?autoplay=true&channel=blastpremier&controls=false&muted=false&parent=test.com
**How to reproduce**
1. Copy the link https://player.twitch.tv/?autoplay=true&channel=blastpremier&controls=false&muted=false&parent=fon.bet
2. Paste it into web-browser
3. Press Enter
**Expected behavior**
The translation opens
**Screenshots**
<img width="1727" alt="image" src="https://github.com/twitchdev/issues/assets/140180207/177a0da3-df6e-4510-a234-87c57bfc9f57">
<img width="1720" alt="image" src="https://github.com/twitchdev/issues/assets/140180207/d1292e99-7c97-4501-b35a-bc449791462e">
<img width="1728" alt="image" src="https://github.com/twitchdev/issues/assets/140180207/ca88e7c1-a11a-4a1d-b20d-cc634dddec71">

**Additional context or questions**

**Comment by iProdigy** [comment]
The `.bet` TLD doesn't seem to be supported (and I doubt Twitch wants their embeds on betting/gambling websites)

**Comment by ttazhetdinov** [comment]
But if I replace fon.bet to something else with .bet (for example, anything.bet : https://player.twitch.tv/?autoplay=true&channel=blastpremier&controls=false&muted=false&parent=anything.bet) it still works
So the problem is in specific domain...

**Comment by iProdigy** [comment]
it appears your domain has been denylisted then

**Comment by Xemdo** [comment]
For embed issues on specific domains, please reach out to developers@twitch.tv
