### ISSUE TITLE
Lifecycle of a EventSub beta only accounts for v1

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#815]
**Brief description**
[Eventsub: Subscription Types](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#public-beta-program) and [Product Lifecycle](https://dev.twitch.tv/docs/product-lifecycle/#api-endpoint-and-subscription-classifications) say that a EventSub `beta` goes into `v1`. This is not strictly true, it can go into any version, not just `v1`

**Expected documentation**

> Unless otherwise noted, EventSub subscriptions that were released as a public beta will be available for 30 days after their version is active and generally available. Subscriptions should be updated to the new version during this timeframe to continue its functionality. Any active beta subscriptions beyond 30 days will be automatically deleted.

**Additional context or questions**

This happened with `v2` of `channel.update`

**Comment by starrrsky** [comment]
Thank you for the suggestion! This has been incorporated into the docs.
