### ISSUE TITLE
Cannot test an extension on iPad

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#819]
**Brief description**

The "this extension is in test mode click here to accept" button is misaligned and cannot be clicked/touched

The alignment is not that good on mobile tbh either

**Screenshots**

![IMG_C5DE2F05B161-1](https://github.com/twitchdev/issues/assets/20999/ad3f30f9-819c-4974-925b-df3706abb8eb)

**Comment by BarryCarlyon** [comment]
iOS layout for comparion
You can get to the button but not the text thats above the button with the warning

![IMG_0718](https://github.com/twitchdev/issues/assets/20999/adb5068a-e585-4b7b-bee3-51d25adf49bd)

**Comment by jbulava** [comment]
Ticketed internally as ANC-3190.

**Comment by jbulava** [comment]
This issue has been addressed and should be in a future mobile release soon. Keeping the issue open until it is in production.

**Comment by Xemdo** [comment]
This fix has been pushed to production, which should resolve the issue.
