### ISSUE TITLE
Extensions Creator dashboard "zone picker" on top of "active dialog"

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#821]
**Brief description**

If a streamer puts an extension into a slot.
The slot picker is on top of the "yay you did this" dialog

**How to reproduce**

activate an extension into a slot, via the dashboard

**Screenshots**

![image](https://github.com/twitchdev/issues/assets/20999/12329b3e-d499-475e-9084-97c25593ed09)

![image](https://github.com/twitchdev/issues/assets/20999/f577cca3-347d-430b-8f73-8fb78440032c)

**Comment by TristanWiley** [comment]
This should be fixed tomorrow
