### ISSUE TITLE
Moderators are not removed from /helix/moderation/moderators when timed out

### ISSUE THREAD

**Issue by EthanBlaisAlarms** [twitchdev/issues#823]
**Brief description**
If a moderator is timed out, whether that is via the helix API or from Twitch itself, sending a request to /helix/moderation/moderators still returns their user information, even though they are not a moderator.

**How to reproduce**
Time out a moderator, send a GET request to /helix/moderation/moderators, response body still includes their user ID, login name, and display name.

**Expected behavior**
The timed-out user won't be included in the response body

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/58613819/301b0507-6c49-41f1-98c1-68109b8f8239)

**Additional context or questions**
Whenever a moderator is timed out, timing out another mod will actually remove them.
![image](https://github.com/twitchdev/issues/assets/58613819/6ebfb01e-6342-4aea-bdd5-5658251edd6b)
(The above screenshot was taken while the account "fireboy65442" was not a moderator. After also timing out one of my accounts, his account was removed from the response while mine still stayed.)

**Comment by BarryCarlyon** [comment]
I suspect caching is in play.
It seems you did a timeout at 01:11:30 and then Instantly checked the Moderators API at 01:11:30

Recheck you test scenrio

By doing the timeout
waiting a second or two and _then_ checking Get Moderators.

I suspect that the interal systems had not percolated the moderator removal _quite yet_ becuase you did "get moderators" too quickly after wacking the moderator based on the presented screenshot/timestamps

This smells of caching or "just too quick"

**Comment by EthanBlaisAlarms** [comment]
My script sends the request every 5 seconds (and temporarily prints the output to the console).
During testing, it continued to return a timed-out moderator for at least 5 minutes after timing out (that's the longest time I ran the test), and likely much longer since I had a moderator get timed out by a chat game and several minutes later, could not be re-modded since the bot thought they were already modded. In addition, this does not happen if I unmod them instead of timing them out.

A temporary workaround that is working is that I have the bot send an unmod request whenever a user is timed out. That seems to properly work.

I also feel like this is a bug with Twitch because I later discovered that the timed-out mod still shows up as a mod in my Twitch creator dashboard.
![image](https://github.com/twitchdev/issues/assets/58613819/cd6be659-7a87-40e8-bf62-f428ae377c85)

After doing that, I then go to my creator dashboard and...
![image](https://github.com/twitchdev/issues/assets/58613819/450dbd83-e3fd-4e5b-b1bb-e9d64954811e)

Still a moderator. Even after refreshing the page.

**Comment by BarryCarlyon** [comment]
So it looks like this is not an API bug (technically) but a first party issue. So the underlying service is at fault.

**Comment by EthanBlaisAlarms** [comment]
Yes, it does look like it's an issue with Twitch, not the API.
Though it's still interesting because the moderator I timed out doesn't have moderation powers anymore, yet still appears as a mod in the creator dashboard, and continues to show like that for several minutes.

Not a mod:
![image](https://github.com/twitchdev/issues/assets/58613819/fac3d6dd-2207-46e5-b1b8-d72925832ac7)

Apparently a mod:
![image](https://github.com/twitchdev/issues/assets/58613819/4a8173e4-aa9b-4325-bb3b-e4765c761288)

So, should I instead report this issue to Twitch?

**Comment by Xemdo** [comment]
Does this only occur when timing out using the API? I could not reproduce it while testing on my channel. My 2nd account was removed from both /moderation/moderators and the Roles Manager as soon as I timed it out.

**Comment by EthanBlaisAlarms** [comment]
As of right now, running the exact same code that caused the problem in the first place, I too am no longer able to replicate it.
It might have been a bug on Twitch's end that has been patched. But at the moment, all seems to be working as intended.
