### ISSUE TITLE
Excessive Data Consumption in Helix API's msg_text Parameter - Check AutoMod Status

### ISSUE THREAD

**Issue by MrSniFo** [twitchdev/issues#825]
**Brief description**
Excessive data consumption vulnerability in the Helix API's msg_text parameter when checking AutoMod status could potentially lead to service disruptions and resource exhaustion.

**How to reproduce**
Make a POST request to the endpoint: https://api.twitch.tv/helix/moderation/enforcements/status
Include the msg_text parameter with a large amount of data.
Observe the behavior of the system as it processes the request.

**Comment by belliapptw** [comment]
Fixed
