### ISSUE TITLE
Get Channel Teams returns 500 instead of 404 when a user doesn't exist

### ISSUE THREAD

**Issue by Xemdo** [twitchdev/issues#826]
**Brief description**

When calling Get Channel Teams, providing a User ID that does not exist will return HTTP status code 500 instead of 404.

**How to reproduce**

Call Get Channel Teams on a user that does not exist. Examples can be random spams of numbers, or any ID that includes letters.
```
> twitch api get teams/channel -q broadcaster_id=notauser
{
  "data": [],
  "error": "Internal Server Error",
  "status": 500
}
```
```
> twitch api get teams/channel -q broadcaster_id=2730423789439829
{
  "data": [],
  "error": "Internal Server Error",
  "status": 500
}
```

**Expected behavior**

Endpoint should return HTTP 404 in these cases, as defined by the documentation.

**Comment by Xemdo** [comment]
Ticketed internally as ASYNC-3968

**Comment by belliapptw** [comment]
updated priority. will be looked at soon.
