### ISSUE TITLE
Embed Vertical Layout is broken - no video

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#827]
**Brief description**

if you do a regular embed
And cause the layout of the embed to be vertical
You get no video

**How to reproduce**

https://twitch.extensions.barrycarlyon.co.uk/viewer/?items=cohhcarnage,ezekiel_iii

And reduce window size until the player switches from horizontal row to vertical stack

There is no difference in behaviour for it the channels are live or not, as in it's broken if the channels are live as well

**Expected behavior**

Video not to disappear

**Screenshots**

![image](https://github.com/twitchdev/issues/assets/20999/9ed6390c-0d62-4456-9c94-0ae5a74cf5fa)

Horizontal layout for comparison

![image](https://github.com/twitchdev/issues/assets/20999/538c2312-b406-41e1-98c9-87827bfa1388)

**Comment by BarryCarlyon** [comment]
This may have originally been reported here https://discuss.dev.twitch.tv/t/embedded-player-video-being-hidden-by-chat-on-mobile/46980/

but OP didn't response with further information

**Comment by Xemdo** [comment]
This issue was resolved today. Let us know here if it pops back up!
