### ISSUE TITLE
`window.Twitch.ext.viewer.helixToken` not documented

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#828]
**Brief description**

`window.Twitch.ext.viewer.helixToken` is not documented in the list of `viewer` vars

https://dev.twitch.tv/docs/extensions/reference/#helper-viewer

**Expected documentation**

```
helixToken
window.Twitch.ext.viewer.helixToken: string

The helix token see https://dev.twitch.tv/docs/extensions/frontend-api-usage
```

**Comment by Xemdo** [comment]
Documented this as requested.
