### ISSUE TITLE
`beta_maintenance` not documented

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#829]
**Brief description**

Both 

- https://dev.twitch.tv/docs/api/reference/#get-eventsub-subscriptions
- https://dev.twitch.tv/docs/eventsub/manage-subscriptions/

Do not document `beta_maintenance` which was used this week for guest star subscription types which are in beta

**Expected documentation**

add `beta_maintenance` to the state list

**Additional context or questions**

https://discuss.dev.twitch.tv/t/eventsub-subscriptions-showing-as-status-beta-maintenance/47048/

**Comment by Xemdo** [comment]
Documented `beta_maintenance` it across the documentation
