### ISSUE TITLE
Messages are not sent publicly

### ISSUE THREAD

**Issue by web3cryptowallet** [twitchdev/issues#830]
**Brief description**
I tried to send my messages but not works 

**How to reproduce**
ellips0nspice: hey! did you see my message in the chat?
jmp77: What did I miss?
ellips0nspice: I don't see my messages on the stream video. I don't know why
ellips0nspice: Really fun stream :)
jmp77: I am not sure why
jmp77: I didn’t see your message either
ellips0nspice: maybe shadow ban. I don't know why.
jmp77: Let me chexk
ellips0nspice: thx
jmp77: i don't see you as banned
jmp77: but the last message in chat was 5/18/2023
ellips0nspice: Thanks. I hope I didn't write anything illegal last time VirtualHug
jmp77: try another message
ellips0nspice: My location is Kyiv, Ukraine. Maybe ban by location
ellips0nspice: tried
jmp77: hmmm
ellips0nspice: Really amazing tunes VirtualHug VirtualHug VirtualHug
jmp77: yeah i am not even seeing your messages show up in the mod section
jmp77: thanks - yeah @davelhouse is great!
ellips0nspice: I'm in Twitch from 2014 but really started at 2020 and @develhouse this is the best thing i have ever seen :) Super! VirtualHug VirtualHug VirtualHug
jmp77: i saw you had your account since 2014 - i asked one of the other mods if they knew what was going on with your account
ellips0nspice: my original account is d08ble from 2014. ellips0nspice account from 2020
jmp77: was your original account banned?
ellips0nspice: Don't know. I haven't been in d08ble for a long time. this account is primary
ellips0nspice: i can check old credentials if needed
ellips0nspice: 'this account is primary' i mean ellips0nspice
ellips0nspice: i'm here every week. watching ASOT and Anjunafamilly. They know me
jmp77: so weird
ellips0nspice: np
ellips0nspice: thanks for the support :)
ellips0nspice: are you from Twitch team?
jmp77: no just a mod for several channels
ellips0nspice: okay, thanks
ellips0nspice: maybe banned on higher level or twitch database error
ellips0nspice: i don't remember because most of the time i'm in view only mode
ellips0nspice: or a hack
ellips0nspice: saw this for the first time in 3 months
ellips0nspice: big thanks, anyway)
jmp77: hmmm might need to check with twitch support
ellips0nspice: fun stream and a great support. thanks
ellips0nspice: yeah, i'll check

**Expected behavior**
Remove shadow ban or fix db

**Screenshots**
I'll make screens if required

**Additional context or questions**
Probably cases
1. Hack
2. Database error
3. Ban by location??

**Comment by Emilgardis** [comment]
this looks like an issue with chat as a product and not something affecting a third party developer product file a ticket with https://help.twitch.tv/s/contactsupport instead

**Comment by Xemdo** [comment]
If this an issue with IRC/chat bots/chat clients, please note it here and we'll investigate.
Otherwise, if this is a first party issue, please report it on the Support page like Emilgardis mentioned.
