### ISSUE TITLE
App Creation doesn't surface name errors - Cannot Create Application

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#831]
**Brief description**

Today a French user got stuck trying to create a new Application as the "name taken/invalid" error wasn't showing

They were just stuck in a loop thinking the captcha failed

**Additional context or questions**

https://discord.com/channels/504015559252377601/523675993823510548/1147133036991873094

**Comment by BarryCarlyon** [comment]
Additional additional context https://discord.com/channels/325552783787032576/326772207844065290/1147278035427541133

Seems that name errors will not show on the create UI but will on the edit existing UI

**Comment by Xemdo** [comment]
Confirming it's the second thing; Errors don't appear when creating a new application, only when editing an existing one. Seems to be irrelevant to language.

**Comment by BarryCarlyon** [comment]
Yeah it was just ironic the two reports were non english speakers. So my initial thouht was "missing translation"

**Comment by rokn** [comment]
I can confirm it was happening for me as well. Was blocked for a day trying to figure it out until I stumbled upon this issue

**Comment by Xemdo** [comment]
Ticketed internally as ASYNC-4026

**Comment by thewbuk** [comment]
Same issue here: creating a new app, not editing

**Comment by guillian77** [comment]
Hi, I cannot create a new app too.

```JSON
# https://gql.twitch.tv/gql - Payload
[
    {
        "operationName": "CreateOauthApp",
        "variables": {
            "input": {
                "name": "HomeAssistant",
                "redirectURIs": [
                    "https://my.home-assistant.io/redirect/oauth"
                ],
                "category": "APPLICATION_INTEGRATION",
                "categoryDescription": "",
                "groupID": "",
                "isPublic": true
            }
        },
        "extensions": {
            "persistedQuery": {
                "version": 1,
                "sha256Hash": "c3f856bc8b0aba229a9ad20f6ebb73d70e8f8ff12e66c0531c1b3099d2225646"
            }
        }
    }
]
```

```JSON
# https://gql.twitch.tv/gql - Response
[
    {
        "errors": [
            {
                "message": "service error",
                "path": [
                    "createOauthApp"
                ]
            }
        ],
        "data": {
            "createOauthApp": null
        },
        "extensions": {
            "durationMilliseconds": 47,
            "operationName": "CreateOauthApp",
            "requestID": "01HQBSK270JXYWXR08FJE3R3VK"
        }
    }
]
```

Same problem on edit too.

**Comment by BarryCarlyon** [comment]
Homeassistant is likely already taken hence the issue

**Comment by guillian77** [comment]
> Homeassistant is likely already taken hence the issue

U're right, thanks 👍

**Comment by jbulava** [comment]
This issue should now be resolved.
