### ISSUE TITLE
Unable to create application integration

### ISSUE THREAD

**Issue by pydlv** [twitchdev/issues#833]
**Brief description**
Unable to create application integration. Button does nothing, failing network call

**How to reproduce**
After filling in form and clicking create, a failing network call is made and nothing happens.

**Expected behavior**

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/24441042/bbf17ea8-5d27-4344-8480-12c640029479)

**Additional context or questions**

**Comment by iProdigy** [comment]
The application name must be unique; `test` is already taken by someone else

**Comment by pydlv** [comment]
> The application name must be unique; `test` is already taken by someone else

Thanks. Putting a different name seems to work. Suggest that you update it to show proper error message to user.

**Comment by iProdigy** [comment]
> Suggest that you update it to show proper error message to user.

I agree; see https://github.com/twitchdev/issues/issues/831
