### ISSUE TITLE
Get Channel Followers - access token wording

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#837]
**Brief description**

https://dev.twitch.tv/docs/api/reference/#get-channel-followers

this doesn’t feel clear

>  The ID in the broadcaster_id query parameter must match the user ID in the access token or the user must be a moderator for the specified broadcaster.

**Expected documentation**

>  The ID in the broadcaster_id query parameter must match the user ID in the access token or the user ID in the access token must be a moderator for the specified broadcaster.

**Comment by Xemdo** [comment]
Seems to have been fixed.
