### ISSUE TITLE
Get Charity Campaign Donations - wrong key on the amount

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#838]
**Brief description**

The API says `target_amount` that should be `amount`

**How to reproduce**

Call Get Charity Campaign Donations

```
    {
      "campaign_id": "2E7IjWnmxUdGrIeu1H6OUEW6kPb",
      "id": "2E7IjWnmxUdGrIeu1H6OUEW6kPb-15185913-2022-11-30T14:28:47Z",
      "target_amount": {
        "currency": "USD",
        "decimal_places": 2,
        "value": 100
      },
      "user_id": "15185913",
      "user_login": "barrycarlyon",
      "user_name": "BarryCarlyon"
    }
```

**Expected behavior**

Should be

```
    {
      "campaign_id": "2E7IjWnmxUdGrIeu1H6OUEW6kPb",
      "id": "2E7IjWnmxUdGrIeu1H6OUEW6kPb-15185913-2022-11-30T14:28:47Z",
      "amount": {
        "currency": "USD",
        "decimal_places": 2,
        "value": 100
      },
      "user_id": "15185913",
      "user_login": "barrycarlyon",
      "user_name": "BarryCarlyon"
    }
```

**Comment by Xemdo** [comment]
Confirmed internally that the API payload is correct, and the documentation is wrong.
Documentation should be updated to reflect the correct payload.

**Comment by BarryCarlyon** [comment]
So when a user donates the API say the user donated a target amount?

**Comment by iProdigy** [comment]
`target_amount` for an individual donation doesn't make sense to me; target is the overall donation value the campaign wants to reach, which is comprised of many individual donations.

This used to be a problem in eventsub as well but was fixed: https://github.com/twitchdev/issues/issues/642#issuecomment-1295432538

**Comment by Xemdo** [comment]
I see, so it seems like it's definitely a bug rather than a documentation quirk.
We'll investigate this internally again and see what the best course of action is.

**Comment by belliapptw** [comment]
Addressed by the team
