### ISSUE TITLE
Missing `created_at` of Users in Helix

### ISSUE THREAD

**Issue by AlexWayfer** [twitchdev/issues#84]
**Brief description**

`created_at` existing in Kraken (V5) for Users: https://dev.twitch.tv/docs/v5/reference/users#get-user

But not in Helix: https://dev.twitch.tv/docs/api/reference#get-users

**How to reproduce**

Make requests to Helix.

**Expected behavior**

Responses have `created_at` field.

**Screenshots**

Kraken:

![2020-03-31_15-07](https://user-images.githubusercontent.com/6510020/78024620-5a2ad580-7361-11ea-9a4f-c3f31b7e670a.png)

Helix:

![2020-03-31_15-08](https://user-images.githubusercontent.com/6510020/78024887-c86f9800-7361-11ea-884c-e233f6a3ef56.png)

**Additional context or questions**

In [the V5 (Kraken) API](https://dev.twitch.tv/docs/v5) you're asking to move to a new API, but without any date of closing V5 API:

![image](https://user-images.githubusercontent.com/6510020/78024991-f1902880-7361-11ea-849f-ad92eb989307.png)

And you're (Helix Devs) "going to look into this" since November 2017: https://discuss.dev.twitch.tv/t/helix-vs-kraken-users-endpoint/12687

**Comment by BarryCarlyon** [comment]
Thats a Feature request not a bug.

It's already open on the Uservoice

https://twitch.uservoice.com/forums/310213-developers/suggestions/37682716-add-created-timestamp-to-helix-users

**Comment by AlexWayfer** [comment]
> Thats a Feature request not a bug.

You have a data‚ you return this data in API v5 and you don't return this data in (the next) API v6. Is it a feature absence? So, there is a feature in API v5 and there is no the same feature in API v6, right? Sounds weird.

If you have the data and you gave this data early, and you don't give the same data now but you can (with all privacy and other permissions) — it's not a feature absence, it's a bug. I suggest you to just clone (inherit) previous API version (5 for 6) and improve it, don't reinvention a bicycle.



> It's already open on the Uservoice

OK, thanks, I din't find this portal on https://dev.twitch.tv/support.

**Comment by BarryCarlyon** [comment]
> You have a data

Me? I don't work for Twitch.

> So, there is a feature in API v5 and there is no the same feature in API v6, right?

Helix is _not_ V6. Versions apply to API's under Kraken, not Helix

> Is it a feature absence?

General discussion on this issue, mainly on Discrd, suggests, it's a "privacy concern to present the created_at publicly"

> I suggest you to just clone (inherit) previous API version (5 for 6) and improve it, don't reinvention a bicycle.

I believe a new API is warranted as Kraken doesn't cut it any more, too many of Twitch's internal systems has changed, which makes providing data to the API "too difficult", without the whole API being replaced.

> it's not a feature absence, it's a bug

It's not a bug, we expect and hope that Helix will have feature parity before Kraken is removed, but we don't know _everything_ that goes on internally at Twitch, in order to decide what should or should not be in Helix.

Anything that is "missing" from Helix, is a feature request. Not a bug.

> OK, thanks, I din't find this portal on https://dev.twitch.tv/support.

Now that _is_ a docs bug, but then this issues repo isn't there either.

**Comment by AlexWayfer** [comment]
> Me? I don't work for Twitch.

No, sorry. It's like… "if you have a (an any) data", in any project, not related to Twitch. I'm trying to think abstractly and logical.

> Helix is not V6. Versions apply to API's under Kraken, not Helix

And what is it then?

> General discussion on this issue, mainly on Discord, suggests, it's a "privacy concern to present the created_at publicly"

The good practice — add an option for this. Even with disabled default. But… the privacy is already broken via Kraken API.

> Let alone the whole Helix data structure layout is completely different to Kraken's and we don't know anything about the internals

You (somebody) have a user name — you give a user name in Helix API as in Kraken API. You also have date of creation — you return it in working Kraken API, but not in new Helix. "Data structure layout"… it's just fields. And yes, there are maybe different tables, data sources, relations and joins. But it's already works in Kraken. It's possible. I don't understand why it can be impossible or too hard to implement in Helix.

> but we don't know everything that goes on internally at Twitch

Yes, and it's a problem, I think.

> Anything that is "missing" from Helix, is a feature request. Not a bug.

"Anything that is missing from Helix, is a bug. Not a feature request."

It's a good practice to discuss with argumentation.

I think it's a bug because this data exists internally, and previous API returns it.

You think that it's not a bug because you don't know about internal Twitch data structure. OK.

> Now that is a docs bug, but then this issues repo isn't there either.

Yep, but I'm honestly don't care about Uservoice link in Twitch docs. And I don't think that Uservoice is more primary than this GitHub repository.

**Comment by jbulava** [comment]
Hi @AlexWayfer, thanks for the feedback.  `created_at` was intentionally left out of the Helix payload, though we have heard plenty of feedback that it is important for some use cases like moderation tools. As Barry mentioned, that feature request is recorded on UserVoice [here](https://twitch.uservoice.com/forums/310213-developers/suggestions/37682716-add-created-timestamp-to-helix-users) for further consideration.  As such, I'm going to close out this issue. Please feel free to upvote the UserVoice entry and sign up there for a notification as the status changes.
