### ISSUE TITLE
Dead Sockets showing after an hour and can't be deleted

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#845]
**Brief description**

EventSub Websockets that die to due socket disconnect
Are still showing in Get EventSubScriptions after their stated 1 hour death time
They cannot be deleted

**How to reproduce**

- Connect a websocket
- Connect some subscriptions
- Disconnect the websocket
- See the socket is dead in Get ES Subs
- Wait and hour
- See they didn't self disappear
- Try to manually tidy up

**Expected behavior**

- Self disappear
or
- can be deleted

**Screenshots**

![image](https://github.com/twitchdev/issues/assets/20999/5b29f8e4-6f59-4c2d-aa44-04111e9753f7)

![image](https://github.com/twitchdev/issues/assets/20999/d44e0267-ff5d-453c-86cb-b6062269341b)

**Additional context or questions**

Initial Report https://discuss.dev.twitch.com/t/unable-to-delete-eventsubs/47991/2

**Comment by ginovva320** [comment]
A bug was recently introduced that causes this. A fix should be deployed in the coming days.

**Comment by BarryCarlyon** [comment]
This is resolved!
