### ISSUE TITLE
Error when trying to create new oauth application

### ISSUE THREAD

**Issue by luke-h1** [twitchdev/issues#849]
**Brief description**
When trying to create a new oauth applicaton on the developer portal, I get the following GraphQL error:

```
[GraphQL] One or more GraphQL errors were detected on request 01HCX56KHFWYZVSB9PVHPJ5Z4D. CreateOauthApp: service error 
```

**How to reproduce**
* Navigate to https://dev.twitch.tv/console/apps/create as an authenticated Twitch user
* Fill out the name, oauth redirect URL and category fields (I used "test-application", "http://localhost" and "application integration" respectively). 
* Click "create" button
* At this stage you should see the above graphql error  

**Expected behavior**
I can create a new oauth application succesfully and receive the client ID + secrets needed to integrate with the Twitch API

**Screenshots**
<img width="1015" alt="Screenshot 2023-10-16 at 22 15 36" src="https://github.com/twitchdev/issues/assets/55030296/db236f8a-2353-4d16-81ce-68e479f2f37a">

**Additional context or questions**

**Comment by iProdigy** [comment]
Duplicate of #831

**Comment by luke-h1** [comment]
Thanks for the super quick response, good to know there is a workaround :), thanks for the help
