### ISSUE TITLE
EventSub: Channel Ad Break Begin Event Example and Reference have inconsistent field names

### ISSUE THREAD

**Issue by iProdigy** [twitchdev/issues#850]
**Brief description**
[Channel Ad Break Begin Notification Example](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelad_breakbegin) has `length_seconds` and `started_at` in the event payload.

[Channel Ad Break Begin Event](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-ad-break-begin-event) refers to those fields as `duration` and `timestamp` respectively.

**Expected documentation**

A single set of correct field names should be used

**Screenshots**

![image](https://github.com/twitchdev/issues/assets/8106344/efba4126-f36f-427b-a8cb-385fcbf28c1f)

![image](https://github.com/twitchdev/issues/assets/8106344/c7174a9c-5d55-4c5e-8f27-d2937e960307)

**Additional context or questions**
Posted here since [#docs-feedback](https://discord.com/channels/504015559252377601/523675755503157248/1164804330164080700) goes unread/untriaged

**Comment by iProdigy** [comment]
`length_seconds` vs. `duration` inconsistency has been fixed.
`started_at` vs. `timestamp` inconsistency remains.

**Comment by iProdigy** [comment]
`length_seconds` has been renamed to `duration_seconds` in eventsub docs

however: `started_at` vs. `timestamp` inconsistency remains

**Comment by Xemdo** [comment]
Last inconsistencies have been fixed
