### ISSUE TITLE
Get Ad Schedule / Snooze Next Ad swapped info

### ISSUE THREAD

**Issue by theca11** [twitchdev/issues#851]
**Brief description**
`Get Ad Schedule` and `Snooze Next Ad` have some swapped info. In particular, the URL/Response Body/Response Codes/Examples of Get Ad are shown in the Snooze section, and viceversa

**Expected documentation**
Each endpoint with their appropriate information

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/48060851/fef0c130-e515-474a-b454-76f2e17d50ba)

**Comment by BarryCarlyon** [comment]
This one got fixed \o/

**Comment by theca11** [comment]
Yep, closing the issue
