### ISSUE TITLE
Unable to register a new application

### ISSUE THREAD

**Issue by fleetfoxx** [twitchdev/issues#856]
**Brief description**
I am unable to register a new application through the developer console. After filling out the application details, clicking the "Create" button does nothing. The developer console in my browser shows graphql errors. I am able to reproduce this in Firefox, Chrome, and Edge.

**How to reproduce**
1. Fill out the "Register Your Application" form.
2. Click the "Create" button.
3. The application is not created.

**Expected behavior**
The application is created.

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/98632874/835aed4d-3f45-45fc-a09d-6300c92a5d5f)

**Additional context or questions**

**Comment by Dkamps18** [comment]
The name must be unique and may not contain the word "Twitch"

**Comment by BarryCarlyon** [comment]
Duplicate of #831

**Comment by Xemdo** [comment]
Closed as duplicate
