### ISSUE TITLE
Can't create a new OAuth application

### ISSUE THREAD

**Issue by PlGGS** [twitchdev/issues#861]
**Brief description**

**How to reproduce**

1. Go to https://dev.twitch.tv/console/apps/create
2. Try to create an application

**Expected behavior**

Some sort of confirmation or redirect to main console page with the new application listed

**Screenshots**

<img width="552" alt="image" src="https://github.com/twitchdev/issues/assets/20197872/5ae23013-922e-42db-bb36-b0b7f50ebc98">

**Additional context or questions**

Duplicate of previously closed issue: [https://github.com/twitchdev/issues/issues/634](https://github.com/twitchdev/issues/issues/634)

**Comment by Emilgardis** [comment]
This looks like a duplicate of #831

**Comment by PlGGS** [comment]
Works as of today ¯\_(ツ)_/¯
