### ISSUE TITLE
Channel Chat Message Delete Notification Example missing `message_id`

### ISSUE THREAD

**Issue by Emilgardis** [twitchdev/issues#864]
**Brief description**
[Channel Chat Message Delete Notification Example](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channel-chat-message-delete-notification-example) is missing a [`message_id`](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-chat-message-delete-event) in event data

**Comment by Xemdo** [comment]
Fixed
