### ISSUE TITLE
Bug with the creation of the application

### ISSUE THREAD

**Issue by 0Mrbilal0** [twitchdev/issues#866]
**Brief description**

When I click on the button for create my application I have this error.

**How to reproduce**

**Expected behavior**

**Screenshots**
<img width="1267" alt="image" src="https://github.com/twitchdev/issues/assets/77295829/f62b083c-bca3-4f89-b8ec-c6368c67ed0a">
**Additional context or questions**

**Comment by Emilgardis** [comment]
this is probably #831 

try another name, it's most likely already taken

**Comment by Xemdo** [comment]
Duplicate of #831
