### ISSUE TITLE
Application registration

### ISSUE THREAD

**Issue by juliocmfj28** [twitchdev/issues#867]
**Brief description**
Does not complete registration

**How to reproduce**
Fill in all the fields and try to register the application

**Expected behavior**
It simply stays on the same screen and does not register the application

**Screenshots**

**Additional context or questions**

**Comment by thedist** [comment]
What is the name of the apo you're attempting to register? If it's already in use, or contains a reserved word like 'Twitch', then that is intentionally being blocked, but there's no error as reported in https://github.com/twitchdev/issues/issues/831
