### ISSUE TITLE
Fail during extension deletion

### ISSUE THREAD

**Issue by Rkrushanovskij** [twitchdev/issues#869]
**Brief description**
On attempt to delete an extension, nothing happened.

**How to reproduce**
1. Have a created extension
2. Attempt to delete it

**Expected behavior**
Extension deleted

**Additional context or questions**
Response from the server:
```
[
    {
        "errors": [
            {
                "message": "service error",
                "path": [
                    "deleteExtension"
                ]
            }
        ],
        "data": {
            "deleteExtension": null
        },
        "extensions": {
            "durationMilliseconds": 20,
            "operationName": "DevDeleteExtension",
            "requestID": "01HG0Q2Y05PNNFSQBATBEQQSQG"
        }
    }
]
```

**Comment by thedist** [comment]
Does your Extension have at least 1 version? If it doesn't have a version then this error is known, see https://github.com/twitchdev/issues/issues/46
