### ISSUE TITLE
The /revoke endpoint returns a 400 response code

### ISSUE THREAD

**Issue by GStefanowich** [twitchdev/issues#87]
**Brief description**
I operate a SaaS, when users un-link their accounts from the service I send a `/revoke` to delete their access tokens. If the user already has disconnected my service via their [connections page](https://www.twitch.tv/settings/connections), a 400 (malformed request) is returned; indicating that my app is doing something incorrectly.

*As per the documentation:*
> Malformed requests return 400 Bad Request, along with information about how to fix the request, typically reminding the requester to include the client_id.

The received response body:
> {
>   "status": 400,
>   "message": "Invalid token"
> }

**How to reproduce**
Perform the same request as indicated by the `/revoke` documentation (With a real client_id)

> curl -X "POST" https://id.twitch.tv/oauth2/revoke --data "client_id=uo6dggojyb8d6soh92zknwmi5ej1q2&token=0123456789abcdefghijABCDEFGHIJ"

**Expected behavior**
As per the developer documentation, all successful attempts to revoke a token should return with a 200 response code. The request went through, the token may or may not have been valid, but it is no longer valid as of the request.

*As per the documentation:*
> Both successful requests and requests with bad tokens return 200 OK with no body. Requests with bad tokens return the same response, as there is no meaningful action a client can take after sending a bad token.

**Comment by lleadbet** [comment]
Ticketed internally as IDPLAT-3877.

**Comment by Xemdo** [comment]
Documentation has been since updated to reflect the new behavior:
https://dev.twitch.tv/docs/authentication/revoke-tokens/

> If the revocation fails, the request returns one of the following HTTP status codes:
> - 400 Bad Request if the client ID is valid but the access token is not.
