### ISSUE TITLE
Incorrect Delete Chat Message param

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#871]
**Brief description**
To delete a single chat message the reference page, [https://dev.twitch.tv/docs/api/reference/#delete-chat-messages](https://dev.twitch.tv/docs/api/reference/#delete-chat-messages), correctly has the `message_id` param, but the moderation page, [https://dev.twitch.tv/docs/api/moderation/ ](https://dev.twitch.tv/docs/api/moderation/) incorrectly uses `id` for the message id which would result in a full chat clear due to the dev not specifying a `message_id` as they used `id` instead.

**Expected documentation**
`The id query parameter that’s set to the ID of the message to delete. The message must be less than 6 hours old and it must not belong to the broadcaster.`

Should be

`The message_id query parameter that’s set to the ID of the message to delete. The message must be less than 6 hours old and it must not belong to the broadcaster.`

Also the example should be changed from

```
curl -X DELETE 'https://api.twitch.tv/helix/moderation/chat?broadcaster_id=1234&moderator_id=5678&id=abc-123-def-456' \
-H 'Authorization: Bearer ln6n5azzuliqq57gmncybxrno4fy' \
-H 'Client-Id: hof5gwx0su6onys0nyan9c87zr6t'
```

to

```
curl -X DELETE 'https://api.twitch.tv/helix/moderation/chat?broadcaster_id=1234&moderator_id=5678&message_id=abc-123-def-456' \
-H 'Authorization: Bearer ln6n5azzuliqq57gmncybxrno4fy' \
-H 'Client-Id: hof5gwx0su6onys0nyan9c87zr6t'```

**Comment by Xemdo** [comment]
Fixed the description and examples
