### ISSUE TITLE
Unable to upload large extension bundle

### ISSUE THREAD

**Issue by KiKoS0** [twitchdev/issues#874]
**Brief description**
I have a relatively large bundle (100+MB mainly image assets) and I upload them from a slow network (8Mbps). A recurring issue I've observed is that the UI consistently times out with an error message before the upload process is completed. (The upload request is still happening in the devtools). Which basically fails to update the manifest.

**How to reproduce**
Upload a large zip file with a slow network.

**Expected behavior**
The zip file is uploaded and updated without any errors.

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/22998716/bc30a38a-d95e-4d2d-a3ea-537dd3ed32a1)

**Comment by BarryCarlyon** [comment]
There is an undocumented file upload limit.

Which we don't know what it is. So your file is too large anyway.

Here you probably want to put your iamges on your OWN CDN which then makes it easier to update them without needing an extension review.

And you just want the layout items in your bundle not your content items

**Comment by KiKoS0** [comment]
I see, the limit is probably set to 100MB, because it worked fine for years when it was just below it.
Thank you I'll use my own cdn. I had it setup this way for a long time to minimize latency and never revisited it.
