### ISSUE TITLE
Cannot create Application

### ISSUE THREAD

**Issue by timogoesling** [twitchdev/issues#875]
Every time i try to create a new application, it doesn't work...
I give a name, redirect URI and a category, then the captcha and then i click continue.

Then the whole site has to reload and i have to do the captcha again...and again....and again...the green tick just disappears.
However, i am not able to create an application in this way.

**Comment by thedist** [comment]
There's a known issue where errors relating to invalid names isn't shown https://github.com/twitchdev/issues/issues/831

Ensure that the name of the app you're attempting to create does not contain any reserved words, such as 'Twitch', and also that it is unique (if you're attempting to use a generic name it could very well already be taken).

**Comment by timogoesling** [comment]
This was the solution, was wondering why it wasn't working for Discord either, but the name Dashboard isn't appropriate. 
Thank you for your help, it really worked out
