### ISSUE TITLE
Version Details gets wiped out when saving Capabilities

### ISSUE THREAD

**Issue by rupture-ttv** [twitchdev/issues#876]
**Brief description**
All of the information in version details gets obliterated when saving the Capabilities information 

**How to reproduce**
Edit the allow list urls for the config page adding or removing some values.
![image](https://github.com/twitchdev/issues/assets/31562317/edd9fc80-9e94-4b14-ab7e-1561c978b899)

Click the save button at the bottom of the page:
![image](https://github.com/twitchdev/issues/assets/31562317/26943a94-294b-4577-adc1-32ae3dec7367)

Then if you try to leave the page you get a warning about losing data.  This warning caused me to click the save button again and then also click the save button in the top section with the radio buttons:
![image](https://github.com/twitchdev/issues/assets/31562317/e5533968-11e5-465f-ad8f-6a9d50ec0a2e)

**Expected behavior**
Everything is saved which it seems to be.  However the data on the version details page gets lost and everything is empty.  I am then allowed to move to hosted tests and when trying to send a chat message on behalf of the extension I get an error about extension_name is required.  This is what lead me to find the bug.

**Screenshots**
Before these steps all of the data here was filled in:
![image](https://github.com/twitchdev/issues/assets/31562317/64b7f96f-4542-4221-ac54-627fb5f428fb)

**Additional context or questions**
@BarryCarlyon also confirmed that this was happening when he tried the same steps.

It only happens when pressing the save button in the radio button section.  If I only press the save button at the bottom of the page then it is not wiped out.

**Comment by BarryCarlyon** [comment]
> It only happens when pressing the save button in the radio button section. If I only press the save button at the bottom of the page then it is not wiped out.

if occurs when you use both save buttons on this page in _either_ order.

So if you do top then bottom, It kills version details
or if you do bottom then top, It kills version details

basically if you use both save buttons on this page without a reload it can wipe out version details it seems

**Comment by jbulava** [comment]
Ticketed internally on ANC-3202.

**Comment by Marenthyu** [comment]
The Name being "Empty" also impacts the [Send Extension Chat Message](https://dev.twitch.tv/docs/api/reference/#send-extension-chat-message) Endpoint, which returns an Error 400 claiming that the extension_name is missing.

I'd argue this should be a Server Error 500 as the Name isn't provided by the Client calling this Method, but it is an invalid state for the Extension in the first place, so won't be a problem once the overall issue is solved.

**Comment by rupture-ttv** [comment]
> The Name being "Empty" also impacts the [Send Extension Chat Message](https://dev.twitch.tv/docs/api/reference/#send-extension-chat-message) Endpoint, which returns an Error 400 claiming that the extension_name is missing.
> 
> I'd argue this should be a Server Error 500 or 412 Precondition Failed as the Name isn't provided by the Client calling this Method, but it is an invalid state for the Extension in the first place, so won't be a problem once the overall issue is solved.

Yeah this is how I uncovered this issue.  My extension was trying to send messages and getting that error.  I was so confused because the code was the same I have always used and I created the extension version by cloning.  I thought I was going crazy when the problem was happening.

**Comment by jbulava** [comment]
A fix for this issue has been deployed today.
