### ISSUE TITLE
Twitch Drop Error

### ISSUE THREAD

**Issue by ghost** [twitchdev/issues#877]
I had an drop from valorant but it didn't came into my account, than i canceled my connection with twitch on riot games but i couldn't cancel my riot games connection on twitch its giving error.

Im just going to cancel my riot games connection and connect it again but its giving error so i couldn't do it

![Twitch - Opera 10 12 2023 17_19_26](https://github.com/twitchdev/issues/assets/76950759/43ad89bf-f143-4b07-9d8e-1ca4d16c9f49)

please help me to cancel it!

**Comment by BarryCarlyon** [comment]
This isn't something third party developers can help with

You need to reach out to riot or twitch support

**Comment by burak39** [comment]
i reached the riot support and they said reach twitch support

where can i find the twitch support then?

**Comment by BarryCarlyon** [comment]
https://help.twitch.tv/

**Comment by burak39** [comment]
thanks
