### ISSUE TITLE
channel points (i dont know if this goes with this catagory )

### ISSUE THREAD

**Issue by puginaburrito** [twitchdev/issues#878]
**Brief description**
channels points not showing in viewer rewards
**How to reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2023-12-14 151744](https://github.com/twitchdev/issues/assets/153870716/66a43ce1-44e3-4b35-b54d-6ef34c1ae7bd)

**Additional context or questions**

**Comment by thedist** [comment]
If your Twitch account is the same as your user here on GitHub, `puginaburrito`, then you're not an Affiliate or Partner so your channel is not eligible to use Channel Points.

Also, this GitHub is to report issues with Twitch's 3rd party dev services. In the future please use [https://help.twitch.tv/](https://help.twitch.tv/) for help with the Twitch site.

**Comment by puginaburrito** [comment]
the help page does not help me

**Comment by Emilgardis** [comment]
affiliate: [FAQ](https://help.twitch.tv/s/article/twitch-affiliate-program-faq?language=en_US#joining), [Joining the affiliate program](https://help.twitch.tv/s/article/joining-the-affiliate-program )
partner: [Partner program](help.twitch.tv/s/article/partner-program-overview#qualifying)

**Comment by puginaburrito** [comment]
ok i did not know that but thank you
