### ISSUE TITLE
Ad Schedule documentation incorrect

### ISSUE THREAD

**Issue by serycodes** [twitchdev/issues#879]
**Brief description**
The [Get Ad Schedule](https://dev.twitch.tv/docs/api/reference/#get-ad-schedule) endpoint returns epoch timestamps for `next_ad_at`, `last_ad_at`, and `snooze_refresh_at`. The documentation states these should be strings with the UTC timestamp in RFC3339 format. The endpoint is returning the wrong format.

In addition, the `snooze_count`, `duration`, and `preroll_free_time` says they should be integers, but the example provided returns strings. The example in the documentation just needs to be corrected. Easy fix.

The [Channel Ad Break Begin Event](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-ad-break-begin-event) documentation also refers to `timestamp` when it should be `started_at`. Easy fix.

**How to reproduce**
GET https://api.twitch.tv/helix/channels/ads?broadcaster_id=30121622
```
{
    "data": [
        {
            "snooze_count": 3,
            "snooze_refresh_at": 0,
            "next_ad_at": 1702019672,
            "duration": 90,
            "last_ad_at": 0,
            "preroll_free_time": 0
        }
    ]
}
```

**Expected behavior**
GET https://api.twitch.tv/helix/channels/ads?broadcaster_id=30121622
```
{
    "data": [
        {
            "snooze_count": 3,
            "snooze_refresh_at": "2023-08-01T23:08:18+00:00",
            "next_ad_at": "2023-08-01T23:08:18+00:00",
            "duration": 90,
            "last_ad_at": "2023-08-01T23:08:18+00:00",
            "preroll_free_time": 0
        }
    ]
}
```

**Comment by iProdigy** [comment]
re: seconds vs strings, see #857 - tho barry claims epoch seconds is intentional (i.e, docs are wrong)

re: eventsub timestamp, see #850

**Comment by serycodes** [comment]
Ha, should have checked first.
