### ISSUE TITLE
Issue creating new app

### ISSUE THREAD

**Issue by emnh** [twitchdev/issues#880]
**Brief description**

I cannot register my app on https://dev.twitch.tv/console/apps/create. I don't get an error message on the page for creating new app, but I get some GraphQL error in JS Console:

dev-main-fcef218df6c209de8b75.js:1 [GraphQL] One or more GraphQL errors were detected on request 01HJ18JBDQG90KS0X9XF47R3JK. CreateOauthApp: service error [{…}]

**How to reproduce**

Try to register an app with name: "Twitch Scheduler", OAuth http://localhost, Category: "Other" and Client Type: Confidential.

**Expected behavior**

Creating the app successfully.

**Screenshots**

**Additional context or questions**

**Comment by Wissididom** [comment]
`Twitch` is a reserved name

**Comment by emnh** [comment]
Ok thank you I changed the name and succeeded in the creation now :)

**Comment by emnh** [comment]
Fixed then I guess, except for the error reporting.
