### ISSUE TITLE
Can't register app

### ISSUE THREAD

**Issue by AlexGouget** [twitchdev/issues#882]
I can't record new App. I only have console error: 

![image](https://github.com/twitchdev/issues/assets/13834739/21b959ee-f2ce-424f-a19f-c6e9d17cf692)

**Comment by iProdigy** [comment]
Duplicate of https://github.com/twitchdev/issues/issues/831

Your app name must be unique and not contain "twitch"

**Comment by Xemdo** [comment]
Indeed a duplicate of #831. Closing
