### ISSUE TITLE
Pending status

### ISSUE THREAD

**Issue by ZonnerGM** [twitchdev/issues#884]
**Brief description**
Hello. I want to embed the Twitch API into my website, to display active broadcasts that I select. However, in order to do this, I need to register my application. I have done that, but I don't understand what I need to do next. Do I wait? If so, how long?
As far as I understand, I need the **client  id** and the **secret  word**
**How to reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/155834757/be180552-1ddc-43a3-bbf7-3b55b76367ef)

**Additional context or questions**

**Comment by Emilgardis** [comment]
To register an application you do it on https://dev.twitch.tv/console/apps, where is this picture from?

**Comment by ZonnerGM** [comment]
From here  https://dev.twitch.tv/organizations  
Screen from here  https://dev.twitch.tv/console/apps are ->
![image](https://github.com/twitchdev/issues/assets/155834757/83b32e1d-880f-476e-8fb2-5da99d42663f)

**Comment by iProdigy** [comment]
If you click the 'Manage' button on the app, you can obtain the client id and secret. You do not need to create an organization

**Comment by ZonnerGM** [comment]
![image](https://github.com/twitchdev/issues/assets/155834757/f404ddf1-3210-426b-84cc-63ec41103265)
Look, i havent sercret word here... sorry for RU =)

**Comment by iProdigy** [comment]
You can press the generate button to get a new client secret & no worries about the RU

**Comment by ZonnerGM** [comment]
![image](https://github.com/twitchdev/issues/assets/155834757/2b7ce8e1-19f5-4d38-81f7-026f5bc4d3b5)
But this is just a save button. And "all ok" on the green button. No "generate button". Where is it?

**Comment by iProdigy** [comment]
You need to create a confidential app to be able to generate a client secret on the manage page. In that screenshot, you're creating a public client type

**Comment by iProdigy** [comment]
Note: for embedding, you don't need client id or secret.

**Comment by ZonnerGM** [comment]
And 

> You need to create a confidential app to be able to generate a client secret on the manage page. In that screenshot, you're creating a public client type

Oh god..thx! I can see it now!
