### ISSUE TITLE
Set Extension Required Configuration - stopped working for versions in local/hosted test

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#886]
**Brief description**

https://dev.twitch.tv/docs/api/reference/#set-extension-required-configuration

Response with "Sorry, you're not allowed to do that" for versions in local or hosted test

**How to reproduce**

- have an extension version that is not released that needs a configuration string to be set before activation
- try to set that string

**Expected behavior**

accepted and extension can be activated

**Screenshots**

![image](https://github.com/twitchdev/issues/assets/20999/c9694657-ca96-489d-b5b3-04d0b43205bd)

**Additional context or questions**

I believe this broke due to changes yesterday

Initial report: https://discord.com/channels/504015559252377601/523676096277905419/1194685221212258524

**Comment by chris-lu** [comment]
Any feedback, workaround or ETA on this? It seems it's still now working, making the whole "Required Configuration" feature useless as new extension cannot be validated.

**Comment by beheh** [comment]
Just to add our voice, we're also affected by this and cannot submit a version with this anymore as we never get past the "Requires Configuration" state in the broadcaster dashboard.

What's even worse, migrating to the Extension Configuration Service is also problematic as to my knowledge the extension will be deactivated for all existing broadcasters. So it seems our only recourse is now to temporarily stop requiring configuration, start writing to the Configuration Segment for broadcasters, and then start requiring it again in a few months.

**Comment by jbulava** [comment]
This issue has been ticketed internally as ANC-3204 for investigation. More details to follow.

**Comment by jbulava** [comment]
A fix for this issue has been deployed today.
