### ISSUE TITLE
Extensions Reference formatting Error for window.Twitch.ext.listen

### ISSUE THREAD

**Issue by Marenthyu** [twitchdev/issues#887]
**Brief description**
In the Table for the Arguments of the window.Twitch.ext.listen function, the last row is unintentional - it should be in the previous row without a line break.
**Expected documentation**
The Text ``[send](https://dev.twitch.tv/docs/extensions/reference/#send) message, except the message is always a string.`` should be in the same row as ``These fields correspond to the values in the``
**Screenshots**
![screenshot](https://lowee.de/chrome_2024-01-13_11-24-43.png)
**Additional context or questions**
Does not impact functionality or understanding, is merely a formatting error.

**Comment by Xemdo** [comment]
This has been fixed
