### ISSUE TITLE
"Project Name" There is none available no matter what I type.. 

### ISSUE THREAD

**Issue by FTXArduous** [twitchdev/issues#889]
If you head into the Twitch Developer rig, it will not let you go past the first slide because the project name is always unavailable.. 

Please fix

**Comment by Dkamps18** [comment]
The Developer Rig has been at its end of support for about a year now and should no-longer be used.

https://discuss.dev.twitch.tv/t/end-of-support-for-the-twitch-developer-rig/42995

**Comment by BarryCarlyon** [comment]
You'll also find that most of the things you tried to make exist on https://dev.twitch.tv/console/extensions/ but lack a version so just add a version/complete the wizard and you've got keys to go.

You will also need to add a version if you want to delete the duplicates (note this won't free up the name for reuse)

**Comment by Xemdo** [comment]
Closing due to the deprecation of the Developer Rig
