### ISSUE TITLE
Stream summary returning random numbers

### ISSUE THREAD

**Issue by Dkamps18** [twitchdev/issues#89]
**Brief description**
Title says everything, After watching the below linked video it should be fully clear
https://cdn.dannyhisstuff.com/static/2020-04-10_21-32-41.mp4

**How to reproduce**
Just make a call to the streams/summary endpoint

**Expected behavior**
Correct numbers.

**Comment by jbulava** [comment]
Team is aware and investigating.

**Comment by Dkamps18** [comment]
Somewhere between the 1st and 27th of May this got fixed.

**Comment by Dkamps18** [comment]
Its drunk again https://cdn.dannyhisstuff.com/static/2020-07-20_10-30-49.mp4
