### ISSUE TITLE
Registering Your Application

### ISSUE THREAD

**Issue by HashPong** [twitchdev/issues#890]
Registering Your Application does nothing. its broken.

![image](https://github.com/twitchdev/issues/assets/52078549/78e45eda-c6e2-43b3-a924-27165540cfb3)

**Comment by Dkamps18** [comment]
Name has to be unique globally and may not contain the word "Twitch", test is for sure taken

**Comment by HashPong** [comment]
> Name has to be unique globally and may not contain the word "Twitch", test is for sure taken

OK that worked. They should add feedback text.

Thanks

**Comment by Emilgardis** [comment]
cc #831
