### ISSUE TITLE
Wrong description on subscription types for eventsub

### ISSUE THREAD

**Issue by jdudetv** [twitchdev/issues#891]
**Brief description**
Description of Channel chat settings update and Channel Chat Notification are swapped

**Expected documentation**
they would each have the others description

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/51935420/6435ab1f-7521-45a1-abe1-7f144a4f1a7e)

**Additional context or questions**

**Comment by Xemdo** [comment]
Fixed
