### ISSUE TITLE
Issue with registering new app

### ISSUE THREAD

**Issue by Blitzz13** [twitchdev/issues#892]
When i try to register my application using the site nothing happens and an error ocurs in the console.

Enter https://dev.twitch.tv/console/apps/create set your correct information click create nothing happens and reCapcha refreshes

When clicking create the application registers  

<img width="1522" alt="Screenshot 2024-01-15 at 21 12 32" src="https://github.com/twitchdev/issues/assets/16774141/6f9f9cda-e7a5-474f-a608-dc7a81ed7110">

**Comment by Blitzz13** [comment]
The issue dublicates this one https://github.com/twitchdev/issues/issues/890. Maybe some kind of indication what the error is should be made.

**Comment by Emilgardis** [comment]
We have a long standing issue about the fact that name errors are not propagated: #831
