### ISSUE TITLE
Device Code Flow login 400: missing device_code

### ISSUE THREAD

**Issue by dennisrijsdijk** [twitchdev/issues#893]
**Brief description**
Trying to authenticate an app with Device Code Flow now returns a JSON page with `{"status":400,"message":"missing device_code"}` on https://id.twitch.tv/oauth2/authorize

**How to reproduce**
Open https://codepen.io/Alca/pen/xxBgmVq?layout=right in browser, press the `Get Code` button and go through authentication flow
Alternate repro: download Firebot from https://firebot.app and attempt to login.

**Expected behavior**
Authentication should function properly.

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/70665154/4f7366f0-d964-49e0-9d1f-6e0cf9fa1f64)

**Comment by Dkamps18** [comment]
This seems to be resolved

**Comment by dennisrijsdijk** [comment]
Resolved here as well, closing.
