### ISSUE TITLE
Sending a chat message with an invalid `reply_parent_message_id` returns generic `msg_rejected`

### ISSUE THREAD

**Issue by Nerixyz** [twitchdev/issues#896]
**Brief description**

Calling `/chat/messages` with an invalid reply-parent-id returns 200 OK:

```json
{
  "data": [
    {
      "drop_reason": {
        "code": "msg_rejected",
        "message": "Your message is being checked by mods and has not been sent."
      },
      "is_sent": false,
      "message_id": ""
    }
  ]
}
```

While it's true that the message is dropped, the reason is too generic. I'd like to know that the `reply_parent_message_id` was invalid.

**How to reproduce**

Call the `POST /chat/messages` endpoint with

```json
{"broadcaster_id": "<your-id>", "sender_id": "<your-id>", "message": "a", "reply_parent_message_id": "1"}
```

**Expected behavior**

It should return 400 or include a proper code and message in the `drop_reason`.

**Comment by Nerixyz** [comment]
Thanks! Returns 400 now:

```json
{
  "data": [],
  "error": "Bad Request",
  "message": "The request's input was not valid. Message cannot be replied to.",
  "status": 400
}
```

**Comment by Xemdo** [comment]
Looks good! Closing this out
