### ISSUE TITLE
user:write:chat scope missing from scopes list

### ISSUE THREAD

**Issue by Katzen48** [twitchdev/issues#897]
**Brief description**
Scope "user:write:chat" for "Send Chat Message" endpoint is missing from the scopes list.

**Expected documentation**
As the scope "user:write:chat" ist required to send a chat message, I would have expected it, to being listed on https://dev.twitch.tv/docs/authentication/scopes/ with a link to the endpoint.

**Screenshots**

**Additional context or questions**

**Comment by Xemdo** [comment]
Updated scopes list
