### ISSUE TITLE
Response examples aren't valid JSON

### ISSUE THREAD

**Issue by Katzen48** [twitchdev/issues#898]
**Brief description**
Some of the response examples are not valid.
They either include wrong characters or structures.

**Expected documentation**
The ``data`` property of the [Get Conduits](https://dev.twitch.tv/docs/api/reference/#get-conduits) response example is on the wrong level of the hierarchy and has to be moved up:
```json
{
  {
  "data": [
    {
      "id": "26b1c993-bfcf-44d9-b876-379dacafe75a",
      "shard_count": 15
    },
    {
      "id": "bfcfc993-26b1-b876-44d9-afe75a379dac",
      "shard_count": 5
    }
  ]
}
```

The object in the ``pagination`` property of the [Get Conduit Shards](https://dev.twitch.tv/docs/api/reference/#get-conduit-shards) response example is an empty object, which is also invalid and should be filled:
```json
{
  "data": [
    {
      "id": "0",
      "status": "enabled",
      "transport": {
        "method": "webhook",
        "callback": "https://this-is-a-callback.com"
      }
    },
    {
      "id": "1",
      "status": "webhook_callback_verification_pending",
      "transport": {
        "method": "webhook",
        "callback": "https://this-is-a-callback-2.com"
      }
    },
    {
      "id": "2",
      "status": "enabled",
      "transport": {
        "method": "websocket",
        "session_id": "9fd5164a-a958-4c60-b7f4-6a7202506ca0",
        "connected_at": "2020-11-10T14:32:18.730260295Z"
      }
    },
    {
      "id": "3",
      "status": "enabled",
      "transport": {
        "method": "websocket",
        "session_id": "238b4b08-13f1-4b8f-8d31-56665a7a9d9f",
        "connected_at": "2020-11-10T14:32:18.730260295Z"
      }
    },
    {
      "id": "4",
      "status": "websocket_disconnected",
      "transport": {
        "method": "websocket",
        "session_id": "ad1c9fc3-0d99-4eb7-8a04-8608e8ff9ec9",
        "connected_at": "2020-11-10T14:32:18.730260295Z",
        "disconnected_at": "2020-11-11T14:32:18.730260295Z"
      }
    }
  ],
  "pagination": {},
}
```

**Screenshots**

**Additional context or questions**

**Comment by Xemdo** [comment]
Can you post an example of the pagination appearing? When I run it, it doesn't even appear:
```json
{
  "data": [
    {
      "id": "<removed>",
      "shard_count": 1
    }
  ]
}
```

**Comment by Xemdo** [comment]
Disregard the above, this is the actual result I get:
```json
{
  "data": [
  ],
  "pagination": {
  }
}
```

**Comment by Katzen48** [comment]
Yeah, I can verify, that the pagination is missing.
```json
{
	"data": [
		{
			"id": "0",
			"status": "webhook_callback_verification_pending",
			"transport": {
				"method": "webhook",
				"callback": "https://this-is-a-callback.com"
			}
		}
	],
	"pagination": {}
}
```

Compared it to the other endpoints, which all return a cursor.
After checking it, the docs seem to align with the response.
Then just the endpoint has inconsistent behaviour.
Thx for checking.

**Comment by Katzen48** [comment]
[Get Conduits](https://dev.twitch.tv/docs/api/reference/#get-conduits) is okay, now (my parser approves 😄 Katzen48/TwitchOpenApi/pull/95)

For the ``pagination`` object in [Get Conduit Shards](https://dev.twitch.tv/docs/api/reference/#get-conduit-shards), the docs seem fine.
Closing this issue.
