### ISSUE TITLE
Conduit Docs examples

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#899]
**Brief description**

A number of issues including but not limited it

A number of POST/PATCH type requests are missing the `Content-Type: application:/json` header in the curl example

**Expected documentation**

Include the `Content-Type` header where relevant

**Additional context or questions**

Missing content-type header

- https://dev.twitch.tv/docs/api/reference/#create-conduits
- https://dev.twitch.tv/docs/api/reference/#update-conduits
- https://dev.twitch.tv/docs/api/reference/#update-conduit-shards

Example passes (documented) query params as JSON body
- https://dev.twitch.tv/docs/api/reference/#delete-conduit

**Comment by Xemdo** [comment]
Updated examples
