### ISSUE TITLE
Create Clip API - Confusing Error

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#9]
**Brief description**

When you specify a bad Bearer token, to the create Clips API (app access token for example)

The API returns

> The 'user_id' parameter cannot be blank.

Which is not a valid query string parameter for this API Leading to confusion

**How to reproduce**

Call create clip API with a App Access Token

**Expected behavior**

Error stating invalid Access Token in use

**Additional context or questions**

https://discuss.dev.twitch.tv/t/new-api-create-clip-api-error-the-user-id-parameter-cannot-be-blank/23300/

**Comment by mauerbac** [comment]
HLX-1334

**Comment by jbulava** [comment]
**The cause**
This API requires User OAuth tokens, but this was not specified in the documentation and was not enforced by the API itself correctly. As a result, requests with app access tokens weren't rejected and the `user_id` sent to the downstream service was a blank string (as it is when using app access tokens). The service returned a `Bad Request` and invalid `user_id` parameter, which the API forwarded to third party developers.

**Mitigation**
There is a ticket to correct the documentation (DXDOC-258) and the API was updated in production on April 22 to return the correct "Missing User OAUTH Token" error message.
