### ISSUE TITLE
Erroneous $dollar signs

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#90]
**Brief description**

The text on the oAuth authorize dialog is display random $ signs

**How to reproduce**

Send someone to Twitch to authorise an application's access to a users account

**Expected behavior**

The text to be correct

**Screenshots**

Errors underlined in blue

![image](https://user-images.githubusercontent.com/20999/79350670-a6fcd780-7f2f-11ea-8a87-00abd4d64228.png)

**Comment by lleadbet** [comment]
This was resolved recently- if you're seeing this again, feel free to reopen.
