### ISSUE TITLE
Emotes endpoints response examples broken

### ISSUE THREAD

**Issue by Katzen48** [twitchdev/issues#901]
**Brief description**
The newest deploy seems to have broken the rendering of the response examples for [Get Channel Emotes](https://dev.twitch.tv/docs/api/reference/#get-channel-emotes) and [Get Global Emotes](https://dev.twitch.tv/docs/api/reference/#get-global-emotes)

**Expected documentation**
There are ``{% raw %}`` expressions in the response examples.
So, whether or not you use Jinja as a templating engine, something might have broken there.

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/19516002/6a681581-28bb-4ead-85f3-6f1840853b73)
![image](https://github.com/twitchdev/issues/assets/19516002/2c151162-76be-41e0-8670-1adc660b06fd)

**Comment by Xemdo** [comment]
Resolved
