### ISSUE TITLE
Get Conduit Shards Example

### ISSUE THREAD

**Issue by Marenthyu** [twitchdev/issues#905]
**Brief description**
In the [Get Conduit Shards](https://dev.twitch.tv/docs/api/reference/#get-conduit-shards) Example, the query Parameter `id` is used.
**Expected documentation**
It should be `conduit_id` instead.
**Screenshots**
https://lowee.de/chrome_2024-02-05_22-40-37.png

**Comment by Xemdo** [comment]
Fixed
