### ISSUE TITLE
Get/Delete EventSub Subscriptions - Conduits

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#908]
**Brief description**

https://dev.twitch.tv/docs/api/reference/#get-eventsub-subscriptions no conduit ref

**Expected documentation**

> If you use [webhooks](https://dev.twitch.tv/docs/eventsub/handling-webhook-events) or [conduits](https://dev.twitch.tv/docs/eventsub/handling-conduit-events/) to receive events, the request must specify an app access token. The request will fail if you use a user access token.

**Comment by Xemdo** [comment]
Added
