### ISSUE TITLE
Drops v2 is still in the Org console

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#909]
**Brief description**
In the Org Console page, `https://dev.twitch.tv/org/ORG ID/console`, the panel for Drops has a Create Drops Campaign button, this links to `https://dev.twitch.tv/org/ORG ID/console/drops-v2/campaign/create` which is no longer usable to create a campaign. Additionally, the `Drops (legacy)` page still exists despite the timeline for its removal having passed.

**How to reproduce**
1. Go to the Org Console `https://dev.twitch.tv/org/ORG ID/console`
2. Click Create Drops Campaign

and

1. Go to the Org Console `https://dev.twitch.tv/org/ORG ID/console`
2. Follow the link to the `Drops (legacy)` page, `https://dev.twitch.tv/org/ORG ID/console/drops-v2/`
3. Be on a page that shouldn't exist.

**Expected behaviour**
The planned date for the final step of the transition to Drops v3, as laid out in the announcement thread [https://discuss.dev.twitch.com/t/improving-the-flexibility-of-twitch-drops/46818](https://discuss.dev.twitch.com/t/improving-the-flexibility-of-twitch-drops/46818), was December 1st, 2023. At that point the `Drops (legacy)` tab was to be removed.

The expected behaviour is for that `Drops (legacy)` page, and links to it, to not exist, and for the Create Drops Campaign link on the main console page to link to v3.

**Comment by Xemdo** [comment]
The deprecation of that page has been moved to be during the month of June, or possibly before.
I'll note to have the original announcement updated. Thank you!
