### ISSUE TITLE
Unescaped HTML-like string "<rgb>" under Channel Chat Message Event

### ISSUE THREAD

**Issue by AlcaDesign** [twitchdev/issues#915]
**Brief description**

The description of the `color` property under [Channel Chat Message Event](https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-chat-message-event) has an erroneously rendered "rgb" HTML element.

**Expected documentation**

```md
The color of the user's name in the chat room. This is a hexadecimal RGB color code in the form, `#<rgb>`. This tag may be empty if it is never set.
```
![image](https://github.com/twitchdev/issues/assets/7132646/c228fd8c-eb59-425f-8b68-5359b486ddea)
or more plainly
![image](https://github.com/twitchdev/issues/assets/7132646/62759d88-756e-4aae-acfb-2a6b27357dca)

**Screenshots**

![image](https://github.com/twitchdev/issues/assets/7132646/fc00d87f-d783-4853-aa74-6c1d78a6ef9f)
![image](https://github.com/twitchdev/issues/assets/7132646/85d586a3-187d-4910-af93-b3852afc3f53)

**Comment by Xemdo** [comment]
This should be fixed
