### ISSUE TITLE
Error when try to create a new application

### ISSUE THREAD

**Issue by PabloFelipeRG** [twitchdev/issues#919]
**Brief description**
After I fullfil the application creation form, when I click the creat button I'm getting no response. When I opened the browser console I saw some graphql errors.

Apparently the error is that the name of the application already exists but the site don't show anything to the user.
**How to reproduce**
Fill out the application creation form and click the create button.
**Expected behavior**
Creates the application successfully
**Screenshots**
![image](https://github.com/twitchdev/issues/assets/37262811/895625e6-0b8c-4f75-835e-2d83fe32368b)

![image](https://github.com/twitchdev/issues/assets/37262811/cf6d879a-4ada-46ea-a432-2af142fe1e10)

**Comment by Dkamps18** [comment]
Duplicate of #831
