### ISSUE TITLE
Incorrect Twitch ID russian translation for PubSub channel points redemptions

### ISSUE THREAD

**Issue by satanch** [twitchdev/issues#92]
When I'm using `channel:read:redemptions` with russian translation I'm getting a wrong text.

![tid](https://user-images.githubusercontent.com/19252217/79672700-2f53d480-81dd-11ea-9fc6-2d945f7bf596.PNG)

Text contains "ваши" which means that application will be able to recieve redemptions only from current user (not from all channel users). This is totally wrong.

Word "ваши" should removed asap. A really big misunderstanding could be occurred.

**Comment by lleadbet** [comment]
This was ticketed as LOC-5280 and was addressed. Let us know if the new translation doesn't resolve the underlying issue- thanks for the flag!
