### ISSUE TITLE
Impossible emote_type example for new get user emotes endpoint

### ISSUE THREAD

**Issue by IAmTomahawkx** [twitchdev/issues#928]
**Brief description**
Docs @ [get user emotes](https://dev.twitch.tv/docs/api/reference/#get-user-emotes).

The example for `emote_type` is "hypetrain", but the docs to the left of the example state that the only possible values are "bitstier", "subscription", and "follower". Both of these can't be true.

**Expected documentation**

Presumably hypetrain should be included in the list of possible emote types.

**Comment by tduva** [comment]
Other `emote_type` values I've seen in actual requests are `smilies`, `globals`, `limitedtime`. `prime`, `twofactor`, `owl2019`. Not sure how much sense it makes to list all of them if there's so many different types, but it shouldn't pretend that it's limited to the listed ones at least.

**Comment by Xemdo** [comment]
Documentation has been updated to reflect all possible emote types.
It should be noted that the list is different for the Get User Emotes API endpoint versus the other emote API endpoints, because this endpoint is the only one that would show these additional emote types
