### ISSUE TITLE
Get Games shows pagination in example

### ISSUE THREAD

**Issue by chillymosh** [twitchdev/issues#929]
**Brief description**
The Get Games endpoint (https://dev.twitch.tv/docs/api/reference/#get-games) shows a pagination cursor on the right hand side for the Example Response.

Request Query Parameters does not have first, after or before parameters which is indicative of an endpoint that returns a cursor.
The Response body also does not specify a cursor is returned.

Upon several tests, this endpoint does not seem to return a cursor, unless there are some edge cases that I have missed.

**Expected documentation**
Remove the pagination cursor from Example Response

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/86857777/444d2f92-d0de-4dd7-913e-1954a8bd890c)

**Additional context or questions**

**Comment by Xemdo** [comment]
Documentation has been updated to fix this issue
