### ISSUE TITLE
user.whisper.message beta endpoint is returned capitalized Whisper property.

### ISSUE THREAD

**Issue by tacoadventure** [twitchdev/issues#930]
I'm testing out the beta user.whisper.message eventsub and there seems to be an issue. The event is sending back what is expected EXCEPT whisper is capitalized in the returning JSON (see below) 

Here is the snippet of the JSON that I got back for the event section of the payload:

{"Whisper": {"text": "!tacos"}, "to_user_id": "431569375", "whisper_id": "88279824-5e1c-4f48-86e9-2eeb02a5ff3c", "from_user_id": "87278179", "to_user_name": "TacoDeliveryDrone", "to_user_login": "tacodeliverydrone", "from_user_name": "TacoAdventure", "from_user_login": "tacoadventure"}

**Comment by Xemdo** [comment]
This should be resolved now
