### ISSUE TITLE
Get EventSub Subscriptions Status websocket_failed_to_reconnect isn't documented

### ISSUE THREAD

**Issue by Samoth69** [twitchdev/issues#931]
**Brief description**

Hello,

While interacting with endpoint [Get EventSub Subscriptions](https://dev.twitch.tv/docs/api/reference/#get-eventsub-subscriptions), my subscriptions all ended at one point in status `websocket_failed_to_reconnect`. This status isn't documented anywhere or I couldn't find it.

**Expected documentation**

`websocket_failed_to_reconnect` should be in Reponse body Status description.

**Screenshots**

N/A

**Additional context or questions**

### API Result for https://api.twitch.tv/helix/eventsub/subscriptions

```json
{
  "total": 11,
  "data": [
    {
      "id": "4fa0bdca-98a7-4307-9038-d86ea4f95ef5",
      "status": "websocket_failed_to_reconnect",
      "type": "stream.online",
      "version": "1",
      "condition": {
        "broadcaster_user_id": "Redacted"
      },
      "created_at": "2024-03-21T17:03:55.498320074Z",
      "transport": {
        "method": "websocket",
        "session_id": "Redacted",
        "connected_at": "2024-03-21T17:03:55Z",
        "disconnected_at": "2024-03-21T17:14:54Z"
      },
      "cost": 0
    },
    {
      "id": "cea0fae2-06fc-4d3a-bc65-e22cdd800d62",
      "status": "websocket_failed_to_reconnect",
      "type": "stream.offline",
      "version": "1",
      "condition": {
        "broadcaster_user_id": "Redacted"
      },
      "created_at": "2024-03-21T17:03:55.895093996Z",
      "transport": {
        "method": "websocket",
        "session_id": "Redacted",
        "connected_at": "2024-03-21T17:03:55Z",
        "disconnected_at": "2024-03-21T17:14:54Z"
      },
      "cost": 0
    }
    items redacted for readability
  ],
  "max_total_cost": 10,
  "total_cost": 0,
  "pagination": {}
}
```

**Comment by Xemdo** [comment]
Statuses not yet documented on this endpoint:

- chat_user_banned
- websocket_failed_to_reconnect

And while we're here, the following are missing from [Get Conduit Shards](https://dev.twitch.tv/docs/api/reference/#get-conduit-shards) and [Updated Conduit Shards](https://dev.twitch.tv/docs/api/reference/#update-conduit-shards):
- websocket_failed_to_reconnect

**Comment by Xemdo** [comment]
Docs have been updated with this information
