### ISSUE TITLE
Attempting to create a new extension or application returns no errors and will not create. 

### ISSUE THREAD

**Issue by vince760** [twitchdev/issues#932]
Attempting to create a new extension allows you to navigate to the create dialog, but when selecting submit there is no response. 

**How to reproduce**
Navigate to dashboard, then register your application. 
Fill out all fields and click create.

**Expected behavior**
Success or Error response

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/26665765/0163a551-c11f-461f-8cb7-feef43b638c6)
![image](https://github.com/twitchdev/issues/assets/26665765/2995fa5b-8197-416b-a3ee-09078d88e53b)

**Comment by Wissididom** [comment]
Likely duplicate of https://github.com/twitchdev/issues/issues/831

**Comment by vince760** [comment]
> Likely duplicate of #831

Thanks, I changed the name of my app. Would think that the UI would be more informational when it comes to errors. Guess not.
