### ISSUE TITLE
User entry for Drops Access selection multiple-user selection isseus

### ISSUE THREAD

**Issue by thedist** [twitchdev/issues#933]
**Brief description**
The Access lists for a Drops Campaign (both test viewers and creator campaign access) used allow for a comma separated list of users, as documented on the access page `You can add multiple channels by separating the usernames with commas.`. Now it only seems to support adding the last value that hasn't already been added.

Additionally, when trying to manually type the list instead of copy/pasting, the first user will create a dropdown box to select the user that matches, but after the comma it will check if the text is a valid user and if so automatically add that, resulting in the wrong accounts being added.

**How to reproduce**
Create a Drops campaign, and on the Access tab attempt to either copy/paste a comma separated list of user names, or manually type them.

For example, if you attempt to copy/paste `qa_partner, qa_moderation, thedist`, into the access list, only `thedist` will be added. If you then press space it'll add the next last user that hasn't already been added, so `qa_moderation` would be added, then another space would add `qa_partner`.

If you attempt to manually type `qa_partner, qa_moderation, thedist` into the access list, `qa_partner`, `qa_m`, `qa_mod`, `qa_moderation`, `thed`, `thedi`, `thedis`, `thedist` get added (varies depending on typing speed).

**Expected behavior**
When Copy/Pasting a list of users it should add all that are valid, not just the last one. When manually typing users it should only add the user when they are selected from the dropdown box, or when a comma is typed, as opposed to checking if it's a valid username on each and every letter and attempting to add it.

**Comment by Xemdo** [comment]
This should be solved now
