### ISSUE TITLE
Incorrect value for "Unique Active Channels"

### ISSUE THREAD

**Issue by guanzo** [twitchdev/issues#94]
**Brief description**
The value for "Unique Active Channels" under https://dev.twitch.tv "Extension Analytics" is "wrong". Wrong in the sense that it doesn't reflect the selected time period.

**How to reproduce**
Just look at the UI value and compare it to the csv value.

It seems like the UI is displaying "Unique Active Channels" for a single day, instead of "Unique Active Channels Last X Days", which is an aggregated value.

**Expected behavior**
It should have the correct value.

**Screenshots**
CSV data. 
![](https://i.gyazo.com/0a5dbad966efcea6ab0968bce6d3d8da.png)

dev.twitch.tv data:
7 days expected value: ~105k
7 days actual value: ~36k

30 days expected value: ~190k
30 days actual value: ~34k
![](https://i.gyazo.com/71ae4da20102607d36a0bd53495848bc.png)

**Additional context or questions**
Discord chat context https://discordapp.com/channels/504015559252377601/523676096277905419/702622121624600637

**Comment by Xemdo** [comment]
Seems to be resolved now
