### ISSUE TITLE
Twitch App screen record, bug web Twitch

### ISSUE THREAD

**Issue by Canal9000** [twitchdev/issues#948]
I did a live stream, screen record, on Twitch APP using my phone Xiaomi Redmi 10
On the Chrome browser, at 720p (source), the viewer can't see. The image breaks.
If selected any other resolution, it works.

Vod: from yesterday 10/05/2024
https://www.twitch.tv/videos/2123908082)

**Comment by Emilgardis** [comment]
This is not twitch support, it's bug reports for Twitch developer products.

try https://help.twitch.tv/s/contactsupport instead 👍🏼
