### ISSUE TITLE
Not is possible taked drop of war of worldships

### ISSUE THREAD

**Issue by ulrichfreia** [twitchdev/issues#949]
Good afternoon, I'm claiming a drop that War Gaming gave in the game War of Worldships, but it won't let me pick it up, it says a note about the drop that claims the game, but I hit it and it doesn't work, can you please look at it, it's happening to a lot of people, thank you.

**Comment by BarryCarlyon** [comment]
For support with drops not working in game you need to contact the game developer

Not the bug tracker for third party developers. You are in the wrong place
