### ISSUE TITLE
Subscriptions/events broadcaster_name/user_name swapped

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#95]
**Brief description**

Consider this payload, from the endpoint

> https://api.twitch.tv/helix/subscriptions/events?broadcaster_id=26610234&first=1

And it's friend on Webhooks

```
{
"id": "REMOVED",
"event_type": "subscriptions.subscribe",
"event_timestamp": "2020-04-24T10:02:59Z",
"version": "1.0",
"event_data": {
"broadcaster_id": "26610234",
"broadcaster_name": "AlphaShadow192",
"gifter_id": "",
"gifter_name": "",
"is_gift": false,
"plan_name": "REMOVED",
"tier": "REMOVED",
"user_id": "59064400",
"user_name": "CohhCarnage"
}
}
```

or

```
{"data":[{"event_data":{"broadcaster_id":"23735582","broadcaster_name":"servusmo
rtis","gifter_id":"","gifter_name":"","is_gift":false,"plan_name":"REMOVED","tier":"REMOVED","user_id":"37765283","user_name":"Sacriel"
},"event_timestamp":"2020-04-22T18:39:56Z","event_type":"subscriptions.subscribe
","id":"REMOVED","version":"1.0"}]}
```

The `user_name` and `broadcaster_name` values have been swapped

**Expected behavior**

The to not be swapped

**Additional context or questions**

First reported on Discord

https://discordapp.com/channels/504015559252377601/523676183804510228/703063979152506950

Problem first logged around (via Webhooks log)

> 2020-04-22T18:02:47Z

**Comment by jbulava** [comment]
Ticketed as HLX-1373.

**Comment by jbulava** [comment]
Issue has been fixed.
