### ISSUE TITLE
Wrong grant_type for device code grant flow

### ISSUE THREAD

**Issue by zaytri** [twitchdev/issues#952]
**Brief description**

In https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#device-code-grant-flow, under the cURL request table for **Obtaining the refresh token/access token pair**, the `grant_type` parameter description states "Must be set to `device_code`."

**Expected documentation**

It should state "Must be set to `urn:ietf:params:oauth:grant-type:device_code`."

**Screenshots**
![image](https://github.com/twitchdev/issues/assets/9072119/cea358e3-f4fe-4f5d-96ef-50039472659e)

**Comment by Xemdo** [comment]
Fixed
