### ISSUE TITLE
Space in the display_name

### ISSUE THREAD

**Issue by Samyy670** [twitchdev/issues#956]
**Brief description**
I think I have a bug, but maybe not just with the API. A viewer had a space at the end of their display_name that wasn't in their login. We checked the Twitch profile form "https://www.twitch.tv/settings/profile" and indeed, there was a space in the display_name.

The viewer in question was "Wundertyran". He fixed the bug by resubmitting the form, so we don't see it on his profile anymore. But I'm wondering, could other viewers have this bug as well?

**Screenshots**
From my external service data:
![image](https://github.com/twitchdev/issues/assets/97808822/196fc76d-20f7-4e24-b5c4-7d1bbb14cd54)

**Comment by BarryCarlyon** [comment]
This isn't a bug this is just how some display names are.

it has been have been like this _forever_ (`/s` on IRC is common)

Some display names have a space on the end or in the middle like riot games.

**Comment by Xemdo** [comment]
Spaces in display names can be expected. In the case of this user, it seems to not be expected, but as Barry mentioned there are users like [/RiotGames](https://twitch.tv/riotgames) who have a space in their name:

```
{
  "data": [
    {
      "broadcaster_type": "partner",
      "created_at": "2012-09-08T06:53:10Z",
      "description": "Welcome to the Riot Games channel, home of LoL Esports and other livestreams related to our games. For LoL Esports broadcasts, schedules, standings and advanced viewing features, head to http://lolesports.com.",
      "display_name": "Riot Games",
      "id": "36029255",
      "login": "riotgames",
      "offline_image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/38179bd5-2370-41b2-9297-5bda81345277-channel_offline_image-1920x1080.jpeg",
      "profile_image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/35b02a12-d516-499e-90f8-7899f136fa18-profile_image-300x300.png",
      "type": "",
      "view_count": 0
    }
  ]
}
```
