### ISSUE TITLE
have not recieved some of the rust bellum twitch drop in my rust account

### ISSUE THREAD

**Issue by CjDarksoul** [twitchdev/issues#965]
**Brief description**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by thedist** [comment]
If you've claimed a Drop, it's up to the developers or publishers of the game that are running the Drops Campaign to fulfil those rewards. so you'll need to reach out to them.

Additionally please keep in mind that claimed Drops may not be fulfilled instantly, some developers do them in batches, some wait for a certain date, it's entirely up to them how and when they distribute them.
