### ISSUE TITLE
The "Monetization" tab.

### ISSUE THREAD

**Issue by Ayrti** [twitchdev/issues#968]
When I try to press "Continue to Onboarding" I receive: Onboarding Status
To monetize your Extension, you must complete the onboarding flow available via the button below. Once complete the additional options will be enabled here.

Your request could not be completed at this time. Please double check the format of your request and try again. If you need additional support, please visit this page to submit a ticket.
Bits Support.

**Comment by BarryCarlyon** [comment]
> If you need additional support, please visit this page to submit a ticket.
> Bits Support.

Did you visit that page to submit a ticket? Which I believe is not here but Twitch Support itself?
