### ISSUE TITLE
Oh Bummer error on Android TV

### ISSUE THREAD

**Issue by croveanz** [twitchdev/issues#970]
**Brief description**
Oh bummer… an error occurred while playing this content on various streamers

**How to reproduce**
Twitch.tv app on Android TV

**Expected behavior**
Not to crash the stream

**Screenshots**
![IMG_4285](https://github.com/user-attachments/assets/9e9b4029-0dc7-41be-a17c-4b76811aeb3a)

**Additional context or questions**
This happens only on TV, no issue on laptop.

**Comment by BarryCarlyon** [comment]
The third party developers bug tracker cannot help you with first party apps

Please contact Twitch Support
