### ISSUE TITLE
When trying to connect to https://irc.twitch.tv/, there is SSL certificate error (depends on server cluster, could not be replicated every time)

### ISSUE THREAD

**Issue by Marcifer** [twitchdev/issues#976]
**Brief description**
Seems like some twitch servers do not serve correct SSL certificate on https://irc.twitch.tv/.

**How to reproduce**
Open any web browser and try to GET https://irc.twitch.tv/.

**Expected behavior**
it should return data from twitch api.

**Screenshots**
![obrazek](https://github.com/user-attachments/assets/d7b3a1f7-aee9-49eb-9c3e-eff9e8287490)
![obrazek](https://github.com/user-attachments/assets/db86744d-ff79-47f5-bcb3-bfa2e4ba4101)

**Additional context or questions**
This seems to be happpening randomly and for some time now.

**Comment by Xemdo** [comment]
irc.twitch.tv is not officially supported as an endpoint. We also do not support HTTPS directly, it must be irc or ws protocols.

For further information our IRC support, see our documentation here:
https://dev.twitch.tv/docs/chat/irc/
