### ISSUE TITLE
Unable to get Entitlements for specific user (500 status)

### ISSUE THREAD

**Issue by chazix** [twitchdev/issues#979]
**Brief description**

We have a specific user for our game that we are unable to get entitlements for.

The response received from the `https://api.twitch.tv/helix/entitlements/drops` endpoint is:
```
{
    "error": "Internal Server Error",
    "status": 500,
    "message": ""
}
```
After ~4.2 seconds of execution.

We know our process works as this is a one off report, and users have been receiving their drops correctly. I have verified on our end that they are linked correctly.

**How to reproduce**

I can provide further information on the specific `user_id`, `game_id`, and `Client-Id` in private as this reproduces the issue.

**Expected behavior**

Any other response besides a `500` status code.

**Comment by BarryCarlyon** [comment]
I'm guessing you also raised this on the forums https://discuss.dev.twitch.com/t/unable-to-get-entitlements-for-specific-user-500-status/59840 ?
