### ISSUE TITLE
Delete Me Please / Issue can no longer be reproduced!

### ISSUE THREAD

**Issue by SoWhoYou** [twitchdev/issues#98]
**Just Delete This Please**

I will make a new report when I can reproduce the issue again, because with no changes to how I was doing things, it just randomly started working again today, very strange. Sorry for the report!

**Comment by SoWhoYou** [comment]
I've done some more testing, and I see that the clips list gets sent back always when accessing the api the way that I did in that screen shot above, regardless of the channel, and/or if offline or not.

I will be doing more testing as soon as the streamer goes live again, to get the raw json data that is being sent back when accessing the api via curl and reply back with more information, forgive my ignorance with the way this report was made. However there still is an issue with this api not working as expected, I just need to give you guys some better data, sorry for rushing the report.

**Comment by BarryCarlyon** [comment]
You can close your own Ticket with the "close issue" or "close and comment" button in github issues itself
