### ISSUE TITLE
Incorrect scope listed in documentation for Resolve Unban Requests

### ISSUE THREAD

**Issue by thePlebDev** [twitchdev/issues#982]
**Brief description**
- The Official documentation for [Resolve Unban Requests](https://dev.twitch.tv/docs/api/reference/#resolve-unban-requests) states the necessary scope as:
    -  ***moderator:manage:unban\\_requests*** 
- However, the proper scope is:
    -  ***moderator:manage:unban\_requests***

**Expected documentation**
-  ***moderator:manage:unban\_requests***

**Screenshots**

<img width="556" alt="IncorrectTwitchDocumenation" src="https://github.com/user-attachments/assets/794ab2a1-8957-4975-a849-091c6d77c6cf">

**Additional context or questions**
- [LINK TO OFFENDING DOCUMENTATION](https://dev.twitch.tv/docs/api/reference/#resolve-unban-requests)
- This seems to be the only part affected by this mistype. The 401 response code states the proper scopes:

<img width="481" alt="ProperScopesUnbanRequests" src="https://github.com/user-attachments/assets/b739155c-5a05-48a4-936c-cbd51a8dd08e">

**Comment by Xemdo** [comment]
This is definitely a typo. Seems in the markdown it was \\_ instead of \_

**Comment by Xemdo** [comment]
Fixed

**Comment by thePlebDev** [comment]
Thanks!!! @Xemdo
