### ISSUE TITLE
Exporting personal data under settings always stuck as processing

### ISSUE THREAD

**Issue by BPWiz** [twitchdev/issues#988]
Under settings there is a request button for your personal data, this process "typically" takes 14 days however is always frozen. 

Be a streamer on twitch, nearly make affiliate, go to settings, request a copy of personal data.

Never concluding its process time

The button continues to say processing a month afterwards.

**Comment by Emilgardis** [comment]
this is not a dev site issue, it's a first party issue. You should probably use https://help.twitch.tv/s/contactsupport

**Comment by Emilgardis** [comment]
![image](https://github.com/user-attachments/assets/2364a146-3cb8-47a5-be92-76f1184284ee)
