### ISSUE TITLE
Inconsistent data structure for chat_moderator_actions PubSub topic

### ISSUE THREAD

**Issue by teraa** [twitchdev/issues#99]
**Brief description**

Data of the messages sent for `chat_moderator_actions.{user_id}.{room_id}` PubSub topic when one of the following chat commands is used

- `/mod`
- `/unmod`
- `/vip`
- `/unvip`

has inconsistent structure with all other messages sent for this **same** topic.

More specifically
- Inconsistently placed `type` field inside the JSON string. All other messages have the `type` field located **inside** the `data` object within the JSON string.
- `channel_id` field is redundant, as that information is contained within the `topic`

**How to reproduce**
- Listen for the said PubSub topic
- Use `/mod user` command (or any of the other commands mentioned above)
- Inspect the received PubSub message

Example received:
```jsonc
{
  "type": "MESSAGE",
  "data": {
    "topic": "chat_moderator_actions.52324616.52324616",
    "message": { // JSON string
      "type": "moderator_added", // Outside data
      "data": {
        "channel_id": "52324616",
        "target_user_id": "130277892",
        "moderation_action": "mod",
        "target_user_login": "tera2",
        "created_by_user_id": "52324616",
        "created_by": "tera_"
      }
    }
  }
}
```
**Expected behavior**

The `type` field should be in same place for all messages, as it is in the following two example messages:

`/subscribersoff` example
```jsonc
{
  "type": "MESSAGE",
  "data": {
    "topic": "chat_moderator_actions.52324616.52324616",
    "message": {
      "data": { // JSON string
        "type": "chat_channel_moderation",  // Inside
        "moderation_action": "subscribersoff",
        "args": null,
        "created_by": "tera_",
        "created_by_user_id": "52324616",
        "msg_id": "",
        "target_user_id": "",
        "target_user_login": "",
        "from_automod": false
      }
    }
  }
}
```

`/timeout` example
```jsonc
{
  "type": "MESSAGE",
  "data": {
    "topic": "chat_moderator_actions.52324616.52324616",
    "message": { // JSON string
      "data": {
        "type": "chat_login_moderation",  // Inside
        "moderation_action": "timeout",
        "args": [
          "tera2",
          "10",
          "test"
        ],
        "created_by": "tera_",
        "created_by_user_id": "52324616",
        "msg_id": "",
        "target_user_id": "130277892",
        "target_user_login": "",
        "from_automod": false
      }
    }
  }
}
```

**Additional context or questions**

Inconsistent placement of the `type` field makes it harder to successfully deserialize the incoming messages.

**Comment by BarryCarlyon** [comment]
See also it's friend

https://twitch.uservoice.com/forums/310213-developers/suggestions/40317874-pubsub-topics-no-moderator-topic-examples-documen

The topic is documented as existing, but theres no formal documentation to cover the packets/events

**Comment by iProdigy** [comment]
Able to reproduce for the `chat_moderator_actions.{user_id}.{room_id}` topic.

The topic `chat_moderator_actions.{channel_id}` does not suffer from this inconsistency; the type is `chat_login_moderation`, as expected.

**Comment by BarryCarlyon** [comment]
Worth nothing that `chat_moderator_actions.{user_id}.{room_id}` no longer "documented" for use, it has been officially replaced by `chat_moderator_actions.{channel_id}`

**Comment by Xemdo** [comment]
PubSub will be deprecated so I'm pre-emptively closing this out.
https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043
