### ISSUE TITLE
i have 86 followers but it says i have  so i cant get affiliate even though ive met the requirements (and same with the avg veiwers) can you please help

### ISSUE THREAD

**Issue by brenner399** [twitchdev/issues#991]
i have 86 followers but it says i have  so i cant get affiliate even though ive met the requirements (and same with the avg veiwers) can you please help

**Comment by thedist** [comment]
This is a developer community, and we can not assist with first party or account related issues here. You'll have to go through Twitch Support [https://help.twitch.tv/](https://help.twitch.tv/)
