### ISSUE TITLE
Unable to enable drops for all viewers

### ISSUE THREAD

**Issue by ohdin021** [twitchdev/issues#993]
**Trying to enable drops for all channels fails**

**unchecking the allow list button and clicking save gives the error "Failed to update allow list" "server error"**

**all channels should have drops enabled for dark and darker**

**
![image](https://github.com/user-attachments/assets/62dae408-7057-480a-8de0-4b9ee3e8e8a5)
![image](https://github.com/user-attachments/assets/aeff248b-930e-4088-882e-d26dadae5306)
**

**Day 1 and Day 2 had limited access for drops, Day 3 (today) was supposed to be enabled for all. Instead we had to manually add 6,000+ accounts because allowing all would not save/work. Now the entire list has disappeared and nobody has drops.**

**Comment by Xemdo** [comment]
This was because the campaign was live at the time of the switch. This should no longer be an issue-- campaigns can be switched from allowlist to no allowlist regardless if they are live, test, or disabled.
