### ISSUE TITLE
Cant request new application secret

### ISSUE THREAD

**Issue by HeyItsDanny** [twitchdev/issues#996]
**Brief description**
I open https://dev.twitch.tv/console/apps and click on “Manage” for my application. Then I confirm the captcha and click on “New secret”. I then confirm, but nothing happens. Normally, the new secret should be displayed. However, nothing happens.

**How to reproduce**
As described above. It happens with Chrome and Edge. Can't create a new secret at the moment.

**Expected behavior**
The new secret should be displayed

**Screenshots**
difficult, as nothing is displayed

**Additional context or questions**

**Comment by BarryCarlyon** [comment]
Couldn't replicate this myself just now, but I don't have a captcha to complet myself.

This could indicate an issue with ad or script blocker or a VPN or similar in your environment
