### ISSUE TITLE
PubSub: Unban request details

### ISSUE THREAD

**Issue by francislavoie** [twitchdev/issues#997]
Looking at the topics https://dev.twitch.tv/docs/pubsub/#topics one thing that seems lacking is information on user unban requests.

I'd like to get events on unban requests (including the full message in the user's request) and if unbanned or denied by a moderator, the message from the moderator.

We use a bot https://github.com/nielsAD/muddy which writes messages in Discord with detail on moderation actions for auditing (making sure everyone agrees on the actions taken, or to search to get context on a previous action). Right now, when we deny/unban, we lose the user's unban request message which sometimes has important context. Our usual workaround is to copy it and write it as a moderator comment or adding it to our Discord channel, but sometimes we forget to do it manually. So we're looking to resolve this hole in our audit logs with automation.

**Comment by Xemdo** [comment]
PubSub is being deprecated on April 14th, 2025. More information can be found here:
https://discuss.dev.twitch.com/t/legacy-pubsub-deprecation-and-shutdown-timeline/58043

We recommend the use of EventSub for your purposes instead:
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelunban_requestcreate
- https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelunban_requestresolve

Currently the resolution text is provided, but the original message is not. I recommend suggesting that feature on our UserVoice:
https://twitch.uservoice.com/forums/310213-developers

**Comment by francislavoie** [comment]
Ah thanks, didn't realize PubSub is being deprecated. Shouldn't there be a notice of that on https://dev.twitch.tv/docs/pubsub/ then?

> Currently the resolution text is provided, but the original message is not. 

Hmm, from my reading it seems like this is the user's unban message? `"text": "unban me",`

> https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-unban-request-create-event
> "text" 	string: 	Message sent in the unban request.

If so then great, it already has the information I'm looking for
